### ISSUE TITLE
azure_rm_networkinterface constantly returns changed status

### ISSUE THREAD

**Issue by msl0** [ansible/ansible_collections_azure#1004]
##### SUMMARY

Ansible constantly returns changed status for `azure_rm_networkinterface` module when `primary` is not defined in `ip_configurations` list.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

azure_rm_networkinterface
##### ANSIBLE VERSION

```paste below
ansible [core 2.12.9]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/vagrant/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/vagrant/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Jun 22 2022, 20:18:18) [GCC 9.4.0]
  jinja version = 2.10.1
  libyaml = True
```

##### COLLECTION VERSION

```paste below
Collection          Version
------------------- -------
azure.azcollection  1.13.0 
```

##### CONFIGURATION

```paste below
empty
```

##### OS / ENVIRONMENT

Ubuntu 20.04

##### STEPS TO REPRODUCE

Run the below playbook twice

```yaml
---
- name: Create Azure VM
  hosts: localhost
  connection: local
  tasks:
    - name: Create resource group
      azure_rm_resourcegroup:
        name: "test-rg"
        location: "westeurope"

    - name: Create virtual network
      azure_rm_virtualnetwork:
        resource_group: "test-rg"
        name: "test-vnet"
        address_prefixes: "10.0.0.0/24"

    - name: Create Network Security Group that allows SSH
      azure_rm_securitygroup:
        resource_group: "test-rg"
        name: "test-nsg"
        rules:
          - name: SSH
            protocol: Tcp
            destination_port_range: 22
            access: Allow
            priority: 1001
            direction: Inbound

    - name: Add subnet
      azure_rm_subnet:
        resource_group: "test-rg"
        name: "test-subnet"
        address_prefix: "10.0.0.0/24"
        virtual_network: "test-vnet"
        security_group_name: "test-nsg"

    - name: Create public IP address
      azure_rm_publicipaddress:
        resource_group: "test-rg"
        allocation_method: Static
        name: "{{ item }}-pip"
      loop: 
        - vm1
        - vm2
      register: output_ip_address

    - name: Public IP of VM
      ansible.builtin.debug:
        msg: "The public IP is {{ item.state.ip_address }}."
      loop: "{{ output_ip_address.results }}"
      loop_control:
        label: "{{ item.item }}"

    - name: Create virtual network interface card
      azure_rm_networkinterface:
        resource_group: "test-rg"
        name: "{{ item.item }}-nic"
        virtual_network: "test-vnet"
        subnet: "test-subnet"
        create_with_security_group: false
        ip_configurations:
          - name: ipconfig
            public_ip_address_name: "{{ item.state.name }}"
      loop: "{{ output_ip_address.results }}"
      loop_control:
        label: "{{ item.item }}"
```

##### EXPECTED RESULTS

Ansible should return ok (no changed) status
``` yaml
...
TASK [Create virtual network interface card] **************************************************************************************************************
ok: [localhost] => (item=vm1)
ok: [localhost] => (item=vm2)
...
```
When I add `primary` in `ip_configurations` to network interface task, then it works as expected.
```yaml
    - name: Create virtual network interface card
      azure_rm_networkinterface:
        resource_group: "test-rg"
        name: "{{ item.item }}-nic"
        virtual_network: "test-vnet"
        subnet: "test-subnet"
        create_with_security_group: false
        ip_configurations:
          - name: ipconfig
            public_ip_address_name: "{{ item.state.name }}"
            primary: true
      loop: "{{ output_ip_address.results }}"
      loop_control:
        label: "{{ item.item }}"
```
Output:
```
TASK [Create virtual network interface card] **************************************************************************************************************
ok: [localhost] => (item=vm1)
ok: [localhost] => (item=vm2)
```
Should it be better described in documentation or this behaviour should be changed?

##### ACTUAL RESULTS

Every time when I run playbook I see changed status for network interface
I see that only etag has changed when comparing JSON view in Azure Portal between runs

```paste below
...
TASK [Create virtual network interface card] **************************************************************************************************************
changed: [localhost] => (item=vm1)
changed: [localhost] => (item=vm2)
...
```
