### ISSUE TITLE
The current version of azure.azcollection.azure_rm_loadbalancer (v1.13) module does not provide an option to create BackEnd Pool

### ISSUE THREAD

**Issue by Sudha2579** [ansible/ansible_collections_azure#1011]
**SUMMARY**
The current version of azure.azcollection.azure_rm_loadbalancer (v1.13) module does not provide an option to create BackEnd Pool

**- Feature Idea**
- 	Azure Ansible module "azure.azcollection.azure_rm_loadbalancer (v1.13)" does not provide an option to create BackEnd Pool,
We are looking for load balancer backend pool feature to be supported in azure module, We're trying to create backend pool for load balancer using ansible.

**COMPONENT NAME**
azure_rm_loadbalancer

**ADDITIONAL INFORMATION**
We're trying to create backend pool for load balancer using ansible.

**Comment by xuzhang3** [comment]
@Sudha2579  create backend pools already support by current version, you just need to specific the pools names in `backend_address_pools`:
```yml
  - name: create public ip
    azure_rm_publicipaddress:
      name: "{{ pipaname }}"
      resource_group: '{{ resource_group }}'
  - name: create load balancer with multiple parameters
    azure_rm_loadbalancer:
      resource_group: '{{ resource_group }}'
      name: "{{ lbname_c1 }}"
      frontend_ip_configurations:
        - name: frontendipconf0
          public_ip_address: "{{ pipaname }}"
      backend_address_pools:
        - name: backendaddrpool0
        - name: backendaddrpool1
      probes:
        - name: prob0
          port: 80
      inbound_nat_pools:
        - name: inboundnatpool0
          frontend_ip_configuration_name: frontendipconf0
          protocol: Tcp
          frontend_port_range_start: 80
          frontend_port_range_end: 81
          backend_port: 8080
      load_balancing_rules:
        - name: lbrbalancingrule0
          frontend_ip_configuration: frontendipconf0
          backend_address_pool: backendaddrpool0
          frontend_port: 80
          backend_port: 80
          probe: prob0
          disable_outbound_snat: True
```
