### ISSUE TITLE
azure_rm_virtualnetwork / azure_rm_virtualnetwork_info: Add support for Flow Timeout

### ISSUE THREAD

**Issue by rnotley** [ansible/ansible_collections_azure#1013]
##### SUMMARY
Add the configurable flow timeout attribute for Azure virtual networks.

**flow_timeout_in_minutes** - (Optional) The flow timeout in minutes for the Virtual Network, which is used to enable connection tracking for intra-VM flows.  Possible values are between 4 and 30 minutes.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
azure_rm_virtualnetwork
azure_rm_virtualnetwork_info

##### ADDITIONAL INFORMATION
Flow Timeouts are disabled by default.  With flow timeouts disabled, Network Flow Logs will not accurately log connection bytes transferred or connection closes for inbound TCP connections.  This is all outlined in [this Microsoft article](https://learn.microsoft.com/en-us/azure/network-watcher/network-watcher-nsg-flow-logging-overview).

> Issues with User-defined Inbound TCP rules: [Network Security Groups (NSGs)](https://learn.microsoft.com/en-us/azure/virtual-network/network-security-groups-overview) are implemented as a [Stateful firewall](https://en.wikipedia.org/wiki/Stateful_firewall?oldformat=true). However, due to current platform limitations, user-defined rules that affect inbound TCP flows are implemented in a stateless fashion. Due to this, flows affected by user-defined inbound rules become non-terminating. Additionally byte and packet counts are not recorded for these flows. Consequently the number of bytes and packets reported in NSG Flow Logs (and Traffic Analytics) could be different from actual numbers. This can be resolved by setting the [FlowTimeoutInMinutes](https://learn.microsoft.com/en-us/powershell/module/az.network/set-azvirtualnetwork) property on the associated virtual networks to a non-null value. Default stateful behavior can be achieved by setting FlowTimeoutInMinutes to 4 minutes. For long running connections, where you do not want flows disconnecting from a service or destination, FlowTimeoutInMinutes can be set to a value upto 30 minutes.

Since that article was written, flow timeouts are now configurable in the Azure portal:
![image](https://user-images.githubusercontent.com/43563416/199570986-51a83ae6-0d2e-44c4-a146-1e77a8ee343c.png)

Example of how to configure:
```yaml
    - name: Create a virtual network
      azure_rm_virtualnetwork:
        resource_group: myResourceGroup
        name: myVirtualNetwork
        address_prefixes_cidr:
            - "10.1.0.0/16"
            - "172.100.0.0/16"
        dns_servers:
            - "127.0.0.1"
            - "127.0.0.2"
        flow_timeout: 4
        tags:
            testing: testing
            delete: on-exit
```
