### ISSUE TITLE
Azure Container Instance Module

### ISSUE THREAD

**Issue by captainrdubb** [ansible/ansible_collections_azure#1014]
##### SUMMARY
I need to set vnet and subnet for a container group

##### ISSUE TYPE
Allow users to set vnet and subnet

##### COMPONENT NAME
[azure_rm_containerinstance](https://github.com/ansible-collections/azure/blob/8707edf10f94b8d89bca13b060259e23350725c7/plugins/modules/azure_rm_containerinstance.py)

##### ADDITIONAL INFORMATION

Inspired by the need to add a [NAT gateway to an Azure Container Instance](https://learn.microsoft.com/en-us/azure/container-instances/container-instances-nat-gateway#deploy-aci-in-a-virtual-network). 

The Azure CLI flavor
```bash
az container create \
  --name appcontainer \
  --resource-group $resourceGroup \
  --image mcr.microsoft.com/azuredocs/aci-helloworld \
  --vnet aci-vnet \
  --vnet-address-prefix 10.0.0.0/16 \
  --subnet aci-subnet \
  --subnet-address-prefix 10.0.0.0/24
```

The Ansible Flavor
```yaml
- name: Deploy Container
  hosts: localhost

  tasks:
  - name: Deploy container instance
    azure_rm_containerinstance:
      vnet: {{ vnet_name }}
      subnet: {{ subnet_name }}
      name: '{{ container_group_name }}'
      containers:
          // container stuff
      volumes:
          // volume stuff
```
