### ISSUE TITLE
azure_rm_keyvault fails if sku family isn't provided

### ISSUE THREAD

**Issue by tgillitzer** [ansible/ansible_collections_azure#1045]
##### SUMMARY

azure_rm_keyvault fails if sku family isn't provided.   Error is:
Error creating the Key Vault instance: Parameter 'Sku.family' can not be None."

example task that fails (from docs):
```
- name: Create instance of Key Vault
  azure_rm_keyvault:
    resource_group: myResourceGroup
    vault_name: samplekeyvault
    enabled_for_deployment: yes
    vault_tenant: 72f98888-8666-4144-9199-2d7cd0111111
    sku:
      name: standard
    access_policies:
      - tenant_id: 72f98888-8666-4144-9199-2d7cd0111111
        object_id: 99998888-8666-4144-9199-2d7cd0111111
        keys:
          - get
          - list
```

Example task that succeeds:
```
- name: Create instance of Key Vault
  azure_rm_keyvault:
    resource_group: myResourceGroup
    vault_name: samplekeyvault
    enabled_for_deployment: yes
    vault_tenant: 72f98888-8666-4144-9199-2d7cd0111111
    sku:
      family: A
      name: standard
    access_policies:
      - tenant_id: 72f98888-8666-4144-9199-2d7cd0111111
        object_id: 99998888-8666-4144-9199-2d7cd0111111
        keys:
          - get
          - list
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure_rm_keyvault

##### ANSIBLE VERSION

```
ansible [core 2.13.4]
  config file = /root/.ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.10/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.10.7 (main, Sep 13 2022, 14:31:33) [GCC 10.2.1 20210110]
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```
# /root/.ansible/collections/ansible_collections
Collection         Version
------------------ -------
azure.azcollection 1.13.0

# /usr/local/lib/python3.10/site-packages/ansible_collections
Collection         Version
------------------ -------
azure.azcollection 1.13.0
```

##### CONFIGURATION

```
CALLBACKS_ENABLED(/root/.ansible.cfg) = ['profile_tasks']
```

##### STEPS TO REPRODUCE

```
Container FROM python:3
```

##### EXPECTED RESULTS

Keyvault should be created without specifying a family as it does in collection version 1.13.

##### ACTUAL RESULTS

Error creating the Key Vault instance: Parameter 'Sku.family' can not be None."

```
[WARNING]: Azure API profile latest does not define an entry for KeyVaultManagementClient
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error creating the Key Vault instance: Parameter 'Sku.family' can not be None."}
```
