### ISSUE TITLE
azure_rm_dnsrecordset can not update SOA record (unable to convert to long)

### ISSUE THREAD

**Issue by akira6592** [ansible/ansible_collections_azure#1047]
##### SUMMARY

azure_rm_dnsrecordset can not update SOA record with error `unable to convert to long`.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

- `azure_rm_dnsrecordset`

##### ANSIBLE VERSION

```paste below
ansible [core 2.12.1]
  config file = None
  configured module search path = ['/Users/akira/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/akira/envs/azure/lib/python3.9/site-packages/ansible
  ansible collection location = /Users/akira/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/akira/envs/azure/bin/ansible
  python version = 3.9.10 (main, Jan 15 2022, 11:48:04) [Clang 13.0.0 (clang-1300.0.29.3)]
  jinja version = 3.0.3
  libyaml = True
```

##### COLLECTION VERSION

```paste below
% ansible-galaxy collection list azure.azcollection

# /Users/akira/.ansible/collections/ansible_collections
Collection         Version
------------------ -------
azure.azcollection 1.14.0 
```

##### CONFIGURATION

```paste below
% ansible-config dump --only-changed
%   # enmpty
```

##### OS / ENVIRONMENT

macOS 12.6

##### STEPS TO REPRODUCE

```yaml
    - name: config soa
      azure.azcollection.azure_rm_dnsrecordset:
        resource_group: "{{ resource_group }}"
        relative_name: "@"
        zone_name: zone01.example.com
        record_type: SOA
        records:
          - host: ns1-07.example.com
            email: azuredns-hostmaster.example.com
            expire_time: 2419200
            minimum_ttl: 300
            refresh_time: 3600
            retry_time: 300
            serial_number: 2022121601
```

##### EXPECTED RESULTS

```
TASK [config soa] ******************************************************************************************
changed: [localhost]
```

##### ACTUAL RESULTS

```paste below
TASK [config soa] ******************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "argument 'serial_number' is of type <class 'int'> found in 'records'. and we were unable to convert to long: 'NoneType' object is not callable"}
```

##### ADDITIONAL INFORMATION

If I changed the `long` below to `int`, it seemed to work fine.

https://github.com/ansible-collections/azure/blob/v1.14.0/plugins/modules/azure_rm_dnsrecordset.py#L312-L316

before

```python
        serial_number=dict(type='long'),
        refresh_time=dict(type='long'),
        retry_time=dict(type='long'),
        expire_time=dict(type='long'),
        minimum_ttl=dict(type='long')
```

after

```python
        serial_number=dict(type='int'),
        refresh_time=dict(type='int'),
        retry_time=dict(type='int'),
        expire_time=dict(type='int'),
        minimum_ttl=dict(type='int')
```
