### ISSUE TITLE
IoTHub - Deployment / Configuration Module

### ISSUE THREAD

**Issue by vasdee** [ansible/ansible_collections_azure#1063]
##### SUMMARY

Include a module that allows creating the following iothub features

* Automatic Deployment / Layered Deployment 
* Module Twin Configuration / Device Twin Configuration

Essentially replicating what is available in the portal 

![image](https://user-images.githubusercontent.com/18690030/210733198-2ad9062a-ca61-49e4-b8b1-158083ff9ec2.png)

These are current available in the azure cli - `az iot edge deployment` and `az iot hub configuration create` both have quite a lot in common with their arguments.

The module should be smart enough to check if the deployment contents has changed, and provide a force/override flag to allow the deployment or configuration to be deleted and re-created ( as it is immutable )

Some arguments like, target, label, tags etc are updatable. Only the content of the deployment is immutable, requiring the deployment to be deleted and re-created. Doing this via the azure cli in ansible is quite cumbersome 

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

azure_rm_iot_deployment

azure_rm_iot_configuration

##### ADDITIONAL INFORMATION

```
- name: Create, Update or Replace the deployment {{ deployment_id }} in iothub - {{ iothub }}
  azure.azcollection.azure_rm_iot_deployment:
      hub: "{{ iothub_name }}"
      resource-group: "{{ resource_group }}"
      subscription: "{{ subscription }}"
      deployment_id: "{{ deployment_id }}" 
      priority: "{{ configuration_priority }}"
      labels: "{{ configuration_labels }}"
      target-condition: "{{ configuration_target_condition }}"
      content: "{{ configuration_tmp_file.path }}"
      layered: true
```
