### ISSUE TITLE
azure_rm_adserviceprincipal_info seems to use the wrong URL

### ISSUE THREAD

**Issue by tgillitzer** [ansible/ansible_collections_azure#1066]
##### SUMMARY
When you call azure_rm_adserviceprincipal_info, if you request a service principal by app_id that is different from the user you are authenticating as (client_id), you get an insufficient permissions error.

If you pass the same ID for the app_id as the user you authenticate as, then it works successfully.

Debugging a little, it looks like the wrong URI is used for the API call.

[MS documentation](https://learn.microsoft.com/en-us/graph/api/serviceprincipal-get?view=graph-rest-1.0&tabs=http) says to get a Service Principal, you should use the following URL:
GET https://graph.microsoft.com/v1.0/servicePrincipals/00063ffc-54e9-405d-b8f3-56124728e051

The module is using this URL instead
when requesting by app_id:
https://graph.windows.net/**tenantId**/servicePrincipals?$filter=servicePrincipalNames%2Fany%28c%3Ac%20eq%20%27**clientId**%27%29&api-version=1.6

Requesting by object_id fails the same way as above for both scenarios and uses the following URL:
https://graph.windows.net/**tenantId**/servicePrincipals/**object_id**?api-version=1.6

I also get the same error when trying to create a service principal using azure_rm_adserviceprincipal_info.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure_rm_adserviceprincipal_info
azure_rm_adserviceprincipal

##### ANSIBLE VERSION
```
ansible [core 2.14.1]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.10/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.10.9 (main, Dec 21 2022, 18:59:22) [GCC 10.2.1 20210110] (/usr/local/bin/python)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION
```
# /root/.ansible/collections/ansible_collections
Collection         Version
------------------ -------
azure.azcollection 1.14.0
```

##### CONFIGURATION
```
CONFIG_FILE() = None
INTERPRETER_PYTHON(env: ANSIBLE_PYTHON_INTERPRETER) = python
```

##### OS / ENVIRONMENT
container based on python:3.10

##### STEPS TO REPRODUCE

We create a service principal using the REST api
POST https://graph.microsoft.com/v1.0/applications, Body displayName: "{{ service_principal_name }}"
POST https://graph.microsoft.com/v1.0/servicePrincipals, Body appId: "{{ service_principal_application_id }}"

Then try to get it with the following task:
```
- name: Get service principal via ansible
    azure.azcollection.azure_rm_adserviceprincipal_info:
      app_id: "{{ service_principal_application_id }}"
      subscription_id: "{{ subscription_id }}"
      tenant: "{{ tenant_id }}"
      client_id: "{{ client_id }}"
      secret: "{{ secret }}"
    register: service_principal_get_results
```

##### EXPECTED RESULTS
The service principal info

##### ACTUAL RESULTS
An error from Azure

```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "failed to get service principal info Insufficient privileges to complete the operation."}
```
