### ISSUE TITLE
Allow users to specify more than 2 DNS servers in the `azure_rm_virtualnetwork` module.

### ISSUE THREAD

**Issue by kmj251** [ansible/ansible_collections_azure#1081]
##### SUMMARY

The `azure_rm_virtualnetwork` does not allow us to specify more than 2 DNS servers for a VNet. We have a requirement to have 3.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

azure_rm_virtualnetwork

##### ANSIBLE VERSION

```
ansible [core 2.13.6]
  config file = /home/vscode/cloud_platform.general_ansible_collection/ansible.cfg
  configured module search path = ['/home/vscode/cloud_platform.general_ansible_collection/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/vscode/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.8.13 (default, Jun 24 2022, 15:27:57) [GCC 8.5.0 20210514 (Red Hat 8.5.0-13)]
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```
Collection         Version
------------------ -------
azure.azcollection 1.14.0 
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml

```

##### EXPECTED RESULTS

Allow us to specify more than 2 DNS servers.

##### ACTUAL RESULTS

```paste below

```

**Comment by akira6592** [comment]
@kmj251 Hello. How did you specify `dns_servers` options? And how actual result?

As far as I could try, the bellow task works fine.

```yaml
- name: Create a virtual network
  azure.azcollection.azure_rm_virtualnetwork:
    resource_group: myResourceGroup
    name: myVirtualNetwork
    dns_servers:
        - "127.0.0.1"
        - "127.0.0.2"
```

ACTUAL RESULTS
```
TASK [Create a virtual network] **********************************************
changed: [localhost]
```

and...
```
$ az network vnet show -n myVirtualNetwork -g myResourceGroup
...omit...
  "dhcpOptions": {
    "dnsServers": [
      "127.0.0.1",
      "127.0.0.2"
    ]
  },
...omit...
```
