### ISSUE TITLE
azure_rm_securitygroup is changed without actual changes when only capitalization differs

### ISSUE THREAD

**Issue by Nothing4You** [ansible/ansible_collections_azure#1095]
##### SUMMARY
Changing capitalization of NSG rule names results in the task always being "changed" but not actually applying changes.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure_rm_securitygroup

##### ANSIBLE VERSION
```
ansible [core 2.14.2]
  config file = .../project/ansible.cfg
  configured module search path = ['.../project/library']
  ansible python module location = /Users/$USER/.asdf/installs/python/3.10.10/lib/python3.10/site-packages/ansible
  ansible collection location = /Users/$USER/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/$USER/.asdf/installs/python/3.10.10/bin/ansible
  python version = 3.10.10 (main, Feb 14 2023, 20:20:54) [Clang 14.0.0 (clang-1400.0.29.202)] (/Users/$USER/.asdf/installs/python/3.10.10/bin/python3.10)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION
```
# /Users/$USER/.ansible/collections/ansible_collections
Collection         Version
------------------ -------
azure.azcollection 1.14.0

# /Users/$USER/.asdf/installs/python/3.10.10/lib/python3.10/site-packages/ansible_collections
Collection         Version
------------------ -------
azure.azcollection 1.14.0
```

##### CONFIGURATION
```
ANSIBLE_NOCOWS(.../project/ansible.cfg) = True
CONFIG_FILE() = .../project/ansible.cfg
DEFAULT_BECOME(.../project/ansible.cfg) = False
DEFAULT_BECOME_ASK_PASS(.../project/ansible.cfg) = False
DEFAULT_BECOME_METHOD(.../project/ansible.cfg) = sudo
DEFAULT_BECOME_USER(.../project/ansible.cfg) = root
DEFAULT_FILTER_PLUGIN_PATH(.../project/ansible.cfg) = ['.../project/library/plugins/filter']
DEFAULT_FORKS(.../project/ansible.cfg) = 5
DEFAULT_HOST_LIST(.../project/ansible.cfg) = ['.../project/inventory']
DEFAULT_LOOKUP_PLUGIN_PATH(.../project/ansible.cfg) = ['.../project/library/plugins/lookup']
DEFAULT_MANAGED_STR(.../project/ansible.cfg) = ...
DEFAULT_MODULE_PATH(.../project/ansible.cfg) = ['.../project/library']
DEFAULT_VAULT_ID_MATCH(.../project/ansible.cfg) = true
INTERPRETER_PYTHON(.../project/ansible.cfg) = auto_silent
MAX_FILE_SIZE_FOR_DIFF(.../project/ansible.cfg) = 1044480
PERSISTENT_COMMAND_TIMEOUT(.../project/ansible.cfg) = 300
RETRY_FILES_ENABLED(.../project/ansible.cfg) = True
```

##### OS / ENVIRONMENT
macOS 13.2.1 (22D68)

##### STEPS TO REPRODUCE

Initialize:

```yaml
- hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Update NSG
      diff: true
      azure.azcollection.azure_rm_securitygroup:
        subscription_id: "{{ nsg_subscription_id }}"
        resource_group: "{{ nsg_resource_group }}"
        name: testing-ansible
        purge_rules: yes
        rules:
          - name: Managed-rule
            priority: 100
            access: Deny
            source_address_prefix: 192.168.252.251/32
            destination_address_prefix: 192.168.252.251/32
            direction: Inbound
            description: test ansible rule
```

Always changed with no change:
```yaml
- hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Update NSG
      diff: true
      azure.azcollection.azure_rm_securitygroup:
        subscription_id: "{{ nsg_subscription_id }}"
        resource_group: "{{ nsg_resource_group }}"
        name: testing-ansible
        purge_rules: yes
        rules:
          - name: managed-rule
            priority: 100
            access: Deny
            source_address_prefix: 192.168.252.251/32
            destination_address_prefix: 192.168.252.251/32
            direction: Inbound
            description: test ansible rule
```

##### EXPECTED RESULTS
Option 1: Rule names are considered case insensitive, documented as such, and the second task doesn't show as changed.
Option 2: Rule names are considered case sensitive and are corrected to match the definitions.

##### ACTUAL RESULTS
Task reports changed, no matter how often you run it, but the rules are not renamed.

```
PLAY [localhost] *************************************************************************************************

TASK [Update NSG] ************************************************************************************************
changed: [localhost]

PLAY RECAP *******************************************************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```
