### ISSUE TITLE
How to get IP address of a VMSS instance?

### ISSUE THREAD

**Issue by N00ree** [ansible/ansible_collections_azure#1098]
Hi,

I need help finding a way to get the private IP address of a Virtual Machine Scale Set instance.

I tried using both azure_rm_virtualmachinescaleset_info and azure_rm_virtualmachinescalesetinstance_info modules, but both of them don't provide any IP info.

Is there any way to achieve this with the azcollection? 

Any help is appreciated, thanks.
Regards

**Comment by akira6592** [comment]
Hello @N00ree .

You can use `azure.azcollection.azure_rm_resource_info` module.

Here is simple sample.

```yaml
- name: Get scaleset info Instance ID 0
  azure.azcollection.azure_rm_resource_info:
    resource_group: "{{ resource_group }}"
    provider: compute
    resource_type: virtualMachineScaleSets
    resource_name: "{{ vmss_name }}"
    api_version: 2022-11-01
    subresource:
      - type: virtualMachines
        name: 0     # in this case instance ID 0
  register: register_instance

- name: Get Network Interface ID
  azure.azcollection.azure_rm_resource_info:
    url: "{{ register_instance.response[0].properties.networkProfile.networkInterfaces[0].id }}"
  register: register_nic

- name: Debug Private IP address
  ansible.builtin.debug:
    msg: "{{ register_nic.response[0].properties.ipConfigurations[0].properties.privateIPAddress }}"    # e.g. 10.0.0.4
```

Using [`Virtual Machine Scale Set VMs - Get`](https://learn.microsoft.com/en-us/rest/api/compute/virtual-machine-scale-set-vms/get?tabs=HTTP) API endpoint.
