### ISSUE TITLE
azure_rm_publicipaddress cannot use Standard SKU with IPv6

### ISSUE THREAD

**Issue by imrejonk** [ansible/ansible_collections_azure#110]
This issue was re-opened here, original discussion can be found in https://github.com/ansible/ansible/issues/66849.

##### SUMMARY

I'm attempting to create a static IPv6 address with the azure_rm_publicipaddress module. Static IPv6 addresses are only supported with the 'Standard' SKU (see [Limitations](https://docs.microsoft.com/en-us/azure/virtual-network/ipv6-public-ip-address-prefix#limitations)). Setting this SKU however results in a StandardSkuPublicIPAddressesMustBeStatic Azure Error, even though I set `allocation_method` to `Static`.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

azure_rm_publicipaddress

##### ANSIBLE VERSION

```paste below
ansible 2.9.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/imre/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/imre/.local/share/virtualenvs/debops-ciphermail-QJnPILZz/lib/python3.7/site-packages/ansible
  executable location = /home/imre/.local/share/virtualenvs/debops-ciphermail-QJnPILZz/bin/ansible
  python version = 3.7.3 (default, Apr  3 2019, 05:39:12) [GCC 8.3.0]
```

##### CONFIGURATION

```paste below
[empty]
```

##### OS / ENVIRONMENT

I'm running Ansible 2.9.4 inside a virtual environment with Python 3.7.3 on Debian 10.2. These are the Azure client libraries in use:
```
azure-cli-core==2.0.35
azure-cli-nspkg==3.0.2
azure-common==1.1.11
azure-graphrbac==0.40.0
azure-keyvault==1.0.0a1
azure-mgmt-authorization==0.51.1
azure-mgmt-automation==0.1.1
azure-mgmt-batch==5.0.1
azure-mgmt-cdn==3.0.0
azure-mgmt-compute==4.4.0
azure-mgmt-containerinstance==1.4.0
azure-mgmt-containerregistry==2.0.0
azure-mgmt-containerservice==4.4.0
azure-mgmt-cosmosdb==0.5.2
azure-mgmt-devtestlabs==3.0.0
azure-mgmt-dns==2.1.0
azure-mgmt-hdinsight==0.1.0
azure-mgmt-iothub==0.7.0
azure-mgmt-keyvault==1.1.0
azure-mgmt-loganalytics==0.2.0
azure-mgmt-marketplaceordering==0.1.0
azure-mgmt-monitor==0.5.2
azure-mgmt-network==2.3.0
azure-mgmt-nspkg==2.0.0
azure-mgmt-rdbms==1.4.1
azure-mgmt-redis==5.0.0
azure-mgmt-resource==2.1.0
azure-mgmt-servicebus==0.5.3
azure-mgmt-sql==0.10.0
azure-mgmt-storage==3.1.0
azure-mgmt-trafficmanager==0.50.0
azure-mgmt-web==0.41.0
azure-nspkg==2.0.0
azure-storage==0.35.1
```

##### STEPS TO REPRODUCE

```yaml
---

- name: Manage Azure cloud infrastructure
  hosts: localhost
  tasks:

    - name: Create static IPv6 address
      azure_rm_publicipaddress:
        name: 'testimre-ipv6'
        resource_group: 'ansible'
        location: 'centralus'
        version: 'ipv6'
        sku: 'Standard'
        allocation_method: 'Static'
```

##### EXPECTED RESULTS

A static IPv6 address should be created with 'Standard' SKU.

##### ACTUAL RESULTS

```paste below
Error creating or updating testimre-ipv6 - Azure Error: StandardSkuPublicIPAddressesMustBeStatic
    Message: Standard sku publicIp /subscriptions/CENSORED/resourceGroups/ansible/providers/Microsoft.Network/publicIPAddresses/testimre-ipv6 must have AllocationMethod set to Static.
```
