### ISSUE TITLE
azure_rm_webapp php added when targeting net_framework v7.0

### ISSUE THREAD

**Issue by sqrlmstr5000** [ansible/ansible_collections_azure#1105]
##### SUMMARY
When creating a web app via azure_rm_webapp targeting `net_framework` version `v7.0` the `php` framework is getting added as well. I'm assuming this is because `v7.0` is not listed in the supported options for `version`. I'm surprised it actually worked but this is the result. The WebApp was created successfully in Azure but targeting multiple frameworks. I was able to change set it correctly in the Azure Portal as a workaround. 

This is part feature enhancement to bring the `azure_rm_webapp` module up to what is in the Azure Portal and as a result this should fix the bug I'm experiencing. 

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
ansible [core 2.14.3]
```

##### COLLECTION VERSION

```paste below
azure.azcollection 1.14.0
```

##### CONFIGURATION

```paste below
ansible-playbook playbook.yml
```

##### OS / ENVIRONMENT

Ubuntu 22.04.1 LTS

##### STEPS TO REPRODUCE

```yaml
  - name: Create app service 
    azure_rm_webapp:
      state: "{{ state }}"
      resource_group: "{{ resource_group }}"
      name: "{{ webapp_name }}"
      always_on: true
      plan:
        resource_group: "{{ resource_group }}"
        name: "{{ plan_name }}"
        is_linux: false
        sku: "{{ plan_sku }}"
        number_of_workers: 1
      frameworks:
        - name: "net_framework"
          version: "v7.0"
    tags:
      - webapp
```

##### EXPECTED RESULTS

```
ok: [localhost] => {
    "webapp_out": {
        "changed": false,
        "failed": false,
        "webapps": [
            {
...
                "frameworks": [
                    {
                        "name": "net_framework",
                        "version": "v7.0"
                    }
                ],
...
            }
        ]
    }
}
```

##### ACTUAL RESULTS

Here is the debug output from the playbook run. You can see that `php` version `5.6` is added to the frameworks of the webapp when it was never listed in the original module configuration. The WebApp was created successfully in Azure but targeting multiple frameworks. 

```paste below
ok: [localhost] => {
    "webapp_out": {
        "changed": false,
        "failed": false,
        "webapps": [
            {
...
                "frameworks": [
                    {
                        "name": "net_framework",
                        "version": "v7.0"
                    },
                    {
                        "name": "php",
                        "version": "5.6"
                    }
                ],
...
            }
        ]
    }
}

```
