### ISSUE TITLE
Unsupported Parameters

### ISSUE THREAD

**Issue by isbn390** [ansible/ansible_collections_azure#1118]
I am using azure.azcollection.azure_rm_aks module for creating aks and as per official document https://docs.ansible.com/ansible/latest/collections/azure/azcollection/azure_rm_aks_module.html#requirements, parameters network_plugin and log_analytics_workspace_resource_id are supported. But I'm getting an error message

"msg": "Unsupported parameters for (azure_rm_aks) module: network_plugin, workspace_resource_id. Supported parameters include: aad_profile, ad_user, addon, adfs_authority_url, agent_pool_profiles,...........................................

azure.azcollection vesion used is 1.14.0

**Comment by akira6592** [comment]
Hello @isbn390 .

Could you tell us your playbook? It should help to resolve the issue.

According to the document, `network_plugin` parameter should be specified under `network_profile`.

And `log_analytics_workspace_resource_id` parameter should be specified under `monitoring` under `addon`.

Example:

```yaml
    - name: Create an AKS instance
      azure.azcollection.azure_rm_aks:
        name: myAKS
        network_profile:
          network_plugin: azure     # here
        addon:
          monitoring:
            log_analytics_workspace_resource_id: myworkspace   # here
        # omit
```
