### ISSUE TITLE
azure_rm_resource idempotency fails for resources that have a list of dicts as a property

### ISSUE THREAD

**Issue by mtraynham** [ansible/ansible_collections_azure#113]
##### SUMMARY
_Copied from https://github.com/ansible/ansible/issues/56356_

The [azure_rm_resource](https://github.com/ansible-collections/azure/blob/dev/plugins/modules/azure_rm_resource.py#L395) uses [ansible.module_utils.dict_transformations.dict_merge](https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/common/dict_transformations.py#L111) for it's idempotency check with the server.  It first merges the server's response with the user provided data and then does a `==` comparison on the two. 
 Unfortunately, this `dict_merge` doesn't recurse through list objects with dicts contained in them.  Therefore, any configuration with a list of dict objects will always be different.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure_rm_resource

##### ANSIBLE VERSION

```paste below
ansible 2.8.0rc2
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Mac OS X

##### STEPS TO REPRODUCE

```yaml
    - name: Creating an Azure Virtual Network Gateway
      azure_rm_resource:
        api_version: "{{ azure_api_version }}"
        ad_user: "{{ azure_user }}"
        password: "{{ azure_password }}"
        subscription_id: "{{ azure_subscription_id }}"
        url: "{{ azure_api_network_prefix }}/virtualNetworkGateways/{{ azure_virtual_network_gateway_name }}"
        idempotency: true
        body:
          location: "{{ azure_location }}"
          properties:
            sku:
              name: Standard
              tier: Standard
            gatewayType: ExpressRoute
            ipConfigurations:
              - name: default
                properties:
                  privateIPAllocationMethod: Dynamic
                  subnet:
                    id: "{{ azure_virtual_network.state.id }}/subnets/GatewaySubnet"
                  publicIPAddress:
                    id: "{{ azure_api_network_prefix }}/publicIPAddresses/{{ azure_public_ip_address.state.name }}"
```

Because this may be hard to recreate, I've pasted below a simple python script which defines the variables being compared (e.g. `body` and `response`) and shows how `dict_merge` is improperly used here.

```python
body = {
    'location': 'westus2',
    'properties': {
        'ipConfigurations': [
            {
                'name': 'default',
                'properties': {
                    'publicIPAddress': {
                        'id': '/subscriptions/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX/resourceGroups/12341234/providers/Microsoft.Network/publicIPAddresses/ansiblePublicIpAddress'
                    },
                    'subnet': {
                        'id': '/subscriptions/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX/resourceGroups/12341234/providers/Microsoft.Network/virtualNetworks/ansibleVirtualNetwork/subnets/GatewaySubnet'
                    }
                }
            }
        ],
        'sku': {
            'name': 'Standard',
            'tier': 'Standard'
        },
        'gatewayType': 'ExpressRoute'
    }
}

response = {
    'name': 'ansibleVirtualNetworkGateway',
    'id': '/subscriptions/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX/resourceGroups/12341234/providers/Microsoft.Network/virtualNetworkGateways/ansibleVirtualNetworkGateway',
    'etag': 'W/\"XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX\"',
    'type': 'Microsoft.Network/virtualNetworkGateways',
    'location': 'westus2',
    'properties': {
        'provisioningState': 'Succeeded',
        'resourceGuid': 'XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX',
        'ipConfigurations': [
            {
                'name': 'default',
                'id': '/subscriptions/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX/resourceGroups/12341234/providers/Microsoft.Network/virtualNetworkGateways/ansibleVirtualNetworkGateway/ipConfigurations/default',
                'etag': 'W/\"XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX\"',
                'type': 'Microsoft.Network/virtualNetworkGateways/ipConfigurations',
                'properties': {
                    'provisioningState': 'Succeeded',
                    'privateIPAllocationMethod': 'Dynamic',
                    'publicIPAddress': {
                        'id': '/subscriptions/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX/resourceGroups/12341234/providers/Microsoft.Network/publicIPAddresses/ansiblePublicIpAddress'
                    },
                    'subnet': {
                        'id': '/subscriptions/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX/resourceGroups/12341234/providers/Microsoft.Network/virtualNetworks/ansibleVirtualNetwork/subnets/GatewaySubnet'
                    }
                }
            }
        ],
        'sku': {
            'name': 'Standard',
            'tier': 'Standard',
            'capacity': 2
        },
        'gatewayType': 'ExpressRoute',
        'vpnType': 'PolicyBased',
        'enableBgp': False,
        'activeActive': False
    }
}


from ansible.module_utils.common.dict_transformations import dict_merge, recursive_diff
from json import dumps

print(dumps(dict_merge(response, body), indent=4, separators=(',', ': ')))
for x in recursive_diff(dict_merge(response, body), response):
    print(dumps(x, indent=4, separators=(',', ': ')))

```

##### EXPECTED RESULTS
No differences from `dict_merge` or a different applicable method to copy existing resource values to the user spec'd resource.

##### ACTUAL RESULTS
Changed on second invocation.

Results from the Python script:
```
{
    "name": "ansibleVirtualNetworkGateway",
    "id": "/subscriptions/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX/resourceGroups/12341234/providers/Microsoft.Network/virtualNetworkGateways/ansibleVirtualNetworkGateway",
    "etag": "W/\"XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX\"",
    "type": "Microsoft.Network/virtualNetworkGateways",
    "location": "westus2",
    "properties": {
        "provisioningState": "Succeeded",
        "resourceGuid": "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX",
        "ipConfigurations": [
            {
                "name": "default",
                "properties": {
                    "publicIPAddress": {
                        "id": "/subscriptions/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX/resourceGroups/12341234/providers/Microsoft.Network/publicIPAddresses/ansiblePublicIpAddress"
                    },
                    "subnet": {
                        "id": "/subscriptions/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX/resourceGroups/12341234/providers/Microsoft.Network/virtualNetworks/ansibleVirtualNetwork/subnets/GatewaySubnet"
                    }
                }
            }
        ],
        "sku": {
            "name": "Standard",
            "tier": "Standard",
            "capacity": 2
        },
        "gatewayType": "ExpressRoute",
        "vpnType": "PolicyBased",
        "enableBgp": false,
        "activeActive": false
    }
}
{
    "properties": {
        "ipConfigurations": [
            {
                "name": "default",
                "properties": {
                    "publicIPAddress": {
                        "id": "/subscriptions/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX/resourceGroups/12341234/providers/Microsoft.Network/publicIPAddresses/ansiblePublicIpAddress"
                    },
                    "subnet": {
                        "id": "/subscriptions/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX/resourceGroups/12341234/providers/Microsoft.Network/virtualNetworks/ansibleVirtualNetwork/subnets/GatewaySubnet"
                    }
                }
            }
        ]
    }
}
{
    "properties": {
        "ipConfigurations": [
            {
                "name": "default",
                "id": "/subscriptions/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX/resourceGroups/12341234/providers/Microsoft.Network/virtualNetworkGateways/ansibleVirtualNetworkGateway/ipConfigurations/default",
                "etag": "W/\"XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX\"",
                "type": "Microsoft.Network/virtualNetworkGateways/ipConfigurations",
                "properties": {
                    "provisioningState": "Succeeded",
                    "privateIPAllocationMethod": "Dynamic",
                    "publicIPAddress": {
                        "id": "/subscriptions/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX/resourceGroups/12341234/providers/Microsoft.Network/publicIPAddresses/ansiblePublicIpAddress"
                    },
                    "subnet": {
                        "id": "/subscriptions/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX/resourceGroups/12341234/providers/Microsoft.Network/virtualNetworks/ansibleVirtualNetwork/subnets/GatewaySubnet"
                    }
                }
            }
        ]
    }
}
```
