### ISSUE TITLE
azure_rm_roleassignment fails with 'Error creating role assignment: (RoleAssignmentExists)'

### ISSUE THREAD

**Issue by Mohammad-Atif-Khan** [ansible/ansible_collections_azure#1137]
##### SUMMARY

When trying to use the `azure_rm_roleassignment` module and the requested assignment exists, the task fails reporting the same:
```
    Error creating role assignment: (RoleAssignmentExists) The role assignment already exists.
    Code: RoleAssignmentExists 
    Message: The role assignment already exists.
```
instead of continuing with a 'success' since the module should be idempotent.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`azure_rm_roleassignment` 

##### ANSIBLE VERSION

```paste below
/usr/local/lib/python3.8/site-packages/paramiko/transport.py:236: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,
ansible [core 2.12.5.post0]
  config file = None
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/runner/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.8.13 (default, Jun 24 2022, 15:27:57) [GCC 8.5.0 20210514 (Red Hat 8.5.0-13)]
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
bash-4.4# ansible-galaxy collection list azure.azcollection.azure_rm_roleassignment
ERROR! Unexpected Exception, this is probably a bug: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
the full traceback was:

Traceback (most recent call last):
  File "/usr/local/bin/ansible-galaxy", line 97, in <module>
    mycli = getattr(__import__("ansible.cli.%s" % sub, fromlist=[myclass]), myclass)
  File "/usr/local/lib/python3.8/site-packages/ansible/cli/galaxy.py", line 24, in <module>
    from ansible.galaxy.api import GalaxyAPI
  File "/usr/local/lib/python3.8/site-packages/ansible/galaxy/api.py", line 28, in <module>
    from ansible.module_utils.urls import open_url, prepare_multipart
  File "/usr/local/lib/python3.8/site-packages/ansible/module_utils/urls.py", line 115, in <module>
    from urllib3.contrib.pyopenssl import PyOpenSSLContext
  File "/usr/lib/python3.8/site-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/usr/local/lib/python3.8/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/local/lib/python3.8/site-packages/OpenSSL/crypto.py", line 1517, in <module>
    class X509StoreFlags(object):
  File "/usr/local/lib/python3.8/site-packages/OpenSSL/crypto.py", line 1537, in X509StoreFlags
    CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

I'm using ansible-navigator with an Execution Environment on docker CE. The above outputs are from inside the EE container.
The collection version is `v1.15.0` as confirmed by looking at changelog:
```
bash-4.4# head /usr/share/ansible/collections/ansible_collections/azure/azcollection/CHANGELOG.md 
# Change Log

## v1.15.0 (2023-03-15)
```
This is the build file for anisble-builder if that is of interest:
```
---
version: 1

build_arg_defaults:
  EE_BASE_IMAGE: 'quay.io/ansible/ansible-runner:latest'

dependencies:
  galaxy: requirements.yml

additional_build_steps:
  append:
    - RUN echo Build Complete
    - RUN uname -a
```

##### STEPS TO REPRODUCE

1. Assign a role to a resource (a resource group in my case) using the module
2. Re-run the exact same task on the same resource group (role assignment) and it fails, reporting that the assignment already exists

```yaml
- name: "[CRU_] [IAM] Update IAM of given RG"
  azure.azcollection.azure_rm_roleassignment:
    role_definition_id: "{{ role_definition.roledefinitions[0].id }}"
    scope: "{{ rg_info.id }}"
    assignee_object_id: "{{ adgroup_object_id }}"
```
where `role_definition` is the output of the `azure_rm_roledefinition_info` module, containing fully qualified definition ID.

##### EXPECTED RESULTS

The module should simply continue with status 'Ok' (ie unchanged) and not fail as it does currently

##### ACTUAL RESULTS

The task fails with `Code: RoleAssignmentExists` 

```paste below
invocation:
  module_args:
      ad_user:
      adfs_authority_url: null 
      api_profile: latest 
      assignee_object_id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx 
      auth_source: auto 
      cert_validation_mode: null 
      client_id: null 
      cloud_environment: AzureCloud 
      id: null 
      log_mode: null 
      log_path: null 
      name: null 
      password: null 
      profile: null 
      role_definition_id: /subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/providers/Microsoft.Authorization/roleDefinitions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx 
      scope: /subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/RG-Ansible-Resources 
      secret: null 
      state: present 
      subscription_id: null 
      tenant: null 
      thumbprint: null 
      x509_certificate_path: null 
  msg: |- 
    Error creating role assignment: (RoleAssignmentExists) The role assignment already exists.
    Code: RoleAssignmentExists 
    Message: The role assignment already exists.

```

**Comment by Mohammad-Atif-Khan** [comment]
@paultaiton as requested, please see output of    ###`azure_rm_roleassignment_info` with the same parameters:
```
  invocation:
    module_args:
      ad_user: null
      adfs_authority_url: null
      api_profile: latest
      assignee: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
      assignee_object_id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
      auth_source: auto
      cert_validation_mode: null
      client_id: null
      cloud_environment: AzureCloud
      id: null
      log_mode: null
      log_path: null
      name: null
      password: null
      profile: null
      role_definition_id: /subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/providers/Microsoft.Authorization/roleDefinitions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
      scope: /subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/RG-Ansible-Resources
      secret: null
      strict_scope_match: false 
      subscription_id: null     
      tenant: null
      thumbprint: null
      x509_certificate_path: null
  roleassignments:
  - assignee_object_id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    id: /subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/RG-Ansible-Resources/providers/Microsoft.Authorization/roleAssignments/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    name: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    principal_id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    principal_type: Group
    role_definition_id: /subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/providers/Microsoft.Authorization/roleDefinitions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    scope: /subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/RG-Ansible-Resources
    type: Microsoft.Authorization/roleAssignments
resolved_action: azure.azcollection.azure_rm_roleassignment_info
start: '2023-04-03T22:10:53.204558'
task: '[CRU_] [IAM] Get existing IAM on given RG'
task_action: azure.azcollection.azure_rm_roleassignment_info
```
#460

**Comment by paultaiton** [comment]
I apologize for the delay, I haven't had a chance to look at this yet.
I will try to review it in more depth this week. Based on what you've pasted, it should work, and this use case was previously tested, so there may be some dificulty in narrowing down the problem.

**Comment by Fred-sun** [comment]
@paultaiton There is no problem for me to create and re-create role assignments locally. Could you please share your playbook and log details? This will help solve the current problem, and if possible, you can try to reinstall a new environment, thank you!
```e.g.
Case:
- name: create role assignment by id
  azure_rm_roleassignment:
    id: "{{ az_resource_group.resourcegroups[0].id }}/providers/Microsoft.Authorization/roleAssignments/{{ uuid }}"
    assignee_object_id: "{{ az_role_assignments.roleassignments[0].principal_id }}"
    role_definition_id: "/subscriptions/{{ az_resource_group.resourcegroups[0].id.split('/')[2] }}/providers/Microsoft.Authorization/roleDefinitions/{{ az_role_definition_guid }}"

- name: create role assignment by id --------- secondary
  azure_rm_roleassignment:
    id: "{{ az_resource_group.resourcegroups[0].id }}/providers/Microsoft.Authorization/roleAssignments/{{ uuid }}"
    assignee_object_id: "{{ az_role_assignments.roleassignments[0].principal_id }}"
    role_definition_id: "/subscriptions/{{ az_resource_group.resourcegroups[0].id.split('/')[2] }}/providers/Microsoft.Authorization/roleDefinitions/{{ az_role_definition_guid }}"

Output:
TASK [create role assignment by id] ************************************************************************************changed: [localhost]

TASK [create role assignment by id --------- secondary] ****************************************************************ok: [localhost]

**Comment by paultaiton** [comment]
@Fred-sun   in your test, did the second run come back as changed = false ? I'm assuming yes, but want to confirm.

**Comment by Mohammad-Atif-Khan** [comment]
hi @Fred-sun ,

here is the full `tasks.yml` file that is called from another playbook using `include_tasks` module:

```
---
- name: "[VALDN] Subscription"
  block:
    - name: "[VALDN] Get subscription_id for {{ subscription }}"
      azure.azcollection.azure_rm_subscription_info:
        tenant: "{{ tenant_id }}"
        name: "{{ subscription|trim }}"
      register: subinfo_result
    - name: Failed to locate unique subscription
      ansible.builtin.fail:
        msg: "{{ subinfo_result.subscriptions|length }} subscription(s) found with given name: {{ subscription }}"
      when: subinfo_result.subscriptions|length < 1 or subinfo_result.subscriptions|length > 1
    - name: "[VALDN] Set subscription_id"
      ansible.builtin.set_fact:
        subscription_id: "{{ subinfo_result.subscriptions[0].subscription_id }}"
  when: subscription_id is not defined or subscription_id == None

- name: "[VALDN] Get RG ID for {{ rg_name }} in {{ subscription_id }}"
  azure.azcollection.azure_rm_resourcegroup_info:
    subscription_id: "{{ subscription_id }}"
    name: "{{ rg_name|trim }}"
  register: rginfo_result
- name: "Failed to locate RG"
  ansible.builtin.fail:
    msg: "'{{ rg_name }}' could not be found in subscription {{ subscription_id }}"
  when: rginfo_result.resourcegroups|length < 1 or rginfo_result.resourcegroups|length > 1
- name: "[CRU_] [RG] Set rg_info"
  ansible.builtin.set_fact:
    rg_info: "{{ rginfo_result.resourcegroups[0] }}"

- name: "[VALDN] Validate IAM inputs"
  block:
    - name: "[VALDN] Set RBAC Role Group name"
      ansible.builtin.set_fact:
        role_group_name: "{{ rbac_group }}"
      when: rbac_group is defined and rbac_group != None    
    - name: "[VALDN] Check if Role Group with intended name exists"
      azure.azcollection.azure_rm_adgroup_info:
        attribute_name: displayName
        attribute_value: "{{ role_group_name }}"
        tenant: "{{ tenant_id }}"
      register: adgroup_info    
    - name: "[VALDN] Role group '{{ rbac_group }}' exists and will be used"
      ansible.builtin.debug:
        msg: "Role group exists ({{ role_group_name }}) and **will be used**"
      when: adgroup_info.ad_groups|length>0    
    - name: "[VALDN] Role group '{{ rbac_group }}' does not exist - it will be created"
      ansible.builtin.debug:
        msg: "Role group with name provided does not exist and **will be created**: '{{ role_group_name }}'"
      when: adgroup_info.ad_groups|length<1
    - name: "[VALDN] Get Object IDs for ITC users"
      azure.azcollection.azure_rm_aduser_info:
        user_principal_name: "{{ item }}"
        tenant: "{{ tenant_id }}"
      loop: "{{ itc_accounts.split(',')|map('trim') }}"
      register: itc_objects
      when: itc_accounts is defined and itc_accounts != None
  when: not (access_needed is not defined or not access_needed|bool)

- name: "[CRU_] [AAD] Set adgroup_object_id"
  ansible.builtin.set_fact:
    adgroup_object_id: "{{ adgroup_info.ad_groups[0].object_id }}"
  when: "'ad_groups' in adgroup_info and adgroup_info.ad_groups|length>0"
- name: "[CRU_] [AAD] Create new Role group ({{ role_group_name }})"
  azure.azcollection.azure_rm_adgroup:
    display_name: "{{ role_group_name }}"
    mail_nickname: None
    tenant: "{{ tenant_id }}"
  register: adgroup_info_tmp
  when: adgroup_info.ad_groups|length<1
- name: "[CRU_] [AAD] Reset adgroup_info"
  ansible.builtin.set_fact:
    adgroup_object_id: "{{ adgroup_info_tmp.object_id }}"
  when: "'object_id' in adgroup_info_tmp"

- name: "[CRU_] [AAD] Update Role Group with ITC accounts"
  azure.azcollection.azure_rm_adgroup:
    object_id: "{{ adgroup_object_id }}"
    present_members: #"{{ itc_accounts.split(',') }}"
      - "https://graph.windows.net/{{ tenant_id }}/directoryObjects/{{ item.ad_users[0].object_id }}"
    tenant: "{{ tenant_id }}"
    subscription_id: "{{ subscription_id }}"
  loop: "{{ itc_objects.results }}"
  when: itc_accounts is defined and itc_accounts != None

- name: "[CRU_] [IAM] Get 'Contributor' role definition ID in RG's scope"
  azure.azcollection.azure_rm_roledefinition_info:
    scope: "{{ rg_info.id }}"
    role_name: 'Contributor'
  register: role_definition

# - ansible.builtin.debug:
#     msg: "{{ role_definition.roledefinitions[0].id|split('/')|last }}"

- name: "[CRU_] [IAM] Get existing IAM on given RG"
  azure.azcollection.azure_rm_roleassignment_info:
    role_definition_id: "{{ role_definition.roledefinitions[0].id }}"
    scope: "{{ rg_info.id }}"
    assignee_object_id: "{{ adgroup_object_id }}"
  register: result


- name: "[CRU_] [IAM] Update IAM of given RG"
  azure.azcollection.azure_rm_roleassignment:
    role_definition_id: "{{ role_definition.roledefinitions[0].id }}"
    scope: "{{ rg_info.id }}"
    assignee_object_id: "{{ adgroup_object_id }}"
  register: result
  until: result is not failed 
  retries: 1
  delay: 10
```

the relevant output as shared earlier is as follows, please let me know if you were asking for something else:

```
TASK [[CRU_] [IAM] Update IAM of given RG] ***********************************************************************
FAILED - RETRYING: [localhost]: [CRU_] [IAM] Update IAM of given RG (1 retries left).
fatal: [localhost]: FAILED! => {"attempts": 1, "changed": false, "msg": "Error creating role assignment: (RoleAssignmentExists) The role assignment already exists.\nCode: RoleAssignmentExists\nMessage: The role assignment already exists."}

PLAY RECAP *******************************************************************************************************
localhost                  : ok=13   changed=0    unreachable=0    failed=1    skipped=5    rescued=0    ignored=0   
```

I've run this on a new EE since the first time the issue occurred (and upgraded the collection version from `v1.14.0` to `v1.15.0` in the process.

I noticed you've used `id` parameter instead of `scope` that I've used (and not sure where you get the `uuid` from?), perhaps that is the key differentiator - can you try with `scope` instead?

**Comment by Fred-sun** [comment]
> @Fred-sun in your test, did the second run come back as changed = false ? I'm assuming yes, but want to confirm.

@paultaiton Yes, idempotent! Thanks!

**Comment by Fred-sun** [comment]
@Mohammad-Atif-Khan The use of scope is as follows:
```e.g.
- name: create role assignment by scope ---- first
  azure_rm_roleassignment:
    scope: "{{ az_resource_group.resourcegroups[0].id }}"
    assignee_object_id: "{{ az_role_assignments.roleassignments[0].principal_id }}"
    role_definition_id: "/subscriptions/{{ az_resource_group.resourcegroups[0].id.split('/')[2] }}/providers/Microsoft.Authorization/roleDefinitions/{{ az_role_definition_guid }}"

- name: create role assignment by scope -------- secondary
  azure_rm_roleassignment:
    scope: "{{ az_resource_group.resourcegroups[0].id }}"
    assignee_object_id: "{{ az_role_assignments.roleassignments[0].principal_id }}"
    role_definition_id: "/subscriptions/{{ az_resource_group.resourcegroups[0].id.split('/')[2] }}/providers/Microsoft.Authorization/roleDefinitions/{{ az_role_definition_guid }}"

results:

TASK [create role assignment by scope ---- first] **********************************************************************
changed: [localhost]

TASK [create role assignment by scope -------- secondary] **************************************************************
ok: [localhost]

**Comment by Mohammad-Atif-Khan** [comment]
@Fred-sun thanks, but that is exactly how I've been using it.

I just tested it again without Execution Environment and I still get the same error. I even tried bypassing ansible-navigator and using ansible-playbook to run it but still the same.

It seems like the `get_roleassignment()` is either returning None or one of the conditions is not evaluating to True, leading to the execution of `create_roleassignment()`

I cannot get debug print statements to work (sorry I've not developed a module yet) - can you advise how I could get some messages out to stdout? I'm trying to debug the module myself but I cannot get any messages out to view during the execution. I've tried the vanilla `print` and also `self.results['debug_print'].append('Getting Role assignment')` but to no luck.

**Comment by Fred-sun** [comment]
@Mohammad-Atif-Khan Repeated tests have not met your problem. Can you try it in a different environment? Also, makesure that the version installed is v1.15.0(latest version). Thanks!

**Comment by paultaiton** [comment]
> @Mohammad-Atif-Khan Repeated tests have not met your problem. Can you try it in a different environment? Also, makesure that the version installed is v1.15.0(latest version). Thanks!

I have also tried replicating the reported issue without success.

**Comment by Fred-sun** [comment]
@paultaiton Can I have a look at your full script? Thanks!

**Comment by Mohammad-Atif-Khan** [comment]
I did try it in a new environment (v1.15.0) and got the same error.

I'm using a workaround, where I run the info module and check if the role assignment exists first and then conditionally run the role assignment thereafter.

**Comment by Fred-sun** [comment]
@Mohammad-Atif-Khan If the roleassignment you created does not exist, can you successfully create it? Thanks!

**Comment by Mohammad-Atif-Khan** [comment]
@Fred-sun , yes, correct. If did not exist it creates it correctly; however if it does exist, it returns an error.

**Comment by Fred-sun** [comment]
@Mohammad-Atif-Khan Are you still using the script in comments? Thanks!

**Comment by paultaiton** [comment]
> @paultaiton Can I have a look at your full script? Thanks!

```
---
- name: Role Assignment Info Play
  hosts: localhost
  gather_facts: false  # not necessary at this time; localhost provides no useful info.
  tasks:
    - name: List Role Assignments at scope
      azure.azcollection.azure_rm_roleassignment:
        assignee_object_id: "{{ az_role_assignment_assignee | default(omit) }}"
        id: "{{ az_role_assignment_id | default(omit) }}"
        name: "{{ az_role_assignment_name | default(omit) }}"
        role_definition_id: "{{ az_role_definition_id | default(omit) }}"
        scope: "{{ az_role_assignment_scope | default(omit) }}"
        state: present
        subscription_id: "{{ az_subscription_id | default(omit) }}"
      register: az_role_assignment
```

It's pretty basic, I do everything via parameters for testing. I cannot get it to fail on creating a role assignment that already exists.

**Comment by Mohammad-Atif-Khan** [comment]
hi @Fred-sun ,

I only modified it to use the workaround I mentioned before. Here is the relevant YAML:

```
- name: "[CRU_] [IAM] Get existing IAM on given RG"
  azure.azcollection.azure_rm_roleassignment_info:
    role_definition_id: "{{ role_definition.roledefinitions[0].id }}"
    scope: "{{ rg_info.id }}"
    assignee_object_id: "{{ adgroup_object_id }}"
  register: assignment_info


- name: "[CRU_] [IAM] Update IAM of given RG"
  azure.azcollection.azure_rm_roleassignment:
    role_definition_id: "{{ role_definition.roledefinitions[0].id }}"
    scope: "{{ rg_info.id }}"
    assignee_object_id: "{{ adgroup_object_id }}"
  register: result
  until: result is not failed 
  retries: 1
  delay: 10
  when: assignment_info.roleassignments|length<1
```

Something very strange I noticed: I retried the original playbook (without workaround), but on a _different subscription_, and **it worked**! It did **not** fail for an existing assignment.

Any idea what could explain that behavior?
