### ISSUE TITLE
Route table updates delete all existing routes in the route table

### ISSUE THREAD

**Issue by octavteodorescu** [ansible/ansible_collections_azure#1142]
##### SUMMARY
I'm trying to make sense of a behavior of the azure collection, specifically for route tables. 
I'm suspecting it may be a bug, but I'm not quite sure.
In summary, whenever there's a route table update done (ansible execution reporting it as changed), all of the routes in the respective route table, get deleted.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure_rm_routetable
https://github.com/ansible-collections/azure/blob/v1.15.0/plugins/modules/azure_rm_routetable.py#L146-L151

##### ANSIBLE VERSION
```
ansible [core 2.14.4]
  config file = /default/ansible/ot/ansible_verbose_dev.cfg
  configured module search path = ['/default/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /default/.local/lib/python3.9/site-packages/ansible
  ansible collection location = /default/.ansible/collections:/usr/share/ansible/collections
  executable location = /default/.local/bin/ansible
  python version = 3.9.13 (main, Nov  9 2022, 13:16:24) [GCC 8.5.0 20210514 (Red Hat 8.5.0-15)] (/usr/bin/python3.9)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION
```
Collection         Version
------------------ -------
ansible.posix      1.5.2
ansible.utils      2.9.0
azure.azcollection 1.15.0
community.general  6.5.0
```

##### CONFIGURATION
```
ansible-config [core 2.14.4]
  config file = /default/ansible/ot/ansible_verbose_dev.cfg
  configured module search path = ['/default/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /default/.local/lib/python3.9/site-packages/ansible
  ansible collection location = /default/.ansible/collections:/usr/share/ansible/collections
  executable location = /default/.local/bin/ansible-config
  python version = 3.9.13 (main, Nov  9 2022, 13:16:24) [GCC 8.5.0 20210514 (Red Hat 8.5.0-15)] (/usr/bin/python3.9)
  jinja version = 3.1.2
  libyaml = True
Using /default/ansible/ot/ansible_verbose_dev.cfg as config file
CONFIG_FILE() = /default/ansible/ot/ansible_verbose_dev.cfg
DEFAULT_DEBUG(/default/ansible/ot/ansible_verbose_dev.cfg) = True
DEFAULT_HOST_LIST(/default/ansible/ot/ansible_verbose_dev.cfg) = ['/default/ansible/ot/azure_inventory.yml']
DEFAULT_LOG_PATH(/default/ansible/ot/ansible_verbose_dev.cfg) = /default/ansible/ot/reports/run.log
DEFAULT_STDOUT_CALLBACK(/default/ansible/ot/ansible_verbose_dev.cfg) = yaml
DEFAULT_VERBOSITY(/default/ansible/ot/ansible_verbose_dev.cfg) = 3
DISPLAY_ARGS_TO_STDOUT(/default/ansible/ot/ansible_verbose_dev.cfg) = True
DISPLAY_SKIPPED_HOSTS(/default/ansible/ot/ansible_verbose_dev.cfg) = True
HOST_KEY_CHECKING(/default/ansible/ot/ansible_verbose_dev.cfg) = False
SHOW_CUSTOM_STATS(/default/ansible/ot/ansible_verbose_dev.cfg) = True
```

##### OS / ENVIRONMENT
Ansible is running in a container, using: ubi8/ubi-minimal:8.7-1107

##### STEPS TO REPRODUCE
- Create a route table in azure, say with propagate routes set to yes.
- Add 2 or more routes to the respective route table.
- Run the ansible routetable module to set propagate routes to no.

The outcome is the existing routes in that route table are deleted. This happens regardless of the propgate routes setting (ie: the reverse would have the same outcome, where you have the propagation set to no and you update with yes)

```yaml
    - name: "Check route table {{ azure_route_table_name }} configuration"
      azure.azcollection.azure_rm_routetable:
        client_id: "{{ hostvars[target_host].client_id }}"
        secret: "{{ hostvars[target_host].secret }}"
        tenant: "{{ hostvars[target_host].tenant }}"
        subscription_id: "{{ hostvars[target_host].subscription_id }}"
        state: "{{ azure_route_table_state | mandatory }}"
        name: "{{ azure_route_table_name | mandatory }}"
        resource_group: "{{ azure_route_table_resource_group | mandatory }}"
        disable_bgp_route_propagation: "{{ azure_route_table_disable_route_propagation | default(omit) }}"
        tags: "{{ azure_route_table_tags | default(omit) }}"
```

##### EXPECTED RESULTS
**The routes set in the respective route tables are not deleted on a route table change**.
The expectation is the route table module does not remove or modify the routes in any way. Furthermore, in support of this expectation is the fact that there are separate modules for routes vs routetables, whilst the latter is not accepting any route related input data/ parameters.

Also the documentation should at least have a note in this section: https://docs.ansible.com/ansible/latest/collections/azure/azcollection/azure_rm_routetable_module.html#parameter-disable_bgp_route_propagation
To mention that this setting is opposite to the setting in the interface. For a user that's not a native english speaker, this aspect can be easily omitted.

##### ACTUAL RESULTS
**All routes in the route table are deleted.**

What I've been able to trace back to is the following:
- in the code section below, the information retrieved from Azure is correct and contains the routes
https://github.com/ansible-collections/azure/blob/ebce7484bff7387ccc627180088008ed39be4a8d/plugins/modules/azure_rm_routetable.py#L131

- however when the actual method is called for executing the change  (see below), the payload passed in, it does not contain any key/value pair for routes). Whilst I'd expect the Azure API to behave differently, it seems that if the existing routes aren't specified in this payload, they get deleted.
Not sure if this interpretation is correct, but at least it should provide a narrower path to search for understanding the problem.
https://github.com/ansible-collections/azure/blob/ebce7484bff7387ccc627180088008ed39be4a8d/plugins/modules/azure_rm_routetable.py#L146-L151
