### ISSUE TITLE
Use azure_rm_resource_info for querying specific aspects of a resource

### ISSUE THREAD

**Issue by Mohammad-Atif-Khan** [ansible/ansible_collections_azure#1148]
##### SUMMARY

I'm trying to use the `azure_rm_resource_info` module to get the access profile for an AKS cluster as documented here:
https://learn.microsoft.com/en-us/rest/api/aks/managed-clusters/list-cluster-user-credentials
but all I can see is the resource info getting returned and there is no option to suffix the `listClusterUserCredential` to the URL

How can the module be used in such cases?

I've tried using the `url` parameter as below but that gets me an error:
```
---
- name: Get AccessProfile for AKS using REST
  connection: local
  hosts: localhost
  gather_facts: false
  vars:
    resource_name: AK-GLB-PUB-DCCLDA00-AWX-01D
    resource_group: RG-GLB-DMZ-DCCLDA00-AWX-01
    resource_type: managedClusters
    provider: ContainerService
    subscription_id: d900d8d2-0000-0000-0000-12c4a93c4000
  tasks:
    - name: Get Cluster Access Profile
      azure.azcollection.azure_rm_resource_info:
        api_version: 2023-02-01
        subscription_id: d900d8d2-0000-0000-0000-12c4a93c4000
        url: "https://management.azure.com/subscriptions/{{ subscription_id }}/resourceGroups/{{ resource_group }}/providers/Microsoft.ContainerService/managedClusters/{{ resource_name }}/listClusterUserCredential?api-version=2023-02-01"
```

Error:
```
ok: [localhost] => {
    "msg": {
        "changed": false,
        "failed": false,
        "response": [
            {
                "error": {
                    "code": "MissingSubscription",
                    "message": "The request did not have a subscription or a valid tenant level resource provider."
                }
            }
        ],
        "url": "POST https://management.azure.com/subscriptions/d900d8d2-0000-0000-0000-12c4a93c4000/resourceGroups/RG-GLB-DMZ-DCCLDA00-AWX-01/providers/Microsoft.ContainerService/managedClusters/AK-GLB-PUB-DCCLDA00-AWX-01D/listClusterUserCredential?api-version=2023-02-01",
        "warnings": [
            "Azure API profile latest does not define an entry for GenericRestClient"
        ]
    }
}
```

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME

azure_rm_resource_info 
##### ANSIBLE VERSION

```paste below
ansible [core 2.14.4]
  config file = None
  configured module search path = ['/home/mkhan/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/mkhan/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /home/mkhan/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/mkhan/.local/bin/ansible
  python version = 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True
```

**Comment by rmuneer** [comment]
I ran some test for the following module and was able to get correct responses when trying to fetch details on the specific AKS resource, however when tried to include the “listClusterUserCredential” parameter it gave me 503 error stating Method not allowed for the URL. It seems like we can pass the “listClusterUserCredential” parameter as a sub resource attribute for the azure_rm_subscription_info module.

---
- name: Get accessprofiles for AKS using REST
  hosts: localhost
  gather_facts: true
  tasks:
    - name: Get cluster access profiles
      azure.azcollection.azure_rm_resource_info:
        resource_group: test_ansible
        provider: containerservice
        resource_type: managedcluster
        resource_name: testcluster
        api_version: "2023-02-01"
      register: result
    - name: Print output
      debug:
        var: result

**Comment by Mohammad-Atif-Khan** [comment]
So I went back and tried using the `azure_rm_resource` module instead of the azure_rm_resource_info (based off a hint I got from chatGPT, it was dreaming up a new module but the approach prompted me to check this module) and it seems to work. This is the revised way to call the REST API for any given, valid URL:

```
    - name: Get Cluster Access Profile
      azure.azcollection.azure_rm_resource:
        url: "https://management.azure.com/subscriptions/{{ subscription_id }}/resourceGroups/{{ resource_group }}/providers/Microsoft.ContainerService/managedClusters/{{ resource_name }}/listClusterUserCredential?api-version=2023-02-01"
        method: POST
      register: output
        
    - ansible.builtin.debug:
        msg: "{{ output }}"
```

`azure_rm_resource_info` is a bit misleading, since in keeping with the convention of 'query' modules, this should allow for non-PUT requests to the API, and the `azure_rm_resource` module is positioned as 'provisioning' module. Either way, improvement in the docs is warranted for the azure collection (more examples would be a massive improvement by itself).
