### ISSUE TITLE
Literal value of ansible variable returned by keyvaultsecret_info "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"

### ISSUE THREAD

**Issue by Klaas-** [ansible/ansible_collections_azure#1155]
##### SUMMARY

Hi,
I am trying to use ansible to rotate secrets for service principals. During this I noticed that I can not retrieve a secret from a keyvault that equals the secret of the service principal currently in use (ie rotating it's own secret).

I am unsure if this is a problem in the module or a more general issue with ansible-core.

References: https://github.com/ansible/awx/issues/13912

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

azure.azcollection.azure_rm_keyvaultsecret_info

##### ANSIBLE VERSION

```paste below
$ ansible --version
ansible [core 2.13.3]
  config file = /home/username/awx_ansible/ansible.cfg
  configured module search path = ['/home/username/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /home/username/awx_ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.9.13 (main, Nov  9 2022, 13:16:24) [GCC 8.5.0 20210514 (Red Hat 8.5.0-15)]
  jinja version = 3.1.2
  libyaml = True
```
I also verified it with a current ansible-core in a venv and in awx-ee

##### COLLECTION VERSION

```paste below
Collection                     Version
------------------------------ -------
ansible.posix                  1.5.1
awx.awx                        22.0.0
azure.azcollection             1.15.0
community.crypto               2.11.1
community.general              6.5.0
containers.podman              1.10.1
fedora.linux_system_roles      1.35.2
infra.controller_configuration 2.3.1
kubernetes.core                2.4.0
ovirt.ovirt                    3.1.2
servicenow.itsm                2.1.0
```

##### CONFIGURATION

```paste below
$ ansible-config dump --only-changed
COLLECTIONS_PATHS(/home/username/awx_ansible/ansible.cfg) = ['/home/username/awx_ansible/collections']
DEFAULT_ROLES_PATH(/home/username/awx_ansible/ansible.cfg) = ['/home/username/awx_ansible/roles']
```

##### OS / ENVIRONMENT

RHEL 8.7

##### STEPS TO REPRODUCE

You need to load the variables via --extra-vars or add them in playbook

```yaml
cat playbooks/minimal_reproducer.yml
- hosts: localhost
  connection: local

  tasks:
  - name: set service principal client secret in key vault
    azure.azcollection.azure_rm_keyvaultsecret:
      keyvault_uri: "{{ key_vault_uri }}"
      client_id: "{{ service_principal_application_id }}"
      secret: "{{ service_principal_client_secret }}"
      tenant: "{{ service_principal_tenant }}"
      subscription_id: "{{ key_vault_subscription_id }}"
      secret_name: "service-principal-client-secret"
      secret_value: "{{ service_principal_client_secret }}"

  - name: get service principal client secret from key vault
    azure.azcollection.azure_rm_keyvaultsecret_info:
      vault_uri: "{{ key_vault_uri }}"
      client_id: "{{ service_principal_application_id }}"
      secret: "{{ service_principal_client_secret }}"
      tenant: "{{ service_principal_tenant }}"
      subscription_id: "{{ key_vault_subscription_id }}"
      name:  "service-principal-client-secret"
    register: azure_rm_keyvaultsecret_info_controller_service_principal_client_secret

  - ansible.builtin.fail:
      msg: Secrets literal value is VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
    when: azure_rm_keyvaultsecret_info_controller_service_principal_client_secret.secrets[0].secret == "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
```

##### EXPECTED RESULTS

playbook does not fail

##### ACTUAL RESULTS

Playbook fails

```paste below
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Secrets literal value is VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"}
```
