### ISSUE TITLE
azure_rm_resource stalling on Service Bus filter operations

### ISSUE THREAD

**Issue by madmalkav** [ansible/ansible_collections_azure#1162]
##### SUMMARY

I have a playbook that takes a json file as input and creates a subscription and loops through a variable to create or remove filters using azure_rm_resource.

I'm launching many of those, and I have observed a pattern that I can reproduce: when I delete a correlation filter and create a new one after, it stalls on the creation part for 3-5 minutes most of the times (sometimes it works OK, but rarely).

I get the following error if I look at the Activity Log of the namespace:

```
Error code

MessagingGatewayTooManyRequests

Message

The messaging entity 'FILTER NAME HERE REDACTED' already exists. To know more visit https://aka.ms/sbResourceMgrExceptions. TrackingId:17353512-3ed0-4139-a774-eafd58a84f6d_B6, SystemTracker:NoSystemTracker, Timestamp:2023-05-15T15:43:58
```

At the beginning I thought it could be some kind of throttling given the MessagingGatewayTooManyRequests error. But it doesn't throw any of the expecteed error sub codes, the message it throws is not related to throttling but to the filter already existing, and I can confirm that indeed the filter was created, so it creates the filter, but throws this error, and then stalls for 3-5 minutes. Then you can see on the Activity Log a successful creation of the filter. Also, there is not enough activity there to generate throttling I think, and it seems I'm the only user on that subscription having this problem.

I tried adding some pause to my playbook to give it some time between azure_rm_resource operations but that didn't work. I also tried to use azure_rm_resource idempotency options, but these weren't work ok either: it didn't fix the problem and it also didn't perform the delete correctly (when it was done OK previously without idempotency).

I'm completely lost at what can be causing this, so any idea on what else I can try would be welcome.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure_rm_resource

##### ANSIBLE VERSION

```
ansible [core 2.14.5]
  config file = None
  configured module search path = ['/home/ansibleuser/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ansibleuser/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /home/ansibleuser/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/ansibleuser/.local/bin/ansible
  python version = 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True

```

##### COLLECTION VERSION

```
# /home/ansibleuser/.ansible/collections/ansible_collections
Collection         Version
------------------ -------
azure.azcollection 1.14.0

# /home/ansibleuser/.local/lib/python3.10/site-packages/ansible_collections
Collection         Version
------------------ -------
azure.azcollection 1.15.0

```

##### CONFIGURATION

```
"CONFIG_FILE() = None"
```

##### OS / ENVIRONMENT
Ubuntu 22.04 Azure B2s VM

##### STEPS TO REPRODUCE

```yaml

# code: language=ansible
- hosts: localhost
# we don't use a var_files entry anylong, we feed the json
  collections:
    - azure.azcollection
  tasks:
    - name: Subscription management
      azure_rm_servicebustopicsubscription:
        auto_delete_on_idle_in_seconds: '{{ autodelete }}'
        dead_lettering_on_filter_evaluation_exceptions: '{{ eval_to_dlq }}'
        dead_lettering_on_message_expiration: '{{ expired_to_dlq }}'
        default_message_time_to_live_seconds: '{{ message_ttl }}'
        lock_duration_in_seconds: '{{ lock_time }}'
        forward_to: "{{ forward_queue }}"
        max_delivery_count: '{{ max_delivery }}'
        name: "{{ sub_name }}"
        namespace: "{{ name_space }}"
        requires_session: '{{ sessions }}'
        resource_group: "{{ resource_group }}"
        state: '{{ sub_status }}'
        topic: "{{ topic }}"
    - name: SQL filter management
      azure_rm_resource:
        api_version: '2021-11-01'
        resource_group: "{{ resource_group }}"
        provider: servicebus
        resource_type: namespaces
        resource_name: "{{ name_space }}"
        state: "{{ item.filter_status }}"
        subresource:
          - type: topics
            name: "{{ topic }}"
          - type: subscriptions
            name: "{{ sub_name }}"
          - type: rules
            name: "{{ item.filter_name }}"
        body:
          properties:
            filterType: SqlFilter
            sqlFilter:
              sqlExpression: "{{ item.sql_expression }}"
      loop: "{{ sql_filter|default([]) }}"
    - name: Correlation filter management
      azure_rm_resource:
        api_version: '2021-11-01'
        resource_group: "{{ resource_group }}"
        provider: servicebus
        resource_type: namespaces
        resource_name: "{{ name_space }}"
        state: "{{ item.filter_status }}"
        subresource:
          - type: topics
            name: "{{ topic }}"
          - type: subscriptions
            name: "{{ sub_name }}"
          - type: rules
            name: "{{ item.filter_name }}"
        body:
          properties:
            filterType: CorrelationFilter
            correlationFilter:
              properties:
                "{{ dict(([item.filter_property]) | zip([item.filter_expression])) }}"
      loop: "{{ correlation_filter|default([]) }}" 
```

##### EXPECTED RESULTS

Actions are done without stalling

##### ACTUAL RESULTS

Filter creation takes minutes to complete
