### ISSUE TITLE
azure_rm_postgresqlserver unable to use Flexible server and point to latest version 14+

### ISSUE THREAD

**Issue by alwaysharsha** [ansible/ansible_collections_azure#1167]
##### SUMMARY
Using the module azure_rm_postgresqlserver there are 2 issues seen
- Doesn't support Flexible server configuration
- Version field is limited till 11 only

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure.azcollection.azure_rm_postgresqlserver module

##### ANSIBLE VERSION

```paste below
ansible --version
ansible [core 2.13.6]
  config file = /root/ansible_work/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules', '/root/ansible_work/libraries/ansible']
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.8.10 (default, Jun 22 2022, 20:18:18) [GCC 9.4.0]
  jinja version = 3.1.2
  libyaml = True

```

##### COLLECTION VERSION

```paste below
ansible-galaxy collection list

# /root/.ansible/collections/ansible_collections
Collection         Version
------------------ -------
ansible.windows    1.12.0
azure.azcollection 1.14.0
```

##### CONFIGURATION

```paste below
ansible-config dump --only-changed
CALLBACKS_ENABLED(/root/ansible_work/ansible.cfg) = ['timer']
DEFAULT_LOOKUP_PLUGIN_PATH(/root/ansible_work/ansible.cfg) = ['/root/.ansible/plugins/lookup', '/usr/share/ansible/plug>
DEFAULT_MODULE_PATH(/root/ansible_work/ansible.cfg) = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/mo>
DEFAULT_ROLES_PATH(/root/ansible_work/ansible.cfg) = ['/root/.ansible/roles', '/usr/share/ansible/roles', '/etc/ansible>
DEFAULT_STDOUT_CALLBACK(/root/ansible_work/ansible.cfg) = yaml
DEFAULT_TIMEOUT(/root/ansible_work/ansible.cfg) = 120
HOST_KEY_CHECKING(/root/ansible_work/ansible.cfg) = False
PLAYBOOK_DIR(/root/ansible_work/ansible.cfg) = /root/ansible_work/playbooks
```

##### OS / ENVIRONMENT

Ubuntu 20.04 docker image

##### STEPS TO REPRODUCE

```yaml
- name: Create (or update) PostgreSQL Server
  azure_rm_postgresqlserver:
    resource_group: "{{ az_rg_name }}"
    name: "{{ az_pgsql_server_name }}"
    sku:
      name: "{{ sku.sku_name }}"
      tier: "{{ sku.sku_tier }}"
    enforce_ssl: true
    storage_autogrow: true
    admin_username: cloudsa
    admin_password: password
    version: 14 #latest version 
    backup_retention_days: 7 #Default 7, value between 7 and 35
    geo_redundant_backup: false #This cannot be updated after first deployment
    tags: "{{ local_tags }}"
```

##### EXPECTED RESULTS

It should create the PostgreSQL Flexible server.

##### ACTUAL RESULTS

```paste below
fatal: [localhost]: FAILED! => changed=false
  invocation:
    module_args:
      ad_user: null
      adfs_authority_url: null
      admin_password: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
      admin_username: cloudsa
      api_profile: latest
      append_tags: true
      auth_source: auto
      backup_retention_days: 7
      cert_validation_mode: null
      client_id: null
      cloud_environment: AzureCloud
      create_mode: default
      enforce_ssl: true
      geo_redundant_backup: false
      location: null
      log_mode: null
      log_path: null
      name: ansi-postgre-01
      password: null
      profile: null
      resource_group: ansi-testing
      restore_point_in_time: null
      secret: null
      sku:
        name: Standard_B1ms
        tier: Standard
      source_server_id: null
      state: present
      storage_autogrow: true
      storage_mb: null
      subscription_id: null
      tags:
        component: poc-postgresql
        environment: test
      tenant: null
      thumbprint: null
      version: '14'
      x509_certificate_path: null
  msg: 'value of version must be one of: 9.5, 9.6, 10, 11, got: 14'
```
