### ISSUE TITLE
azure_rm_virtualmachine: Ability to modify/unset User Assigned and System Assigned identities on VMs

### ISSUE THREAD

**Issue by cpiment** [ansible/ansible_collections_azure#1173]
##### SUMMARY

Currently only System Assigned managed identities can be enabled in Virtual Machines and only while creating the VM (you can not assign the identity once the machine is provisioned). It would be great if both System Assigned and User Assigned identities could be configured using azure_rm_virtualmachine.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

azure_rm_virtualmachine

##### ADDITIONAL INFORMATION

I have forked the collection and made a first approach of this feature, but it would be great if we could discuss here if my approach is correct. Some samples that work in my fork:

```yaml
- name: Set identities IDs to test. Identities ansible-test-vm-identity and ansible-test-vm-identity-2 have to be created previously
  set_fact:
    user_identity_1: "/subscriptions/{{ azure_subscription_id }}/resourcegroups/{{ resource_group }}/providers/Microsoft.ManagedIdentity/userAssignedIdentities/ansible-test-vm-identity"
    user_identity_2: "/subscriptions/{{ azure_subscription_id }}/resourcegroups/{{ resource_group }}/providers/Microsoft.ManagedIdentity/userAssignedIdentities/ansible-test-vm-identity-2"

- name: Append another UserAssigned
  azure_rm_virtualmachine:
    name: "{{ vm_name }}"
    resource_group: "{{ resource_group }}"
    vm_identity:
      type: "UserAssigned"
      user_assigned_identities:
        id: 
        - "{{ user_identity_2 }}"
        append: true
  register: vm_output

- name: Add SystemAssigned
  azure_rm_virtualmachine:
    name: "{{ vm_name }}"
    resource_group: "{{ resource_group }}"
    vm_identity:
      type: "SystemAssigned, UserAssigned"
      user_assigned_identities:
        append: true
  register: vm_output

- name: Force only one UserAssigned
  azure_rm_virtualmachine:
    name: "{{ vm_name }}"
    resource_group: "{{ resource_group }}"
    vm_identity:
      type: "SystemAssigned, UserAssigned"
      user_assigned_identities:
        id: 
        - "{{ user_identity_2 }}"
        append: false
  register: vm_output

- name: Remove UserAssigned
  azure_rm_virtualmachine:
    name: "{{ vm_name }}"
    resource_group: "{{ resource_group }}"
    vm_identity:
      type: "SystemAssigned"
  register: vm_output

- name: Disable SystemAssigned
  azure_rm_virtualmachine:
    name: "{{ vm_name }}"
    resource_group: "{{ resource_group }}"
    vm_identity:
      type: "None"
  register: vm_output
```
