### ISSUE TITLE
writing on azure keyvault returns error

### ISSUE THREAD

**Issue by butelo** [ansible/ansible_collections_azure#1184]
##### SUMMARY
In 1.16.0 version writing values to azure keyvault is not working
Same steps do work in 1.15.0 
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure_rm_keyvault

##### ANSIBLE VERSION

```
ansible [core 2.15.0]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /app/ansible-playbook/lib/python3.10/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = ansible-playbook/bin/ansible
  python version = 3.10.11 (main, May 11 2023, 23:59:31) [GCC 12.2.1 20220924] (/app/ansible-playbook/bin/python)
  jinja version = 3.1.2
  libyaml = False
```

##### COLLECTION VERSION

```
azure.azcollection            1.16.0 
```

##### OS / ENVIRONMENT

Docker image 
https://mcr.microsoft.com/en-us/product/azure-cli/about

##### STEPS TO REPRODUCE
you can reproduce following this tutorial:
https://learn.microsoft.com/en-us/azure/developer/ansible/key-vault-configure-secrets?tabs=ansible

step 1:
being logged in in Azure create a value in an existing keyvault with a playbook like this:

```yaml
---
- hosts: localhost
  connection: local

  tasks:

  - name: Get Key Vault by name
    azure_rm_keyvault_info:
      resource_group: ansible-kv-test-rg
      name: <vaultName>
    register: keyvault

  - name: set KeyVault uri fact
    set_fact: keyvaulturi="{{ keyvault['keyvaults'][0]['vault_uri'] }}"

  - name: Create a secret
    azure_rm_keyvaultsecret:
      secret_name: adminPassword
      secret_value: <secretValue>
      keyvault_uri: "{{ keyvaulturi }}"

```
apply the playbook 

`ansible-playbook create_kv_secret.yml`

##### EXPECTED RESULTS
Value is updated on the keyvault

##### ACTUAL RESULTS

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: KeyError: 'client_id'
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1686057345.3356755-215-125516659736374/AnsiballZ_azure_rm_keyvaultsecret.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1686057345.3356755-215-125516659736374/AnsiballZ_azure_rm_keyvaultsecret.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1686057345.3356755-215-125516659736374/AnsiballZ_azure_rm_keyvaultsecret.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.azure.azcollection.plugins.modules.azure_rm_keyvaultsecret', init_globals=dict(_module_fqn='ansible_collections.azure.azcollection.plugins.modules.azure_rm_keyvaultsecret', _modlib_path=modlib_path),\n  File \"/usr/local/lib/python3.10/runpy.py\", line 224, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/local/lib/python3.10/runpy.py\", line 96, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/local/lib/python3.10/runpy.py\", line 86, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_azure_rm_keyvaultsecret_payload_0ajg29u_/ansible_azure_rm_keyvaultsecret_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_keyvaultsecret.py\", line 271, in <module>\n  File \"/tmp/ansible_azure_rm_keyvaultsecret_payload_0ajg29u_/ansible_azure_rm_keyvaultsecret_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_keyvaultsecret.py\", line 267, in main\n  File \"/tmp/ansible_azure_rm_keyvaultsecret_payload_0ajg29u_/ansible_azure_rm_keyvaultsecret_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_keyvaultsecret.py\", line 140, in __init__\n  File \"/tmp/ansible_azure_rm_keyvaultsecret_payload_0ajg29u_/ansible_azure_rm_keyvaultsecret_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py\", line 472, in __init__\n  File \"/tmp/ansible_azure_rm_keyvaultsecret_payload_0ajg29u_/ansible_azure_rm_keyvaultsecret_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_keyvaultsecret.py\", line 151, in exec_module\n  File \"/tmp/ansible_azure_rm_keyvaultsecret_payload_0ajg29u_/ansible_azure_rm_keyvaultsecret_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_keyvaultsecret.py\", line 212, in get_keyvault_client\nKeyError: 'client_id'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

```
