### ISSUE TITLE
Feature request: Allow deployment of VM with Capacity Reservation Group

### ISSUE THREAD

**Issue by xanderwessels** [ansible/ansible_collections_azure#1191]
##### SUMMARY

I want to deploy a VM into a [capacity reservation group](https://learn.microsoft.com/en-us/azure/virtual-machines/capacity-reservation-overview) and I could not find ANY reference in the documentation about it, so I am requesting this feature. Could potentially be a bigger feature, aka also allow for the creation of said capacity reservation groups. 

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
An additional parameter for the `azure_rm_virtualmachine` module, see [docs](https://learn.microsoft.com/en-us/azure/virtual-machines/capacity-reservation-associate-vm?tabs=api1%2Capi2%2Capi3#associate-a-new-vm)

##### ADDITIONAL INFORMATION

My usecase is to deploy new machines and associate them with an already existing capacity reservation group, so supplying the capacity reservation group during deployment is the most natural to me:

```yaml
- name: Create VM associated to a capacity reservation group
  azure_rm_virtualmachine:
    resource_group: myResourceGroup
    name: testvm10
    admin_username: "{{ username }}"
    admin_password: "{{ password }}"
    capacity_reservation_group:  "{{ capacity_reservation_group }}"
    image:
      offer: CentOS
      publisher: OpenLogic
      sku: '7.1'
      version: latest
```
