### ISSUE TITLE
"msg": "Error retrieving resource group myrg - __init__() got an unexpected keyword argument 'credential'

### ISSUE THREAD

**Issue by venkateshm2012** [ansible/ansible_collections_azure#1230]
##### SUMMARY
Unable to use azure_rm_networkinterface module to make update a existing network interface's ip configurations  

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Module- azure_rm_networkinterface
plugin - NetworkManagementClient Class (https://learn.microsoft.com/en-us/python/api/azure-mgmt-network/azure.mgmt.network.networkmanagementclient?view=azure-python ) 
others - azure_rm_common.py

##### ANSIBLE VERSION

"ansible [core 2.12.5.post0]\n  config file = None\n  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']\n  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible\n  ansible collection location = /runner/requirements_collections:/home/runner/.ansible/collections:/usr/share/ansible/collections\n  executable location = /usr/local/bin/ansible\n  python version = 3.8.16 (default, Jan 17 2023, 18:50:05) [GCC 8.5.0 20210514 (Red Hat 8.5.0-18)]\n  jinja version = 2.11.3\n  libyaml = True"

```

##### COLLECTION VERSION
<!--- Paste verbatim output from "ansible-galaxy collection list <namespace>.<collection>"  between the quotes
for example: community.general:7.2.0 
-->
[```paste below]
(azure.azcollection:1.16.0)

```

##### CONFIGURATION

```paste below
N/A
```

##### OS / ENVIRONMENT

Centos Version 8

##### STEPS TO REPRODUCE

try to run a playbook using azure_rm_networkinterface module to do some simple task, adding a nic or updating a ipconfiguration of the existing nic

```yaml
- name: Get NIC details by IP
  hosts: localhost
  gather_facts: false
       
    - name: Add new secondary IP configuration
      ansible.builtin.azure_rm_networkinterface:
        resource_group: my_rg
        name: nic_name
        virtual_network: vnet1
        subnet_name: sn1
        ip_configurations:
          - name: test1
            private_ip_address: '192.168.44.166'
            private_ip_allocation_method: Dynamic
            primary: false
            load_balancer_backend_address_pools: null
            public_ip_address: null
            public_ip_allocation_method: null
            application_security_groups: null 
            application_gateway_backend_address_pools: null    
        state: present
```

##### EXPECTED RESULTS

update the ipconfiguration  of the nic1 with the new secondary interface. 

##### ACTUAL RESULTS

```paste belowThe full traceback is:

  File "/tmp/ansible_azure_rm_networkinterface_payload_a17e2n3y/ansible_azure_rm_networkinterface_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py", line 596, in get_resource_group

    return self.rm_client.resource_groups.get(resource_group)

  File "/tmp/ansible_azure_rm_networkinterface_payload_a17e2n3y/ansible_azure_rm_networkinterface_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py", line 1102, in rm_client

    self._resource_client = self.get_mgmt_svc_client(ResourceManagementClient,

  File "/tmp/ansible_azure_rm_networkinterface_payload_a17e2n3y/ansible_azure_rm_networkinterface_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py", line 950, in get_mgmt_svc_client

    client = client_type(**client_kwargs)

fatal: [localhost]: FAILED! => {

    "changed": false,

    "invocation": {

        "module_args": {

            "ad_user": null,

            "adfs_authority_url": null,

            "api_profile": "latest",

            "append_tags": true,

            "auth_source": "auto",

            "cert_validation_mode": null,

            "client_id": null,

            "cloud_environment": "AzureCloud",

            "create_with_security_group": true,

            "dns_servers": null,

            "enable_accelerated_networking": false,

            "enable_ip_forwarding": false,

            "ip_configurations": null,

            "location": null,

            "log_mode": null,

            "log_path": null,

            "name": "nic1",

            "open_ports": null,

            "os_type": "Linux",

            "password": null,

            "private_ip_address": null,

            "private_ip_allocation_method": "Dynamic",

            "profile": null,

 

   "msg": "Error retrieving resource group myrg - __init__() got an unexpected keyword argument 'credential'"
<img width="816" alt="Screenshot 2023-08-01 at 10 44 19 AM" src="https://github.com/ansible-collections/azure/assets/74171842/21f92774-7546-460f-b869-9d6e56d9faf2">


```
