### ISSUE TITLE
Creation of azure_rm_openshiftmanagedcluster_kubeconfig_info module

### ISSUE THREAD

**Issue by MaxBab** [ansible/ansible_collections_azure#1235]
##### SUMMARY
Hello,
I would like to be able to fetch kubeconfig file from the ARO cluster (openshift managed cluster).
I've created a module and would like to contribute it to the collection.

##### ISSUE TYPE
- Feature Idea

##### ADDITIONAL INFORMATION
The name of the modules could be `azure_rm_openshiftmanagedcluster_kubeconfig_info`.

The module is used in the following flow:
```yaml
- name: Obtain kubeconfig file of ARO cluster
  azure_rm_openshiftmanagedcluster_kubeconfig_info:
    name: myCluster
    resource_group: myResourceGroup
  register: kubeconf

- name: Print registered kubeconfig file
  debug:
    msg: "{{ kubeconf['kubeconfig'] }}"

- name: Fetch kubeconfig and save it as mycluster_kubeconfig filename
  azure_rm_openshiftmanagedcluster_kubeconfig_info:
    name: myCluster
    resource_group: myResourceGroup
    path: ./files/mycluster_kubeconfig

- name: Fetch kubeconfig and save it to specified directory (file will be named as kubeconfig by default)
  azure_rm_openshiftmanagedcluster_kubeconfig_info:
    name: myCluster
    resource_group: myResourceGroup
    path: ./files/
```
