### ISSUE TITLE
azure_rm_manageddisk - required parameter 'storageAccountId' is missing

### ISSUE THREAD

**Issue by OlehAhieienko** [ansible/ansible_collections_azure#1241]
##### SUMMARY

Playbook fails with an error `Error creating the managed disk: (BadRequest) Required parameter 'storageAccountId' is missing (null).`, while `storage_account_id` is set.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

azure.azcollection.azure_rm_manageddisk

##### ANSIBLE VERSION

```paste below
$ ansible --version
ansible [core 2.15.2]
  config file = /home/user/Documents/ansible/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/ansible-azure-venv/lib/python3.11/site-packages/ansible
  ansible collection location = /home/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/user/ansible-azure-venv/bin/ansible
  python version = 3.11.3 (main, Jun  5 2023, 09:32:32) [GCC 13.1.1 20230429] (/home/user/ansible-azure-venv/bin/python)
  jinja version = 3.1.2
  libyaml = True

```

##### COLLECTION VERSION

```paste below
$ ansible-galaxy collection list azure.azcollection

# /home/user/.ansible/collections/ansible_collections
Collection         Version
------------------ -------
azure.azcollection 1.16.0 

# /home/user/ansible-azure-venv/lib/python3.11/site-packages/ansible_collections
Collection         Version
------------------ -------
azure.azcollection 1.16.0 
```

##### CONFIGURATION

```paste below
$ ansible-config dump --only-changed
CONFIG_FILE() = /home/user/Documents/ansible/ansible.cfg
DEFAULT_ROLES_PATH(/home/user/Documents/ansible/ansible.cfg) = ['/home/user/Documents/ansible/roles', '/home/user/Documents/ansible/roles']
```

##### OS / ENVIRONMENT

Linux; Ansible and azure are installed via pip in own venv

##### STEPS TO REPRODUCE

```yaml
- name: Create storage account
  azure.azcollection.azure_rm_storageaccount:
    resource_group: myresourcegroup
    name: mystorageaccount
    account_type: Premium_LRS
  register: _azure_storageaccount_result

- name: Upload blob
  azure.azcollection.azure_rm_storageblob:
    resource_group: myresourcegroup
    storage_account_name: mystorageaccount
    container_name: mycontainer
    blob_name: vm-system-disk.vhd
    blob_type: page
    src: vm-system-disk.vhd

- name: Create VHD
  azure.azcollection.azure_rm_manageddisk:
    resource_group: myresourcegroup
    storage_account_id: "{{ _azure_storageaccount_result.state.id }}"
    name: vm-system-disk.vhd
    create_option: import
    source_uri: "https://mystorageaccount.blob.core.windows.net/mycontainer/vm-system-disk.vhd"
    os_type: linux
    storage_account_type: Premium_LRS
```

##### EXPECTED RESULTS

Create managed disk from blob without errors

##### ACTUAL RESULTS

```paste below
TASK [test : Create VHD] ***************
task path: /home/user/Documents/test/ansible/roles/test/tasks/create_vm.yaml:52
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: user
<127.0.0.1> EXEC /bin/sh -c 'echo ~user && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/user/.ansible/tmp `"&& mkdir "` echo /home/user/.ansible/tmp/ansible-tmp-1691687930.3451612-941527-278168925696637 `" && echo ansible-tmp-1691687930.3451612-941527-278168925696637="` echo /home/user/.ansible/tmp/ansible-tmp-1691687930.3451612-941527-278168925696637 `" ) && sleep 0'
Using module file /home/user/.ansible/collections/ansible_collections/azure/azcollection/plugins/modules/azure_rm_manageddisk.py
<127.0.0.1> PUT /home/user/.ansible/tmp/ansible-local-9409743lwrewfj/tmprlza16uk TO /home/user/.ansible/tmp/ansible-tmp-1691687930.3451612-941527-278168925696637/AnsiballZ_azure_rm_manageddisk.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/user/.ansible/tmp/ansible-tmp-1691687930.3451612-941527-278168925696637/ /home/user/.ansible/tmp/ansible-tmp-1691687930.3451612-941527-278168925696637/AnsiballZ_azure_rm_manageddisk.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/home/user/ansible-azure-venv/bin/python /home/user/.ansible/tmp/ansible-tmp-1691687930.3451612-941527-278168925696637/AnsiballZ_azure_rm_manageddisk.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/user/.ansible/tmp/ansible-tmp-1691687930.3451612-941527-278168925696637/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
  File "/tmp/ansible_azure.azcollection.azure_rm_manageddisk_payload_k610snzd/ansible_azure.azcollection.azure_rm_manageddisk_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_manageddisk.py", line 587, in create_or_update_managed_disk
  File "/home/user/ansible-azure-venv/lib/python3.11/site-packages/azure/core/tracing/decorator.py", line 76, in wrapper_use_tracer
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/ansible-azure-venv/lib/python3.11/site-packages/azure/mgmt/compute/v2021_04_01/operations/_disks_operations.py", line 430, in begin_create_or_update
    raw_result = self._create_or_update_initial(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/ansible-azure-venv/lib/python3.11/site-packages/azure/mgmt/compute/v2021_04_01/operations/_disks_operations.py", line 375, in _create_or_update_initial
    raise HttpResponseError(response=response, error_format=ARMErrorFormat)
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "ad_user": null,
            "adfs_authority_url": null,
            "api_profile": "latest",
            "append_tags": true,
            "attach_caching": null,
            "auth_source": "auto",
            "cert_validation_mode": null,
            "client_id": null,
            "cloud_environment": "AzureCloud",
            "create_option": "import",
            "disk_size_gb": null,
            "location": null,
            "log_mode": null,
            "log_path": null,
            "lun": null,
            "managed_by": null,
            "managed_by_extended": null,
            "max_shares": null,
            "name": "srv02-os.vhd",
            "os_type": "linux",
            "password": null,
            "profile": null,
            "resource_group": "cccccc",
            "secret": null,
            "source_uri": "https://aaaaaaaa.blob.core.windows.net/bbbbbbbbbb/srv02-os.vhd",
            "state": "present",
            "storage_account_id": "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/cccccc/providers/Microsoft.Storage/storageAccounts/aaaaaaaa",
            "storage_account_type": "Premium_LRS",
            "subscription_id": "",
            "tags": null,
            "tenant": null,
            "thumbprint": null,
            "x509_certificate_path": null,
            "zone": null
        }
    },
    "msg": "Error creating the managed disk: (BadRequest) Required parameter 'storageAccountId' is missing (null).\nCode: BadRequest\nMessage: Required parameter 'storageAccountId' is missing (null)."
}
```
