### ISSUE TITLE
 azure.azcollection.azure_rm_virtualmachine -->  (InvalidParameter) The value  provided for the VM size is not valid.

### ISSUE THREAD

**Issue by KingJim1984** [ansible/ansible_collections_azure#1243]
##### SUMMARY
Hello, I try to deploy an Azure VirtualMachine with ansible automation platform. I try a lot of vm sizes and other locactions, but I get on every combination from size and location the following error:
 ```
(InvalidParameter) The value  provided for the VM size is not valid.The valid sizes in the current region are: Standard_NC4as_T4_v3,Standard_NC8as_T4_v3,Standard_NC16as_T4_v3,Standard_NC64as_T4_v3,Standard_B1ls,Standard_B1ms,Standard_B1s,Standard_B2ms,Standard_B2s,Standard_B4ms,Standard_B8ms,Standard_B12ms,Standard_B16ms,Standard_B20ms,Standard_D1_v2,Standard_D2_v2,Standard_D3_v2.....
```
##### ISSUE TYPE
- Bug Report (maybe?)

##### COMPONENT NAME
azure.azcollection.azure_rm_virtualmachine 

##### ANSIBLE VERSION
```ansible [core 2.15.2]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/ansible/.ansible/plugins/modules', '/sr/share/ansible/plugins/modules']
  ansible python module location = /home/ansible/.local/lib/python3.9/site-packges/ansible
  ansible collection location = /etc/ansible/{{ ANSIBLE_HOME ~ "/collections:/ur/share/ansible/collections" }}
  executable location = /home/ansible/.local/bin/ansible
  python version = 3.9.16 (main, May 29 2023, 00:00:00) [GCC 11.3.1 20221121 (Rd Hat 11.3.1-4)] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```
##### COLLECTION VERSION

```Collection         Version
------------------ -------
azure.azcollection 1.16.0
```
##### CONFIGURATION

```COLLECTIONS_PATHS(/etc/ansible/ansible.cfg) = ['/etc/ansible/{{ ANSIBLE_HOME ~ "/collections', '/usr/share/ansible/collec>
CONFIG_FILE() = /etc/ansible/ansible.cfg
DEFAULT_ACTION_PLUGIN_PATH(/etc/ansible/ansible.cfg) = ['/etc/ansible/{{ ANSIBLE_HOME ~ "/plugins/action', '/usr/share/an>
ENABLE_TASK_DEBUGGER(/etc/ansible/ansible.cfg) = True
```
##### OS / ENVIRONMENT
RedHat 9 - Proxmox Installation -  Ansible Automation Platform Controller 4.4.0

##### STEPS TO REPRODUCE

```yaml
---
- name: Create Azure VM
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Create Azure VM
      azure.azcollection.azure_rm_virtualmachine:
        resource_group: "{{ Resource_Group_Name }}" 
        name: "{{ vm_name }}"
        location: "{{ location }}"
        admin_username: "{{ vm_username }}"
        admin_password: "{{ vm_password }}"
        image:
          publisher: "canonical"
          sku: "minimal-22_04-lts-gen2"
          offer: "0001-com-ubuntu-minimal-jammy"
          version: "latest"
          vm_size: "{{ vm_size }}"
          ssh_password_enabled: "false"
        network_interfaces:
          - name: "nic01"
        os_type: Linux
        state: present
        subscription_id: "{{ azure_subscription_id }}"
        client_id: "{{ azure_client_id }}"
        secret: "{{ azure_client_secret }}"
        tenant: "{{ azure_tenant_id }}"
```
