### ISSUE TITLE
Authentication Issue: azure.azcollection.azure_rm_storageblob Fails with Disabled Shared Keys, While az CLI with --auth-mode login Succeeds

### ISSUE THREAD

**Issue by donjuanmon** [ansible/ansible_collections_azure#1255]
##### SUMMARY

The `azure.azcollection.azure_rm_storageblob` module fails to upload a file to an Azure storage blob when the storage account has shared keys disabled. However, the equivalent az CLI command with `--auth-mode login` works.

We are using a Service Principal to authenticate against the Storage Account. Permissions are correct and the SPN can interact with the Storage Account through native az CLI commands. `azure.azcollection.azure_rm_storageblob` does not have an az CLI equivalent `--auth-mode login`

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`azure.azcollection.azure_rm_storageblob`

##### ANSIBLE VERSION

```paste below
ansible [core 2.15.4rc1]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.17 (main, Aug  9 2023, 00:00:00) [GCC 11.4.1 20230605 (Red Hat 11.4.1-2)] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
Collection         Version
------------------ -------
azure.azcollection 1.17.0 
```

##### CONFIGURATION

```paste below
None, this is within an AWX Execution Environment
```

##### OS / ENVIRONMENT

AWX Execution Environment Image. Targeting localhost (AWX Pod) to run operations.

##### STEPS TO REPRODUCE

- Disable shared keys on the Azure storage account.
- Try to upload a file using the azure.azcollection.azure_rm_storageblob module with SPN authentication.

```yaml
- name: Download azse to Azure Storage Blob
  azure.azcollection.azure_rm_storageblob:
    resource_group: "rg-test-{{ curr_env }}"
    storage_account_name: "sttestassets{{ curr_env }}"
    container: "storageexplorer"
    blob: "StorageExplorer-{{ azse_version }}-linux-x64.tar.gz"
    src: "{{ azse_lnx_download.dest }}"
    auth_source: auto
    subscription_id: "{{ lookup('env', 'AZURE_SUBSCRIPTION_ID') }}"
    client_id: "{{ lookup('env', 'AZURE_CLIENT_ID') }}"
    tenant: "{{ lookup('env', 'AZURE_TENANT') }}"
    secret: "{{ lookup('env', 'AZURE_SECRET') }}"
```

*NOTE* The following code works and uploads the file as expected:
```yaml
- name: Login with az-cli
  ansible.builtin.command:
    cmd: az login --service-principal -u "{{ lookup('env', 'AZURE_CLIENT_ID') }}" -p "{{ lookup('env', 'AZURE_SECRET') }}" --tenant "{{ lookup('env', 'AZURE_TENANT') }}"
  no_log: true

- name: Show az Account
  ansible.builtin.command:
    cmd: az account show

- name: Set subscription_id
  ansible.builtin.command:
    cmd: az account set --subscription "{{ lookup('env', 'AZURE_SUBSCRIPTION_ID') }}"

- name: Try native az command
  ansible.builtin.command: |
    az storage blob upload \
        --auth-mode login \
        --account-name "sttestassets{{ curr_env }}" \
        --container-name "storageexplorer" \
        --name "StorageExplorer-{{ azse_version }}-linux-x64.tar.gz" \
        --file "{{ azse_lnx_download.dest }}"
```

##### EXPECTED RESULTS

The Blob successfully uploads into the specified storage container.

##### ACTUAL RESULTS

All attempts to use `azure.azcollection.azure_rm_storageblob` fail saying "Key based authentication is not permitted on this storage account". We do not enable keys for security reasons. 

Temporarily enabling shared keys fixes the problem. We'd like to use this module without enable shared keys.

```paste below
{
  "module_stdout": "",
  "module_stderr": "Traceback (most recent call last):\n  File \"/runner/.ansible/tmp/ansible-tmp-1694211285.207559-79-236369543819326/AnsiballZ_azure_rm_storageblob.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/runner/.ansible/tmp/ansible-tmp-1694211285.207559-79-236369543819326/AnsiballZ_azure_rm_storageblob.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/runner/.ansible/tmp/ansible-tmp-1694211285.207559-79-236369543819326/AnsiballZ_azure_rm_storageblob.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.azure.azcollection.plugins.modules.azure_rm_storageblob', init_globals=dict(_module_fqn='ansible_collections.azure.azcollection.plugins.modules.azure_rm_storageblob', _modlib_path=modlib_path),\n  File \"/usr/lib64/python3.9/runpy.py\", line 225, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.9/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib64/python3.9/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_azure.azcollection.azure_rm_storageblob_payload_khwly5l7/ansible_azure.azcollection.azure_rm_storageblob_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_storageblob.py\", line 645, in <module>\n  File \"/tmp/ansible_azure.azcollection.azure_rm_storageblob_payload_khwly5l7/ansible_azure.azcollection.azure_rm_storageblob_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_storageblob.py\", line 641, in main\n  File \"/tmp/ansible_azure.azcollection.azure_rm_storageblob_payload_khwly5l7/ansible_azure.azcollection.azure_rm_storageblob_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_storageblob.py\", line 253, in __init__\n  File \"/tmp/ansible_azure.azcollection.azure_rm_storageblob_payload_khwly5l7/ansible_azure.azcollection.azure_rm_storageblob_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py\", line 472, in __init__\n  File \"/tmp/ansible_azure.azcollection.azure_rm_storageblob_payload_khwly5l7/ansible_azure.azcollection.azure_rm_storageblob_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_storageblob.py\", line 268, in exec_module\n  File \"/tmp/ansible_azure.azcollection.azure_rm_storageblob_payload_khwly5l7/ansible_azure.azcollection.azure_rm_storageblob_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_storageblob.py\", line 403, in get_container\n  File \"/usr/local/lib/python3.9/site-packages/azure/core/tracing/decorator.py\", line 78, in wrapper_use_tracer\n    return func(*args, **kwargs)\n  File \"/usr/local/lib/python3.9/site-packages/azure/storage/blob/_container_client.py\", line 502, in get_container_properties\n    process_storage_error(error)\n  File \"/usr/local/lib/python3.9/site-packages/azure/storage/blob/_shared/response_handlers.py\", line 181, in process_storage_error\n    exec(\"raise error from None\")   # pylint: disable=exec-used # nosec\n  File \"<string>\", line 1, in <module>\nazure.core.exceptions.HttpResponseError: Key based authentication is not permitted on this storage account.\nRequestId:403a0f69-601e-004a-6aa1-e28510000000\nTime:2023-09-08T22:14:46.7567550Z\nErrorCode:KeyBasedAuthenticationNotPermitted\nContent: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>KeyBasedAuthenticationNotPermitted</Code><Message>Key based authentication is not permitted on this storage account.\nRequestId:403a0f69-601e-004a-6aa1-e28510000000\nTime:2023-09-08T22:14:46.7567550Z</Message></Error>\n",
  "exception": "Traceback (most recent call last):\n  File \"/runner/.ansible/tmp/ansible-tmp-1694211285.207559-79-236369543819326/AnsiballZ_azure_rm_storageblob.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/runner/.ansible/tmp/ansible-tmp-1694211285.207559-79-236369543819326/AnsiballZ_azure_rm_storageblob.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/runner/.ansible/tmp/ansible-tmp-1694211285.207559-79-236369543819326/AnsiballZ_azure_rm_storageblob.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.azure.azcollection.plugins.modules.azure_rm_storageblob', init_globals=dict(_module_fqn='ansible_collections.azure.azcollection.plugins.modules.azure_rm_storageblob', _modlib_path=modlib_path),\n  File \"/usr/lib64/python3.9/runpy.py\", line 225, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.9/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib64/python3.9/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_azure.azcollection.azure_rm_storageblob_payload_khwly5l7/ansible_azure.azcollection.azure_rm_storageblob_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_storageblob.py\", line 645, in <module>\n  File \"/tmp/ansible_azure.azcollection.azure_rm_storageblob_payload_khwly5l7/ansible_azure.azcollection.azure_rm_storageblob_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_storageblob.py\", line 641, in main\n  File \"/tmp/ansible_azure.azcollection.azure_rm_storageblob_payload_khwly5l7/ansible_azure.azcollection.azure_rm_storageblob_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_storageblob.py\", line 253, in __init__\n  File \"/tmp/ansible_azure.azcollection.azure_rm_storageblob_payload_khwly5l7/ansible_azure.azcollection.azure_rm_storageblob_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py\", line 472, in __init__\n  File \"/tmp/ansible_azure.azcollection.azure_rm_storageblob_payload_khwly5l7/ansible_azure.azcollection.azure_rm_storageblob_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_storageblob.py\", line 268, in exec_module\n  File \"/tmp/ansible_azure.azcollection.azure_rm_storageblob_payload_khwly5l7/ansible_azure.azcollection.azure_rm_storageblob_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_storageblob.py\", line 403, in get_container\n  File \"/usr/local/lib/python3.9/site-packages/azure/core/tracing/decorator.py\", line 78, in wrapper_use_tracer\n    return func(*args, **kwargs)\n  File \"/usr/local/lib/python3.9/site-packages/azure/storage/blob/_container_client.py\", line 502, in get_container_properties\n    process_storage_error(error)\n  File \"/usr/local/lib/python3.9/site-packages/azure/storage/blob/_shared/response_handlers.py\", line 181, in process_storage_error\n    exec(\"raise error from None\")   # pylint: disable=exec-used # nosec\n  File \"<string>\", line 1, in <module>\nazure.core.exceptions.HttpResponseError: Key based authentication is not permitted on this storage account.\nRequestId:403a0f69-601e-004a-6aa1-e28510000000\nTime:2023-09-08T22:14:46.7567550Z\nErrorCode:KeyBasedAuthenticationNotPermitted\nContent: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>KeyBasedAuthenticationNotPermitted</Code><Message>Key based authentication is not permitted on this storage account.\nRequestId:403a0f69-601e-004a-6aa1-e28510000000\nTime:2023-09-08T22:14:46.7567550Z</Message></Error>\n",
  "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
  "rc": 1,
  "_ansible_no_log": null,
  "changed": false,
  "_ansible_delegated_vars": {
    "ansible_host": "localhost",
    "ansible_port": null,
    "ansible_user": "adminuser",
    "ansible_connection": "local"
  }
}
```

**Comment by DevopsMercenary** [comment]
https://github.com/ansible-collections/azure/issues/1293

**Comment by donjuanmon** [comment]
Hello,

#1315 did not fix this issue on my end. Using the following code, I still receive `Key based authentication is not permitted on this storage account.`

Code:
```
- name: Download azse to Azure Storage Blob
  azure.azcollection.azure_rm_storageblob:
    resource_group: "rg-test-{{ curr_env }}"
    storage_account_name: "sttestassets{{ curr_env }}"
    container: "storageexplorer"
    blob: "StorageExplorer-{{ azse_version }}-linux-x64.tar.gz"
    src: "{{ azse_lnx_download.dest }}"
    auth_source: auto
    auth_mode: login
    subscription_id: "{{ lookup('env', 'AZURE_SUBSCRIPTION_ID') }}"
    client_id: "{{ lookup('env', 'AZURE_CLIENT_ID') }}"
    tenant: "{{ lookup('env', 'AZURE_TENANT') }}"
    secret: "{{ lookup('env', 'AZURE_SECRET') }}"
```

Logging in with az cli and changing `auth_source: cli` also has no effect.

**Comment by markstoel** [comment]
I suggest you reopen this case because it is not fixed.
My collection version:
```yaml 
ansible-galaxy collection list azure.azcollection

# /home/marks/projects/voyager/collections/ansible_collections
Collection         Version
------------------ -------
azure.azcollection 2.3.0  

- name: Download the files from azure blob storage
  azure.azcollection.azure_rm_storageblob:
    subscription_id: "{{ subscriptionid }}"
    resource_group: "{{ resourcegroup }}"
    storage_account_name: "{{ storageaccount }}"
    container: "{{ container }}"
    blob: "{{ item }}"
    dest: "{{ download_path }}/{{ item }}"
    state: present
    auth_mode: login
    
result:
task path: /home/marks/projects/voyager/roles/raet_download_blob/tasks/main.yml:23
woensdag 08 mei 2024  10:49:02 +0200 (0:00:00.030)       0:00:00.634 ********** 
Using module file /home/marks/projects/voyager/collections/ansible_collections/azure/azcollection/plugins/modules/azure_rm_storageblob.py
Pipelining is enabled.
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: marks
<localhost> EXEC /bin/sh -c '/usr/bin/env python3 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "<stdin>", line 107, in <module>
  File "<stdin>", line 99, in _ansiballz_main
  File "<stdin>", line 47, in invoke_module
  File "<frozen runpy>", line 226, in run_module
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "/tmp/ansible_azure.azcollection.azure_rm_storageblob_payload_zqqintep/ansible_azure.azcollection.azure_rm_storageblob_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_storageblob.py", line 680, in <module>
  File "/tmp/ansible_azure.azcollection.azure_rm_storageblob_payload_zqqintep/ansible_azure.azcollection.azure_rm_storageblob_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_storageblob.py", line 676, in main
  File "/tmp/ansible_azure.azcollection.azure_rm_storageblob_payload_zqqintep/ansible_azure.azcollection.azure_rm_storageblob_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_storageblob.py", line 288, in __init__
  File "/tmp/ansible_azure.azcollection.azure_rm_storageblob_payload_zqqintep/ansible_azure.azcollection.azure_rm_storageblob_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py", line 475, in __init__
  File "/tmp/ansible_azure.azcollection.azure_rm_storageblob_payload_zqqintep/ansible_azure.azcollection.azure_rm_storageblob_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_storageblob.py", line 303, in exec_module
  File "/tmp/ansible_azure.azcollection.azure_rm_storageblob_payload_zqqintep/ansible_azure.azcollection.azure_rm_storageblob_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_storageblob.py", line 438, in get_container
  File "/home/marks/.pyenv/versions/3.11.7/lib/python3.11/site-packages/azure/core/tracing/decorator.py", line 76, in wrapper_use_tracer
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/marks/.pyenv/versions/3.11.7/lib/python3.11/site-packages/azure/storage/blob/_container_client.py", line 502, in get_container_properties
    process_storage_error(error)
  File "/home/marks/.pyenv/versions/3.11.7/lib/python3.11/site-packages/azure/storage/blob/_shared/response_handlers.py", line 181, in process_storage_error
    exec("raise error from None")   # pylint: disable=exec-used # nosec
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
azure.core.exceptions.HttpResponseError: Key based authentication is not permitted on this storage account.
RequestId:045c9adb-a01e-0052-0c24-a19f02000000
Time:2024-05-08T08:49:04.4398408Z
ErrorCode:KeyBasedAuthenticationNotPermitted
Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>KeyBasedAuthenticationNotPermitted</Code><Message>Key based authentication is not permitted on this storage account.
RequestId:045c9adb-a01e-0052-0c24-a19f02000000
Time:2024-05-08T08:49:04.4398408Z</Message></Error>
failed: [localhost] (item=7z.msi) => changed=false 
  ansible_loop_var: item
  item: 7z.msi
  module_stderr: |-
    Traceback (most recent call last):
      File "<stdin>", line 107, in <module>
      File "<stdin>", line 99, in _ansiballz_main
      File "<stdin>", line 47, in invoke_module
      File "<frozen runpy>", line 226, in run_module
      File "<frozen runpy>", line 98, in _run_module_code
      File "<frozen runpy>", line 88, in _run_code
      File "/tmp/ansible_azure.azcollection.azure_rm_storageblob_payload_zqqintep/ansible_azure.azcollection.azure_rm_storageblob_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_storageblob.py", line 680, in <module>
      File "/tmp/ansible_azure.azcollection.azure_rm_storageblob_payload_zqqintep/ansible_azure.azcollection.azure_rm_storageblob_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_storageblob.py", line 676, in main
      File "/tmp/ansible_azure.azcollection.azure_rm_storageblob_payload_zqqintep/ansible_azure.azcollection.azure_rm_storageblob_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_storageblob.py", line 288, in __init__
      File "/tmp/ansible_azure.azcollection.azure_rm_storageblob_payload_zqqintep/ansible_azure.azcollection.azure_rm_storageblob_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py", line 475, in __init__
      File "/tmp/ansible_azure.azcollection.azure_rm_storageblob_payload_zqqintep/ansible_azure.azcollection.azure_rm_storageblob_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_storageblob.py", line 303, in exec_module
      File "/tmp/ansible_azure.azcollection.azure_rm_storageblob_payload_zqqintep/ansible_azure.azcollection.azure_rm_storageblob_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_storageblob.py", line 438, in get_container
      File "/home/marks/.pyenv/versions/3.11.7/lib/python3.11/site-packages/azure/core/tracing/decorator.py", line 76, in wrapper_use_tracer
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/home/marks/.pyenv/versions/3.11.7/lib/python3.11/site-packages/azure/storage/blob/_container_client.py", line 502, in get_container_properties
        process_storage_error(error)
      File "/home/marks/.pyenv/versions/3.11.7/lib/python3.11/site-packages/azure/storage/blob/_shared/response_handlers.py", line 181, in process_storage_error
        exec("raise error from None")   # pylint: disable=exec-used # nosec
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "<string>", line 1, in <module>
    azure.core.exceptions.HttpResponseError: Key based authentication is not permitted on this storage account.
    RequestId:045c9adb-a01e-0052-0c24-a19f02000000
    Time:2024-05-08T08:49:04.4398408Z
    ErrorCode:KeyBasedAuthenticationNotPermitted
    Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>KeyBasedAuthenticationNotPermitted</Code><Message>Key based authentication is not permitted on this storage account.
    RequestId:045c9adb-a01e-0052-0c24-a19f02000000
    Time:2024-05-08T08:49:04.4398408Z</Message></Error>
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1```

**Comment by Fred-sun** [comment]
@markstoel From the above error, the reason for the failure is that key-based authentication is not allowed on this storage account, can you check the authentication method of your account?

**Comment by markstoel** [comment]
@Fred-sun 
The same error occurs when I include the client credentials. We use the default of reading env first en we have the environment variables set 
AZURE_TENANT
AZURE_SUBSCRIPTION_ID
AZURE_CLIENT_ID
AZURE_SECRET

so for example this code also fails with the same error:

```yaml
- name: Download the files from azure blob storage
  azure.azcollection.azure_rm_storageblob:
    client_id: "{{ secrets.azure.subscriptions.client_id }}"
    secret: "{{ secrets.azure.subscriptions.secret }}"
    tenant: "{{ secrets.azure.subscriptions.tenant }}"
    subscription_id: "{{ subscriptionid }}"
    resource_group: "{{ resourcegroup }}"
    storage_account_name: "{{ storageaccount }}"
    container: "{{ container }}"
    blob: "{{ item }}"
    dest: "{{ download_path }}/{{ item }}"
    state: present
    auth_mode: login
```
