### ISSUE TITLE
ImportError: cannot import name 'RecoveryServicesBackupClient' from 'azure.mgmt.recoveryservicesbackup' (/usr/local/lib/python3.10/dist-packages/azure/mgmt/recoveryservicesbackup/__init__.py) #31993

### ISSUE THREAD

**Issue by markarping** [ansible/ansible_collections_azure#1260]
##### SUMMARY

ansible [core 2.15.4]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.10/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True

python3 --version
Python 3.10.12

name: Get Azure VM Info
hosts: localhost
gather_facts: no # We don't need facts for this playbook
tasks:
name: Get VM Info
azure_rm_virtualmachine_info:
resource_group: "{{ Resourcegroupname }}"
name: "{{ vmname}}"
register: vm_info
name: Display VM Info
debug:
msg: vm_info
Expected behavior
The full traceback is:
Traceback (most recent call last):
File "/tmp/ansible_azure_rm_virtualmachine_info_payload_98uulu_q/ansible_azure_rm_virtualmachine_info_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py", line 275, in
from azure.mgmt.recoveryservicesbackup import RecoveryServicesBackupClient
ImportError: cannot import name 'RecoveryServicesBackupClient' from 'azure.mgmt.recoveryservicesbackup' (/usr/local/lib/python3.10/dist-packages/azure/mgmt/recoveryservicesbackup/init.py)

##### ISSUE TYPE
ImportError: cannot import name 'RecoveryServicesBackupClient' from 'azure.mgmt.recoveryservicesbackup' (/usr/local/lib/python3.10/dist-packages/azure/mgmt/recoveryservicesbackup/__init__.py) #31993

##### ANSIBLE VERSION
ansible [core 2.15.4]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.10/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True

``
##### COLLECTION VERSION

```paste below

# /usr/lib/python3/dist-packages/ansible_collections
Collection        Version
----------------- -------
community.general 1.3.6

# /usr/local/lib/python3.10/dist-packages/ansible_collections
Collection        Version
----------------- -------
community.general 7.4.0

```

##### CONFIGURATION

```paste below
 ansible-config dump --only-changed
CONFIG_FILE() = /etc/ansible/ansible.cfg
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = ['/home/ansible/inventory/inv']
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = ['/home/ansible/roles']
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
INTERPRETER_PYTHON(/etc/ansible/ansible.cfg) = /usr/bin/python3.10

```

##### OS / ENVIRONMENT

cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

*-firmware
          description: BIOS
          vendor: American Megatrends Inc.
          physical id: 0
          version: 090008
          date: 12/07/2018
          size: 64KiB
          capacity: 256KiB

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_azure_rm_virtualmachine_info_payload_fb_d5cd6/ansible_azure_rm_virtualmachine_info_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py", line 275, in <module>
    from azure.mgmt.recoveryservicesbackup import RecoveryServicesBackupClient
ImportError: cannot import name 'RecoveryServicesBackupClient' from 'azure.mgmt.recoveryservicesbackup' (/usr/local/lib/python3.10/dist-packages/azure/mgmt/recoveryservicesbackup/__init__.py)

"msg": "Failed to import the required Python library (ansible[azure] (azure >= 2.0.0)) on ansiblekmtl's Python /usr/bin/python3. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"
}

```paste below

```

**Comment by markarping** [comment]
Can you update the bug fix solutions to fix this issue.

**Comment by GaretJax** [comment]
https://github.com/Azure/azure-sdk-for-python/issues/28757#issuecomment-1448729884 this fix works for me.

https://github.com/ansible-collections/azure/blob/86e0f070372400d6b50ce66f6f78542b18fd8e38/plugins/module_utils/azure_rm_common.py#L275-L276

```diff
-from azure.mgmt.recoveryservicesbackup import RecoveryServicesBackupClient
-import azure.mgmt.recoveryservicesbackup.models as RecoveryServicesBackupModels
+from azure.mgmt.recoveryservicesbackup.activestamp import RecoveryServicesBackupClient
+import azure.mgmt.recoveryservicesbackup.activestamp.models as RecoveryServicesBackupModels
```

**Comment by Fred-sun** [comment]
@GaretJax @markarping The above prompt appears because the version you installed does not match the version specified for your requirements. The version now required is azure-mgmt-recoveryservicesbackup==3.0.0. I recommend you try this version. Thank you!

**Comment by eliassal** [comment]
@GaretJax I had azure-mgmt-recoveryservicesbackup 7.0.0 which I removed when I trtied to install 3.0.0, here is the output

> pip install azure-mgmt-recoveryservicesbackup version==3.0.0
> Defaulting to user installation because normal site-packages is not writeable
> Requirement already satisfied: azure-mgmt-recoveryservicesbackup in /usr/lib/python3.11/site-packages (6.0.0)
> ERROR: Could not find a version that satisfies the requirement version==3.0.0 (from versions: 0.1.0, 0.1.1)
> ERROR: No matching distribution found for version==3.0.0

**Comment by eliassal** [comment]
when I tried agai as now it is version 6.0.0 I got the sasme result

> The full traceback is:
> Traceback (most recent call last):
>   File "/tmp/ansible_azure_rm_virtualnetwork_payload_nuo_y727/ansible_azure_rm_virtualnetwork_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py", line 264, in <module>
>     from azure.mgmt.recoveryservicesbackup import RecoveryServicesBackupClient
> ImportError: cannot import name 'RecoveryServicesBackupClient' from 'azure.mgmt.recoveryservicesbackup' (/usr/lib/python3.11/site-packages/azure/mgmt/recoveryservicesbackup/__init__.py)
> fatal: [localhost]: FAILED! => {
>     "changed": false,
>     "invocation": {
>         "module_args": {
>             "ad_user": null,
>             "address_prefixes": "10.10.0.0/16",
>             "address_prefixes_cidr": [
>                 "10.10.0.0/16"
>             ],
>             "adfs_authority_url": null,
>             "api_profile": "latest",
>             "append_tags": true,
>             "auth_source": "auto",
>             "cert_validation_mode": null,
>             "client_id": null,
>             "cloud_environment": "AzureCloud",
>             "dns_servers": null,
>             "flow_timeout_in_minutes": null,
>             "location": null,
>             "log_mode": null,
>             "log_path": null,
>             "name": "awesomevnet",
>             "password": null,
>             "profile": null,
>             "purge_address_prefixes": false,
>             "purge_dns_servers": false,
>             "resource_group": "manageazureansible",
>             "secret": null,
>             "state": "present",
>             "subscription_id": null,
>             "tags": null,
>             "tenant": null,
>             "thumbprint": null,
>             "x509_certificate_path": null
>         }
>     },
>     "msg": "Failed to import the required Python library (ansible[azure] (azure >= 2.0.0)) on puppetmaster29's Python /usr/bin/python3. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"
>

**Comment by Fred-sun** [comment]
@eliassal This is because there is a problem with your environment after you reinstall it. Can you reconfigure the environment and try again? Please refer to the following order(https://github.com/ansible-collections/azure). Thank you!
```e.g.
pip3 install ansible[azure]  --- Install ansible
ansible-galaxy collection install azure.azcollection  ---- Install Azure Collections
pip3 install -r ~/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt ---- install dependence

**Comment by eliassal** [comment]
@Fred-sun Thanks, I followed the exact same instructions, rerun ansible-playbook I got

> ERROR! couldn't resolve module/action 'azure_rm_virtualnetwork'. This often indicates a misspelling, missing collection, or incorrect module path.
> 
> The error appears to be in '/home/salam/projects/content-managing-azure-resources-with-ansible/deploying-azure-virtual-machines/vm.yml': line 23, column 7, but may
> be elsewhere in the file depending on the exact syntax problem.
> 
> The offending line appears to be:
> 
>   tasks:
>     - name: Create virtual network
>       ^ here

**Comment by eliassal** [comment]
@Fred-sun for your covenienance, here is the ansible playbook

```
---
- name: Create Azure VM
  hosts: localhost
  connection: local
  
  collections:
    - azure.azcollection
  
  vars_prompt:
    - name: password
      prompt: "Enter local administrator password"
  
  vars:
    resource_group_name: manageazureansible
    vm_name: awesomevm1
    vnet_name: awesomevnet
    subnet_name: awesomesubnet1
    public_ip_name: awesomepublicip1
    security_group_name: awesomesecgroup1
    network_interface_name: awesomenic1
  
  tasks:
    - name: Create virtual network
      azure_rm_virtualnetwork:
        resource_group: "{{ resource_group_name }}"
        name: "{{ vnet_name }}"
        address_prefixes: "10.10.0.0/16"
    
    - name: Add subnet
      azure_rm_subnet:
        resource_group: "{{ resource_group_name }}"
        name: "{{ subnet_name }}"
        address_prefix: "10.10.0.0/24"
        virtual_network: "{{ vnet_name }}"
    
    - name: Create public ip
      azure_rm_publicipaddress:
        resource_group: "{{ resource_group_name }}"
        allocation_method: Static
        name: "{{ public_ip_name }}"
    
    - name: Create security group that allows RDP
      azure_rm_securitygroup:
        resource_group: "{{ resource_group_name }}"
        name: "{{ security_group_name }}"
        rules:
          - name: 'allow_rdp'
            protocol: Tcp
            destination_port_range: 3389
            access: Allow
            priority: 1001
            direction: Inbound
          - name: 'allow_web_traffic'
            protocol: Tcp
            destination_port_range:
              - 80
              - 443
            access: Allow
            priority: 1002
            direction: Inbound
          - name: 'allow_powershell_remoting'
            protocol: Tcp
            destination_port_range: 
              - 5985
              - 5986
            access: Allow
            priority: 1003
            direction: Inbound
    
    - name: Create NIC
      azure_rm_networkinterface:
        resource_group: "{{ resource_group_name }}"
        name: "{{ network_interface_name }}"
        virtual_network: "{{ vnet_name }}"
        subnet: "{{ subnet_name }}"
        public_ip_name: "{{ public_ip_name }}"
        security_group: "{{ security_group_name }}"
    
    - name: Create virtual machine
      azure_rm_virtualmachine:
        resource_group: "{{ resource_group_name }}"
        name: "{{ vm_name }}"
        vm_size: Standard_DS1_v2
        managed_disk_type: Standard_LRS
        admin_username: awesomeadmin
        admin_password: "{{ password }}"
        network_interfaces: "{{ network_interface_name }}"
        os_type: Windows
        image:
            offer: WindowsServer
            publisher: MicrosoftWindowsServer
            sku: 2019-Datacenter
            version: latest
      no_log: true


```
