### ISSUE TITLE
azure_rm_adapplication module not idempotent

### ISSUE THREAD

**Issue by Anthirian** [ansible/ansible_collections_azure#1264]
##### SUMMARY
Creating a new AAD application results in duplicates and is therefore not idempotent.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`azure_rm_adapplication`

##### ANSIBLE VERSION

```paste below
ansible [core 2.15.3]
  config file = /home/geert/ansible.cfg
  configured module search path = ['/home/geert/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/virtualenvs/ansible/lib/python3.10/site-packages/ansible
  ansible collection location = /home/geert/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/virtualenvs/ansible/bin/ansible
  python version = 3.10.13 (main, Aug 29 2023, 13:29:07) [GCC] (/opt/virtualenvs/ansible/bin/python)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
# /home/geert/.ansible/collections/ansible_collections
Collection         Version
------------------ -------
azure.azcollection 1.17.0

# /opt/virtualenvs/ansible/lib/python3.10/site-packages/ansible_collections
Collection         Version
------------------ -------
azure.azcollection 1.16.0
```

##### CONFIGURATION

```paste below
CALLBACKS_ENABLED(/home/geert/ansible.cfg) = ['profile_roles', 'timer', 'mail', 'pushover']
CONFIG_FILE() = /home/geert/ansible.cfg
DEFAULT_ASK_VAULT_PASS(/home/geert/ansible.cfg) = True
DEFAULT_HOST_LIST(/home/geert/ansible.cfg) = ['/home/geert/inventory.yml']
DEFAULT_LOAD_CALLBACK_PLUGINS(/home/geert/ansible.cfg) = True
DEFAULT_LOG_PATH(/home/geert/ansible.cfg) = /home/geert/ansible.log
DEFAULT_REMOTE_USER(/home/geert/ansible.cfg) = ansible
DEFAULT_STDOUT_CALLBACK(/home/geert/ansible.cfg) = yaml
DEFAULT_TIMEOUT(/home/geert/ansible.cfg) = 60
EDITOR(env: EDITOR) = vim
HOST_KEY_CHECKING(/home/geert/ansible.cfg) = False
PAGER(env: PAGER) = less
```

##### OS / ENVIRONMENT
```
$ cat /etc/os-release
NAME="openSUSE Tumbleweed"
# VERSION="20230917"
ID="opensuse-tumbleweed"
ID_LIKE="opensuse suse"
VERSION_ID="20230917"
PRETTY_NAME="openSUSE Tumbleweed"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:tumbleweed:20230917"
BUG_REPORT_URL="https://bugzilla.opensuse.org"
SUPPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org"
DOCUMENTATION_URL="https://en.opensuse.org/Portal:Tumbleweed"
LOGO="distributor-logo-Tumbleweed"
```

```
$ uname -a
Linux laptop-geert 6.5.3-1-default #1 SMP PREEMPT_DYNAMIC Thu Sep 14 08:46:53 UTC 2023 (786e0d6) x86_64 x86_64 x86_64 GNU/Linux
```

##### STEPS TO REPRODUCE

Use the following playbook after setting the right variables for the testing environment.

```yaml
---
- name: Create Azure AD Application
  hosts: localhost
  vars:
    tenant_id: XXX
    callback_url: https://XXX
    client_secret: XXX
  tasks:
    - name: Create Entra ID App Registration
      azure.azcollection.azure_rm_adapplication:
        tenant: "{{ tenant_id }}"
        display_name: Ansible
        state: present
        reply_urls: "{{ callback_url }}"
        available_to_other_tenants: true
        credential_description: Ansible
        password: "{{ client_secret }}"
        required_resource_accesses:
          # https://learn.microsoft.com/en-us/graph/migrate-azure-ad-graph-configure-permissions?tabs=http%2Cupdatepermissions-azureadgraph-msgraph-powershell
          - resource_app_id: 00000003-0000-0000-c000-000000000000  # Microsoft.Graph
            resource_access:
              - id: 570282fd-fa5c-430d-a7fd-fc8dc98a9dca  # Mail.Read
                type: Scope
```

##### EXPECTED RESULTS
The application should be created if it does not exist, and don't create a new one if the application with the same name already exists.

In the code there is a `get_resource()` method that gets called from the `exec_module()` method to determine whether the application that needs to be destroyed actually exists. This could be hooked into during creation and call `update_resource()` instead if it exists already.

##### ACTUAL RESULTS
The application is registered every time the playbook is ran. Azure AD does allow multiple applications with the same name, so it becomes very messy fast.
