### ISSUE TITLE
Creating identity with `certificate_authority` auth method fails

### ISSUE THREAD

**Issue by trdvangraft** [ansible/ansible_collections_azure#1276]
##### SUMMARY

When trying to create a device identity using the `certificate_authority` as auth method the device does not get created.
This seems to be a missing attribute within the azure_rm_iotdevice.py module. 

Checking the code it is logical as the attribute does not actually exists therefore the fix should be quite trivial
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

azure.azcollection

##### ANSIBLE VERSION

```paste below
ansible [core 2.13.12]
```

##### COLLECTION VERSION

```paste below
azure.azcollection 1.18.1
community.general  7.4.0  
```

##### OS / ENVIRONMENT

Ubuntu 20.04

##### STEPS TO REPRODUCE

```yaml
azure.azcollection.azure_rm_iotdevice:
      edge_enabled: yes
      primary_thumbprint: "{{ cert_fingerprint }}"
      secondary_thumbprint: "{{ cert_fingerprint }}"
      hub: "{{ iothub_hostname }}"
      name: "{{inventory_hostname}}"
      client_id: "{{ azure_client_id }}"
      secret: "{{ azure_secret }}"
      subscription_id: "{{ azure_subscription_id }}" 
      tenant: "{{ tenant_id }}"
      auth_method: "certificate_authority"
      hub_policy_key: {{ hub_policy_key }}
      hub_policy_name: "iothubowner"
    register: iotdevice_upload
```

##### EXPECTED RESULTS

The device gets created in the expected IoT hub

##### ACTUAL RESULTS

```paste below
FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_azure.azcollection.azure_rm_iotdevice_payload__hczpyi4/ansible_azure.azcollection.azure_rm_iotdevice_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_iotdevice.py\", line 397, in create_device\nAttributeError: 'AzureRMIoTDevice' object has no attribute 'primary_thumbprint'
```
