### ISSUE TITLE
How to use System Managed Identities on Azure VMs via MSI? 

### ISSUE THREAD

**Issue by DevopsMercenary** [ansible/ansible_collections_azure#1293]
##### SUMMARY

Does Ansible support system-assigned managed identities when being run remotely on an Azure VM ?

For example, I’m running ansible locally, and updating the configuration of my VM that is running in Azure. During the configuration, I want the VM to pull a blob out of a storage account. I’ve given the VM the Appropriate RBAC permissions to do so. If I ssh to my VM and manually use the Azure CLI or AZCopy I can get the blob from the storage account.

I do have the MSILinuxExtension installed and I can get a token if I call it directly.  

```
curl 'http://localhost:50342/oauth2/token?&resource=https://management.azure.com/' -H Metadata:true
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

azure.azcollection.azure_rm_storageblob:

##### ANSIBLE VERSION

```
ansible [core 2.15.5]
  config file = /Users/greg/.ansible.cfg
  configured module search path = ['/Users/greg/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/homebrew/Cellar/ansible/8.5.0/libexec/lib/python3.11/site-packages/ansible
  ansible collection location = /Users/greg/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/homebrew/bin/ansible
  python version = 3.11.6 (main, Oct  2 2023, 20:46:14) [Clang 14.0.3 (clang-1403.0.22.14.1)] (/opt/homebrew/Cellar/ansible/8.5.0/libexec/bin/python)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```
ansible-galaxy collection list  azure.azcollection

# /Users/greg/.ansible/collections/ansible_collections
Collection         Version
------------------ -------
azure.azcollection 1.18.1

# /opt/homebrew/Cellar/ansible/8.5.0/libexec/lib/python3.11/site-packages/ansible_collections
Collection         Version
------------------ -------
azure.azcollection 1.18.1
```

##### CONFIGURATION

```
ansible-config dump --only-changed
CONFIG_FILE() = /Users/greg/.ansible.cfg
```

##### OS / ENVIRONMENT

 I'm running on a Mac with Ventura 13.6 (22G120)
The VM that I'm configuring is Unbuntu 20_04 LTS

##### STEPS TO REPRODUCE

```yaml

- name: Update devops-test-host Host
  hosts: devops-test-host
  remote_user: azureadmin
  become: yes
  become_method: sudo

  vars:
    ansible_ssh_private_key_file: "/tmp/devops-test-host-host-admin-ssh-private-key"

  tasks:
  - name: Get the install file from blobstorage
    azure.azcollection.azure_rm_storageblob:
      resource_group: devops-storage-account
      storage_account_name: devopsstoragecom
      container: software
      blob: devops-test-host/v4.3.2/devops-test-host_Linux_ubuntu2004_x64
      dest: /opt/devops-test-host/devops-test-host_Linux_ubuntu2004_x64
      auth_source: msi

```

##### EXPECTED RESULTS

I expect the blob to be downloaded

##### ACTUAL RESULTS

```paste below
https://gist.github.com/DevopsMercenary/dc772f99144c7f1b6a64c50738dc7f4d
```
