### ISSUE TITLE
KeyError: 'value' on ret.append(secret_res.json()["value"])

### ISSUE THREAD

**Issue by TiTi** [ansible/ansible_collections_azure#1297]
##### SUMMARY
azure_keyvault_secret lookup ignores specified client_id/secret/tenant_id and tries to use MSI (Managed Service Identity)

We get a weird error saying "value" is not present in the response:
```
12:11:28  exception during Jinja2 execution: Traceback (most recent call last):
12:11:28    File "/usr/local/lib/python3.10/site-packages/ansible_collections/azure/azcollection/plugins/lookup/azure_keyvault_secret.py", line 203, in run
12:11:28      ret.append(secret_res.json()["value"])
12:11:28  KeyError: 'value'
```

However, after troubleshooting, I can say that happens because the request to the vault is made with the wrong identity and indeed there is no secret 'value' in the response but:
```
{"error":{"code":"Forbidden","message":"The user, group or application 'appid=c4219d50-9291-4cf7-a38a-b7367511eac6;oid=a39f3977-5258-4162-927d-a4270e16b05c;iss=https://sts.windows.net/<silenced>/' does not have secrets get permission on key vault 'kv-<silenced>;location=francecentral'. For help resolving this issue, please see https://go.microsoft.com/fwlink/?linkid=2125287","innererror":{"code":"AccessDenied"}}}
```

Our controller node happens to run in a container running on azure.  
azure_keyvault_secret.py first tries to get a token by going to http://169.254.169.254/metadata/identity/oauth2/token and this works in our case...
https://github.com/ansible-collections/azure/blob/dev/plugins/lookup/azure_keyvault_secret.py#L145C31-L145C84
However, the associated managed identity is handled by the team responsible for our CI/CD, and it's NOT the one we want to use to read a key vault secret. We currently have no way to override this.
Despite specifying client_id/secret/tenant_id, code relies on TOKEN_ACQUIRED and lookup_secret_non_msi is never called.

It would be nice to:
- automatically skip MSI token grab when client_id/secret/tenant_id are specified
- ability to configure code path for DefaultAzureCredential() scenario (by environment variables)  
for instance having a dedicated lookup parameter like: `, skip_msi=true, `

##### ISSUE TYPE
- Bug Report
- Feature Idea

##### COMPONENT NAME
azure_keyvault_secret

##### ANSIBLE VERSION

```
ansible-playbook [core 2.15.4]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.10/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.10.13 (main, Aug 26 2023, 01:12:06) [GCC 12.2.1 20220924] (/usr/local/bin/python)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```
ansible==8.4.0
thus azure.azcollection is in: v1.17.0 (2023-8-23)
```

##### STEPS TO REPRODUCE

Set up a key vault.
Try to use lookup('azure.azcollection.azure_keyvault_secret' from an ansible controller node which is a resource on azure having a managed identity (ex: vm or container);
But:
- do not allow keyvault access policies for this managed identity
- allow keyvault access policies to ANOTHER identity
In the following example, we grab the other identity credentials in an hashicorp vault:

```yaml
---

- name: Test keyvault module
  hosts: localhost
  gather_facts: false
  vars:
    vault_response: "{{ lookup('community.hashi_vault.vault_kv2_get', '03411/h/deploy_app_{{ short_env }}', engine_mount_point='eul').secret }}"
  environment:
    AZURE_SUBSCRIPTION_ID: "{{ sid }}"
    AZURE_TENANT: "{{ vault_response['tenant_id'] }}"
    AZURE_CLIENT_ID: "{{ vault_response['client_id'] }}"
    AZURE_SECRET: "{{ vault_response['client_secret'] }}" # for most of azure.azcollection modules
    AZURE_CLIENT_SECRET: "{{ vault_response['client_secret'] }}"  # for azure.azcollection.azure_keyvault_secret lookup
  tasks:
    - name: Show kv secret with params
      ansible.builtin.debug:
        msg: "{{ lookup('azure.azcollection.azure_keyvault_secret', 'hpsecret', vault_url='https://kv-<silenced>.vault.azure.net', client_id=vault_response['client_id'], secret=vault_response['client_secret'], tenant_id=vault_response['tenant_id']) }}"

    - name: Show kv secret
      ansible.builtin.debug:
        msg: "{{ lookup('azure.azcollection.azure_keyvault_secret', 'hpsecret', vault_url='https://kv-<silenced>.vault.azure.net') }}"

```

##### EXPECTED RESULTS

The secret is properly read and returned in both tasks.

##### ACTUAL RESULTS

We get an exception in azure_keyvault_secret.py, thus stopping the play.

```
12:11:28  exception during Jinja2 execution: Traceback (most recent call last):
12:11:28    File "/usr/local/lib/python3.10/site-packages/ansible_collections/azure/azcollection/plugins/lookup/azure_keyvault_secret.py", line 203, in run
12:11:28      ret.append(secret_res.json()["value"])
12:11:28  KeyError: 'value'
12:11:28  
12:11:28  During handling of the above exception, another exception occurred:
12:11:28  
12:11:28  Traceback (most recent call last):
12:11:28    File "/usr/local/lib/python3.10/site-packages/ansible/template/__init__.py", line 865, in _lookup
12:11:28      ran = instance.run(loop_terms, variables=self._available_variables, **kwargs)
12:11:28    File "/usr/local/lib/python3.10/site-packages/ansible_collections/azure/azcollection/plugins/lookup/azure_keyvault_secret.py", line 205, in run
12:11:28      raise AnsibleError('Failed to fetch secret ' + term + '.')
12:11:28  ansible.errors.AnsibleError: Failed to fetch secret hpsecret.
12:11:28  fatal: [localhost]: FAILED! => {
12:11:28      "msg": "An unhandled exception occurred while running the lookup plugin 'azure.azcollection.azure_keyvault_secret'. Error was a <class 'ansible.errors.AnsibleError'>, original message: Failed to fetch secret hpsecret.. Failed to fetch secret hpsecret."
12:11:28  }
```

##### TROUBLESHOOTING
To obtain a token from the managed identity, you can use:
```yaml
    - name: Get managed identity url
      ansible.builtin.uri:
        url: http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https://vault.azure.net
        headers:
          Metadata: "true"
        return_content: true
      register: msi_token
```
Then you can check the keyvault response by doing a curl or this (overriding default az rest token):
```
az rest --url "https://kv-<silenced>.vault.azure.net/secrets/hpsecret?api-version=2016-10-01" --resource "https://vault.azure.net" --headers Authorization="Bearer <access_token>"
```
=>Forbidden({"error":{"code":"Forbidden","message": ....
