### ISSUE TITLE
Unable to assign PPG to existing Azure VM using azure_rm_virtualmachine module

### ISSUE THREAD

**Issue by fendisuyanto** [ansible/ansible_collections_azure#1298]
##### SUMMARY
I try to assign an existing Azure VM to a PPG, but not able to find any documentation how to do it.
And the only module look like make sense is azure_rm_virtualmachine.
I didn't get any error when execute that, but it will not assign the PPG and no error

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure_rm_virtualmachine

##### ANSIBLE VERSION

```paste below
ansible [core 2.12.2]
  python version = 3.8.12
  ninja version = 2.10.3
```

##### COLLECTION VERSION

```paste below
# /home/user/.ansible/collections/ansible_collections
Collection.             Version
------------------ --------
azure.azcollecton 1.18.1

# /usr/share/ansible/collections/ansible_collections
Collection.             Version
------------------ --------
azure.azcollecton 1.16.0
```

##### CONFIGURATION

```paste below
CALLBACKS_ENABLED(/home/user/.ansible.cfg) = ['timer','profile_tasks','profile_roles']
DEFAULT_FORKS(/home/user/.ansible.cfg) = 10
DEPRECATION_WARNINGS(env: ANSIBLE_DEPRECATION_WARNINGS) = False
HOST_KEY_CHECKING(env: ANSIBLE_HOST_KEY_CHECKING) = False
```

##### OS / ENVIRONMENT

OS = RHEL 8.6
Azure VM

##### STEPS TO REPRODUCE

Update the VM using Ansible module azure_rm_virtualmachine

```yaml
- name: Update PPG
   azure_rm_virtualmachine:
     resource_group: "{{ resource_group }}"
     name: "{{ azure_vm_name }}"
     proximity_placement_group: "{{ ppg_id }}"
   delegate_to: localhost
```

##### EXPECTED RESULTS

VM assign to PPG

##### ACTUAL RESULTS

Ansible result only show as OK
but nothing change on the VM when check from Azure portal on the VM or on the PPG

```paste below

```
