### ISSUE TITLE
azure_rm_aks add networkPluginMode overlay when using the Azure CNI Option

### ISSUE THREAD

**Issue by zathorne** [ansible/ansible_collections_azure#1312]
##### SUMMARY

When deploying a new cluster it would be helpful to enable the Overlay feature when using the azure network plugin. Currently after a cluster is built, one needs to use the Azure CLI to enable the "overlay"

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

network_plugin_mode

Current JSON when building from UI. 
1.	“networkPlugin” == “azure” and 
2.	“networkPluginMode” == “overlay”

##### ADDITIONAL INFORMATION

Deploy clusters using the network overlay functionality currently available in the azure cli. Currently only the network plugin type of "azure" and "kubenet" are supported. This would enhance the Azure network plugin

```yaml
network_profile:
          network_plugin: azure
          network_plugin_mode: overlay

```
