### ISSUE TITLE
azure_rm_storageblob - AttributeError: 'Cloud' object has no attribute 'decode'

### ISSUE THREAD

**Issue by filippoantoniolussana** [ansible/ansible_collections_azure#1337]
I'm getting the following error when trying to use azure_rm_storageblob. (Azure collection 2.0.0)
**Error:**
```
AttributeError: 'Cloud' object has no attribute 'decode'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

**Related task:**
```
- name: Download the file locally
      azure.azcollection.azure_rm_storageblob:
        resource_group: 
        auth_source: cli
        subscription_id: 
        storage_account_name: 
        container: 
        blob: 
        dest: 
      delegate_to: localhost
```

**Ansible version:**
```
ansible [core 2.15.6]
  config file = None
  configured module search path = ['/home/filippo/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/filippo/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /home/filippo/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```
