### ISSUE TITLE
Module azure.azcollection.azure_rm_virtualmachine: additionalCapabilities.ultraSSDEnabled

### ISSUE THREAD

**Issue by niolap** [ansible/ansible_collections_azure#1356]
##### SUMMARY

Currently it's not possible (unless I missed it) with the module azure_rm_virtualmachine to create a VM that has the ultraSSD mode enable.

Because of this, it's not possible to attache UltraSSD disk after the VM creation:

```bash
TASK [yak.core.os_storage : Create and attach the managed disk to VM] ****************************************************************************************************************************************************************************************************
failed: [azure/srv-linux-02 -> localhost] (item=1) => {"ansible_loop_var": "item", "changed": false, "item": "1", "msg": "Error updating virtual machine srv-linux-02 - (InvalidParameter) StorageAccountType UltraSSD_LRS can be used only when additionalCapabilities.ultraSSDEnabled is set.\nCode: InvalidParameter\nMessage: StorageAccountType UltraSSD_LRS can be used only when additionalCapabilities.ultraSSDEnabled is set.\nTarget: managedDisk.storageAccountType"}
```

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

Module: azure_rm_virtualmachine

##### ADDITIONAL INFORMATION

```yaml
- name: Create VM with defaults
  azure_rm_virtualmachine:
    resource_group: myResourceGroup
    name: testvm10
    ################################
    additional_capabilities:           # We should be able to enable the additionalCapabilities.ultraSSDEnabled
      ultra_ssd_enabled: Yes           # with that option.
    ################################
    admin_username: "{{ username }}"
    admin_password: "{{ password }}"
    image:
      offer: CentOS
      publisher: OpenLogic
      sku: '7.1'
      version: latest
```
