### ISSUE TITLE
No module named 'azure.mgmt.recoveryservicesbackup.models' error with Entra ID App Registration

### ISSUE THREAD

**Issue by Anthirian** [ansible/ansible_collections_azure#1357]
##### SUMMARY

I'm seeing Python import errors deploying an Entra ID app registration using the Azure collection.

This seems to be related:

https://github.com/ansible-collections/azure/issues/1260#issuecomment-1723531288

##### ISSUE TYPE

- Bug Report

##### COMPONENT NAME

- `azure.azcollection.azure_rm_adapplication` (Ansible module)
- `azure.mgmt.recoveryservicesbackup.models` (Python module)

##### ANSIBLE VERSION

```paste below
ansible [core 2.15.6]
  config file = /home/anthirian/ansible.cfg
  configured module search path = ['/home/anthirian/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.11/site-packages/ansible
  ansible collection location = /home/anthirian/collections:/home/anthirian/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.11.6 (main, Nov 15 2023, 09:22:27) [GCC] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```
$ ansible-galaxy collection list azure.azcollection

# /home/anthirian/collections/ansible_collections
Collection         Version
------------------ -------
azure.azcollection 2.0.0

# /usr/lib/python3.11/site-packages/ansible_collections
Collection         Version
------------------ -------
azure.azcollection 1.19.0
[...]
```

##### CONFIGURATION

```
CALLBACKS_ENABLED(/home/anthirian/ansible.cfg) = ['profile_roles', 'timer', 'mail', 'pushover']
COLLECTIONS_PATHS(/home/anthirian/ansible.cfg) = ['/home/anthirian/collections', '/home/anthirian/.ansible/collections', '/usr/share/ansible/collect>
CONFIG_FILE() = /home/anthirian/ansible.cfg
DEFAULT_LOAD_CALLBACK_PLUGINS(/home/anthirian/ansible.cfg) = True
DEFAULT_LOG_PATH(/home/anthirian/ansible.cfg) = /home/anthirian/ansible.log
DEFAULT_STDOUT_CALLBACK(/home/anthirian/ansible.cfg) = yaml
DEFAULT_TIMEOUT(/home/anthirian/ansible.cfg) = 60
EDITOR(env: EDITOR) = vim
HOST_KEY_CHECKING(/home/anthirian/ansible.cfg) = False
PAGER(env: PAGER) = less
```

##### OS / ENVIRONMENT

```
$ uname -a
Linux mg-geert 6.6.2-1-default #1 SMP PREEMPT_DYNAMIC Mon Nov 20 11:22:36 UTC 2023 (263a855) x86_64 x86_64 x86_64 GNU/Linux
```

```
$ cat /etc/os-release
NAME="openSUSE Tumbleweed"
# VERSION="20231126"
ID="opensuse-tumbleweed"
ID_LIKE="opensuse suse"
VERSION_ID="20231126"
PRETTY_NAME="openSUSE Tumbleweed"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:tumbleweed:20231126"
BUG_REPORT_URL="https://bugzilla.opensuse.org"
SUPPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org"
DOCUMENTATION_URL="https://en.opensuse.org/Portal:Tumbleweed"
LOGO="distributor-logo-Tumbleweed"
```

```
$ sudo zypper info ansible-core ansible

Information for package ansible-core:
-------------------------------------
Repository     : openSUSE-Tumbleweed-Oss
Name           : ansible-core
Version        : 2.15.6-1.1
Arch           : noarch
Vendor         : openSUSE
Installed Size : 11,3 MiB
Installed      : Yes
Status         : up-to-date
Source package : ansible-core-2.15.6-1.1.src
Upstream URL   : https://ansible.com/
Summary        : Radically simple IT automation
Description    :
    Ansible is a radically simple IT automation system. It handles
    configuration management, application deployment, cloud provisioning,
    ad-hoc task execution, network automation, and multi-node orchestration. Ansible makes complex
    changes like zero-downtime rolling updates with load balancers easy. More information on the Ansible `website <https://ansible.com/>`_.


Information for package ansible:
--------------------------------
Repository     : openSUSE-Tumbleweed-Oss
Name           : ansible
Version        : 8.6.1-1.1
Arch           : noarch
Vendor         : openSUSE
Installed Size : 469,2 MiB
Installed      : Yes
Status         : up-to-date
Source package : ansible-8.6.1-1.1.src
Upstream URL   : https://ansible.com/
Summary        : Radically simple IT automation
Description    :
    Ansible is a radically simple model-driven configuration management, multi-node
    deployment, and remote task execution system. Ansible works over SSH and does
    not require any software or daemons to be installed on remote nodes. Extension
    modules can be written in any language and are transferred to managed machines
    automatically.
```

##### STEPS TO REPRODUCE

I have a playbook containing just one task:

```yaml
- name: Create new Entra ID App Registration
  delegate_to: localhost
  azure.azcollection.azure_rm_adapplication:
    tenant: some_tenant
    display_name: App Registration
    state: present
    reply_urls: https://callback.url/login/authorized
    available_to_other_tenants: true
    credential_description: Ansible
    password: something
    required_resource_accesses:
      # https://learn.microsoft.com/en-us/graph/migrate-azure-ad-graph-configure-permissions?tabs=http%2Cupdatepermissions-azureadgraph-msgraph-powershell
      - resource_app_id: 00000003-0000-0000-c000-000000000000  # Microsoft.Graph
        resource_access:
          - id: 570282fd-fa5c-430d-a7fd-fc8dc98a9dca  # Mail.Read
            type: Scope
          - id: 818c620a-27a9-40bd-a6a5-d96f7d610b4b  # MailboxSettings.ReadWrite
            type: Scope
          - id: dfabfca6-ee36-4db2-8208-7a28381419b3  # Notes.Read.All
            type: Scope
          - id: e1fe6dd8-ba31-4d61-89e7-88639da4683d  # User.Read
            type: Scope
          - id: b340eb25-3456-403f-be2f-af7a0d370277  # User.ReadBasic.All
            type: Scope
          - id: e383f46e-2787-4529-855e-0e479a3ffac0  # Mail.Send
            type: Scope
          - id: ff74d97f-43af-4b68-9f2a-b77ee6968c5d  # Contacts.Read
            type: Scope
          - id: 863451e7-0667-486c-a5d6-d135439485f0  # Files.ReadWrite.All
            type: Scope
  register: new_app_registration_result
  failed_when: >
    (new_app_registration_result is failed) and
    ("Another object with the same value for property identifierUris already exists." not in new_app_registration_result.msg)
```

##### EXPECTED RESULTS

App registration successful

##### ACTUAL RESULTS

```
TASK [remote-host : Create new Entra ID App Registration] **********************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ModuleNotFoundError: No module named 'azure.mgmt.recoveryservicesbackup.models'
fatal: [remote-host -> localhost]: FAILED! => changed=false
  failed_when_result: true
  msg: Failed to import the required Python library (ansible[azure] (azure >= 2.0.0)) on mg-geert's Python /usr/bin/python3. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible
 is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter
```
