### ISSUE TITLE
`protocol` parameter case mismatch `azure_rm_securitygroup`

### ISSUE THREAD

**Issue by Mohammad-Atif-Khan** [ansible/ansible_collections_azure#1358]
##### SUMMARY

I'm trying to extract NSG rules from an NSG in Azure and then apply those to another NSG, however, the data returned by `azure_rm_securitygroup_info` module has the `protocol` attribute in all upper case while the `azure_rm_securitygroup` module expects it with only the [first letter capitalized](https://docs.ansible.com/ansible/latest/collections/azure/azcollection/azure_rm_securitygroup_module.html#parameter-rules/protocol)
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

azure.azcollection.azure_rm_securitygroup_info
azure.azcollection.azure_rm_securitygroup
##### ANSIBLE VERSION

```paste below
---
ansible:
  collections:
    details: {}
    errors:
    - |-
      ERROR! Unexpected Exception, this is probably a bug: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
  version:
    details: ansible [core 2.12.5.post0]
```

##### COLLECTION VERSION

```paste below
# /usr/share/ansible/collections/ansible_collections
Collection         Version
------------------ -------
azure.azcollection 1.16.0 
```

##### CONFIGURATION

```paste below
CONFIG_FILE() = /etc/ansible/ansible.cfg
```

##### OS / ENVIRONMENT

Execution Environment via ansible-navigator

##### STEPS TO REPRODUCE

```yaml
#### get NSG info using:
- name: Get NSG Info
  azure.azcollection.azure_rm_securitygroup_info:
    subscription_id: "{{ subscription_id }}" 
    resource_group: "{{ rg_name }}"
    name: "{{ nsg_name }}"
  register: nsg_info
```
#### you get output like:
```
TASK [Print NSG rules] ********************************************************************************************************************************
ok: [localhost] => {
    "msg": [
        {
            "access": "Allow",
            "description": "CIDR blocks",
            "destination_address_prefix": "*",
            "destination_address_prefixes": [],
            "destination_application_security_groups": null,
            "destination_port_range": null,
            "destination_port_ranges": [
                "22",
                "3389"
            ],
            "direction": "Inbound",
            "etag": "W/\"0a1b2237-3af4-477a-d3afa99e3594\"",
            "id": "/subscriptions/xxxxxxxxxxx-xxxx-xxxx-xxxxx-xxxxxxxxx/resourceGroups/RG-xxxxxxxxx-01/providers/Microsoft.Network/networkSecurityGroups/DCCLDA00DEV01-nsg/securityRules/rule1",
            "name": "rule1",
            "priority": 320,
            "protocol": "TCP",
            "provisioning_state": "Succeeded",
            "source_address_prefix": null,
            "source_address_prefixes": [
                "185.46.212.0/22"
  
            ],
            "source_application_security_groups": null,
            "source_port_range": "*",
            "source_port_ranges": []
        }
    ]
}
```
#### then try to apply it via azure.azcollection.azure_rm_securitygroup :
```
- name: Create NSG
  azure.azcollection.azure_rm_securitygroup:
    subscription_id: "{{ subscription_id }}"
    resource_group: "{{ rg_name }}"
    name: "{{ nsg_name }}"
    location: "{{ azure_region }}"
    rules: "{{ nsg_info.securitygroups.0.rules }}"
```
#### you get the error:
`fatal: [localhost]: FAILED! => {"changed": false, "msg": "value of protocol must be one of: Udp, Tcp, Icmp, *, got: TCP found in rules"}`

##### EXPECTED RESULTS

Either the `azure.azcollection.azure_rm_securitygroup_info` should return output that is compatible with input for `azure.azcollection.azure_rm_securitygroup` 
OR
`azure.azcollection.azure_rm_securitygroup` should not care about the case of the protocol parameter value supplied

##### ACTUAL RESULTS

```paste below
as explained above
```
