### ISSUE TITLE
Can´t retrieve secret from Key Vault : vault_uri parameter in azure_rm_keyvault_info is not recognized

### ISSUE THREAD

**Issue by rbaret** [ansible/ansible_collections_azure#1389]
##### SUMMARY
When trying to retrieve a secret from Azure Key Vault using the azure.azcollection.azure_rm_keyvault_info module, the vault_uri parameter is not recognized, causing the playbook to fail.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure.azcollection.azure_rm_keyvault_info from azure.azcollection v2.1.1

##### ANSIBLE VERSION

```paste below
"ansible [core 2.15.6]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /root/.local/lib/python3.11/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.11.5 (main, Oct 25 2023, 14:45:39) [GCC 8.5.0 20210514 (Red Hat 8.5.0-21)] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True"
```

##### COLLECTION VERSION

```paste below
"# /root/.ansible/collections/ansible_collections
Collection         Version
------------------ -------
azure.azcollection 2.1.1  

# /root/.local/lib/python3.11/site-packages/ansible_collections
Collection         Version
------------------ -------
azure.azcollection 1.19.0 "
```

##### CONFIGURATION

```paste below
"CONFIG_FILE() = None
EDITOR(env: EDITOR) = nano
PAGER(env: PAGER) = less"
```

##### OS / ENVIRONMENT
Ansible host from which commands are run : 
```
Linux ansible 6.5.11-7-pve #1 SMP PREEMPT_DYNAMIC PMX 6.5.11-7 (2023-12-05T09:44Z) x86_64 x86_64 x86_64 GNU/Linux

CentOS Stream release 8
```

##### STEPS TO REPRODUCE

Create a secret in azure keyvault.
Log into azure using ```az login``` and an account with enough permissions on the keyvault
Set the following simple playbook ```kv.yaml```

```yaml
name: Retrieve Azure kv secret
hosts: localhost
vars:
  kevault_uri: "https://<your_kv_name.vault.azure.com"
  keyvault_secret_name: "secret_name"
tasks:
    - name: Retrieve secret from Azure Key Vault
      azure.azcollection.azure_rm_keyvault_info:
        vault_uri: "{{ keyvault_uri }}"
        name: "{{ keyvault_secret_name }}"
        auth_source: cli
      register: mysecret
```
Run the playbook : 
```ansible-playbook kv.yaml```

##### EXPECTED RESULTS

I expect the playbook to connect to the vault and retrieve the secret using the passed parameters

##### ACTUAL RESULTS

I get an error message statig that the "vault_uri" parameter in the ```azure.azcollection.azure_rm_keyvault_info``` is invalid although it is a mandatory parameter as stated in the documentation : https://galaxy.ansible.com/ui/repo/published/azure/azcollection/docs/?version=2.1.1

https://galaxy.ansible.com/ui/repo/published/azure/azcollection/docs/?version=1.19.0

The list of supported parameters also doesn´t match the one from the documentation.
Missing parameters in list compared to documentation : 
- show_deleted_key
- vault_uri
- version

Supported parameters listed in error but non-existent in official documentation : 
- resource_group

```paste below
fatal: [mariadb1]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (azure.azcollection.azure_rm_keyvault_info) module: vault_uri. Supported parameters include: ad_user, adfs_authority_url, api_profile, auth_source, cert_validation_mode, client_id, cloud_environment, log_mode, log_path, name, password, profile, resource_group, secret, subscription_id, tags, tenant, thumbprint, x509_certificate_path."}
```
