### ISSUE TITLE
Authenticating to Azure using Azure usernamd and password fails

### ISSUE THREAD

**Issue by kmj251** [ansible/ansible_collections_azure#1408]
##### SUMMARY

"UsernamePasswordCredential.get_token failed: Authentication failed: AADSTS900144: The request body must contain the following parameter: 'client_id'

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

azure_rm_common.py

##### ANSIBLE VERSION

```paste below
ansible [core 2.15.8]
```

##### COLLECTION VERSION

```paste below
azure.azcollection     2.1.1
```

##### CONFIGURATION

```paste below
CONFIG_FILE() = None
PAGER(env: PAGER) = cat%  
```

##### STEPS TO REPRODUCE

Set environment variables AZURE_AD_USER, AZURE_PASSWORD, AZURE_SUBSCRIPTION_ID

```yaml
---
- name: "Azure Get Subscription Info test"
  hosts: localhost
  connection: local

  tasks:
    - name: "Get Newly Created Azure Subscription Info"
      azure.azcollection.azure_rm_subscription_info:
        id: "<subscription_id>"
      register: sub_info_output
```

##### EXPECTED RESULTS

Playbook doesn't error with missing client_id missing in payload error.

##### ACTUAL RESULTS

Module fails with "UsernamePasswordCredential.get_token failed: Authentication failed: AADSTS900144: The request body must contain the following parameter: 'client_id'..."

```paste below
"UsernamePasswordCredential.get_token failed: Authentication failed: AADSTS900144: The request body must contain the following parameter: 'client_id'..."
```
