### ISSUE TITLE
azure_rm_adapplication_info only returns 100 applications when querying for all applications in the tenant

### ISSUE THREAD

**Issue by kmj251** [ansible/ansible_collections_azure#1419]
##### SUMMARY

Run the azure_rm_adapplication_info to gather all of the applications in the tenant. Use the registered output to find the enterprise app using the name of the app (not the object_id, or application_id).
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

azure_rm_adapplication_info

##### ANSIBLE VERSION

```paste below
ansible [core 2.15.8]
```

##### COLLECTION VERSION

```paste below
2.1.1
```

##### CONFIGURATION

```paste below
CONFIG_FILE() = None
PAGER(env: PAGER) = cat%
```

##### STEPS TO REPRODUCE

```yaml
- name: "Get all AD Applications from Tenant"
  azure.azcollection.azure_rm_adapplication_info:
    tenant: "{{ prod_tenant }}"
  register: ad_app_tenant_info
```

##### ACTUAL RESULTS

```paste below

```
Only 100 rows are returned. Per the Python SDK [documentation ](https://learn.microsoft.com/en-us/graph/api/application-list?view=graph-rest-1.0&tabs=python)for MSGraph, 100 objects returned is the default.
