### ISSUE TITLE
azure_rm_webapp missing basic auth configuration capability as exists in the underlying Python Azure SDK

### ISSUE THREAD

**Issue by jartoo** [ansible/ansible_collections_azure#1427]
##### SUMMARY
azure_rm_webapp does not appear to expose the update_auth_settings as shown in this example from the Azure SDK:

https://github.com/Azure/azure-sdk-for-python/blob/azure-mgmt-web_7.2.0/sdk/appservice/azure-mgmt-web/generated_samples/update_auth_settings.py

##### ISSUE TYPE
Expose the underlying Azure SDK functional properties to include, per the SDK:

allowedExternalRedirectUrls
clientId
defaultProvider
enabled
runtimeVersion
tokenRefreshExtensionHours
tokenStoreEnabled
unauthenticatedClientAction
etc...

##### COMPONENT NAME
azure_rm_webapp
azure_rm_webapp_info (also applies here for querying purposes)

##### ADDITIONAL INFORMATION
This will enable easy authentication configuration for Azure Application Services

```
- name: Create a linux web app with language framework
  azure.azcollection.azure_rm_webapp:
    resource_group: "{{ azure_resource_group }}"
    name: "{{ azure_web_app_name }}"
    https_only: true
    min_tls_version: 1.2
    ftps_state: Disabled
    plan:
      resource_group: "{{ azure_resource_group }}"
      name: "{{ azure_web_app_plan_name }}"
    site_auth_settings:
      allowed_external_redirect_urls:
        - "{{ azure_redirect_url1 }}"
        - "{{ azure_redirect_url2 }}"
      client_id: "{{ azure_client_id }}"
      default_provider: "Microsoft"
      enabled: True
```
