### ISSUE TITLE
azure_rm_adpassword fail with message: Updates to converged applications are not allowed in this version

### ISSUE THREAD

**Issue by polo2ro** [ansible/ansible_collections_azure#1441]
##### SUMMARY

We are building an ansible role to maintain an application with a password up to date, if no valid password exists, the role create it. before the last azure update, the role was working well with azure_rm_adpassword and no "value" attribute.
First thing, we encountered the following error message:

**when creating a new password, module parameter value can't be None**

So we tried to set the value parameter but without success

**failed to create new password: Updates to converged applications are not allowed in this version.**

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

azure_rm_adpassword

##### ANSIBLE VERSION

```paste below

ansible [core 2.15.6]
  config file = /home/paul/.ansible.cfg
  configured module search path = ['/home/paul/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/paul/.local/lib/python3.9/site-packages/ansible
  ansible collection location = /home/paul/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/paul/.local/bin/ansible
  python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True


```

##### COLLECTION VERSION

```paste below
# /home/paul/.ansible/collections/ansible_collections
Collection         Version
------------------ -------
azure.azcollection 1.19.0 

# /home/paul/.local/lib/python3.9/site-packages/ansible_collections
Collection         Version
------------------ -------
azure.azcollection 1.19.0 

# /usr/lib/python3/dist-packages/ansible_collections
Collection         Version
------------------ -------
azure.azcollection 1.4.0
```

##### CONFIGURATION

```paste below
CONFIG_FILE() = /home/paul/.ansible.cfg
DEFAULT_STDOUT_CALLBACK(/home/paul/.ansible.cfg) = debug
```

##### STEPS TO REPRODUCE

```yaml

- name: Create a new ad password if necessary
  azure.azcollection.azure_rm_adpassword:
    app_id: '{{ cloud_storage_client_id }}'
    tenant: '{{ azure_env.AZURE_TENANT }}'
    value: "{{ lookup('password', '/dev/null length=19 chars=ascii_letters') }}"
  register: ad_password_created
  when: ad_app_password | length == 0

```

##### ACTUAL RESULTS

```paste below

```
