### ISSUE TITLE
azure_rm_roleassignment fails when the role assignment already exists

### ISSUE THREAD

**Issue by wrprice** [ansible/ansible_collections_azure#145]
Migrating from ansible/ansible#67529 unrequested but on behalf of @adhodgson1. The details below are copied from that report.

##### SUMMARY
The azure_rm_roleassignment module runs in a playbook fine the first time but on subsequent plays it throws an error that the role already exists.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure_rm_roleassignment

##### ANSIBLE VERSION
Tested with Ansible 2.8.5 and 2.9.5 installed via Pip with the ansible[azure] packages

##### STEPS TO REPRODUCE

```yaml
- name: Ensure SPN has 'network contributor' rights to Subnet
  azure_rm_roleassignment:
    scope: "{{ subnet_resource_id }}"
    assignee_object_id: "{{ spn_objectid }}"
    role_definition_id: "/subscriptions/{{ azure_subscription_id }}/providers/Microsoft.Authorization/roleDefinitions/4d97b98b-1d4f-4787-a291-c67834d212e7"
    auth_source: cli
  environment:
    AZURE_CONFIG_DIR: "{{ azure_config_spn_role_assign }}"
  # Workaround for the bug
  failed_when: output_subnet_contributor.failed and 'The role assignment already exists' not in output_subnet_contributor.msg
  register: output_subnet_contributor
```

##### EXPECTED RESULTS
All plays run without error.

##### ACTUAL RESULTS
First play completes successfully, subsequent plays fail:

```paste below
TASK [aks : Ensure SPN has 'network contributor' rights to Subnet] *****************************************************
fatal: [localhost]: FAILED! => {
    "changed": false
}

MSG:

Error creating role assignment: Azure Error: RoleAssignmentExists
Message: The role assignment already exists.
```
