### ISSUE TITLE
virtual machine detach managed disk

### ISSUE THREAD

**Issue by uccsjarmo** [ansible/ansible_collections_azure#1457]
##### SUMMARY

Currently, it is not possible to detach a managed disk from a virtual machine. It would be nice if the managed disk could be attached/detached using the azure_rm_manageddisk module with property attached.  Attached property value could be true by default

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

azure_rm_manageddisk

##### ADDITIONAL INFORMATION

```yaml
- name: attach managed disk to vm
   azure.azcollection.azure_rm_manageddisk:
     name: "disk-0"
     lun: 0
     location: swedencentral
     resource_group: rg-example
     disk_size_gb: 40
     managed_by: server
     attached: true

- name: detach managed disk from vm
   azure.azcollection.azure_rm_manageddisk:
     name: "disk-0"
     lun: 0
     location: swedencentral
     resource_group: rg-example
     disk_size_gb: 40
     managed_by: server
     attached: false
```
