### ISSUE TITLE
Attaching existing managed disk(s) at VM creation

### ISSUE THREAD

**Issue by wrprice** [ansible/ansible_collections_azure#146]
The use case is that I have an _existing_ managed disk that is _not_ attached to any VM. I want to now create a VM that uses this disk, and the disk must be attached _at provisioning time_ so that it is accessible/visible to initial provisioning scripts (i.e. cloud-init).

Specifically, creating the VM and associating the disk with it later is not sufficient. That is why using the azure_rm_manageddisk module to control the disk's `managed_by` property is not a viable workaround.

There is an [example][line464] in the documentation, see `lun: 0`:

```
- name: Create a VM with OS and multiple data managed disks
  azure_rm_virtualmachine:
    # ...
    data_disks:
      - lun: 0
        managed_disk_id: "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxxxxx/resourceGroups/myResourceGroup/providers/Microsoft.Compute/disks/myDisk"
      - lun: 1
        disk_size_gb: 128
        managed_disk_type: Premium_LRS
```

This appears to be a missing feature.  The `managed_disk_id` property is not defined in the documentation, and the only use in the module source code appears to be for deleting VMs and their resources.  On create, the following error is observed:

> azure_rm_virtualmachine.py, line 1414, in exec_module
> KeyError: 'disk_size_gb'

Currently, all data disks needed during initial provisioning must be created new, by this module, as in the example above for `lun: 1` and cannot use an existing disk.  It also means the user cannot have fine-grained control of the disk's name or other properties in advance.  Using other modules to attach a data disk _after_ the VM has been provisioned is possible, as long as the disk is not needed during initial provisioning.

[line464]: https://github.com/Azure/azure_preview_modules/blob/354baf42ae4e571e5e788d03ef6a3ef267d9377f/library/azure_rm_virtualmachine.py#L464

Reopened from Azure/azure_preview_modules/issues/362 which was closed due to repo/project migration.
