### ISSUE TITLE
azure.azcollection.azure_rm_adapplication add option 'reply_urls_with_type'

### ISSUE THREAD

**Issue by therapac** [ansible/ansible_collections_azure#1490]
##### SUMMARY
It would be very useful if we could provide a type for the 'reply_urls'. We would like to have a 'reply_urls_with_type' (see ADDITIONAL INFORMATION).

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
azure.azcollection.azure_rm_adapplication module

##### ADDITIONAL INFORMATION
```python
reply_urls:
    description:
        - Space-separated URIs to which Azure AD will redirect in response to an OAuth 2.0 request.
        - The value does not need to be a physical endpoint, but must be a valid URI.
    type: list
    elements: str

# new option
reply_urls_with_type:
    description:
        - Space-separated URIs to which Azure AD will redirect in response to an OAuth 2.0 request.
    type: list
    elements: dict
    suboptions:
        url:
            description:
                - The value does not need to be a physical endpoint, but must be a valid URI.
            type: str
        type:
            description:
                - Each URI value should contain an associated app type value. Supported type values are
                    - "Web"
                    - "InstalledClient"
                    - "Spa"
            type: str
```

```yaml
- name: Setting facts so that they will be persisted in the fact cache
  ansible.builtin.set_fact:
    __app_id: "36b5a239-14c8-4a67-23f3-15225b489053"
    __reply_urls:
      - url:  "https://www.test.ch"
        type: "Web"

- name: Create application
  azure.azcollection.azure_rm_adapplication:
    app_id:                 "{{ __app_id }}"
    reply_urls_with_type:   "{{ __adapp.reply_urls }}"
```
