### ISSUE TITLE
 azure.azcollection.azure_rm_adgroup module Should allow for setting the description of the group #1485  > Only a partial Fix. Will not update existing groups.

### ISSUE THREAD

**Issue by hematic** [ansible/ansible_collections_azure#1521]
##### SUMMARY
I reported an issue that description should be supported. This was approved and fixed. Works perfectly for new groups that are created.

However for existing groups with no description, ansible will just show "OK" and doesn't believe a change is necessary. This means the field can't be updated on existing groups.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
 azure.azcollection.azure_rm_adgroup

##### ANSIBLE VERSION

```paste below

```

##### COLLECTION VERSION

```
azure.azcollection 2.3.0
```

##### CONFIGURATION

```
  tasks:
    - name: Create EntraID Group
      azure.azcollection.azure_rm_adgroup:
        tenant: "{{ azure_tenant_id }}"
        display_name: "{{ group_display_name }}"
        mail_nickname: "{{ group_mail_nickname }}"
        description: "{{ group_description }}"
        state: 'present'
```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```
