### ISSUE TITLE
Add UserAssigned Identities to the postgrsqlflexibleserver module

### ISSUE THREAD

**Issue by p3ck** [ansible/ansible_collections_azure#1527]
##### SUMMARY
Add support for specifying user assigned identities for postgresql flexible server

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
plugins/modules/azure_rm_postgresqlflexibleserver.py

##### ADDITIONAL INFORMATION
Managed Identities in Azure is a common request from many customers

```yaml
- name: Create User Managed Identities
  azure_rm_resource:
    resource_group: "{{ resource_group }}"
    provider: ManagedIdentity
    resource_type: userAssignedIdentities
    resource_name: "{{ item }}"
    api_version: "2023-01-31"
    body:
      location: eastus
    state: present
  loop:
    - "ansible-test-pgsql-identity"

- name: Set identities IDs to test. Identities ansible-test-vm-identity and ansible-test-vm-identity-2 have to be created previously
  ansible.builtin.set_fact:
    user_identity_1: "/subscriptions/{{ azure_subscription_id }}/resourcegroups/{{ resource_group }}/providers/Microsoft.ManagedIdentity/userAssignedIdentities/ansible-test-pgsql-identity"

- name: Update postgresql server with UserAssigned identity
  azure_rm_postgresqlflexibleserver:
    name: postflexible{{ rpfx }}
    resource_group: "{{ resource_group }}"
    identity:
      type: UserAssigned
      user_assigned_identities:
        id:
          - "{{ user_identity_1 }}"
```
