### ISSUE TITLE
azure_rm_subscription_info does not function as documented or expectd

### ISSUE THREAD

**Issue by Michandrz** [ansible/ansible_collections_azure#1535]
##### SUMMARY
I'm trying to create an automated inventory system. Step one of this is to pull all subscriptions that the client id and secret have access to. The documentation provides this example:

```
- name: Get facts for all subscriptions, including ones that are disabled.
  azure_rm_subscription_info:
    all: true
```

I have the Tennant, Client ID and Secret all being passed as env vars.

However, trying to call that without auth_source set or set to auto, yields an error about the AZ profile path not being valid. 

Providing the auth_source: env the module complains about not having a subscription set. 

Providing the subscription ID I get a successful call, however, it only returns me the details about the subscription info for the ID provided.

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

AWX-Operator 2.14.0
AWX: 24.1.0
Ansible: 2.15.10

##### COLLECTION VERSION

```
I can't easily do this. Here is collections/requirements.yml
---
collections:
  - name: ansible-utils-2.5.0.tar.gz
  - name: community-general-5.8.0.tar.gz
  - name: google-cloud-1.3.0.tar.gz 
  - name: vmware-vcd-1.0.2.tar.gz
  - name: ibm-cloudcollection-1.51.0.modified.tar.gz 
  - name: ansible-netcommon-2.5.1.tar.gz
  - name: ansible-posix-1.5.4.tar.gz 
  - name: community-crypto-2.2.2.tar.gz
  - name: paloaltonetworks-panos-2.18.0.tar.gz
  - name: awx-awx-23.5.1.tar.gz 
  - name: community-google-1.0.0.tar.gz
  - name: azure-azcollection-2.3.0.tar.gz

```

##### CONFIGURATION

```
unable

```

##### OS / ENVIRONMENT

Host is localhost on the default AWX-EE.

##### STEPS TO REPRODUCE

See summary above

##### EXPECTED RESULTS
Expecting to see all subscriptions that the client id and secret have access to

##### ACTUAL RESULTS
Errors related to authentication. see summary above.
