### ISSUE TITLE
network_profile.service_cidr not used when creating aks-cluster

### ISSUE THREAD

**Issue by stoetti** [ansible/ansible_collections_azure#154]
##### SUMMARY
When a aks cluster shall be created the service_cidr-range is not used for creating the cluster. I use a predefined subnet which has CIDR 10.0.0.0/16 defined, this leads to an error when creating the ASK-cluster. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ansible_rm_aks

##### ANSIBLE VERSION
```paste below
ansible 2.9.9
  config file = ***
  configured module search path = ['***', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.3 (default, May 15 2020, 00:00:00) [GCC 10.1.1 20200507 (Red Hat 10.1.1-1)]
```

##### CONFIGURATION

```paste below
DEFAULT_ROLES_PATH(/home/***/ansible.cfg) = ['/home/***/gitrepos/devops/ansible/roles', '/home/***/.ansible/roles', '/usr/share/ansible/roles', '/etc/ansible/roles']
```

##### OS / ENVIRONMENT

Fedora 32

##### STEPS TO REPRODUCE

```yaml
    - name: create AKS cluster
      tags:
        - setup
      azure_rm_aks:
        name: poc
        kubernetes_version: 1.16.9
        location: "northeurope"
        resource_group: "test"
        dns_prefix: test
        linux_profile:
          admin_username: azureuser
          ssh_key: "{{ ssh_keypair.public_key }}"
        service_principal:
          client_id: "{{ azure_client_id }}"
          client_secret: "{{ azure_client_secret }}"
        agent_pool_profiles:
          - name: default
            count: 3
            vm_size: Standard_D2_v2
            vnet_subnet_id: "{{ vnet_subnet_id }}"
        network_profile:
          dns_service_ip: "10.20.0.10"
          service_cidr: "10.20.0.0/16"
```

##### EXPECTED RESULTS
AKS-cluster is created using the service CIDR range defined.

##### ACTUAL RESULTS
Command does not use defined service CIDR for creating AKS-cluster 

```paste below
TASK [create AKS cluster] **********************************************************************************************************************************************************************************************************************************************************************************************
task path: /home/***/gitrepos/deployments/engel/edp-aks/dev.yml:88
File lookup using /home/***/gitrepos/deployments/engel/edp-aks/.config/azure/aks-deployment.json as file
File lookup using /home/***/gitrepos/deployments/engel/edp-aks/.config/azure/aks-deployment.json as file
File lookup using /home/***/gitrepos/deployments/engel/edp-aks/.config/azure/aks-deployment.json as file
File lookup using /home/***/gitrepos/deployments/engel/edp-aks/.config/azure/aks-deployment.json as file
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: ***
<127.0.0.1> EXEC /bin/sh -c 'echo ~*** && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/***/.ansible/tmp `"&& mkdir /home/***/.ansible/tmp/ansible-tmp-1591775639.2046506-449783-58509718343021 && echo ansible-tmp-1591775639.2046506-449783-58509718343021="` echo /home/***/.ansible/tmp/ansible-tmp-1591775639.2046506-449783-58509718343021 `" ) && sleep 0'
Using module file /usr/lib/python3.8/site-packages/ansible/modules/cloud/azure/azure_rm_aks.py
<127.0.0.1> PUT /home/***/.ansible/tmp/ansible-local-449603hiopnvm3/tmp6zg16s85 TO /home/stoetti/.ansible/tmp/ansible-tmp-1591775639.2046506-449783-58509718343021/AnsiballZ_azure_rm_aks.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/***/.ansible/tmp/ansible-tmp-1591775639.2046506-449783-58509718343021/ /home/***/.ansible/tmp/ansible-tmp-1591775639.2046506-449783-58509718343021/AnsiballZ_azure_rm_aks.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'AZURE_CLIENT_ID=3337e48f-136f-4c54-8327-81fa1c70c965 AZURE_SECRET=8328b361-4cf8-46a9-a8c2-e27a8019877f AZURE_SUBSCRIPTION_ID=1e170a3b-1b87-43e1-ad80-d1e2356d8b5a AZURE_TENANT=dae3d2ce-f4dc-4f24-9fd5-02fe86125e11 KUBECONFIG=/home/stoetti/gitrepos/deployments/engel/edp-aks/.config/edp_aks_ansible_kube_config /usr/bin/python3 /home/stoetti/.ansible/tmp/ansible-tmp-1591775639.2046506-449783-58509718343021/AnsiballZ_azure_rm_aks.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/stoetti/.ansible/tmp/ansible-tmp-1591775639.2046506-449783-58509718343021/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
  File "/tmp/ansible_azure_rm_aks_payload_2kxp0ahq/ansible_azure_rm_aks_payload.zip/ansible/modules/cloud/azure/azure_rm_aks.py", line 708, in create_update_aks
  File "/home/***/.local/lib/python3.8/site-packages/azure/mgmt/containerservice/v2018_03_31/operations/managed_clusters_operations.py", line 593, in create_or_update
    raw_result = self._create_or_update_initial(
  File "/home/***/.local/lib/python3.8/site-packages/azure/mgmt/containerservice/v2018_03_31/operations/managed_clusters_operations.py", line 550, in _create_or_update_initial
    raise exp
[WARNING]: Azure API profile latest does not define an entry for ContainerServiceClient
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "aad_profile": null,
            "ad_user": null,
            "addon": null,
            "adfs_authority_url": null,
            "agent_pool_profiles": [
                {
                    "count": 3,
                    "dns_prefix": null,
                    "name": "default",
                    "os_disk_size_gb": null,
                    "os_type": null,
                    "ports": null,
                    "storage_profiles": null,
                    "vm_size": "Standard_D2_v2",
                    "vnet_subnet_id": "***"
                }
            ],
            "api_profile": "latest",
            "append_tags": true,
            "auth_source": null,
            "cert_validation_mode": null,
            "client_id": null,
            "cloud_environment": "AzureCloud",
            "dns_prefix": "test",
            "enable_rbac": false,
            "kubernetes_version": "1.16.9",
            "linux_profile": {
                "admin_username": "azureuser",
                "ssh_key": "***"
            },
            "location": "northeurope",
            "name": "test",
            "network_profile": {
                "dns_service_ip": "10.20.0.10",
                "docker_bridge_cidr": null,
                "network_plugin": null,
                "network_policy": null,
                "pod_cidr": null,
                "service_cidr": "10.20.0.0/16"
            },
            "password": null,
            "profile": null,
            "resource_group": "test",
            "secret": null,
            "service_principal": {
                "client_id": "***",
                "client_secret": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
            },
            "state": "present",
            "subscription_id": null,
            "tags": null,
            "tenant": null
        }
    },
    "msg": "Error creating the AKS instance: Operation failed with status: 'Bad Request'. Details: The specified service CIDR 10.0.0.0/16 is conflicted with an existing subnet CIDR"
}

```
