### ISSUE TITLE
azure_rm_adapplication_info add option "app_diff"

### ISSUE THREAD

**Issue by TheNotoriousRMM** [ansible/ansible_collections_azure#1559]
##### SUMMARY
With the help of this option, you can compare a list of app names, app IDs, or both to the current state on Azure. The apps that are currently in Azure and are not provided with app_diff will be marked as absent in the return under app_diff.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
azure_rm_adapplication_info module

##### ADDITIONAL INFORMATION
```yaml
DOCUMENTATION = '''
options:
    app_diff:
        description:
            - The application Name or the app id.
        type: list
        elements: dict

EXAMPLES = '''
- name: get ad app diff ---- by display name
  azure_rm_adapplication_info:
    app_diff:
        - app_display_name: "{{ display_name }}"
        - app_id: "{{ app_id }}"

RETURN = '''
app_diff:
    description:
        - The info of the ad application.
    type: complex
    returned: aways
    contains:
        app_display_name:
            description:
                - Object's display name or its prefix.
            type: str
            returned: always
            sample: app
        app_id:
            description:
                - The application ID.
            returned: always
            type: str
            sample: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
        identifier_uris:
            description:
                - The identifiers_uri list of app.
            type: list
            returned: always
            sample: ["http://ansible-atodorov"]
        object_id:
            description:
                - It's application's object ID.
            returned: always
            type: str
            sample: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
        sign_in_audience:
            description:
                - The application can be used from any Azure AD tenants
            type: str
            returned: always
            sample: AzureADandPersonalMicrosoftAccount
        available_to_other_tenants:
            description:
                - The application can be used from any Azure AD tenants
            type: str
            returned: always
            sample: AzureADandPersonalMicrosoftAccount
        public_client_reply_urls:
            description:
                - The public client redirect urls.
                - Space-separated URIs to which Azure AD will redirect in response to an OAuth 2.0 request.
            returned: always
            type: list
            sample: []
        web_reply_urls:
            description:
                - The web redirect urls.
                - Space-separated URIs to which Azure AD will redirect in response to an OAuth 2.0 request.
            returned: always
            type: list
            sample: []
        spa_reply_urls:
            description:
                - The spa redirect urls.
                - Space-separated URIs to which Azure AD will redirect in response to an OAuth 2.0 request.
            returned: always
            type: list
            sample: []
        state:
            description:
                - absent --> The app isn't in the app_diff.
            returned: always
            type: str
            sample: absent
```
