### ISSUE TITLE
Feature Request: azure_rm_virtualmachine powerstate as a single parameter

### ISSUE THREAD

**Issue by joechancellor** [ansible/ansible_collections_azure#1578]
##### SUMMARY

Currently there are three different parameters to set powerstate: started, restarted and allocated.  Change that into a single parameter.
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

azure_rm_virtualmachine
##### ADDITIONAL INFORMATION

Currently there are three different parameters for powerstate: started, restarted and allocated.  With a single parameter it would enable the powerstate to be a variable and promote code reuse.  With three different parameters it requires three different tagged tasks in a single playbook, or three different playbooks to set powerstate.

```
- name: Power Off
  azure_rm_virtualmachine:
    resource_group: myResourceGroup
    name: testvm002
    powerstate: stop

- name: Power On
  azure_rm_virtualmachine:
    resource_group: myResourceGroup
    name: testvm002

- name: Restart
  azure_rm_virtualmachine:
    resource_group: myResourceGroup
    name: testvm002
    powerstate: restart

- name: Deallocate
  azure_rm_virtualmachine:
    resource_group: myResourceGroup
    name: testvm002
    powerstate: deallocate

```
