### ISSUE TITLE
azure_rm_storageaccount: Add allowSharedKeyAccess as option

### ISSUE THREAD

**Issue by sodds-eq** [ansible/ansible_collections_azure#1582]
##### SUMMARY
Allow more Configuration so be done for an Azure Storage Account:

  * "allowSharedKeyAccess": false/true

Maps to:
![image](https://github.com/ansible-collections/azure/assets/54023618/8c3fc9c9-71fa-4a83-8ea8-7c33b038f2dc)

In the GUI under Settings->Configuration
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

azure_rm_storageaccount
##### ADDITIONAL INFORMATION
Would make it possible to enabled or disable storage account key access to the resource.
```yaml
- name: create an account
  azure_rm_storageaccount:
    resource_group: myResourceGroup
    name: clh0002
    type: Standard_RAGRS
    allow_shared_key_access: false
```
