### ISSUE TITLE
[azure_rm_openshiftmanagedcluster] Add support for outbound-type

### ISSUE THREAD

**Issue by Soraph** [ansible/ansible_collections_azure#1600]
##### SUMMARY
It is not possible to create an ARO cluster with the option `--outbound-type` using the module `azure_rm_openshiftmanagedcluster`

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
azure.azcollection.azure_rm_openshiftmanagedcluster

##### ADDITIONAL INFORMATION
A simplified example based on the sample code from the documentation:
```yaml
- name: Create openshift cluster
  azure_rm_openshiftmanagedcluster:
    resource_group: "myResourceGroup"
    name: "myCluster"
    location: "eastus"
    outbound_type: "UserDefinedRouting" 
    // Or a structure that allow personalization for the other possible
    // types as per microsoft documentation on the matter

    ... 
```
