### ISSUE TITLE
azure_rm_loadbalancer support for outbound rules

### ISSUE THREAD

**Issue by wrprice** [ansible/ansible_collections_azure#162]
##### SUMMARY

Add **Outbound Rule** support to _azure_rm_loadbalancer_.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

azure_rm_loadbalancer

##### ADDITIONAL INFORMATION

Support something like:

```yaml
- azure_rm_loadbalancer:
    name: outboundOnlyLb
    resource_group: myRg
    sku: Standard
    frontend_ip_configurations:
      - name: egressIp
        public_ip_address: myPip
    backend_address_pools:
      - name: egressPool
    outbound_rules:
      - name: egressPoolRule
        frontend_ip_configuration: egressIp
        backend_address_pool: egressPool
        protocol: All
        idle_timeout: 4 # minutes
        tcp_reset: yes
        port_allocation:
          method: "ports_per_instance" # other options: "default", "maximum_backend_instances"
          limit: 1024 # ignored when `method` = "default"
```
