### ISSUE TITLE
Add support to Azure StackHCI vms in the inventory plugin

### ISSUE THREAD

**Issue by TiTi** [ansible/ansible_collections_azure#1622]
##### SUMMARY
Add ability to list Azure Stack HCI vms

I already implemented the change in this PR: https://github.com/ansible-collections/azure/pull/1620

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
inventory plugin

##### ADDITIONAL INFORMATION

Idea is to have a dynamic inventory with the AzureStackHCI vms (which are Arc vms and thus appear in azure management plane).
So that i can run my playbooks also on those vms, without the need to build a static inventory.

Most stack hci vm properties are common to azure vms.
Some properties are specific to hci vms: customLocation, memoryMB, processors count

inventory.azure_rm.yml sample:
```yaml
---

plugin: azure.azcollection.azure_rm
auth_source: auto
include_vm_resource_groups: []
include_hcivm_resource_groups:
  - rg-veeam-prd
subscription_id: <YOUR_GUID>
plain_host_names: true
default_host_filters:
  - powerstate != 'running'
  - provisioning_state != 'succeeded'
hostvar_expressions:
  # overrides the default ansible_host value with a custom Jinja2 expression
  # kerberos needs FQDN
  ansible_host: (private_ipv4_addresses | first) if os_profile.system == 'linux' else computer_name
conditional_groups:
  windows: os_profile.system == 'windows'
  linux: os_profile.system == 'linux'
  # since this will be true for every host, every host sourced from this inventory plugin config will be in the
  # group 'ind4_prd'
  ind4_prd: true
  kerberos: os_profile.system == 'windows'
keyed_groups:
  # places each host in a group named 'tag_(tag name)_(tag value)' for each tag on a VM.
  - prefix: tag
    key: tags

```
The new keyword in the above sample is: `include_hcivm_resource_groups`
Note that above sample ignores azure vm from the same resource group voluntarily, with: `include_vm_resource_groups: []`
