### ISSUE TITLE
ManagedClusterAgentPoolProfile' object has no attribute 'type'\n

### ISSUE THREAD

**Issue by boraozkan** [ansible/ansible_collections_azure#164]
##### SUMMARY

I run aks module azure_rm_aks with below yaml but I am getting and error: 
` ManagedClusterAgentPoolProfile' object has no attribute 'type'\n
`
```
---
  - name: Create a managed Azure Container Services (AKS) cluster
    azure.azcollection.azure_rm_aks:
      name: "myaks"
      location: "uksouth"
      resource_group: "mytest"
      dns_prefix: "myaks1"
      kubernetes_version: "1.16.9"
      linux_profile:
        admin_username: "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
        ssh_key: "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
      service_principal:
        client_id: "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
        client_secret: "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
      agent_pool_profiles:
        - name: default
          type: VirtualMachineScaleSets
          count: 2
          vm_size: Standard_D2_v2
          enable_auto_scaling: True
          max_count: 3
          min_count: 1
      node_resource_group: nodetest
      enable_rbac: yes
      tags:
        Environment: Production
```
##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```
fatal: [127.0.0.1]: FAILED! => {
    "changed": false,
    "module_stderr": "ports is not a known attribute of class <class 'azure.mgmt.containerservice.v2019_04_01.models._models_py3.ManagedClusterAgentPoolProfile'> and will be ignored\ndns_prefix is not a known attribute of class <class 'azure.mgmt.containerservice.v2019_04_01.models._models_py3.ManagedClusterAgentPoolProfile'> and will be ignored\nstorage_profiles is not a known attribute of class <class 'azure.mgmt.containerservice.v2019_04_01.models._models_py3.ManagedClusterAgentPoolProfile'> and will be ignored\nTraceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1592237171.5729246-2721-114335529477920/AnsiballZ_azure_rm_aks.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1592237171.5729246-2721-114335529477920/AnsiballZ_azure_rm_aks.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1592237171.5729246-2721-114335529477920/AnsiballZ_azure_rm_aks.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.azure.azcollection.plugins.modules.azure_rm_aks', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib/python3.5/runpy.py\", line 196, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.5/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib/python3.5/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_azure.azcollection.azure_rm_aks_payload_cqzday9l/ansible_azure.azcollection.azure_rm_aks_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_aks.py\", line 921, in <module>\n  File \"/tmp/ansible_azure.azcollection.azure_rm_aks_payload_cqzday9l/ansible_azure.azcollection.azure_rm_aks_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_aks.py\", line 917, in main\n  File \"/tmp/ansible_azure.azcollection.azure_rm_aks_payload_cqzday9l/ansible_azure.azcollection.azure_rm_aks_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_aks.py\", line 587, in __init__\n  File \"/tmp/ansible_azure.azcollection.azure_rm_aks_payload_cqzday9l/ansible_azure.azcollection.azure_rm_aks_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py\", line 419, in __init__\n  File \"/tmp/ansible_azure.azcollection.azure_rm_aks_payload_cqzday9l/ansible_azure.azcollection.azure_rm_aks_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_aks.py\", line 729, in exec_module\n  File \"/tmp/ansible_azure.azcollection.azure_rm_aks_payload_cqzday9l/ansible_azure.azcollection.azure_rm_aks_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_aks.py\", line 794, in create_update_aks\n  File \"/tmp/ansible_azure.azcollection.azure_rm_aks_payload_cqzday9l/ansible_azure.azcollection.azure_rm_aks_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_aks.py\", line 348, in create_aks_dict\n  File \"/tmp/ansible_azure.azcollection.azure_rm_aks_payload_cqzday9l/ansible_azure.azcollection.azure_rm_aks_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_aks.py\", line 425, in create_agent_pool_profiles_dict\n  File \"/tmp/ansible_azure.azcollection.azure_rm_aks_payload_cqzday9l/ansible_azure.azcollection.azure_rm_aks_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_aks.py\", line 425, in <listcomp>\nAttributeError: 'ManagedClusterAgentPoolProfile' object has no attribute 'type'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

```paste below

```
