### ISSUE TITLE
restorable_dropped_database_id isn't a valid parameter for the azure_rm_sqldatabase module, but it is in the Examples.

### ISSUE THREAD

**Issue by joechancellor** [ansible/ansible_collections_azure#1640]
##### SUMMARY

This is in the examples of the python code and the online documentation for examples:
```
- name: Restore SQL Database
  azure_rm_sqldatabase:
    resource_group: myResourceGroup
    server_name: sqlcrudtest-5961
    name: restoreddb
    location: eastus
    create_mode: restore
    restorable_dropped_database_id: "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/myResourceGroup/providers/Microsoft.Sql/s
                                     ervers/testsvr/restorableDroppedDatabases/testdb2,131444841315030000"
```
restorable_dropped_database_id is not a valid module parameter

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME

azure_rm_sqldatabase
##### ANSIBLE VERSION

```
ansible [core 2.15.12]
  config file = /home/zee_root/lin_ansible/ansible.cfg
  configured module search path = ['/home/zee_root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/zee_root/.local/lib/python3.9/site-packages/ansible
  ansible collection location = /home/zee_root/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/zee_root/.local/bin/ansible
  python version = 3.9.5 (default, Nov 23 2021, 15:27:38) [GCC 9.3.0] (/usr/bin/python3.9)
  jinja version = 3.1.4
  libyaml = False
```

**Comment by Fred-sun** [comment]
@joechancellor Deleted in pr #1652

**Comment by joechancellor** [comment]
Hi @Fred-sun , I just wanted to comment that the correct syntax for a restore is like this:

```
  azure_rm_sqldatabase:
    resource_group: myResourceGroup
    server_name: sqlcrudtest-5961
    name: restoreddb
    location: eastus 
    create_mode: restore
    source_database_id: '/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/myResourceGroup/providers/Microsoft.Sql/servers/testsvr/databases/testdb'
    source_database_deletion_date: '2024-07-26T17:50:01Z'
```
