### ISSUE TITLE
[azure_rm_common/azure_rm_virtualnetwork] CIDR_PATTERN fails on IPv6 Addresses

### ISSUE THREAD

**Issue by tsmithCmdlnk** [ansible/ansible_collections_azure#1647]
##### SUMMARY

When creating a new virtual network with the option `purge_address_prefixes: true`, ansible fails with the following error message:
```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Parameter error: invalid address prefix value fd87:2656:c878::/48"}
```

If I run the playbook without `purge_address_prefixes` being true, it will create the virtual network without issue.

Digging through the source code I found the error message came from [this line](https://github.com/ansible-collections/azure/blob/e5ea1ed680bdc18138f2365804cfb4427ea1c6e1/plugins/modules/azure_rm_virtualnetwork.py#L278) which is only possible if `purge_address_prefixes` is true and if `CIDR_PATTERN.match` fails.

More digging shows that `CIDR_PATTERN` is imported from [azure_rm_common.py](https://github.com/ansible-collections/azure/blob/a24be3b6af5b2764d8f283546b463beea4a2877c/plugins/module_utils/azure_rm_common.py#L213) and appears to only match against IPv4 addresses.

I'm not familiar with the Regex flavour used by Python or this library so I can't confirm that, however I can confirm that the given IPv6 prefix is valid and works within the Azure panel.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

- azure_rm_virtualnetwork
- azure_rm_common

##### ANSIBLE VERSION

```paste below
ansible [core 2.17.1]
  config file = /home/tsmith/Projects/<snip>/ansible-workspace/ansible.cfg
  configured module search path = ['/home/tsmith/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/tsmith/Projects/<snip>/ansible-workspace/.venv/lib/python3.10/site-packages/ansible
  ansible collection location = /home/tsmith/Projects/<snip>/ansible-workspace/.collections
  executable location = /home/tsmith/Projects/<snip>/ansible-workspace/.venv/bin/ansible
  python version = 3.10.12 (main, Mar 22 2024, 16:50:05) [GCC 11.4.0] (/home/tsmith/Projects/<snip>/ansible-workspace/.venv/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
# /home/tsmith/Projects/<snip>/ansible-workspace/.collections/ansible_collections
Collection         Version
------------------ -------
azure.azcollection 2.6.0
```

##### CONFIGURATION

```paste below
COLLECTIONS_PATHS(/home/tsmith/Projects/<snip>/ansible-workspace/ansible.cfg) = ['/home/tsmith/Projects/<snip>/ansible-workspace/.collections']
CONFIG_FILE() = /home/tsmith/Projects/<snip>/ansible-workspace/ansible.cfg
DEFAULT_MANAGED_STR(/home/tsmith/Projects/<snip>/ansible-workspace/ansible.cfg) = This file is managed by Ansible, any changes will be overwritten af>
DEFAULT_ROLES_PATH(/home/tsmith/Projects/<snip>/ansible-workspace/ansible.cfg) = ['/home/tsmith/Projects/<snip>/ansible-workspace/roles']
EDITOR(env: EDITOR) = /home/tsmith/.nix-profile/bin/vim
PAGER(env: PAGER) = less

```

##### OS / ENVIRONMENT

```bash
PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

##### STEPS TO REPRODUCE

```yaml
---
- name: "Example Playbook"
  hosts: localhost

  vars:
    resource_group_name: "bug-report"
    location: "westus2"
    virtual_network_name: "bug-report-vnet"
    virtual_network:
       address_space: 
         - "10.6.0.0/23"
         - "fd87:2656:c878::/48"
       subnets:
        - name: "EastUS"
          cidr:
            - "10.6.0.0/24"
            - "fd87:2656:c878:1::/64"
        - name: "WestUS2"
          location: "westus2"
          cidr:
            - "10.6.1.0/24"
            - "fd87:2656:c878:2::/64"

- name: "Create Virtual Network"
  azure.azcollection.azure_rm_virtualnetwork:
    purge_address_prefixes: true
    resource_group: "{{ resource_group_name }}"
    location: "{{ virtual_network.location | default(location) }}"
    name: "{{ virtual_network_name }}"
    address_prefixes_cidr: '{{ virtual_network.address_space }}'

- name: "Create Subnets"
  azure.azcollection.azure_rm_subnet:
    resource_group: "{{ resource_group_name }}"
    virtual_network_name: "{{ virtual_network_name }}"
    name: "{{ item.name }}"
    address_prefixes_cidr: "{{ item.cidr }}"
  loop: "{{ virtual_network.subnets }}"
```

##### EXPECTED RESULTS

Resulting Virtual Network to be created with the provided IPv6 address space

##### ACTUAL RESULTS

Ansible fails to view `fd87:2656:c878::/48` as a correctly formatted CIDR.

```paste below
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: tsmith
<127.0.0.1> EXEC /bin/sh -c 'echo ~tsmith && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/tsmith/.ansible/tmp `"&& mkdir "` echo /home/tsmith/.ansible/tmp/ansible-tmp-1721763069.8833342-319476-122505644496886 `" && echo ansible-tmp-1721763069.8833342-319476-122505644496886="` echo /home/tsmith/.ansible/tmp/ansible-tmp-1721763069.8833342-319476-122505644496886 `" ) && sleep 0'
Using module file /home/tsmith/Projects/<snip>/ansible-workspace/.collections/ansible_collections/azure/azcollection/plugins/modules/azure_rm_virtualnetwork.py
<127.0.0.1> PUT /home/tsmith/.ansible/tmp/ansible-local-319269rk318kex/tmp_gsk8kxl TO /home/tsmith/.ansible/tmp/ansible-tmp-1721763069.8833342-319476-122505644496886/AnsiballZ_azure_rm_virtualnetwork.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/tsmith/.ansible/tmp/ansible-tmp-1721763069.8833342-319476-122505644496886/ /home/tsmith/.ansible/tmp/ansible-tmp-1721763069.8833342-319476-122505644496886/AnsiballZ_azure_rm_virtualnetwork.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/home/tsmith/Projects/<snip>/ansible-workspace/.venv/bin/python3 /home/tsmith/.ansible/tmp/ansible-tmp-1721763069.8833342-319476-122505644496886/AnsiballZ_azure_rm_virtualnetwork.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/tsmith/.ansible/tmp/ansible-tmp-1721763069.8833342-319476-122505644496886/ > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "ad_user": null,
            "address_prefixes_cidr": [
                "10.6.0.0/23",
                "fd87:2656:c878::/48"
            ],
            "adfs_authority_url": null,
            "api_profile": "latest",
            "append_tags": true,
            "auth_source": "auto",
            "cert_validation_mode": null,
            "client_id": null,
            "cloud_environment": "AzureCloud",
            "disable_instance_discovery": false,
            "dns_servers": null,
            "flow_timeout_in_minutes": null,
            "location": "eastus",
            "log_mode": null,
            "log_path": null,
            "name": "<snip>",
            "password": null,
            "profile": null,
            "purge_address_prefixes": true,
            "purge_dns_servers": false,
            "resource_group": "<snip>",
            "secret": null,
            "state": "present",
            "subscription_id": null,
            "tags": null,
            "tenant": null,
            "thumbprint": null,
            "x509_certificate_path": null
        }
    },
    "msg": "Parameter error: invalid address prefix value fd87:2656:c878::/48"
}

```
