### ISSUE TITLE
azure_rm_virtualmachineextension/azure_rm_virtualmachineextension_info  support auto upgrade

### ISSUE THREAD

**Issue by Klaas-** [ansible/ansible_collections_azure#1661]
##### SUMMARY

Currently there is no way to enable automatic upgrades on extensions. This is supported for many via 
properties.enableAutomaticUpgrade (https://learn.microsoft.com/en-us/rest/api/compute/virtual-machine-extensions/create-or-update?view=rest-compute-2024-03-01&tabs=HTTP)

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

azure_rm_virtualmachineextension
(and return info of azure_rm_virtualmachineextension_info)

##### ADDITIONAL INFORMATION

```yaml
- name: Create VM Extension
  azure_rm_virtualmachineextension:
    name: AzureMonitorLinuxAgent
    location: eastus
    resource_group: myResourceGroup
    virtual_machine_name: myvm
    publisher: Microsoft.Azure.Monitor
    virtual_machine_extension_type: AzureMonitorLinuxAgent
    type_handler_version: 1.0
    auto_upgrade_minor_version: true
    enable_automatic_upgrade: true
```
