### ISSUE TITLE
azure_rm_manageddisk trying to modify creation_data when it should not

### ISSUE THREAD

**Issue by Klaas-** [ansible/ansible_collections_azure#1665]
##### SUMMARY
I am trying to update tags on an OS disk, if I do that the manageddisk module tries to modify the creationData property which azure api blocks.
I looked at the output of the API for the disk, its 
```
    "creationData": {
      "createOption": "FromImage",
      "imageReference": {
        "id": "/Subscriptions/[...]/Providers/Microsoft.Compute/Locations/GermanyWestCentral/Publishers/RedHat/ArtifactTypes/VMImage/Offers/RHEL/Skus/9-lvm-gen2/Versions/9.4.202407053"
      }
```
Also the azure_rm_manageddisk_info can't seem to read the source_uri in this case.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

azure.azcollection.azure_rm_manageddisk

##### ANSIBLE VERSION

```paste below
2.15
```

##### COLLECTION VERSION

```paste below
2.6.0
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

RHEL8

##### STEPS TO REPRODUCE

```yaml

Create a disk from a RHEL image, my case its:
    publisher: RedHat
    offer: RHEL
    sku: 9-lvm-gen2
    version: latest

- name: Create managed disk
  azure.azcollection.azure_rm_manageddisk:
    subscription_id: "{{ subscription_id }}"
    name: "{{ inventory_hostname_short }}-disk1-os"
    resource_group: "{{ resource_group_name }}"
    tags: "{{ new_tags }}"

```

##### EXPECTED RESULTS

It will update the tags

##### ACTUAL RESULTS

```paste below
"Error creating the managed disk: (PropertyChangeNotAllowed) Changing property 'creationData' is not allowed.
Code: PropertyChangeNotAllowed
Message: Changing property 'creationData' is not allowed.
Target: creationData
```
