### ISSUE TITLE
Virtual Network -- show usage

### ISSUE THREAD

**Issue by Klaas-** [ansible/ansible_collections_azure#1672]
##### SUMMARY
Hi,
I would like to have an info module that shows the usage of the subnets within a virtual network. This can either be added to the azure_rm_virtualnetwork_info module or be it's own azure_rm_virtualnetwork_usage_info for example.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
azure_rm_virtualnetwork_info

##### ADDITIONAL INFORMATION

The API for it is here:
https://learn.microsoft.com/en-us/rest/api/virtualnetwork/virtual-networks/list-usage?view=rest-virtualnetwork-2024-01-01

```yaml
- name: Get facts for one virtual network
  azure.azcollection.azure_rm_virtualnetwork_usage_info:
    resource_group: myResourceGroup
    name: secgroup001
```

**Comment by Klaas-** [comment]
Workaround using the generic resource module:
```
    - name: Get virtual network usage info
      azure.azcollection.azure_rm_resource_info:
        subscription_id: "{{ subscription_id }}"
        resource_group: "{{ resource_group }}"
        provider: Network
        resource_type: virtualNetworks
        resource_name: "{{ virtual_network_name }}/usages"
```

**Comment by Klaas-** [comment]
I am unsure if the resource_name is meant to be used that way or if I should use `subresource` in some way that I was unable to figure out :)

**Comment by Klaas-** [comment]
And maybe also my full usecase, getting the subnet with the highest number of available IPs for any given subnet, matching a regex:

```
    - name: Get virtual network usage info
      azure.azcollection.azure_rm_resource_info:
        subscription_id: "{{ subscription_id }}"
        resource_group: "{{ resource_group }}"
        provider: Network
        resource_type: virtualNetworks
        resource_name: "{{ virtual_network_name }}/usages"
      register: virtualnetwork_usage_info

    - name: Initialize subnet_remaining_capacity_hash variable
      ansible.builtin.set_fact:
        subnet_remaining_capacity_hash: []

    - name: Append each subnet details to subnet_remaining_capacity_hash
      ansible.builtin.set_fact:
        subnet_remaining_capacity_hash: "{{ subnet_remaining_capacity_hash + [{'id': item.id, 'remaining_capacity': item.limit - item.currentValue}] }}"
      loop: "{{ virtualnetwork_usage_info.response }}"

    - name: Filter subnets matching the defined string
      ansible.builtin.set_fact:
        subnets_matching_regex: "{{ subnet_remaining_capacity_hash | selectattr('id', 'search', match_regex) | list }}"

    - name: Find the subnet with the highest remaining capacity
      ansible.builtin.set_fact:
        subnet_highest_remaining_capacity: "{{ (subnets_matching_regex | sort(attribute='remaining_capacity', reverse=True)) | first }}"

    - name: Show ID of the highest remaining capacity subnet in given virtual network
      ansible.builtin.debug:
        var: subnet_highest_remaining_capacity.id
```
