### ISSUE TITLE
Disks IOPS, throughput and PremiumV2 parameters

### ISSUE THREAD

**Issue by KevinKeo** [ansible/ansible_collections_azure#1708]
##### SUMMARY

Hello,

It is currently not possible to specify Disk IOPS and Disk throughput.
In addition, for the storage_account_type, the Premium SSD V2 is currently not available.

The values disk IOPS and disk throughput are only used if storage_account_type is Premium SSD V2 or UltraSSD_LRS

##### ISSUE TYPE
- Disks IOPS, throughput parameters
- Additional value PremiumV2_LRS for storage_account_type

##### COMPONENT NAME

azure.azcollection.azure_rm_manageddisk

##### ADDITIONAL INFORMATION

```yaml
- name: Mount the managed disk to multiple VMs
  azure_rm_manageddisk:
    resource_group: myResourceGroup
    name: freddisk04
    disk_size_gb: 1024
    disk_iops: 3000
    disk_throughput: 125
    storage_account_type: PremiumV2_LRS
```
