### ISSUE TITLE
azure_rm_openshiftmanagedcluster - does not accept pull secret

### ISSUE THREAD

**Issue by tze-dev** [ansible/ansible_collections_azure#1729]
##### SUMMARY

`azure_rm_openshiftmanagedcluster` keeps returning error "The provided pull secret is invalid." when a pull secret content is specified as input.
The same pull secret was tested using Terraform without any issue - this eliminated any issue with the pull secret itself.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

azure_rm_openshiftmanagedcluster

##### ANSIBLE VERSION

```paste below
ansible [core 2.17.4]
  config file = None
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/.pyenv/versions/3.11.6/envs/ansible/lib/python3.11/site-packages/ansible
  ansible collection location = /home/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/user/.pyenv/versions/ansible/bin/ansible
  python version = 3.11.6 (main, Sep 25 2024, 17:20:53) [GCC 11.4.0] (/home/user/.pyenv/versions/3.11.6/envs/ansible/bin/python3.11)
  jinja version = 3.1.4
  libyaml = True
```

##### COLLECTION VERSION

```paste below
# /home/user/.ansible/collections/ansible_collections
Collection         Version
------------------ -------
azure.azcollection 2.7.0

# /home/user/.pyenv/versions/3.11.6/envs/ansible/lib/python3.11/site-packages/ansible_collections
Collection         Version
------------------ -------
azure.azcollection 2.7.0
```

##### CONFIGURATION

```paste below
CONFIG_FILE() = None
```

##### STEPS TO REPRODUCE

```yaml
- name: Create openshift cluster
  azure_rm_openshiftmanagedcluster:
    resource_group: "myResourceGroup"
    name: "myCluster"
    location: "eastus"
    cluster_profile:
      cluster_resource_group_id: "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/clusterResourceGroup"
      domain: "mydomain"
      pull_secret: "{{  lookup('ansible.builtin.file', 'pullsecret.json') }}"
    service_principal_profile:
      client_id: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
      client_secret: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    network_profile:
      pod_cidr: "10.128.0.0/14"
      service_cidr: "172.30.0.0/16"
    worker_profiles:
      - vm_size: "Standard_D4s_v3"
        subnet_id: "/subscriptions/xx-xx-xx-xx-xx/resourceGroups/myResourceGroup/Microsoft.Network/virtualNetworks/myVnet/subnets/worker"
        disk_size: 128
        count: 3
    master_profile:
      vm_size: "Standard_D8s_v3"
      subnet_id: "/subscriptions/xx-xx-xx-xx-xx/resourceGroups/myResourceGroup/providers/Microsoft.Network/virtualNetworks/myVnet/subnets/master"
```

##### EXPECTED RESULTS

Expect the ARO cluster to be created in Azure.

##### ACTUAL RESULTS

It keeps failing with the following error:

code: InvalidParameter
message: The provided pull secret is invalid.

```paste below
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error creating the OpenShiftManagedCluster instance: {'properties': {'clusterProfile': {'pullSecret': '{\\\\\"auths\\\\\":{\\\\\"registry.connect.redhat.com\\\\\":{\\\\\"auth\\\\\":\\\\\"\\\\\"},\\\\\"registry.redhat.io\\\\\":{\\\\\"auth\\\\\":\\\\\"\\\\\"}}}', 'domain': 'aro', 'resourceGroupId': '/subscriptions/0000000-b7f4-4da0-bae5-71d8f0f00000/resourceGroups/aro-cluster-cluster'}, 'servicePrincipalProfile': {'ClientId': '00000-ba2c-4c23-9e57-7f0208000000', 'clientSecret': '********'}, 'networkProfile': {'podCidr': '10.128.0.0/14', 'serviceCidr': '172.30.0.0/16'}, 'masterProfile': {'subnetId': '/subscriptions/000000-b7f4-4da0-bae5-71d8f00000/resourceGroups/aro-rg/providers/Microsoft.Network/virtualNetworks/aro-vnet/subnets/aro-master', 'vmSize': 'Standard_D8s_v3'}, 'workerProfiles': [{'name': 'worker', 'subnetId': '/subscriptions/00000-b7f4-4da0-bae5-71d8f000000/resourceGroups/aro-rg/providers/Microsoft.Network/virtualNetworks/aro-vnet/subnets/aro-worker', 'count': 3, 'vmSize': 'Standard_D4s_v3', 'diskSizeGB': 128}], 'apiserverProfile': {'visibility': 'Private', 'url': None, 'ip': None}, 'ingressProfiles': [{'visibility': 'Public', 'name': 'default'}]}, 'location': 'australiaeast'}\n('{\\n    \"error\": {\\n        \"code\": \"InvalidParameter\",\\n        \"message\": \"The provided pull secret is invalid.\",\\n        \"target\": \"properties.clusterProfile.pullSecret\"\\n    }\\n}\\n', 400)"}
```
