### ISSUE TITLE
Add IP configuration in the azure_rm_privateendpoint module

### ISSUE THREAD

**Issue by pwakano** [ansible/ansible_collections_azure#1766]
##### SUMMARY

The Private Endpoint can have a custom IP configuration as shown here https://learn.microsoft.com/en-us/rest/api/virtualnetwork/private-endpoints/create-or-update?view=rest-virtualnetwork-2024-03-01&tabs=HTTP#privateendpointipconfiguration and here https://learn.microsoft.com/en-us/cli/azure/network/private-endpoint?view=azure-cli-latest#az-network-private-endpoint-create
This option is not yet available in the azure_rm_privateendpoint module, so it would be nice to have this option when creating a private endpoint. By having this, azure won't pick any random empty IP available in the subnet, which might cause conflicts later.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

azure_rm_privateendpoint

##### ADDITIONAL INFORMATION

If the IP is freely chosen by Azure when creating the private endpoint, it may conflict with some IP which is manually assigned to some other resource such as a VM.

```yaml
- name: Create private endpoint with custom ip configuration
  azure_rm_privateendpoint:
    name: testprivateendpoint
    resource_group: v-xisuRG
    private_link_service_connections:
      - name: Test_private_link_service
        private_link_service_id: /subscriptions/xxx/resourceGroups/myResourceGroup/providers/Microsoft.Network/privateLinkServices/testervice
    subnet:
      id: /subscriptions/xxx/resourceGroups/myResourceGroup/providers/Microsoft.Network/virtualNetworks/fredvnet/subnets/default
    ip_configurations:
      - name: myEndpointIPConfig
        properties:
          group_id: blob
          member_name: blob
          private_ip_address: 1.2.3.4
    tags:
      key1: value1
```
