### ISSUE TITLE
Add "osName" from MS API "instanceView" to "azure_rm.py" Inventory Plugin

### ISSUE THREAD

**Issue by obartonek** [ansible/ansible_collections_azure#1776]
##### SUMMARY
The current `azure_rm.py` plugin for Ansible inventory source supports only the `osType` attribute (e.g., `Linux`, `Windows`).

I would like to ask for adding the `osName` attribute from MS API `instanceView`, which provides more granular OS details (e.g., `RedHat`, `Ubuntu`, `Oracle`, etc.). This enhancement would enable better filtering and grouping of machines in Ansible inventories based on their specific operating system.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
`azure_rm.py`

##### ADDITIONAL INFORMATION
Adding `osName` would allow users to define conditional groups based on the specific operating system, providing more flexibility and precision when managing diverse environments.

```yaml
plugin: azure.azcollection.azure_rm

conditional_groups:
  windows22_group: os_name == 'Windows Server 2022'
  windows19_group: os_name == 'Windows Server 2019'
  windows16_group: os_name == 'Windows Server 2016'
  redhat_group: os_name == 'RedHat' 
  oracle_group: os_name == 'Oracle'
  ubuntu_group: os_name == 'Ubuntu'
```
