### ISSUE TITLE
azure_rm_keyvault access_policies dictionary missing "permissions"

### ISSUE THREAD

**Issue by joechancellor** [ansible/ansible_collections_azure#1805]
##### SUMMARY
Completing idempotent updates of the access policies for an Azure KeyVault require that you read the existing access policies and then add or remove a permission from the access_policies dictionary.  The azure_rm_keyvault and the azure_rm_keyvault_info both return "permissions" as an element of the access_policies dictionary, but the azure_rm_keyvault module does not accept permissions as an element of its access_policies dictionary.

Request is to add "permissions" to the azure_rm_keyvault "access_policies" dictionary or remove it from the returned values of azure_rm_keyvault and azure_rm_keyvault_info. 

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
azure_rm_keyvault

##### ADDITIONAL INFORMATION
Adding permissions would help with idempotent updates of Azure Key Vault access policies.  Attempting to update or add an item to the existing access policy requires all existing access policies to be specified.

Existing:
```yaml
- name: Create instance of Key Vault
  azure_rm_keyvault:
    resource_group: myResourceGroup
    vault_name: samplekeyvault
    enabled_for_deployment: true
    enable_rbac_authorization: true
    vault_tenant: 72f98888-8666-4144-9199-2d7cd0111111
    sku:
      name: standard
      family: A
    access_policies:
      - tenant_id: 72f98888-8666-4144-9199-2d7cd0111111
        object_id: 99998888-8666-4144-9199-2d7cd0111111
        keys:
          - get
          - list

```
Add:
```yaml
- name: Create instance of Key Vault
  azure_rm_keyvault:
    resource_group: myResourceGroup
    vault_name: samplekeyvault
    enabled_for_deployment: true
    enable_rbac_authorization: true
    vault_tenant: 72f98888-8666-4144-9199-2d7cd0111111
    sku:
      name: standard
      family: A
    access_policies:
      - tenant_id: 72f98888-8666-4144-9199-2d7cd0111111
        object_id: 99998888-8666-4144-9199-2d7cd0111111
        permissions: 
          keys:
            - get
            - list

```

**Comment by Fred-sun** [comment]
@joechancellor Thank you for submitting the problem and the solution, but in order to avoid affecting the current users, we still need to discuss how to better change this problem, thank you!

**Comment by Fred-sun** [comment]
@joechancellor This is not a bug, the permission layer is missing from the configuration, but the data structure is built when it is created. The return value is the structure returned by the API and serialized. Although the two are different in structure, there is no mistake. So I think we can continue to do this, to avoid having an impact on the current users. Thank you!

**Comment by joechancellor** [comment]
Just so it's out there for other people to see.  If you attempt to read the access_policies using azure_rm_keyvault or azure_rm_keyvault_info, you can't use the output directly for azure_rm_keyvault.  You have to use azure_rm_resource to directly use the results.

**Comment by Fred-sun** [comment]
@joechancellor The azure_rm_keyvault_info command is used to obtain keyvault information. The following information is displayed. You can print the return value using the register value. Thank you!
```e.g.
test playbook:
- name: Get fact of Key Vault
  azure_rm_keyvault_info:
    resource_group: "{{ resource_group }}"
    name: "vault{{ rpfx }}"
  register: output
```
```e.g.
return value:
    "output": {
        "changed": false,
        "failed": false,
        "keyvaults": [
            {
                "access_policies": [
                    {
                        "object_id": "xxxxxxxxxxxxxxxxxxxxxxxxxx",
                        "permissions": {
                            "certificates": null,
                            "keys": [
                                "get",
                                "list",
                                "update",
                                "create",
                                "import",
                                "delete",
                                "recover",
                                "backup",
                                "restore"
                            ],
                            "secrets": [
                                "get",
                                "list",
                                "set",
                                "delete",
                                "recover",
                                "backup",
                                "restore"
                            ],
                            "storage": null
                        },
                        "tenant_id": "xxxxxxxxxxxxxx"
                    }
                ],
                "enable_purge_protection": false,
                "enable_rbac_authorization": null,
                "enable_soft_delete": true,
                "enabled_for_deployment": true,
                "enabled_for_disk_encryption": null,
                "enabled_for_template_deployment": null,
                "id": "/subscriptions/xxxxxx/resourceGroups/v-xisuRG02/providers/Microsoft.KeyVault/vaults/vaultrfred011",
                "location": "eastus",
                "name": "vaultrfred011",
                "network_acls": null,
                "public_network_access": "Enabled",
                "sku": {
                    "family": "A",
                    "name": "standard"
                },
                "soft_delete_retention_in_days": 90,
                "tags": {},
                "vault_uri": "https://vaultrfred011.vault.azure.net/"
            }
        ]
    }

**Comment by joechancellor** [comment]
Yeah, I understand.  The problem is that I can’t just add an additional access policy using azure_rm_keyvault.  Attempting to add a single new access policy using azure_rm_keyvault removes all existing access policies (very bad).  I have to read all existing access policies, and then append a new access policy to that list to ensure that I don’t remove any existing policies.  Everything that reads existing policies returns “permissions” as part of the access_policies dictionary.  Permissions is not part of the “access_policies” dictionary, so azure_rm_keyvault can’t be used easily.

```yaml
- name: Setup new list element
  ansible.builtin.set_fact:
    new_access_policy:
      - objectId: '{{ az_sql_provisioned_status.response.0.identity.principalId }}'
        tenantId: '{{ az_sql_provisioned_status.response.0.identity.tenantId }}'
        permissions:
          keys:
            - "get"
            - "unwrapkey"
            - "wrapkey"

- name: Get KeyVault Info
  azure.azcollection.azure_rm_resource_info:
    resource_group: '{{ rg_name }}'
    provider: 'KeyVault'
    resource_type: 'vaults'
    resource_name: '{{ dbaas_keyvault_name }}'
  register: keyvault_info

- name: Grant permissions to Az SQL DB Server on KeyVault
  azure.azcollection.azure_rm_resource:
    resource_group: '{{ rg_name }}'
    provider: 'KeyVault'
    resource_type: 'vaults'
    resource_name: '{{ dbaas_keyvault_name }}'
    idempotency: true
    api_version: '2024-04-01-preview'
    body:
      location: '{{ dbaas_location }}'
      properties:
        accessPolicies: '{{ keyvault_info.response.0.properties.accessPolicies + new_access_policy }}'
        tenantId: '{{ dbaas_admins.tenantId }}'
        enableSoftDelete: true
        enablePurgeProtection: true
        sku:
          family: 'A'
          name: 'premium'
  when: new_access_policy.0.objectId not in (keyvault_info.response.0.properties.accessPolicies | map(attribute='objectId'))
```
