### ISSUE TITLE
azure_rm_keyvaultsecret secret recovery failing

### ISSUE THREAD

**Issue by markatdxb** [ansible/ansible_collections_azure#1809]
##### SUMMARY

Azure KV secret module should be able to recover deleted secret but throwing error instead
Basically following the module example:
```
- name: Recover a delete secret
  azure_rm_keyvaultsecret:
    secret_name: MySecret
    keyvault_uri: https://contoso.vault.azure.net/
    recover_if_need: true
```

Process tested in Postman with the same access credentials is able to recover the secret

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

azure.azcollection.azure_rm_keyvaultsecret

##### ANSIBLE VERSION

```paste below
2.17.7
```

##### COLLECTION VERSION

```paste below
Collection         Version
------------------ -------
azure.azcollection 3.1.0
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml
    - name: Recover deleted secret
      azure.azcollection.azure_rm_keyvaultsecret:
        cert_validation_mode: validate
        client_id: "{{ az_client_id }}"
        secret: "{{ az_client_secret }}"
        tenant: "{{ az_tenant_id }}"
        subscription_id: "{{ az_subscription_id }}"
        secret_name: MT-TEST03
        keyvault_uri: "{{ az_vault_uri }}"
        recover_if_need: true
```

##### EXPECTED RESULTS

Secret MT-TEST03 recovered

##### ACTUAL RESULTS

error in task execution

```paste below
fatal: [localhost]: FAILED! => {"changed": false, "msg": "state is present but all of the following are missing: secret_value"}
```
