### ISSUE TITLE
Modules ignore `subscription_id` when using CLI auth; resources get created in the wrong subscription.

### ISSUE THREAD

**Issue by UnwashedMeme** [ansible/ansible_collections_azure#181]
See https://github.com/Azure/azure_preview_modules/issues/321 and #53. 

To me this is a basic WTF issue. If I can't specify where a resource gets created properly then how am I supposed to do any serious automation?  There has been a pull-request present for 4months #53. Please fix this already.

This is especially frustrating when dealing with things that span multiple subscriptions. E.g. I want to look up vnet facts in one subscription to use it for a VM on the other subscription. Or I have a playbook that is creating a VM on each subscription.  Or I want to assign a VM identity permission to a resource in a different subscription.

A playbook, e.g.
```
- name: Create Azure VMs
  strategy: free
  hosts:
    - localhost
  gather_facts: false

  tasks:
    - name: "Create Resource group"
      delegate_to: localhost
      azure.azcollection.azure_rm_resourcegroup:
        name: "foobar"
        location: "eastus2"
        auth_source: cli
        subscription_id: "ecb1bdd8-..."
```
Ignores the `subscription_id` field:

```
$ az account list --verbose --query '[*].{id:id,isDefault:isDefault,state:state}'
[
  {
    "id": "f1c043c7-...",
    "isDefault": false,
    "state": "Enabled"
  },
  {
    "id": "ecb1bdd8-...",
    "isDefault": true,
    "state": "Enabled"
  }
]

$ ansible-playbook -v subtest.yml

TASK [Create Resource group] **********************************************************************************************************************
task path: /workspaces/sqlserver-deployment/subtest.yml:7
changed: [localhost] => changed=true 
  contains_resources: false
  invocation:
    module_args:
      ad_user: null
      adfs_authority_url: null
      api_profile: latest
      append_tags: true
      auth_source: cli
      cert_validation_mode: null
      client_id: null
      cloud_environment: AzureCloud
      force_delete_nonempty: false
      location: eastus2
      name: foobar
      password: null
      profile: null
      secret: null
      state: present
      subscription_id: f1c043c7-...
      tags: null
      tenant: null
  state:
    id: /subscriptions/ecb1bdd8-.../resourceGroups/foobar
    location: eastus2
    name: foobar
    provisioning_state: Succeeded
    tags: null```

Note that even though I specifically asked for the rg to be created in "f1c043c7-..." it was created in "ecb1bdd8-..." .

My work around at the moment is: 
```
    - name: "Ensure the correct subscription"
      delegate_to: localhost
      shell: "az account set -s {{ subscription }}"
```
but this fails when trying to run for multiple inventory items simultaneously (e.g. build 1 vm on each vm).

**Comment by UnwashedMeme** [comment]
I didn't re-create this issue from the old repo to this repo immediately upon development being transitioned over because "There's already a pull-request, it will be fixed soon; I'll try to keep the noise down."

At this point it just came up, again, as a blocker. So I'm hear to make some noise about it again.   @Fred-sun, please get this fix  through.

**Comment by Fred-sun** [comment]
> I didn't re-create this issue from the old repo to this repo immediately upon development being transitioned over because "There's already a pull-request, it will be fixed soon; I'll try to keep the noise down."
> 
> At this point it just came up, again, as a blocker. So I'm hear to make some noise about it again. @Fred-sun, please get this fix through.

Thanks for your update! I will check it!

**Comment by UnwashedMeme** [comment]
For other people coming through, still waiting on this to be fixed, here's a workaround sketch:
```
  block:
  - name: "Switch to other subscription"
    delegate_to: localhost
    check_mode: false
    command: "az account set -s 'FOOBAR'"
  - name: "Grant access"
    delegate_to: localhost
    azure_rm_roleassignment: 
       subscription_id: "foobar"  # THIS STILL DOESN'T WORK
       ...
  - name: "Switch back to original subscription"
    delegate_to: localhost
    check_mode: false
    command: "az account set -s ORIGINAL"
```
