### ISSUE TITLE
Add ability to gather resource health states via ansible

### ISSUE THREAD

**Issue by Klaas-** [ansible/ansible_collections_azure#1817]
##### SUMMARY
I would like to gather resource health states via ansible, currently there is no module for this. This is supported by API via https://learn.microsoft.com/en-us/rest/api/resourcehealth/availability-statuses/get-by-resource?view=rest-resourcehealth-2024-02-01&tabs=HTTP

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
resourcehealth

##### ADDITIONAL INFORMATION

Workaround is to use the generic resource info module

```yaml
    - name: Gather information about vm resource health
      azure.azcollection.azure_rm_resource_info:
        subscription_id: "{{ subscription_id }}"
        resource_group: "{{ resource_group_name }}"
        provider: Compute
        resource_type: virtualMachines
        resource_name: "{{ virtual_machine_name }}"
        api_version: 2024-02-01&$expand=recommendedactions
        subresource:
          - name: current
            namespace: Microsoft.ResourceHealth
            type: availabilityStatuses
```
the api_version discovery does not seem to work for subresources, I had to set it manually. Also I am abusing that field to also expand the result with recommendedactions :)
