### ISSUE TITLE
azure_rm_aks module throws error: 'NoneType object has no attribute enable_secure_boot

### ISSUE THREAD

**Issue by haijeploeg** [ansible/ansible_collections_azure#1823]
##### SUMMARY
`azure_rm_aks` module throws error `NoneType object has no attribute 'enable_secure_boot'`. The issue appears the be introduced in this commit: [04024f6](https://github.com/ansible-collections/azure/commit/04024f6), but I am not 100% certain.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`azure_rm_aks`

##### ANSIBLE VERSION
```bash
ansible [core 2.18.2]
  config file = None
  configured module search path = ['/Users/hploeg/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/hploeg/Workspace/warpnet/gitlab/azure/ansible-azure/env/lib/python3.13/site-packages/ansible
  ansible collection location = /Users/hploeg/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/hploeg/Workspace/warpnet/gitlab/azure/ansible-azure/env/bin/ansible
  python version = 3.13.2 (main, Feb  4 2025, 14:51:09) [Clang 16.0.0 (clang-1600.0.26.6)] (/Users/hploeg/Workspace/warpnet/gitlab/azure/ansible-azure/env/bin/python3.13)
  jinja version = 3.1.5
  libyaml = True
```

##### COLLECTION VERSION
```bash
# /Users/hploeg/.ansible/collections/ansible_collections
Collection         Version
------------------ -------
azure.azcollection 3.2.0
```

##### CONFIGURATION
```
CONFIG_FILE() = None
PAGER(env: PAGER) = less

GALAXY_SERVERS:
```

##### OS / ENVIRONMENT
- Python 3.13.2
- Tested on multiple OS: MacOS 15.3, ubuntu 24.04

##### STEPS TO REPRODUCE
1. use latest version of azure.azcollection
2. Define AKS cluster as below

```yaml
- name: "Ensure a correct state of AKS cluster"
  azure.azcollection.azure_rm_aks:
    name: "aks-k8s-test-001"
    resource_group: "rg-k8s-test-001"
    enable_rbac: "True"
    dns_prefix: "aks-k8s-test-001"
    kubernetes_version: "1.31.5"
    agent_pool_profiles: 
      - name: 'nodepool001'
        count: 3
        min_count: 3
        max_count: 5
        enable_auto_scaling: True
        vm_size: 'Standard_B4ms'
        mode: 'System'
        vnet_subnet_id: '/subscriptions/xxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/rg-k8s-test-001/providers/Microsoft.Network/virtualNetworks/vnet-k8s-test-001/subnets/snet-k8s-test-001'
        os_disk_size_gb: 50
        security_profile:
          enable_secure_boot: False
          enable_vtpm: False 
        orchestrator_version: '1.31.5'
    network_profile:
      network_plugin: 'kubenet'
      network_policy': 'calico'
    api_server_access_profile: "{'authorized_ip_ranges': [x.x.x.x/32', 'x.x.x.x/32']}"
    aad_profile:
      admin_group_object_ids: "['xxxxx123-xxxxx123-xxxx-xxxxxxxx']"
      managed: yes
    tags:
      'ansible-managed': 'True'
```

3. Run the playbook

Issue also persists with removing `security_profile` config.

##### EXPECTED RESULTS
The AKS cluster is created/updated/configured.

##### ACTUAL RESULTS
Throws this error:

```bash
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: NoneType object has no attribute enable_secure_boot
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):
  File \"/Users/hploeg/.ansible/tmp/ansible-tmp-1739530936.850776-24408-219931791947230/AnsiballZ_azure_rm_aks.py\", line 107, in <module>
    _ansiballz_main()
    ~~~~~~~~~~~~~~~^^
  File \"/Users/hploeg/.ansible/tmp/ansible-tmp-1739530936.850776-24408-219931791947230/AnsiballZ_azure_rm_aks.py\", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File \"/Users/hploeg/.ansible/tmp/ansible-tmp-1739530936.850776-24408-219931791947230/AnsiballZ_azure_rm_aks.py\", line 47, in invoke_module
    runpy.run_module(mod_name=ansible_collections.azure.azcollection.plugins.modules.azure_rm_aks, init_globals=dict(_module_fqn=ansible_collections.azure.azcollection.plugins.modules.azure_rm_aks, _modlib_path=modlib_path),
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                     run_name=__main__, alter_sys=True)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File \"<frozen runpy>\", line 226, in run_module
  File \"<frozen runpy>\", line 98, in _run_module_code
  File \"<frozen runpy>\", line 88, in _run_code
  File \"/var/folders/kw/b30vjw_16bs7jbwj13d9n17h0000gn/T/ansible_azure.azcollection.azure_rm_aks_payload_55_9gmu5/ansible_azure.azcollection.azure_rm_aks_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_aks.py\", line 1888, in <module>
  File \"/var/folders/kw/b30vjw_16bs7jbwj13d9n17h0000gn/T/ansible_azure.azcollection.azure_rm_aks_payload_55_9gmu5/ansible_azure.azcollection.azure_rm_aks_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_aks.py\", line 1884, in main
  File \"/var/folders/kw/b30vjw_16bs7jbwj13d9n17h0000gn/T/ansible_azure.azcollection.azure_rm_aks_payload_55_9gmu5/ansible_azure.azcollection.azure_rm_aks_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_aks.py\", line 1327, in __init__
  File \"/var/folders/kw/b30vjw_16bs7jbwj13d9n17h0000gn/T/ansible_azure.azcollection.azure_rm_aks_payload_55_9gmu5/ansible_azure.azcollection.azure_rm_aks_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py\", line 482, in __init__
  File \"/var/folders/kw/b30vjw_16bs7jbwj13d9n17h0000gn/T/ansible_azure.azcollection.azure_rm_aks_payload_55_9gmu5/ansible_azure.azcollection.azure_rm_aks_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_aks.py\", line 1348, in exec_module
  File \"/var/folders/kw/b30vjw_16bs7jbwj13d9n17h0000gn/T/ansible_azure.azcollection.azure_rm_aks_payload_55_9gmu5/ansible_azure.azcollection.azure_rm_aks_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_aks.py\", line 1758, in get_aks
  File \"/var/folders/kw/b30vjw_16bs7jbwj13d9n17h0000gn/T/ansible_azure.azcollection.azure_rm_aks_payload_55_9gmu5/ansible_azure.azcollection.azure_rm_aks_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_aks.py\", line 881, in create_aks_dict
  File \"/var/folders/kw/b30vjw_16bs7jbwj13d9n17h0000gn/T/ansible_azure.azcollection.azure_rm_aks_payload_55_9gmu5/ansible_azure.azcollection.azure_rm_aks_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_aks.py\", line 1013, in create_agent_pool_profiles_dict
AttributeError: NoneType object has no attribute enable_secure_boot
", "module_stdout": "", "msg": "MODULE FAILURE: No start of json char found
See stdout/stderr for the exact error", "rc": 1}
```
