### ISSUE TITLE
azure_rm_manageddisk: allow creation of managed disk from a compute gallery image

### ISSUE THREAD

**Issue by cmasopust** [ansible/ansible_collections_azure#1829]
##### SUMMARY
We are creating our own OS images and store them in an Azure Compute Gallery.  When then creating a VM we want to use that images. So, please add an option to allow creation of a managed disk from these compute gallery images.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
azure_rm_manageddisk

##### ADDITIONAL INFORMATION
More details about creation from the Azure API:
[Create a managed disk from an Azure Compute Gallery image](https://learn.microsoft.com/en-us/rest/api/compute/disks/create-or-update?view=rest-compute-2023-04-02&tabs=HTTP#create-a-managed-disk-from-an-azure-compute-gallery-image.)

```yaml
- azure.azcollection.azure_rm_manageddisk:
    name: disk1
    create_option: from_image
    gallery_image_reference:
       id: ...
```
