### ISSUE TITLE
azure_rm_virtualmachine issue in the time of VM creation from a specialized image

### ISSUE THREAD

**Issue by arnabnss** [ansible/ansible_collections_azure#1849]
##### SUMMARY

azure_rm_virtualmachine issue in the time of VM creation from a specialized image.
When try to execute the playbook, it's giving an error - fatal: [localhost]: FAILED! => {"changed": false, "msg": "Parameter error: admin_username required when creating a virtual machine."}
When I add the admin_username field, it's giving an error - fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error creating or updating virtual machine myVM - (InvalidParameter) Parameter OSProfile is not allowed with a specialized image.\nCode: InvalidParameter\nMessage: Parameter OSProfile is not allowed with a specialized image.\nTarget: osProfile"}

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

azure_rm_virtualmachine

##### ANSIBLE VERSION

```paste below
ansible [core 2.17.9]
```

##### COLLECTION VERSION

```paste below
azure.azcollection 2.7.0
```

##### CONFIGURATION

```paste below
CONFIG_FILE() = /etc/ansible/ansible.cfg
```

##### OS / ENVIRONMENT

Target infrastructure is Azure

##### STEPS TO REPRODUCE

- name: Create VM
    azure_rm_virtualmachine:
      resource_group: myResourceGroup
      location: eastus
      name: myVM
      vm_size: Standard_B1s
      admin_username: test
      os_type: Linux
      managed_disk_type: "StandardSSD_LRS"
      network_interfaces: myVM-nic
      image:
        id: "/subscriptions/123456/resourceGroups/myResourceGroup/providers/Microsoft.Compute/galleries/2025/images/myimage/versions/0.0.1"

```yaml
- name: Create VM
    azure_rm_virtualmachine:
      resource_group: myResourceGroup
      location: eastus
      name: myVM
      vm_size: Standard_B1s
      #admin_username: test
      os_type: Linux
      managed_disk_type: "StandardSSD_LRS"
      network_interfaces: myVM-nic
      image:
        id: "/subscriptions/123456/resourceGroups/myResourceGroup/providers/Microsoft.Compute/galleries/2025/images/myimage/versions/0.0.1"

- name: Create VM
    azure_rm_virtualmachine:
      resource_group: myResourceGroup
      location: eastus
      name: myVM
      vm_size: Standard_B1s
      admin_username: test
      os_type: Linux
      managed_disk_type: "StandardSSD_LRS"
      network_interfaces: myVM-nic
      image:
        id: "/subscriptions/123456/resourceGroups/myResourceGroup/providers/Microsoft.Compute/galleries/2025/images/myimage/versions/0.0.1"
```

##### EXPECTED RESULTS

If I run the first command/playbook it's giving an error - **fatal: [localhost]: FAILED! => {"changed": false, "msg": "Parameter error: admin_username required when creating a virtual machine."}**

When I run the second command/playbook it's giving an error - **fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error creating or updating virtual machine myVM - (InvalidParameter) Parameter OSProfile is not allowed with a specialized image.\nCode: InvalidParameter\nMessage: Parameter OSProfile is not allowed with a specialized image.\nTarget: osProfile"}**

##### ACTUAL RESULTS

```paste below
As we know in specialized image from azure VM Image Versions don't need any username/password in the time of VM creation. But the ansible azure_rm_virtualmachine module compulsory required field is admin_username.
But when I have added the admin_username option in the task, specialized image doesn't support that.
Please tell me in this condition how I can create a VM when the Image of the VM is specialized & stored inside VM Image Versions.
```
