### ISSUE TITLE
`azure.azcollection.azure_rm_keyvaultsecret_info`: Attribute / Method `secret` not working when filtering by `tags`

### ISSUE THREAD

**Issue by FireDrunk** [ansible/ansible_collections_azure#1850]
##### SUMMARY
When using the `tags` filter in `azure.azcollection.azure_rm_keyvaultsecret_info` the secrets are not automatically retrieved.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure.azcollection.azure_rm_keyvaultsecret_info

##### ANSIBLE VERSION

```
ansible [core 2.16.14]
  config file = None
  python version = 3.10.12 (main, Feb  4 2025, 14:57:36) [GCC 11.4.0]
  jinja version = 3.1.4
  libyaml = True
```

##### COLLECTION VERSION
```
azure.azcollection 3.2.0
```

##### CONFIGURATION
```
None
```

##### OS / ENVIRONMENT
Python 3.10, running in virtualenv using Ansible 9.13

##### STEPS TO REPRODUCE
```yaml
- name: "Get all secrets from Azure Key Vault"
  azure.azcollection.azure_rm_keyvaultsecret_info:
    vault_uri: "{{ vault_uri }}"
    tags:
      - "environment:{{ env }}"
      - "purpose:my_purpose"
      - "cluster:{{ cluster_name }}"
  register: my_secrets
  run_once: True
  delegate_to: localhost
  become: False

- name: "Detected Service Accounts"
  run_once: True
  debug:
    msg: "Detected Secret: {{ item }}, Secret: {{ item.secret }}"
  loop: "{{ my_secrets.secrets }}"
```
##### EXPECTED RESULTS
There should be a `secret` value and perhaps a `name` field.

##### ACTUAL RESULTS
Ansible fails with the no attribute found `secret`.

Example result:
```json
ok: [<snip> -> localhost] => {
    "changed": false,
    "invocation": {
        "module_args": {
            "ad_user": null,
            "adfs_authority_url": null,
            "api_profile": "latest",
            "auth_source": "auto",
            "cert_validation_mode": null,
            "client_id": null,
            "cloud_environment": "AzureCloud",
            "disable_instance_discovery": false,
            "log_mode": null,
            "log_path": null,
            "name": "",
            "password": null,
            "profile": null,
            "secret": null,
            "show_deleted_secret": false,
            "subscription_id": null,
            "tags": [
                "environment:test",
                "purpose:<snip>",
                "cluster:<snip>"
            ],
            "tenant": null,
            "thumbprint": null,
            "vault_uri": "https://<snip>.vault.azure.net/",
            "version": "current",
            "x509_certificate_path": null
        }
    },
    "secrets": [
        {
            "attributes": {
                "created": "2025-03-11T14:01:19+00:00",
                "enabled": true,
                "expires": null,
                "not_before": null,
                "recovery_level": "Recoverable+Purgeable",
                "updated": "2025-03-11T14:01:19+00:00"
            },
            "sid": "https://<snip>.vault.azure.net/secrets/secret-a",
            "tags": {
                "environment": "test",
                "cluster": "<snip>",
                "purpose": "<snip>",
                "roles": "<snip>",
                "service_account": "<name>",
                "system": "infra",
                "team": "infra"
            },
            "version": null
        },
        {
            "attributes": {
                "created": "2025-03-11T14:01:19+00:00",
                "enabled": true,
                "expires": null,
                "not_before": null,
                "recovery_level": "Recoverable+Purgeable",
                "updated": "2025-03-11T14:01:19+00:00"
            },
            "sid": "https://<snip>.vault.azure.net/secrets/secret-b",
            "tags": {
                "environment": "test",
                "cluster": "<snip>",
                "purpose": "<snip>",
                "roles": "<snip>",
                "service_account": "<name>",
                "system": "infra",
                "team": "infra"
            },
            "version": null
        }
    ]
}
```

So it does find the secrets, so there is no authentication issue, just the result.
It seems the result dict is not filled up properly, the `version` and `name` attributes are also `null` or not set which seems incorrect.

**Comment by FireDrunk** [comment]
When doing an explicit lookup of an individual secret retrieved in this list, it works:

```
- name: "Get secret from Azure"
  azure.azcollection.azure_rm_keyvaultsecret_info:
    vault_uri: "{{ vault_uri }}"
    name: "{{ item.sid.split('/') | last }}"
  register: result
  run_once: True
  delegate_to: localhost
  become: False
  loop: "{{ my_secrets.secrets }}"
```

So it might be by design that when not explicitly naming the secret you want, but just filtering by tags, it won't retrieve the actual secret.

This is not clear from the docs, so if this is by design, the docs should probably reflect this.
