### ISSUE TITLE
azure_rm_networkinterface updating network interface not working

### ISSUE THREAD

**Issue by Klaas-** [ansible/ansible_collections_azure#1855]
##### SUMMARY
The update of an existing NIC is not working as expected

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure_rm_networkinterface

##### ANSIBLE VERSION

```paste below
ansible [core 2.16.3]
  config file = /home/homedir/ansible.cfg
  configured module search path = ['/home/homedir/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.12/site-packages/ansible
  ansible collection location = /home/homedir/collections
  executable location = /usr/bin/ansible
  python version = 3.12.8 (main, Dec  9 2024, 15:25:01) [GCC 8.5.0 20210514 (Red Hat 8.5.0-22)] (/usr/bin/python3.12)
  jinja version = 3.1.2
  libyaml = True

```

##### COLLECTION VERSION

```paste below

# /home/homedir/collections/ansible_collections
Collection         Version
------------------ -------
azure.azcollection 3.3.1

```

##### CONFIGURATION

```paste below
COLLECTIONS_PATHS(/home/homedir/ansible.cfg) = ['/home/homedir/collections']
CONFIG_FILE() = /home/homedir/ansible.cfg
DEFAULT_NO_TARGET_SYSLOG(/home/homedir/ansible.cfg) = True
DEFAULT_ROLES_PATH(/home/homedir/ansible.cfg) = ['/home/homedir/roles']
```

##### OS / ENVIRONMENT

RHEL8.10

##### STEPS TO REPRODUCE

```yaml
- name: Test Azure NIC updating
  hosts: all
  gather_facts: false
  connection: local

  tasks:
    - name: Create NIC in Azure
      azure.azcollection.azure_rm_networkinterface:
        client_id: "{{ service_principal_application_id }}"
        secret: "{{ service_principal_client_secret }}"
        tenant: "{{ service_principal_tenant }}"
        subscription_id: 000-subscription-id
        name: ansibletestnic
        resource_group: resource_group_name
        create_with_security_group: false
        subnet_name: subnet_name
        virtual_network_name:
          name: vnet_name
          resource_group: vnet_resource_group_name
        tags:
          TestTag: TestValue
          TestTag2: TestValue2

    - name: Update tags
      azure.azcollection.azure_rm_networkinterface:
        client_id: "{{ service_principal_application_id }}"
        secret: "{{ service_principal_client_secret }}"
        tenant: "{{ service_principal_tenant }}"
        subscription_id: 000-subscription-id
        name: ansibletestnic
        resource_group: resource_group_name
        tags:
          TestTag: UpdateTestValue
```

##### EXPECTED RESULTS

The 2nd task should update the tags of the first task

##### ACTUAL RESULTS

```paste below
fatal: [localhost]: FAILED! => {"changed": false, "msg": "state is present but all of the following are missing: subnet_name, virtual_network"}
```

I also tested to add subnet_name and virtual_network then it tries to delete the ip configurations and add a default NSG. So I am guessing the update logic here is not properly implemented. If the resource already exists, it should take the existing configuration and just update the set arguments of the current module call.
Tags may also be a special case where you need to merge exiting tags with tags set in module call (or maybe even make it configureable -- merge tags or overwrite all

**Comment by Klaas-** [comment]
Workaround using azure_rm_resource
```
- name: Update VM NIC in Azure
  azure.azcollection.azure_rm_resource:
    client_id: "{{ service_principal_application_id }}"
    secret: "{{ service_principal_client_secret }}"
    tenant: "{{ service_principal_tenant }}"
    subscription_id: 000-subscription-id
    resource_group: resource_group_name
    resource_name: ansibletestnic
    provider: Network
    resource_type: networkInterfaces
    method: PATCH
    api_version: 2024-05-01
    body:
      tags:
        TestTag: UpdateTestValue
```
This will replace tags with whatever is defined in tags.
