### ISSUE TITLE
Parameter app_role_assignment_required ignored on creating service principal

### ISSUE THREAD

**Issue by Matbefn** [ansible/ansible_collections_azure#1857]
##### SUMMARY

We are currently creating an automation with Ansible to create service principals in Azure.
When we set the parameter app_role_assignment_required: true it is ignored.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

azure_rm_adapplication

##### ANSIBLE VERSION

```paste below
ansible [core 2.18.3]
  config file = /home/myuser/.ansible.cfg
  configured module search path = ['/home/myuser/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/myuser/virtualenv/ansible_312/lib/python3.12/site-packages/ansible
  ansible collection location = /home/myuser/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/myuser/virtualenv/ansible_312/bin/ansible
  python version = 3.12.9 (main, Feb  5 2025, 08:49:01) [GCC 9.4.0] (/home/myuser/virtualenv/ansible_312/bin/python3.12)
  jinja version = 3.1.6
  libyaml = True

```

##### COLLECTION VERSION

```paste below
azure.azcollection                       3.2.0
```

##### CONFIGURATION

```paste below
CONFIG_FILE() = /home/myuser/.ansible.cfg

GALAXY_SERVERS:
```

##### OS / ENVIRONMENT

Ubuntu 20.04 python 3.12 venv

##### STEPS TO REPRODUCE

Example tasks below

```yaml
- name: Create Azure AD Application
      azure.azcollection.azure_rm_adapplication:
        display_name: "{{ display_name }}"
        tenant: "{{ tenant }}"
        auth_source: cli
        subscription_id: "{{ subscription_id }}"
        notes: |
          Created by HyCore
          Request ID
          Owner: {{ user_email }}
      register: app_reg

    - name: Debug
      ansible.builtin.debug:
        msg: "{{ app_reg.app_id }}"

    - name: Create service principal
      azure.azcollection.azure_rm_adserviceprincipal:
        app_id: "{{ app_reg.app_id }}"
        app_role_assignment_required: true
      register: service_principal

    - name: Debug
      ansible.builtin.debug:
        msg: "{{ service_principal }}"
```

##### EXPECTED RESULTS

The service principal is created with Role Assignment required set to yes / true.

##### ACTUAL RESULTS

```changed: [localhost] => {
    "app_display_name": "Application 1",
    "app_id": "<app_id>",
    "app_role_assignment_required": false,
    "changed": true,
    "invocation": {
        "module_args": {
            "ad_user": null,
            "adfs_authority_url": null,
            "api_profile": "latest",
            "app_id": "<app_id>",
            "app_role_assignment_required": true,
            "auth_source": "auto",
            "cert_validation_mode": null,
            "client_id": null,
            "cloud_environment": "AzureCloud",
            "disable_instance_discovery": false,
            "log_mode": null,
            "log_path": null,
            "password": null,
            "profile": null,
            "secret": null,
            "state": "present",
            "subscription_id": null,
            "tenant": null,
            "thumbprint": null,
            "x509_certificate_path": null
        }
    },
    "object_id": "<object_id>"
}
```
Output of module return
```
ok: [localhost] => {
    "msg": {
        "app_display_name": "Application 1",
        "app_id": "<app_id>",
        "app_role_assignment_required": false,
        "changed": true,
        "failed": false,
        "object_id": "<object_id>"
    }
}
```

```paste below

```
