### ISSUE TITLE
azure_rm_manageddisk updating tags on os disk no longer works

### ISSUE THREAD

**Issue by Klaas-** [ansible/ansible_collections_azure#1858]
##### SUMMARY
Hi,
it seems that https://github.com/ansible-collections/azure/pull/1833 broke updating tags on os disks.
It works fine with azure_rm_manageddisk prior to #1833 merge

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure_rm_manageddisk

##### ANSIBLE VERSION

```paste below
ansible [core 2.16.3]
  config file = /home/homedir/ansible.cfg
  configured module search path = ['/home/homedir/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.12/site-packages/ansible
  ansible collection location = /home/homedir/collections
  executable location = /usr/bin/ansible
  python version = 3.12.8 (main, Dec  9 2024, 15:25:01) [GCC 8.5.0 20210514 (Red Hat 8.5.0-22)] (/usr/bin/python3.12)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
# /home/homedir/collections/ansible_collections
Collection         Version
------------------ -------
azure.azcollection 3.3.1
```

##### CONFIGURATION

```paste below
COLLECTIONS_PATHS(/home/homedir/ansible.cfg) = ['/home/homedir/collections']
CONFIG_FILE() = /home/homedir/ansible.cfg
DEFAULT_NO_TARGET_SYSLOG(/home/homedir/ansible.cfg) = True
DEFAULT_ROLES_PATH(/home/homedir/ansible.cfg) = ['/home/homedir/roles']
```

##### STEPS TO REPRODUCE

```yaml
  azure.azcollection.azure_rm_manageddisk:
    client_id: "{{ service_principal_application_id }}"
    secret: "{{ service_principal_client_secret }}"
    tenant: "{{ service_principal_tenant }}"
    subscription_id: "{{ subscription_id }}"
    name: "{{ disk_name }}"
    resource_group: "{{ resource_group_name }}"
    tags:
      Tag1: Value1
```

##### EXPECTED RESULTS

Works, updates tags on os disk

##### ACTUAL RESULTS

```paste below
{"ansible_loop_var": "item", "changed": false, "item": "hostname-disk1-os", "msg": "When create_option=fromimage is configured, image_reference or gallery_image_reference must be configured"}
```
