### ISSUE TITLE
azure_rm_roleassignment not idempotent

### ISSUE THREAD

**Issue by Klaas-** [ansible/ansible_collections_azure#1859]
##### SUMMARY
azure_rm_roleassignment not idempotent

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure_rm_roleassignment

##### ANSIBLE VERSION

```paste below
ansible [core 2.16.3]
  config file = /home/homedir/ansible.cfg
  configured module search path = ['/home/homedir/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.12/site-packages/ansible
  ansible collection location = /home/homedir/collections
  executable location = /usr/bin/ansible
  python version = 3.12.8 (main, Dec  9 2024, 15:25:01) [GCC 8.5.0 20210514 (Red Hat 8.5.0-22)] (/usr/bin/python3.12)
  jinja version = 3.1.2
  libyaml = True

```

##### COLLECTION VERSION

```paste below

# /home/homedir/collections/ansible_collections
Collection         Version
------------------ -------
azure.azcollection 3.3.1

```

##### CONFIGURATION

```paste below
COLLECTIONS_PATHS(/home/homedir/ansible.cfg) = ['/home/homedir/collections']
CONFIG_FILE() = /home/homedir/ansible.cfg
DEFAULT_NO_TARGET_SYSLOG(/home/homedir/ansible.cfg) = True
DEFAULT_ROLES_PATH(/home/homedir/ansible.cfg) = ['/home/homedir/roles']
```

##### OS / ENVIRONMENT

RHEL8.10

##### STEPS TO REPRODUCE

```yaml
- name: Test azure_rm_roleassignment
  hosts: all
  gather_facts: false
  connection: local

  tasks:
    - name: Create a role assignment
      azure.azcollection.azure_rm_roleassignment:
        client_id: "{{ service_principal_application_id }}"
        secret: "{{ service_principal_client_secret }}"
        tenant: "{{ service_principal_tenant }}"
        subscription_id: "{{ subscription_id }}"
        scope: "{{ id }}"
        assignee_object_id: "{{ object_id }}"
        role_definition_id: "{{ role_definition_idd }}"
  
    - name: Run role assignment again
      azure.azcollection.azure_rm_roleassignment:
        client_id: "{{ service_principal_application_id }}"
        secret: "{{ service_principal_client_secret }}"
        tenant: "{{ service_principal_tenant }}"
        subscription_id: "{{ subscription_id }}"
        scope: "{{ id }}"
        assignee_object_id: "{{ object_id }}"
        role_definition_id: "{{ role_definition_idd }}"
```

##### EXPECTED RESULTS

The 2nd task should say ok, nothing changed

##### ACTUAL RESULTS

```paste below
{"changed": false, "msg": "Error creating role assignment: (RoleAssignmentExists) The role assignment already exists.\nCode: RoleAssignmentExists\nMessage: The role assignment already exists."}
```
