### ISSUE TITLE
The azure_rm_servicebus module has a property premium_messaging_partitions which is missing a legal value (0) and has a bad default (1)

### ISSUE THREAD

**Issue by shannon-alliance** [ansible/ansible_collections_azure#1870]
##### SUMMARY
The azure_rm_servicebus module has a property `premium_messaging_partitions` which is missing a legal value (0) and has a bad default (1)

What the module should do is add 0 (zero) to the list of supported values for the `premium_messaging_partitions` property and make it the default when the property is excluded.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure_rm_servicebus

##### ANSIBLE VERSION

```paste below
ansible [core 2.18.3]
  config file = /Users/*******/*******/ansible/ansible.cfg
  configured module search path = ['/Users/*******/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/*******/.local/pipx/venvs/ansible-core/lib/python3.12/site-packages/ansible
  ansible collection location = /Users/*******/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/*******/.local/bin/ansible
  python version = 3.12.0 (main, Mar  1 2025, 13:13:54) [Clang 16.0.0 (clang-1600.0.26.6)] (/Users/*******/.local/pipx/venvs/ansible-core/bin/python)
  jinja version = 3.1.6
  libyaml = True
```

##### COLLECTION VERSION

```paste below
Collection         Version
------------------ -------
azure.azcollection 3.2.0  

# /Users/*******/.local/pipx/venvs/ansible-core/lib/python3.12/site-packages/ansible_collections
Collection         Version
------------------ -------
azure.azcollection 3.2.0  
```

##### CONFIGURATION

```paste below
CONFIG_FILE() = /Users/*******/*******/ansible/ansible.cfg
DEFAULT_HOST_LIST(/Users/*******/*******/ansible/ansible.cfg) = ['/Users/*******/*******/ansible/inventory/localhost.yml']
DEFAULT_REMOTE_USER(/Users/*******/*******/ansible/ansible.cfg) = alliance
DEFAULT_VAULT_PASSWORD_FILE(/Users/*******/*******/ansible/ansible.cfg) = /Users/*******/*******/ansible/vault-password.txt
HOST_KEY_CHECKING(/Users/*******/*******/ansible/ansible.cfg) = False
PAGER(env: PAGER) = less

GALAXY_SERVERS:
```

##### OS / ENVIRONMENT

All OS

##### STEPS TO REPRODUCE

Any attempt to use `azure_rm_servicebus` with a standard or basic plan will fail. It doesn't matter if you exclude the `premium_messaging_partitions` property or provide it with a value because all the allowed values (1,2 or 4) are not supported on standard and basic plans (premium only).

```yaml
- name: SHOULD FAIL because premium_messaging_partitions > 0 is not supported on standard and basic sku
  azure.azcollection.azure_rm_servicebus:
    subscription_id: "{{ service_bus_subscription_id }}"
    resource_group: "{{ service_bus_resource_group }}"
    name: "{{ service_bus_name }}"
    location: "{{ service_bus_location }}"
    sku: "standard"  # or "basic" (premium will work)
    premium_messaging_partitions: 1

- name: SHOULD WORK BUT FAILS because premium_messaging_partitions == 0 is not supported by module
  azure.azcollection.azure_rm_servicebus:
    subscription_id: "{{ service_bus_subscription_id }}"
    resource_group: "{{ service_bus_resource_group }}"
    name: "{{ service_bus_name }}"
    location: "{{ service_bus_location }}"
    sku: "standard"  # or "basic" (premium will work)
    premium_messaging_partitions: 0

- name: SHOULD WORK BUT FAILS because premium_messaging_partitions defaults to 1 even when the sku doesn't support it
  azure.azcollection.azure_rm_servicebus:
    subscription_id: "{{ service_bus_subscription_id }}"
    resource_group: "{{ service_bus_resource_group }}"
    name: "{{ service_bus_name }}"
    location: "{{ service_bus_location }}"
    sku: "standard"  # or "basic" (premium will work)

- name: WORKS but only because premium sku allows it
  azure.azcollection.azure_rm_servicebus:
    subscription_id: "{{ service_bus_subscription_id }}"
    resource_group: "{{ service_bus_resource_group }}"
    name: "{{ service_bus_name }}"
    location: "{{ service_bus_location }}"
    sku: premium
    premium_messaging_partitions: 1
```

##### EXPECTED RESULTS

The first example SHOULD FAIL because azure requires a premium sku/plan to use premium_messaging_partitions. 

The next three examples should all work.
 
What is expected is that premium_messaging_partitions: 0 is a valid choice and it should also be the 

##### ACTUAL RESULTS

```paste below
WHEN USING 0 AS PROPERTY VALUE:
fatal: [localhost]: FAILED! => {"changed": false, "msg": "value of premium_messaging_partitions must be one of: 1, 2, 4, got: 0"}

WHEN USING 1, 2 or 4 AS PROPERTY VALUE (OR MISSING PROPERTY):
Error creating namespace myservicebusname - (PremiumMessagingPartitionsNotSupportedForStandardOrBasic) The specified value 1 is invalid. The property PremiumMessagingPartitions is supported only for Premium messaging namespaces and it must be 0 for Standard and Basic namespaces
```
