### ISSUE TITLE
Creating App registration with certificate leads to error

### ISSUE THREAD

**Issue by Matbefn** [ansible/ansible_collections_azure#1872]
##### SUMMARY

We are creating a app registration with azure_rm_adapplication and want to directly add the certificate.
We tried several formats of the public key, but weren't successful

Error message is always: `KeyValue cannot be null or empty`

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

azure_rm_adapplication

##### ANSIBLE VERSION

```paste below
ansible [core 2.15.12]
  config file = /home/<user>/.ansible.cfg
  configured module search path = ['/home/<user>/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/<user>/virtualenv/ansible_312/lib/python3.12/site-packages/ansible
  ansible collection location = /home/<user>/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/<user>/virtualenv/ansible_312/bin/ansible
  python version = 3.12.9 (main, Feb  5 2025, 08:49:01) [GCC 9.4.0] (/home/<user>/virtualenv/ansible_312/bin/python)
  jinja version = 3.1.4
  libyaml = True
```

##### COLLECTION VERSION

```paste below
azure.azcollection 3.2.0
```

##### CONFIGURATION

```paste below
CONFIG_FILE() = /home/<user>/.ansible.cfg
GALAXY_SERVER_LIST(/home/<user>/.ansible.cfg) = ['zf_hub_published', 'zf_hub_certified', 'zf_hub_community']

```

##### OS / ENVIRONMENT

NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"

##### STEPS TO REPRODUCE

```yaml
- name: Create Azure AD Application
      azure.azcollection.azure_rm_adapplication:
        display_name: "{{ display_name }}"
        tenant: "{{ tenant }}"
        auth_source: cli
        subscription_id: "{{ subscription_id }}"
        key_usage: Verify
        key_value: "{{ lookup('file', '/tmp/cert_test/cert_base64.der') | b64decode }}"
        notes: |
          Request ID
          Owner: {{ user_email }}
      register: app_reg
```

##### EXPECTED RESULTS

App registration is executed and publlick key is stored

##### ACTUAL RESULTS

```paste below
The full traceback is:
  File "/tmp/ansible_azure.azcollection.azure_rm_adapplication_payload_it9j5awe/ansible_azure.azcollection.azure_rm_adapplication_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_adapplication.py", line 666, in create_resource
    response = asyncio.get_event_loop().run_until_complete(self.create_application(create_app))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 691, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/tmp/ansible_azure.azcollection.azure_rm_adapplication_payload_it9j5awe/ansible_azure.azcollection.azure_rm_adapplication_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_adapplication.py", line 887, in create_application
    return await self._client.applications.post(body=creat_app)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/<user>/virtualenv/ansible_312/lib/python3.12/site-packages/msgraph/generated/applications/applications_request_builder.py", line 96, in post
    return await self.request_adapter.send_async(request_info, Application, error_mapping)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/<user>/virtualenv/ansible_312/lib/python3.12/site-packages/kiota_http/httpx_request_adapter.py", line 193, in send_async
    await self.throw_failed_responses(response, error_map, parent_span, parent_span)
  File "/home/<user>/virtualenv/ansible_312/lib/python3.12/site-packages/kiota_http/httpx_request_adapter.py", line 575, in throw_failed_responses
    raise exc
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "ad_user": null,
            "adfs_authority_url": null,
            "allow_guests_sign_in": null,
            "api_profile": "latest",
            "app_id": null,
            "app_roles": null,
            "auth_source": "cli",
            "cert_validation_mode": null,
            "client_id": null,
            "cloud_environment": "AzureCloud",
            "credential_description": null,
            "disable_instance_discovery": false,
            "display_name": "<Display name>",
            "end_date": null,
            "homepage": null,
            "identifier_uris": null,
            "key_type": "AsymmetricX509Cert",
            "key_usage": "Verify",
            "key_value": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "log_mode": null,
            "log_path": null,
            "native_app": null,
            "notes": "Request ID\nOwner: <email>\n",
            "oauth2_allow_implicit_flow": null,
            "optional_claims": null,
            "password": null,
            "profile": null,
            "public_client_reply_urls": null,
            "required_resource_accesses": null,
            "secret": null,
            "sign_in_audience": null,
            "spa_reply_urls": null,
            "start_date": null,
            "state": "present",
            "subscription_id": "597c344e-187e-4081-9c5d-65b8ebd09247",
            "tenant": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "thumbprint": null,
            "web_reply_urls": null,
            "x509_certificate_path": null
        }
    },
    "msg": "Error creating application, display_name:  APIError\n        Code: 400\n        message: None\n        error: MainError(additional_data={}, code='KeyCredentialsInvalidValue', details=[ErrorDetails(additional_data={'blockedWord': '', 'prefix': '', 'suffix': ''}, code='InvalidKeyValue', message='KeyValue cannot be null or empty', target='None')], inner_error=InnerError(additional_data={}, client_request_id='f1fb8e31-4b0d-4fbd-a9e8-8932df48a377', date=datetime.datetime(2025, 3, 24, 7, 40, 5), odata_type=None, request_id='574cfd4c-ddb1-4f40-9f54-f87957d96f03'), message='KeyValue cannot be null or empty', target=None)\n        "
```

**Comment by Fred-sun** [comment]
@Matbefn According to your error, the value of your key_value is empty.  Can you confirm whether the open file exists and the file content is empty or not. Thank you!

**Comment by Matbefn** [comment]
@Fred-sun yes, the file exists and it contains the certificate. In the mean time I did some tests and use the file directly in a Graph API call.

Read the file:
```
- name: Slurp
      ansible.builtin.slurp:
        src: /tmp/cert_test/tmp/certfile.pem
      register: cert_file
```

Use in Ansible
```
 - name: Create Azure AD Application
      azure.azcollection.azure_rm_adapplication:
        display_name: "{{ display_name }}"
        tenant: "{{ tenant }}"
        auth_source: cli
        subscription_id: "{{ subscription_id }}"
        key_usage: Verify
        key_value: "{{ cert_file.content }} "
        notes: |
          Created by HyCore
          Request ID
          Owner: {{ owner_email }}
      register: app_reg
```

Use with Graph API
```
    - name: Add API permission User.Read
      ansible.builtin.uri:
        url: "https://graph.microsoft.com/v1.0/applications/{{ app_reg.object_id }}"
        method: PATCH
        headers:
          Authorization: "Bearer {{ access_token }}"
          Content-Type: "application/json"
        body_format: json
        body:
          {
            "keyCredentials": [
              {
                "key": "{{ cert_file.content }}",
                "type": "AsymmetricX509Cert",
                "usage": "Verify"
              }
            ]
          }
        status_code:
          - 204
      register: result

```

From a documentation point of view, the format of the certificate should be the same if I use the ansible module or the graph api directly?
