### ISSUE TITLE
virtualnetworkgatewayconnection module not working for IPSec tunnel

### ISSUE THREAD

**Issue by lodex2** [ansible/ansible_collections_azure#1873]
##### SUMMARY
I'm trying to setup a VPN tunnel between an on-premise VPN appliance and Azure. However, the module seems to be restricted to "Vnet2Vnet" tunnels. There are missing and conflicting parameters for an IPSec tunnel to a "non-Azure" endpoint.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
virtualnetworkgatewayconnection

##### ANSIBLE VERSION

```paste below
ansible [core 2.16.3]
  config file = /Users/mholz/ops/deploy/ansible/ansible.cfg
  configured module search path = ['/Users/mholz/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/mholz/.pyenv/versions/3.11.7/envs/ansible/lib/python3.11/site-packages/ansible
  ansible collection location = /Users/mholz/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/mholz/.pyenv/versions/ansible/bin/ansible
  python version = 3.11.7 (main, Nov  5 2024, 10:29:31) [Clang 16.0.0 (clang-1600.0.26.4)] (/Users/mholz/.pyenv/versions/3.11.7/envs/ansible/bin/python)
  jinja version = 3.1.4
  libyaml = True
```

##### COLLECTION VERSION

```paste below
Collection         Version
------------------ -------
azure.azcollection 3.3.1
```

##### CONFIGURATION

```paste below
CACHE_PLUGIN(/Users/mholz/ops/deploy/ansible/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/Users/mholz/ops/deploy/ansible/ansible.cfg) = .ansible_facts_cache_dir/
CACHE_PLUGIN_TIMEOUT(/Users/mholz/ops/deploy/ansible/ansible.cfg) = 3600
CONFIG_FILE() = /Users/mholz/ops/deploy/ansible/ansible.cfg
DEFAULT_GATHERING(/Users/mholz/ops/deploy/ansible/ansible.cfg) = smart
DEFAULT_MANAGED_STR(/Users/mholz/ops/deploy/ansible/ansible.cfg) = Ansible managed: {file} modified on %Y-%m-%d %H:%M:%S by {uid} on {host}
DEFAULT_ROLES_PATH(/Users/mholz/ops/deploy/ansible/ansible.cfg) = ['/Users/mholz/ops/deploy/ansible/roles']
DEFAULT_VAULT_PASSWORD_FILE(/Users/mholz/ops/deploy/ansible/ansible.cfg) = /Users/mholz/ops/deploy/ansible/open-vault.sh
DISPLAY_SKIPPED_HOSTS(/Users/mholz/ops/deploy/ansible/ansible.cfg) = False
EDITOR(env: EDITOR) = nvim
HOST_KEY_CHECKING(/Users/mholz/ops/deploy/ansible/ansible.cfg) = False
INVENTORY_ENABLED(/Users/mholz/ops/deploy/ansible/ansible.cfg) = ['auto', 'yaml']
PAGER(env: PAGER) = less
TRANSFORM_INVALID_GROUP_CHARS(/Users/mholz/ops/deploy/ansible/ansible.cfg) = silently
```

##### STEPS TO REPRODUCE

Attempt to create a VPN connection with connection type 'IPsec'

```yaml
- name: create local network gateway
  azure.azcollection.azure_rm_localnetworkgateway:
    name: "lgw-test-local-gateway" 
    resource_group: "my_resource_group"
    gateway_ip_address: 1.2.3.4
    local_network_address_space:
      address_prefixes: 
        - 1.1.1.1/32
        - 2.2.2.2/32
  register: lgw_config

- name: 'create VPN connection'
  azure.azcollection.azure_rm_virtualnetworkgatewayconnection:
    name: "ipsec_connection"
    resource_group: "my_resource_group"
    connection_type: IPsec
    connection_protocol: IKEv2
    shared_key: 12345qwert
    dpd_timeout_seconds: 45
    virtual_network_gateway1: replace/with/path/to/vpn_gateway
    local_network_gateway2: "{{ lgw_config.state.name }}"
```

##### EXPECTED RESULTS

A VPN connection is created.

##### ACTUAL RESULTS

The creation fails due to a undefined variable `virtual_network_gateway2`, which should not be necessary in this case

```paste below
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Create or Updated a network gateway connection in a resource group Failed, Exception as (InvalidRequestFormat) Cannot parse the request.\nCode: InvalidRequestFormat\nMessage: Cannot parse the request.\nException Details:\t(MissingJsonReferenceId) Value for reference id is missing. Path properties.virtualNetworkGateway2.\n\tCode: MissingJsonReferenceId\n\tMessage: Value for reference id is missing. Path properties.virtualNetworkGateway2."}
```
If I define the missing variable for debugging purposes, there is another error:
```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Create or Updated a network gateway connection in a resource group Failed, Exception as (InvalidConnectionTypeForVnet2VnetConnection) Invalid ConnectionType specified for VnetToVnet connection. The connection type specified is IPsec\nCode: InvalidConnectionTypeForVnet2VnetConnection\nMessage: Invalid ConnectionType specified for VnetToVnet connection. The connection type specified is IPsec"}
```
In addition (but possibly other issues):
- it's not possible to configure IPSec tunnel policy parameters
- the 'local' VPN gateway (in variable `virtual_network_gateway1`) cannot be referenced by name only. This is unfortunate since there is no 'info' module for VPN gateways to get its ID in a convenient way.
