### ISSUE TITLE
Add ability to azure_rm_virtualmachine to deploy from a self-managed image gallery definition

### ISSUE THREAD

**Issue by TypeMayVary** [ansible/ansible_collections_azure#1882]
##### SUMMARY

Allow the deployment of Virtual Machines using the ID of a Share Image Gallery (much like the existing use of a community gallery).

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

change to existing **azure_rm_virtualmachine** module (_azure_rm_virtualmachine.py_)

##### ADDITIONAL INFORMATION

I make use of the the azure_rm_virtualmachine module to deploy VMs from images published in the public marketplace for testing my Ansible roles against infrastructure deployed in Azure. I have a requirement to deploy from a custom image that we've created, to have a more valid test run of the roles (as the roles are used on infrastructure with the same configuration that is in the custom image). 

The custom image in question in stored as a version in our own Shared Image Gallery. Today, the azure_rm_virtualmachine module does not allow deployment from a custom image in a Shared Image Gallery. I believe this is a relatively common procedure, as Azure seems to have more of a preference of people utilising SIGs and Image Versions, rather than Managed Images which they commonly reference as 'legacy' in their documentation.

The implementation of the functionality seems simple (on the face of it):
The addition of the following code in the [relevant if-else block](https://github.com/ansible-collections/azure/blob/51b4ddf6eef5e5e9bf7ff93d2c3c4edcf4b57f00/plugins/modules/azure_rm_virtualmachine.py#L1461)

```
elif self.image.get('shared_gallery_image_id') is not None:
                    image_reference = self.compute_models.ImageReference(shared_gallery_image_id=self.image['shared_gallery_image_id'])
```

[The relevant SDK attribute reference](https://learn.microsoft.com/en-us/python/api/azure-mgmt-compute/azure.mgmt.compute.v2024_11_01.models.imagereference?view=azure-python#variables), for reference.

This would allow deployment of VMs using the module like so:
```yaml

- name: Create VM with shared gallery image ID
  azure_rm_virtualmachine:
    resource_group: "{{ resource_group }}"
    name: "shared-image-vm"
    admin_username: testuser
    ssh_password_enabled: false
    managed_disk_type: Premium_LRS
    open_ports:
      - 33
    ssh_public_keys:
      - path: /home/testuser/.ssh/authorized_keys
        key_data: "ssh-rsa ************* @qq.com"
    vm_size: Standard_B1ms
    image:
      shared_gallery_image_id: "/subscriptions/{{ subscription_id }}/resourceGroups/{{ resource_group }}/providers/Microsoft.Compute/galleries/MyCustomGalleryName/images/MyCustomImageDefinitionName"

```
