### ISSUE TITLE
azure_rm_backuppolicy not idempotent

### ISSUE THREAD

**Issue by Klaas-** [ansible/ansible_collections_azure#1888]
##### SUMMARY
azure_rm_backuppolicy is not idempotent, executing the module twice with same data results in a change each time

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure_rm_backuppolicy

##### ANSIBLE VERSION

```paste below
ansible [core 2.16.3]
```

##### COLLECTION VERSION

```paste below
3.3.1
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

Will create a PR with integration test that shows the issue, easiest way is just create the same policy twice

```yaml

- name: Create a daily VM backup policy
  azure_rm_backuppolicy:
    vault_name: "{{ vault_name }}"
    name: "{{ policy_name_daily }}"
    resource_group: "{{ resource_group }}"
    state: present
    backup_management_type: "AzureIaasVM"
    schedule_run_frequency: "Daily"
    instant_recovery_snapshot_retention: 2
    daily_retention_count: 12
    time_zone: "Pacific Standard Time"
    schedule_run_time: 14
  register: daily_policy_output

- name: Create a daily VM backup policy (idempotent)
  azure_rm_backuppolicy:
    vault_name: "{{ vault_name }}"
    name: "{{ policy_name_daily }}"
    resource_group: "{{ resource_group }}"
    state: present
    backup_management_type: "AzureIaasVM"
    schedule_run_frequency: "Daily"
    instant_recovery_snapshot_retention: 2
    daily_retention_count: 12
    time_zone: "Pacific Standard Time"
    schedule_run_time: 14
  register: daily_policy_output_idempotent
  
- name: Assert that there is no change after second deletion of daily backup policy
  ansible.builtin.assert:
    that:
      - not daily_policy_output_idempotent.changed

```

##### EXPECTED RESULTS

one changed, one ok, asset succeeds

##### ACTUAL RESULTS

```paste below
two changed, assert fails
```
