### ISSUE TITLE
Not able to set the deployment provider to GitHub Actions

### ISSUE THREAD

**Issue by srivatsan-nagarajan** [ansible/ansible_collections_azure#1896]
##### SUMMARY
I have followed the steps as per the ansible official documentation to create the azure webapp and I'm not able to link to github repository.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure_rm_webapp

##### ANSIBLE VERSION
```
ansible [core 2.18.4]
  config file = None
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/ansible
  ansible collection location = /home/runner/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/hostedtoolcache/Python/3.12.3/x64/bin/ansible
  python version = 3.12.3 (main, Sep 26 2024, 18:18:55) [GCC 13.2.0] (/opt/hostedtoolcache/Python/3.12.3/x64/bin/python)
  jinja version = 3.1.6
  libyaml = True
ansible-galaxy [core 2.18.4]
  config file = None
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/ansible
  ansible collection location = /home/runner/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/hostedtoolcache/Python/3.12.3/x64/bin/ansible-galaxy
  python version = 3.12.3 (/opt/hostedtoolcache/Python/3.12.3/x64/bin/python)
  jinja version = 3.1.6
  libyaml = True
ansible-playbook [core 2.18.4]
  config file = None
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/ansible
  ansible collection location = /home/runner/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/hostedtoolcache/Python/3.12.3/x64/bin/ansible-playbook
  python version = 3.12.3 
  jinja version = 3.1.6
  libyaml = True

```

##### COLLECTION VERSION

```
# /home/runner/.ansible/collections/ansible_collections
Collection         Version
------------------ -------
azure.azcollection 3.3.1  
adal==1.2.7
aiohappyeyeballs==2.6.1
aiohttp==3.11.16
aiosignal==1.3.2
ansible-core==2.18.4
anyio==4.9.0
applicationinsights==0.11.[10](https://github.com/The-Coca-Cola-Company/coke-cps-azure-deployment/actions/runs/14379732544/job/40320419251#step:7:11)
argcomplete==3.3.0
attrs==25.3.0
azure-cli-core==2.64.0
azure-cli-telemetry==1.1.0
azure-common==1.1.28
azure-containerregistry==1.2.0
azure-core==1.31.0
azure-identity==1.19.0
azure-iot-hub==2.6.1
azure-keyvault==4.2.0
azure-keyvault-certificates==4.9.0
azure-keyvault-keys==4.10.0
azure-keyvault-secrets==4.9.0
azure-mgmt-apimanagement==4.0.1
azure-mgmt-authorization==4.0.0
azure-mgmt-automation==1.1.0b4
azure-mgmt-batch==17.3.0
azure-mgmt-cdn==13.1.1
azure-mgmt-compute==33.0.0
azure-mgmt-containerinstance==10.1.0
azure-mgmt-containerregistry==10.3.0
azure-mgmt-containerservice==32.1.0
azure-mgmt-core==1.4.0
azure-mgmt-cosmosdb==10.0.0b3
azure-mgmt-datafactory==9.0.0
azure-mgmt-devtestlabs==10.0.0b2
azure-mgmt-dns==8.1.0
azure-mgmt-eventhub==[11](https://github.com/The-Coca-Cola-Company/coke-cps-azure-deployment/actions/runs/14379732544/job/40320419251#step:7:12).1.0
azure-mgmt-hdinsight==9.1.0b1
azure-mgmt-iothub==3.0.0
azure-mgmt-keyvault==10.3.1
azure-mgmt-loganalytics==13.0.0b7
azure-mgmt-managedservices==7.0.0b2
azure-mgmt-managementgroups==1.1.0b2
azure-mgmt-marketplaceordering==1.2.0b2
azure-mgmt-monitor==6.0.2
azure-mgmt-network==28.0.0
azure-mgmt-notificationhubs==8.1.0b1
azure-mgmt-nspkg==3.0.2
azure-mgmt-privatedns==1.1.0
azure-mgmt-rdbms==10.2.0b17
azure-mgmt-recoveryservices==3.0.0
azure-mgmt-recoveryservicesbackup==9.1.0
azure-mgmt-redis==14.4.0
azure-mgmt-resource==23.2.0
azure-mgmt-resourcehealth==1.0.0b6
azure-mgmt-search==9.2.0b2
azure-mgmt-servicebus==8.2.1
azure-mgmt-sql==4.0.0b19
azure-mgmt-storage==21.2.1
azure-mgmt-trafficmanager==1.1.0
azure-mgmt-web==7.3.1
azure-nspkg==3.0.2
azure-storage-blob==[12](https://github.com/The-Coca-Cola-Company/coke-cps-azure-deployment/actions/runs/14379732544/job/40320419251#step:7:13).23.0b1
bcrypt==4.3.0
certifi==2025.1.31
cffi==1.17.1
charset-normalizer==3.4.1
cryptography==44.0.2
Deprecated==1.2.18
distro==1.9.0
frozenlist==1.5.0
h11==0.14.0
h2==4.2.0
hpack==4.1.0
httpcore==1.0.7
httpx==0.28.1
humanfriendly==10.0
hyperframe==6.1.0
idna==3.10
importlib_metadata==8.6.1
isodate==0.7.2
Jinja2==3.1.6
jmespath==1.0.1
jsonschema==4.23.0
jsonschema-specifications==2024.10.1
knack==0.11.0
MarkupSafe==3.0.2
microsoft-kiota-abstractions==1.9.3
microsoft-kiota-authentication-azure==1.9.3
microsoft-kiota-http==1.9.3
microsoft-kiota-serialization-form==1.9.3
microsoft-kiota-serialization-json==1.9.3
microsoft-kiota-serialization-multipart==1.9.3
microsoft-kiota-serialization-text==1.9.3
msal==1.30.0
msal-extensions==1.2.0
msgraph-core==1.3.3
msgraph-sdk==1.6.0
msrest==0.7.1
msrestazure==0.6.4.post1
multidict==6.4.2
netaddr==1.3.0
oauthlib==3.2.2
opentelemetry-api==1.31.1
opentelemetry-sdk==1.31.1
opentelemetry-semantic-conventions==0.52b1
oras==0.2.28
packaging==24.2
paramiko==3.5.1
pkginfo==1.12.1.2
portalocker==2.10.1
propcache==0.3.1
psutil==7.0.0
pycparser==2.22
Pygments==2.19.1
PyJWT==2.10.1
PyNaCl==1.5.0
pyOpenSSL==25.0.0
PySocks==1.7.1
python-dateutil==2.9.0.post0
PyYAML==6.0.2
referencing==0.36.2
requests==2.32.3
requests-oauthlib==2.0.0
resolvelib==1.0.1
rpds-py==0.24.0
six==1.17.0
sniffio==1.3.1
std-uritemplate==2.0.3
tabulate==0.9.0
typing_extensions==4.[13](https://github.com/The-Coca-Cola-Company/coke-cps-azure-deployment/actions/runs/14379732544/job/40320419251#step:7:14).1
uamqp==1.6.11
urllib3==2.3.0
wrapt==1.17.2
xmltodict==0.[14](https://github.com/The-Coca-Cola-Company/coke-cps-azure-deployment/actions/runs/14379732544/job/40320419251#step:7:15).2
yarl==1.19.0
zipp==3.21.0

```

##### CONFIGURATION
None. Haven't set up one using the defaults.

##### OS / ENVIRONMENT
 Image: ubuntu-24.04
 Version: 20250406.1.0
 Included Software: https://github.com/actions/runner-images/blob/ubuntu24/20250406.1/images/ubuntu/Ubuntu2404-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu24%2F20250406.1

##### STEPS TO REPRODUCE
I have passed the params for the scm and deployment source. I have tried changing scm type GitHub, GitHubActions and it doesn't work as expected.

```
---
- name: Initial Setup
  hosts: webservers
  connection: local
  gather_facts: false

  tasks:

    - name: Create Java Web App Service on Linux
      azure.azcollection.azure_rm_webapp:
        client_id: "{{ app_client_id }}"
        secret: "{{ app_secret }}"
        tenant: "{{ tenant_id }}"
        subscription_id: "{{ subscription_id }}"
        resource_group: "{{ resource_group }}"
        location: "{{ location }}"
        name: "{{ webapp_name }}"
        plan:
          resource_group: "{{ resource_group }}"
          name: "{{ plan_name }}"
          is_linux: true
          sku: P1v3
          number_of_workers: 1
        frameworks:
          - name: "java"
            version: "17"
        scm_type: "GitHub" #GithubAction
        deployment_source:
          branch: "sri-dev"
          url: "https://github.com/The-Coca-Cola-Company/coke-aps-backend"
        tags:
          ApplicationCode: "tei"
        site_auth_settings:
          enabled: true
          token_store_enabled: true
          client_id: "***"
          client_secret_setting_name: "***"
          issuer: "***"
          config_version: "v2"
          runtime_version: "v2"
          unauthenticated_client_action: "RedirectToLoginPage"
        app_settings:
          client_application_requirement: "SelfSigned"
          identity_requirement: "Any"
          tenant_requirement: "Issuer"
          require_authentication: true
        client_affinity_enabled: false
        min_tls_version: 1.2
        always_on: true
        identity:
          type: SystemAssigned

```

##### EXPECTED RESULTS

![Image](https://github.com/user-attachments/assets/eab04da5-4b52-43ed-a037-10faf712b02c)

##### ACTUAL RESULTS

![Image](https://github.com/user-attachments/assets/436ac115-37e3-4408-b510-b8467ca4a64a)

``` when scm is set to GitHub```

![Image](https://github.com/user-attachments/assets/271e6690-fe6c-4eaa-a2bf-e694938974b6)

``` when scm is set to GitHubAction```

##### CONCLUSION
However, things work well when executed with azure cli for webapp deployment settings. In the cli, I can see that there is an external flag for --github-actions whereas it isn't there in the azure_rm_webapp module using in ansible. This is a blocker for me for MTP. Can you please review and get back to me how to resolve this.
