### ISSUE TITLE
Cannot specify subscription for remote network when creating peering

### ISSUE THREAD

**Issue by MikePeckOneValley** [ansible/ansible_collections_azure#1907]
##### SUMMARY

I'm trying to create a vnet peering that crosses subscriptions.  The web portal allows me to do this, but the ansible module does not.  More details under Steps To Reproduce.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure_rm_virtualnetworkpeering

##### ANSIBLE VERSION
```
%  ansible --version
ansible [core 2.18.0]
  config file = /Users/mpeck/.ansible.cfg
  configured module search path = ['/Users/mpeck/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/homebrew/lib/python3.13/site-packages/ansible
  ansible collection location = /Users/mpeck/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/homebrew/bin/ansible
  python version = 3.13.2 (main, Feb  4 2025, 14:51:09) [Clang 15.0.0 (clang-1500.1.0.2.5)] (/opt/homebrew/opt/python@3.13/bin/python3.13)
  jinja version = 3.1.4
  libyaml = True
```

##### COLLECTION VERSION
```
% ansible-galaxy collection list
Using /Users/mpeck/.ansible.cfg as config file

# /Users/mpeck/.ansible/collections/ansible_collections
Collection         Version
------------------ -------
azure.azcollection 3.1.0
```

##### CONFIGURATION
```
% ansible-config dump --only-changed
Using /Users/mpeck/.ansible.cfg as config file
CONFIG_FILE() = /Users/mpeck/.ansible.cfg
DEFAULT_LOG_PATH(/Users/mpeck/.ansible.cfg) = /Users/mpeck/.ansible/log/ansible.log
DEFAULT_VERBOSITY(/Users/mpeck/.ansible.cfg) = 1

GALAXY_SERVERS:
```

##### OS / ENVIRONMENT
MacOS M1 chip Venture 13.6.6 (22G630)

##### STEPS TO REPRODUCE

Create a playbook as shown below, and run it.

Look at the docs found here: https://docs.ansible.com/ansible/latest/collections/azure/azcollection/azure_rm_virtualnetworkpeering_module.html#parameter-remote_virtual_network

This fragment does not accept `subscription_id` as it should.  The documentation link above does not reflect it, the examples at the bottom do not, and I have tried it in an example, and the subscription is silently ignored.

Except the error message reflects the subscription of the net I'm adding the peering to:
```
TASK [Create vnet peering to aks] **************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error creating Azure Virtual Network Peering: (InvalidGlobalResourceReference) Resource /subscriptions/7a648a44-<redacted>/resourceGroups/<redacted>-rg/providers/Microsoft.Network/virtualNetworks/<redacted>-aks-vnet referenced by resource /subscriptions/7a648a44-<redacted>/resourceGroups/<redacted>-2/providers/Microsoft.Network/virtualNetworks/<redacted>-2/virtualNetworkPeerings/<redacted>-2-aks was not found. Please make sure that the referenced resource exists.\nCode: InvalidGlobalResourceReference\nMessage: Resource /subscriptions/7a648a44-<redacted>/resourceGroups/<redacted>-rg/providers/Microsoft.Network/virtualNetworks/<redacted>-aks-vnet referenced by resource /subscriptions/7a648a44-<redacted>/resourceGroups/<redacted>-2/providers/Microsoft.Network/virtualNetworks/<redacted>-2/virtualNetworkPeerings/<redacted>-2-aks was not found. Please make sure that the referenced resource exists.."}
```

The ansible play that caused this is:
```
  vars:
    id_subscription: 7a648a44-<redacted>
    id_subscription_aks: 340f9fe4-<redacted>
    id_tenant: 604c40e9-<redacted>
    name_rg: <redacted>-2
    name_vnet: <redacted>-2
    name_vnet_peer_aks_netrg: <redacted>-rg
    name_vnet_peer_aks_netname: <redacted>-aks-vnet
    name_vnet_peering_aks: <redacted>-2-aks

    - name: Create vnet peering to aks
      delegate_to: localhost
      azure.azcollection.azure_rm_virtualnetworkpeering:
        name: "{{ name_vnet_peering_aks }}"
        resource_group: "{{ name_rg }}"
        subscription_id: "{{ id_subscription }}"
        tenant: "{{ id_tenant }}"

        virtual_network: "{{ name_vnet }}"
        remote_virtual_network:
          subscription_id: "{{ id_subscription_aks }}"
          resource_group: "{{ name_vnet_peer_aks_netrg }}"
          name: "{{ name_vnet_peer_aks_netname }}"
```
I believe the issue is that the remote_virtual_network is in a different subscription, and the ansible library doesn't allow specifying that.

##### EXPECTED RESULTS
The peering to have been created

##### ACTUAL RESULTS
```
ASK [Create vnet peering to aks] **************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error creating Azure Virtual Network Peering: (InvalidGlobalResourceReference) Resource /subscriptions/7a648a44-<redacted>/resourceGroups/<redacted>-rg/providers/Microsoft.Network/virtualNetworks/<redacted>-aks-vnet referenced by resource /subscriptions/7a648a44-<redacted>/resourceGroups/<redacted>-2/providers/Microsoft.Network/virtualNetworks/<redacted>-2/virtualNetworkPeerings/<redacted>-2-aks was not found. Please make sure that the referenced resource exists.\nCode: InvalidGlobalResourceReference\nMessage: Resource /subscriptions/7a648a44-<redacted>/resourceGroups/<redacted>-rg/providers/Microsoft.Network/virtualNetworks/<redacted>-aks-vnet referenced by resource /subscriptions/7a648a44-<redacted>/resourceGroups/<redacted>-2/providers/Microsoft.Network/virtualNetworks/<redacted>-2/virtualNetworkPeerings/<redacted>-2-aks was not found. Please make sure that the referenced resource exists.."}
```

**Comment by Fred-sun** [comment]
@MikePeckOneValley I supported remote networks not under the same subscription in #1909. Could you give it a try? Thank you!

**Comment by MikePeckOneValley** [comment]
I'm sorry, but I don't know how to test the change.

Do I need to find the two files you changed and edit them locally?  (And then hope that ansible doesn't detect the mods and re-download the packaged versions?)

**Comment by MikePeckOneValley** [comment]
ok, I made edits to my local file, with the diff showing this:
```
% diff azure_rm_virtualnetworkpeering.py azure_rm_virtualnetworkpeering.py-orig
316c316
<                                                 vnet.get('subscription_id', self.subscription_id),
---
>                                                 self.subscription_id,
319c319
<                                                 vnet.get('resource_group', self.resource_group))
---
>                                                 vnet['resource_group'])
```

This worked with the following plays:
```
    - name: Create vnet peering to aks
      delegate_to: localhost
      azure.azcollection.azure_rm_virtualnetworkpeering:
        name: "{{ name_vnet_peering_aks }}"
        resource_group: "{{ name_rg }}"
        subscription_id: "{{ id_subscription }}"
        tenant: "{{ id_tenant }}"

        virtual_network: "{{ name_vnet }}"
        remote_virtual_network:
          subscription_id: "{{ id_subscription_aks }}"
          resource_group: "{{ name_vnet_peer_aks_netrg }}"
          name: "{{ name_vnet_peer_aks_netname }}"

    - name: Create vnet peering on aks side
      delegate_to: localhost
      azure.azcollection.azure_rm_virtualnetworkpeering:
        name: "{{ name_vnet_peering_aks }}"
        resource_group: "{{ name_vnet_peer_aks_netrg }}"
        subscription_id: "{{ id_subscription_aks }}"
        tenant: "{{ id_tenant }}"

        virtual_network: "{{ name_vnet_peer_aks_netname }}"
        remote_virtual_network:
          subscription_id: "{{ id_subscription }}"
          resource_group: "{{ name_rg }}"
          name: "{{ name_vnet }}"
```

I'm also pleased to see that vnet peerings with vnets in the same subscription work without having to add the subscription id for the remote vnet.
