### ISSUE TITLE
Cannot specify subscription for virtual network link in private dns zone

### ISSUE THREAD

**Issue by MikePeckOneValley** [ansible/ansible_collections_azure#1920]
##### SUMMARY

I'm trying to create a virtual network link in a private dns zone, where the target vnet is in a different  subscription.  Then portal allows me to specify a subscription in order to select the correct vnet.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure_rm_privatednszonelink

##### ANSIBLE VERSION
```
%  ansible --version
ansible [core 2.18.0]
  config file = /Users/mpeck/.ansible.cfg
  configured module search path = ['/Users/mpeck/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/homebrew/lib/python3.13/site-packages/ansible
  ansible collection location = /Users/mpeck/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/homebrew/bin/ansible
  python version = 3.13.2 (main, Feb  4 2025, 14:51:09) [Clang 15.0.0 (clang-1500.1.0.2.5)] (/opt/homebrew/opt/python@3.13/bin/python3.13)
  jinja version = 3.1.4
  libyaml = True
```

##### COLLECTION VERSION
```
% ansible-galaxy collection list
Using /Users/mpeck/.ansible.cfg as config file

# /Users/mpeck/.ansible/collections/ansible_collections
Collection         Version
------------------ -------
azure.azcollection 3.1.0
```

##### CONFIGURATION
```
% ansible-config dump --only-changed
Using /Users/mpeck/.ansible.cfg as config file
CONFIG_FILE() = /Users/mpeck/.ansible.cfg
DEFAULT_LOG_PATH(/Users/mpeck/.ansible.cfg) = /Users/mpeck/.ansible/log/ansible.log
DEFAULT_VERBOSITY(/Users/mpeck/.ansible.cfg) = 1

GALAXY_SERVERS:
```

##### OS / ENVIRONMENT
MacOS M1 chip Venture 13.6.6 (22G630)

##### STEPS TO REPRODUCE

Create a playbook as shown below, and run it.

Look at the docs found here: https://docs.ansible.com/ansible/latest/collections/azure/azcollection/azure_rm_privatednszonelink_module.html#ansible-collections-azure-azcollection-azure-rm-privatednszonelink-module

This fragment does not accept `subscription_id` as it should.  The documentation link above does not reflect it, the examples at the bottom do not, and I have tried it in an example, and the subscription is silently ignored.

Except the error message reflects the subscription of the net I'm adding the peering to:
```
TASK [Connect DNS] *****************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error creating or updating virtual network link BuildPool1-aks - (BadRequest) Virtual network resource not found for '/subscriptions/340f9fe4-<redacted>/resourceGroups/tsudev-rg-noderg/providers/Microsoft.Network/virtualNetworks/BuildPool1'\nCode: BadRequest\nMessage: Virtual network resource not found for '/subscriptions/340f9fe4-<redacted>/resourceGroups/tsudev-rg-noderg/providers/Microsoft.Network/virtualNetworks/BuildPool1'"}
```

The ansible play that caused this is:
```
  vars:
    id_subscription: 7a648a44-<redacted>
    id_subscription_aks: 340f9fe4-<redacted>
    name_dnslink: BuildPool1-aks
    name_dnslink_rg: tsudev-rg-noderg
    name_dnslink_zone: 33ef08d2-<redacted>.privatelink.northcentralus.azmk8s.io

    - name: Connect DNS
      azure.azcollection.azure_rm_privatednszonelink:
        name: "{{ name_dnslink }}"
        resource_group: "{{ name_dnslink_rg }}"
        subscription_id: "{{ id_subscription_aks }}"
        tenant: "{{ id_tenant }}"

        virtual_network: "{{ name_vnet }}"
        virtual_network_subscription: "{{ id_subscription }}"
        zone_name: "{{ name_dnslink_zone }}"
```
I believe the issue is that the virtual_network is in a different subscription, and the ansible library doesn't allow specifying that.

##### EXPECTED RESULTS
The link to have been created

##### ACTUAL RESULTS
```
TASK [Connect DNS] *****************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error creating or updating virtual network link BuildPool1-aks - (BadRequest) Virtual network resource not found for '/subscriptions/340f9fe4-<redacted>/resourceGroups/tsudev-rg-noderg/providers/Microsoft.Network/virtualNetworks/BuildPool1'\nCode: BadRequest\nMessage: Virtual network resource not found for '/subscriptions/340f9fe4-<redacted>/resourceGroups/tsudev-rg-noderg/providers/Microsoft.Network/virtualNetworks/BuildPool1'"}

```
