### ISSUE TITLE
cannot import 'SerializationError' from 'azure.core.exceptions'

### ISSUE THREAD

**Issue by RWintersVcare** [ansible/ansible_collections_azure#1945]
--> couldnt find, apologies if this is a duplicate

##### SUMMARY
Using azure.azcollection.azure_rm_densrecordset_info in an ansible task fails with the following error.
"The error was: cannot import name 'SerializationError' form 'azure.com.exceptions' (/usr/lib/python3/dist-packages/azure/core/exceptions.py)"
Ansible task msg: "Failed to import the required Python libarry (ansible[azure] (azure >= 2.0.0.)) on [Hostname]'s python /usr/bin/python3. 

I have done 'pip install -r requirements.txt --force' with collection's requirement.txt file. They are installed system globally, but this host only runs ansible playbooks and this hasn't been an issue yet.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure.azcollection.azure_rm_dnsrecordset_info
azure.azcollection.azure_rm_dnsrecordset

##### ANSIBLE VERSION

```
ansible [core 2.17.12]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.10/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.10.12 (main, Feb  4 2025, 14:57:36) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True
```

##### COLLECTION VERSION

```
# /root/.ansible/collections/ansible_collections
Collection         Version
------------------ -------
azure.azcollection 3.3.1 
```

##### CONFIGURATION

```paste below
ANSIBLE_FORCE_COLOR(/repo/AnsiblePlatformProduction/ansible.cfg) = True
ANSIBLE_NOCOWS(/repo/AnsiblePlatformProduction/ansible.cfg) = True
ANSIBLE_PIPELINING(/repo/AnsiblePlatformProduction/ansible.cfg) = True
CONFIG_FILE() = /repo/AnsiblePlatformProduction/ansible.cfg
DEFAULT_FORKS(/repo/AnsiblePlatformProduction/ansible.cfg) = 20
DEFAULT_GATHERING(/repo/AnsiblePlatformProduction/ansible.cfg) = smart
DEFAULT_ROLES_PATH(/repo/AnsiblePlatformProduction/ansible.cfg) = ['/root/.ansible/roles', '/usr/share/ansible/roles', '/etc/ansible/roles', '/repo/AnsiblePlatformProduction/roles']
DEFAULT_TIMEOUT(/repo/AnsiblePlatformProduction/ansible.cfg) = 60
INVENTORY_ENABLED(/repo/AnsiblePlatformProduction/ansible.cfg) = ['vcare.tools.group_intersection_list', 'netbox.netbox.nb_inventory', 'ini', 'yaml', 'community.docker.docker_containers']
PERSISTENT_COMMAND_TIMEOUT(/repo/AnsiblePlatformProduction/ansible.cfg) = 60
```

##### OS / ENVIRONMENT

Ansible controller runs on a VM running Ubuntu 22.04.5, kernel 5.15.0-130-generic and the ansible task is delegated to localhost.
The playbook is run throug a Rundeck Job, Rundeck V5.2.0 (though all other jobs go as it should be).

##### STEPS TO REPRODUCE

```yaml
    - name: Tasks when dns_provider is azure
      connection: local
      delegate_to: localhost
      become: false
      when: dns_provider == 'azure'
      block:
        - name: Get srv record entries for {{ ansible_hostname }}
          azure.azcollection.azure_rm_dnsrecordset_info:
            resource_group: "{{ azure_resource_group }}"
            relative_name: "{{ item.dns_relative_name }}"
            zone_name: "{{ dns_zone_name }}"
            client_id: "{{ azure_client_id }}"
            secret: "{{ azure_client_secret }}"
            tenant: "{{ azure_tenant_id }}"
            subscription_id: "{{ azure_subscription_id }}"
            record_type: SRV
          register: srv_records
          loop: "{{ srv_record_entries }}"
          loop_control:
            label: "{{ item.dns_relative_name }}"

        - name: Debug srv_records
          ansible.builtin.debug:
            var: srv_records
```

##### EXPECTED RESULTS

A correct debugging of the registered variable

##### ACTUAL RESULTS

I have Redacted a few fields as it involves publicly resolvable domain names
This is the output of the ansible task with -vvvv

```paste below
TASK [Get srv record entries for [[HOSTNAME REDACTED]] ] ******************************
task path: /repo/AnsiblePlatformProduction/playbooks/kamailio/update_kamailio_edge.yml:68
Using module file /var/lib/rundeck/.ansible/collections/ansible_collections/azure/azcollection/plugins/modules/azure_rm_dnsrecordset_info.py
Pipelining is enabled.
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: rundeck
<localhost> EXEC /bin/sh -c '/usr/bin/python3 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_azure.azcollection.azure_rm_dnsrecordset_info_payload_7d7jxfw7/ansible_azure.azcollection.azure_rm_dnsrecordset_info_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py", line 244, in <module>
    from azure.mgmt.network import NetworkManagementClient
  File "/usr/lib/python3/dist-packages/azure/mgmt/network/__init__.py", line 9, in <module>
    from ._network_management_client import NetworkManagementClient
  File "/usr/lib/python3/dist-packages/azure/mgmt/network/_network_management_client.py", line 17, in <module>
    from msrest import Deserializer, Serializer
  File "/usr/local/lib/python3.10/dist-packages/msrest/__init__.py", line 28, in <module>
    from .configuration import Configuration
  File "/usr/local/lib/python3.10/dist-packages/msrest/configuration.py", line 38, in <module>
    from .universal_http.requests import (
  File "/usr/local/lib/python3.10/dist-packages/msrest/universal_http/__init__.py", line 53, in <module>
    from ..exceptions import ClientRequestError, raise_with_traceback
  File "/usr/local/lib/python3.10/dist-packages/msrest/exceptions.py", line 31, in <module>
    from azure.core.exceptions import SerializationError, DeserializationError
ImportError: cannot import name 'SerializationError' from 'azure.core.exceptions' (/usr/lib/python3/dist-packages/azure/core/exceptions.py)
failed: [ [[HOSTNAME]] -> localhost] (item=_sip.[[REDACTED]] ) => 
    ansible_loop_var: item
    changed: false
    invocation:
        module_args:
            ad_user: null
            adfs_authority_url: null
            api_profile: latest
            append_tags: true
            auth_source: auto
            cert_validation_mode: null
            client_id: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
            cloud_environment: AzureCloud
            disable_instance_discovery: false
            log_mode: null
            log_path: null
            password: null
            profile: null
            record_type: SRV
            relative_name: _sip.[[REDACTED]]
            resource_group: [[REDACTED]]
            secret: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
            subscription_id: [[REDACTED]]
            tags: null
            tenant: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
            thumbprint: null
            top: null
            x509_certificate_path: null
            zone_name: [[REDACTED]]
    item:
        dns_relative_name: _sip.[[REDACTED]]
        srv_entry_port: [[REDACTED]]
    msg: Failed to import the required Python library (ansible[azure] (azure >= 2.0.0))
        on VC-AMS-RUNDECK01's Python /usr/bin/python3. Please read the module documentation
        and install it in the appropriate location. If the required library is installed,
        but Ansible is using the wrong Python interpreter, please consult the documentation
        on ansible_python_interpreter
```

Hopefully someone can help with this?
