### ISSUE TITLE
azure_rm_resource_info Fails to Handle HEAD Responses Without JSON Body

### ISSUE THREAD

**Issue by Brunoquindeler** [ansible/ansible_collections_azure#1946]
#### Summary:
The **azure_rm_resource_info** module fails with the error "**Failed to parse response: Expecting value: line 1 column 1 (char 0)**" when performing a **HEAD** request, as it attempts to parse an empty response body as JSON. This issue is similar to the one fixed for the **azure_rm_resource** module in PR #1341, but the fix was not applied to **azure_rm_resource_info**.

####  Issue Type:
Bug Report

####  Component Name:
**azure_rm_resource_info**

####  Collection Version:
**azure.azcollection 3.3.1**

####  Environment:

Operating System: [Oracle 8]
Python Version: [ Python 3.12]
Cloud Environment: Azure Public Cloud

####  Steps to Reproduce:

Run the following Ansible task to check the existence of an Azure Cosmos DB account name using the **HEAD** method:

```yaml 
- name: Check if Cosmos DB account exists
  azure.azcollection.azure_rm_resource_info:
    method: HEAD
    provider: DocumentDB
    resource_type: databaseAccountNames
    resource_name: "{{ account_name }}"
    api_version: "2025-04-15"
  register: check_account_exist_result
```
```bash
The task fails with the error:FAILED! => {"changed": false, "msg": "Failed to parse response: Expecting value: line 1 column 1 (char 0)"}
```

https://learn.microsoft.com/en-us/rest/api/cosmos-db-resource-provider/database-accounts/check-name-exists?view=rest-cosmos-db-resource-provider-2025-04-15&tabs=HTTP

```textplan
HEAD https://management.azure.com/providers/Microsoft.DocumentDB/databaseAccountNames/{accountName}?api-version=2025-04-15
```

####  Expected Behavior

The **azure_rm_resource_info** module should handle **HEAD** responses (which contain no body) without attempting to parse the response as JSON.

####  Actual Behavior

The module fails with the error "Failed to parse response: Expecting value: line 1 column 1 (char 0)" because it tries to parse the empty response body as JSON.

####  Additional Context

This issue is similar to the one addressed in PR #1341 for the azure_rm_resource module ([link to PR](https://github.com/ansible-collections/azure/pull/1341)), which fixed handling of non-JSON responses.
The azure_rm_resource_info module appears to lack the same fix, causing it to fail when processing HEAD responses from the Azure API (e.g., https://management.azure.com/providers/Microsoft.DocumentDB/databaseAccountNames/{account_name}?api-version=2025-04-15).

####  Labels

bug
azure
module
azure_rm_resource_info
