### ISSUE TITLE
Add support for Resolution Policy on Private DNS Zone vNet Link

### ISSUE THREAD

**Issue by hctagalong** [ansible/ansible_collections_azure#1961]
##### SUMMARY

Add support for setting resolution_policy on private dns zone vent link within the `azure.azcollection.azure_rm_privatednszonelink` module. Microsoft documentation for this feature is [found here](https://learn.microsoft.com/en-us/azure/dns/private-dns-fallback).

Supported values are: `Default` or `NxDomainRedirect`

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

azure.azcollection.azure_rm_privatednszonelink

##### ADDITIONAL INFORMATION

Used to enable/disable the "Fallback to Internet" flag for a Private DNS zone vNet link.

```yaml
- name: Create a virtual network link
  azure_rm_privatednszonelink:
    resource_group: myResourceGroup
    name: vnetlink1
    zone_name: privatezone.com
    virtual_network: MyAzureVNet
    resolution_policy: NxDomainRedirect <----- Requested new feature
    state: present
```

**Comment by Fred-sun** [comment]
Added in #1962

**Comment by Fred-sun** [comment]
@hctagalong I have added this parameters. Could you give it a try? Thank you!

**Comment by hctagalong** [comment]
@Fred-sun It's possible that I'm doing something incorrectly, however, it doesn't appear that when I try to change the `resolution_policy` for an existing vNet link that the state shows as "changed" (when running in check mode). Examples:

### Ansible Task
``` 
    - name: Create vNet links for PrivateLink DNS Zones
      delegate_to: localhost
      azure.azcollection.azure_rm_privatednszonelink:
        name: "{{ virtual_network_link_name }}"
        virtual_network: "/subscriptions/{{ subscription_id }}/resourceGroups/{{ virtual_network_link_vnet_rg }}/providers/Microsoft.Network/virtualNetworks/{{ virtual_network_link_vnet }}"
        zone_name: "{{ item.zone_name }}"
        resolution_policy: "{{ item.zone_resolution_policy | default('Default') }}"
        subscription_id: "{{ subscription_id }}"
        resource_group: "{{ privatelink_dns_zone_resource_group.name }}"
      loop: "{{ dns_zones }}"
```

### Sample Output

_Observe tha tthe item changed status is `false`_

```
ok: [vm-xxxxxx.com -> localhost] => (item={'zone_name': 'privatelink.web.core.windows.net', 'zone_resolution_policy': 'NxDomainRedirect'}) => {"ansible_loop_var": "item", "changed": false, "item": {"zone_name": "privatelink.web.core.windows.net", "zone_resolution_policy": "NxDomainRedirect"}, "state": {"etag": "\"<redacted>\"", "id": "/subscriptions/xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/rg-ncus-xxx-xxxxxxx/providers/Microsoft.Network/privateDnsZones/privatelink.web.core.windows.net/virtualNetworkLinks/dnsvnetlink-az-xxx-xxxx-1", "location": "global", "name": "dnsvnetlink-az-xxx-xxxx-1", "provisioning_state": "Succeeded", "registration_enabled": false, "tags": {"createdDate": "2023-01-13T16:53:54.3563844Z"}, "type": "Microsoft.Network/privateDnsZones/virtualNetworkLinks", "virtual_network": {"id": "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/rg-xxx-xxxx-xxx/providers/Microsoft.Network/virtualNetworks/vnet1-xxx-xxxx"}, "virtual_network_link_state": "Completed"}}
```

I would have thought that when I change the `zone_resolution_policy` that would have gotten a a `"changed": true`. But again, this could be a testing fault on my side (I had trouble getting the updated code to work).

**Comment by Fred-sun** [comment]
@hctagalong I have update it! Would you retry it! Thanks!

**Comment by Fred-sun** [comment]
Any feedback for this?

**Comment by hctagalong** [comment]
> Any feedback for this?

I'll take a look this morning.

**Comment by hctagalong** [comment]
@Fred-sun Here is what I've observed:

From `az cli`:
1. If the private-dns vNet link has never had the resolution policy set, showing the link details `resolutionPolicy` is not returned. Not anything to do with your code, just a behavior that I noticed.
2. Once the link has been set, now the `resolutionPolicy` will be returned with whatever value is appropriate for the current state.

The above was tested with: `az network private-dns link vnet show --subscription <subscription_name> --resource-group <resource_group_name> --zone-name <private_dns_zone_name> --name <zone_link_name>`

With your changes, when my playbook task sets the `resolution_policy` to either value, a state change is always signaled regardless if it matches the current state or not. Here's an example:

_partial vars:_
```yaml 
- zone_name: "privatelink.zone.name.a.com"
  zone_resolution_policy: "Default" <--- Current state IS the default
- zone_name: "privatelink.zone.name.b.com"
```

_task:_
```yaml
- name: Create vNet links for PrivateLink DNS Zones
      delegate_to: localhost
      azure.azcollection.azure_rm_privatednszonelink:
        name: "{{ virtual_network_link_name }}"
        virtual_network: "/subscriptions/{{ subscription_id }}/resourceGroups/{{ virtual_network_link_vnet_rg }}/providers/Microsoft.Network/virtualNetworks/{{ virtual_network_link_vnet }}"
        zone_name: "{{ item.zone_name }}"
        resolution_policy: "{{ item.zone_resolution_policy | default('Default') }}"
        subscription_id: "{{ subscription_id }}"
        resource_group: "{{ privatelink_dns_zone_resource_group.name }}"
      loop: "{{ dns_zones }}"
```

Not sure if there is anything that can be done about this behavior since the az cli appears to be inconsistent with what is returned.
