### ISSUE TITLE
`azure_rm_azurefirewall` does not accept FQDNs as destinations in network rules

### ISSUE THREAD

**Issue by lodex2** [ansible/ansible_collections_azure#1990]
##### SUMMARY

Besides IP addresses and Service Tags, Azure Firewall accepts FQDNs as destinations in network rules. The corresponding Ansible module, however, does not.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`azure_rm_azurefirewall` module

##### ANSIBLE VERSION

```paste below
ansible [core 2.16.3]
  config file = /Users/mholz/ops/deploy/ansible/ansible.cfg
  configured module search path = ['/Users/mholz/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/mholz/.pyenv/versions/3.11.7/envs/ansible/lib/python3.11/site-packages/ansible
  ansible collection location = /Users/mholz/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/mholz/.pyenv/versions/ansible/bin/ansible
  python version = 3.11.7 (main, Nov  5 2024, 10:29:31) [Clang 16.0.0 (clang-1600.0.26.4)] (/Users/mholz/.pyenv/versions/3.11.7/envs/ansible/bin/python)
  jinja version = 3.1.4
  libyaml = True
```

##### COLLECTION VERSION

```paste below
Collection         Version
------------------ -------
azure.azcollection 3.5.0
```

##### CONFIGURATION

```paste below
CACHE_PLUGIN(/Users/mholz/ops/deploy/ansible/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/Users/mholz/ops/deploy/ansible/ansible.cfg) = .ansible_facts_cache_dir/
CACHE_PLUGIN_TIMEOUT(/Users/mholz/ops/deploy/ansible/ansible.cfg) = 3600
CONFIG_FILE() = /Users/mholz/ops/deploy/ansible/ansible.cfg
DEFAULT_GATHERING(/Users/mholz/ops/deploy/ansible/ansible.cfg) = smart
DEFAULT_MANAGED_STR(/Users/mholz/ops/deploy/ansible/ansible.cfg) = Ansible managed: {file} modified on %Y-%m-%d %H:%M:%S by {uid} on {host}
DEFAULT_ROLES_PATH(/Users/mholz/ops/deploy/ansible/ansible.cfg) = ['/Users/mholz/ops/deploy/ansible/roles']
DEFAULT_VAULT_PASSWORD_FILE(/Users/mholz/ops/deploy/ansible/ansible.cfg) = /Users/mholz/ops/deploy/ansible/open-vault.sh
DISPLAY_SKIPPED_HOSTS(/Users/mholz/ops/deploy/ansible/ansible.cfg) = False
EDITOR(env: EDITOR) = nvim
HOST_KEY_CHECKING(/Users/mholz/ops/deploy/ansible/ansible.cfg) = False
INVENTORY_ENABLED(/Users/mholz/ops/deploy/ansible/ansible.cfg) = ['auto', 'yaml']
PAGER(env: PAGER) = less
TRANSFORM_INVALID_GROUP_CHARS(/Users/mholz/ops/deploy/ansible/ansible.cfg) = silently
```

##### STEPS TO REPRODUCE

Create a network rule with a FQDN in `destination_addresses`.

```yaml
- name: Create Azure Firewall
  azure_rm_azurefirewall:
    resource_group: myResourceGroup
    name: myAzureFirewall
    tags:
      key1: value
    network_rule_collections:
      - priority: 112
        action: deny
        rules:
          - name: L4-traffic
            description: Block traffic based on source IPs and ports
            protocols:
              - tcp
            source_addresses:
              - 192.168.1.1-192.168.1.12
              - 10.1.4.12-10.1.4.255
            destination_addresses:
              - www.example.com
            destination_ports:
              - 443-444
              - '8443'
        name: netrulecoll
    ip_configurations:
      - subnet: >-
          /subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/myResourceGroup
          /providers/Microsoft.Network/virtualNetworks/myVirtualNetwork
          /subnets/AzureFirewallSubnet
        public_ip_address: >-
          /subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/myResourceGroup
          /providers/Microsoft.Network/publicIPAddresses/
          myPublicIpAddress
        name: azureFirewallIpConfiguration
```

##### EXPECTED RESULTS

A new network rules is created.

##### ACTUAL RESULTS

Creation of the network rule fails.

```paste below
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error creating the AzureFirewall instance: ('{\"error\":{\"code\":\"AzureFirewallRuleInvalidIpAddressOrRangeFormat\",\"message\":\"AzureFirewallRule L4-traffic: Invalid IP address value or range or Service Tag www.example.com.\",\"details\":[]}}', 400)"}
```
