### ISSUE TITLE
Recovery Services Vault

### ISSUE THREAD

**Issue by paultaiton** [ansible/ansible_collections_azure#210]
##### SUMMARY

There is currently no module for Azure Recovery Services Vault.
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

azure_rm_recoveryservicesvault
azure_rm_recoveryservicesvault_info

##### ADDITIONAL INFORMATION

The 2 modules (regular mutable and _info,) would be used to create, update, and lookup recovery services vaults in Azure.

```yaml
azure_rm_recoveryservicesvault:
  name: pauls-recovery-vault
  location: westus
  sku:
    name: Standard
  resource_group: target-resource-group
  subscription_id: 00000000-0000-0000-0000-000000000000

azure_rm_recoveryservicesvault_info:
  resource_group: target-resource-group
  subscription_id: 00000000-0000-0000-0000-000000000000

```

I am planning on writing the modules myself, but wanted to post an Issue ahead of time to solicit feedback and comments, and to make sure no one else is already working on it.
