### ISSUE TITLE
azure_rm_mariadbserver - add support for version 10.3

### ISSUE THREAD

**Issue by mikkolaakko** [ansible/ansible_collections_azure#242]
##### SUMMARY

Add support for Azure Database for MariaDB version 10.3

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

azure_rm_mariadbserver

##### ADDITIONAL INFORMATION

My application requires MariaDB version 10.3. Version 10.2 and 10.3 are available on Azure but I cannot create 10.3 using Ansible.

```yaml
- name: Create Azure Database for MariaDB
  azure_rm_mariadbserver:
    resource_group: "{{ resource_group }}"
    name: "{{ mariadb_name }}"
    sku:
      name: GP_Gen5_4
      tier: GeneralPurpose
    location: "{{ location }}"
    version: "10.3"
    admin_username: "{{ mariadb_admin_username }}"
    admin_password: "{{ mariadb_admin_password }}"
```
