### ISSUE TITLE
azure_rm_dnsrecordset limits txt records to 256 chars

### ISSUE THREAD

**Issue by eddiezab** [ansible/ansible_collections_azure#275]
##### SUMMARY

azure_rm_dnsrecordset limits txt records to less that 256 characters. To automate DKIM records, you need to reduce the recommended bit length from 1024.
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

azure_rm_dnsrecordset
##### ANSIBLE VERSION

```ansible 2.9.13
  config file = None
  configured module search path = ['/home/rt-op/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/rt-op/virtualenv/azure/lib/python3.7/site-packages/ansible
  executable location = /home/rt-op/virtualenv/azure/bin/ansible
  python version = 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]
```

##### CONFIGURATION

```<empty>
```

##### OS / ENVIRONMENT

No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

##### STEPS TO REPRODUCE

azure_rm_dnsrecordset:
    resource_group: Redirectors
    relative_name: mail._domainkey
    zone_name: "<zone name>"
    record_type: TXT
    records:
    - entry: "<any record greater than 256 characters in length.>"

```yaml
azure_rm_dnsrecordset:
    resource_group: Redirectors
    relative_name: mail._domainkey
    zone_name: "<zone name>"
    record_type: TXT
    records:
    - entry: "<any record greater than 256 characters in length.>"
```

##### EXPECTED RESULTS

A TXT record is created with the specified contents. 

##### ACTUAL RESULTS

```
fatal: [tst-edge]: FAILED! => {"changed": false, "msg": "Error creating or updating dns record mail._domainkey - Operation failed with status: 'Bad Request'. Details: The value 'v=DKIM1; h=sha256; k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAooJxVNHBOKdyq0CfIr4WJPDFirXp+QGwh/9tkvICPGjMmgRO/Kpgf9Rr06RSZyEbLLd4nDINoQWlainx0Fci4X9hSLeenuL6jkYh39FUOGo3ja6gofHkwdLVhlP9iAjQxyf0Yw1AGrSj5VZcpzzlCqyqzTAiPxBly4U4A3FhAiJbhkpz3LCiiiii' for the TXT record is not valid."}
```
