### ISSUE TITLE
Add computer_name to the list of host variables for azure_rm plugin

### ISSUE THREAD

**Issue by PavelPikat** [ansible/ansible_collections_azure#279]
##### SUMMARY
Make Windows computer name available as host variable for azure_rm plugin, so it can be used to override `ansible_host`

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

azure_rm inventory plugin

##### ADDITIONAL INFORMATION

My use cases revolves around Domain joined Azure Windows VMs without public IPs. I have Ansible controller within my domain and I use Kerberos authentication. My VM name and computer name are different, so I can't use built-in `name` host variable offered by azure_rm plugin. It works by hard-coding computer name, but ideally I would like to have `computer_name` provided by the inventory plugin similar to `name` and other host variables.

```yaml
plugin: azure_rm
auth_source: credential_file
profile: development
plain_host_names: false
include_vm_resource_groups:
  - <my-rg>
keyed_groups:
  - prefix: tag
    key: tags
hostvar_expressions:
  ansible_user: "'user@DOMAIN.LOCAL'"
  ansible_password: "'pw'"
  ansible_connection: "'winrm'"
  ansible_winrm_transport: "'kerberos'"
  ansible_winrm_server_cert_validation: "'ignore'"
  ansible_host: "computer_name + '.DOMAIN.LOCAL'"
```
