### ISSUE TITLE
VMSS Extension - Parameter type is Invalid

### ISSUE THREAD

**Issue by el-memer** [ansible/ansible_collections_azure#281]
##### SUMMARY
VMSS Extension module not working for **ApplicationHealthLinux** type.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
**azure_rm_virtualmachinescalesetextension**

##### ANSIBLE VERSION

```
ansible 2.10.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/el_memer/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/el_memer/.pyenv/versions/3.6.0/lib/python3.6/site-packages/ansible
  executable location = /home/el_memer/.pyenv/versions/3.6.0/bin/ansible
  python version = 3.6.0 (default, Sep 25 2020, 10:00:05) [GCC 9.3.0]

```

##### CONFIGURATION

```paste below
TRANSFORM_INVALID_GROUP_CHARS(/etc/ansible/ansible.cfg) = never
```

##### STEPS TO REPRODUCE

- Create a Linux VMSS 

- Add an ApplicationHealthLinux extension

```yaml
    - name: Install VMSS Extension
      azure_rm_virtualmachinescalesetextension:
        name: ApplicationHealthLinux
        location: "{{ location }}"
        resource_group: "{{ resourcegroup }}"
        vmss_name: "{{ vmss_name }}"
        publisher: Microsoft.ManagedServices
        type: ApplicationHealthLinux
        type_handler_version: 1.0
        settings: '{      
          "protocol": "tcp",
          "port": 3310 }'
        auto_upgrade_minor_version: false
```

##### EXPECTED RESULTS

Extension created 

##### ACTUAL RESULTS

Modules output error below

```paste below
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "ad_user": null,
            "adfs_authority_url": null,
            "api_profile": "latest",
            "auth_source": "auto",
            "auto_upgrade_minor_version": false,
            "cert_validation_mode": null,
            "client_id": null,
            "cloud_environment": "AzureCloud",
            "location": "westeurope",
            "name": "ApplicationHealthLinux",
            "password": null,
            "profile": null,
            "protected_settings": null,
            "publisher": "Microsoft.ManagedServices",
            "resource_group": <resource-group>,
            "secret": null,
            "settings": {
                "port": 3310,
                "protocol": "tcp"
            },
            "state": "present",
            "subscription_id": null,
            "tenant": null,
            "type": "ApplicationHealthLinux",
            "type_handler_version": "1.0",
            "vmss_name": <VMSS_name>
        }
    },
    "msg": "Error creating the VMSS extension: Azure Error: InvalidParameter\nMessage: The value of parameter type is invalid.\nTarget: type"
}

```
