### ISSUE TITLE
[Feature Idea] azure_rm_aks - Add Availability Zones Option of Agent Pool Profile

### ISSUE THREAD

**Issue by MarcGi** [ansible/ansible_collections_azure#289]
##### SUMMARY
Currently, when creating a default agent pool via the azure_rm_aks module, there is no option to specify the availability zones for the ScaleSet to deploy across, this is currently available via Az Cli and could be a feature brought to the azure_rm_aks module.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
azure_rm_aks

##### ADDITIONAL INFORMATION
Az Cli Documentation:
https://docs.microsoft.com/en-us/azure/aks/availability-zones

Possible implementation:
```yaml
    agent_pool_profiles:
      - name: default
        count: 3
        enable_auto_scaling: True
        max_count: 10
        min_count: 3
        type: VirtualMachineScaleSets
        availability_zones:
         - 1
         - 2
         - 3
        vm_size: Standard_DS2_v2
```
