### ISSUE TITLE
azure_rm_virtualmachinescaleset_info returns empty array

### ISSUE THREAD

**Issue by david-freistrom** [ansible/ansible_collections_azure#293]
##### SUMMARY
The module azure_rm_virtualmachinescaleset_info return an empty list all the time
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure_rm_virtualmachinescaleset_info

##### ANSIBLE VERSION
```paste below
ansible 2.10.1
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.6 (default, Sep 24 2020, 21:54:23) [GCC 8.3.0]
```

##### CONFIGURATION
```paste below

```

##### OS / ENVIRONMENT
PYTHON_VERSION=3.8.6
AZURE_TENANT=XXX
ANSIBLE_BECOME_PASS=SECRET
PWD=/project
HOME=/root
LANG=C.UTF-8
AZURE_SUBSCRIPTION_ID=XXX
ANSIBLE_SSH_PASS=SECRET
AZURE_CLIENT_ID=XXX
PYTHON_PIP_VERSION=20.2.3
PYTHON_GET_PIP_SHA256=6e0bb0a2c2533361d7f297ed547237caf1b7507f197835974c0dd7eba998c53c
AZURE_SECRET=XXX
PYTHON_GET_PIP_URL=https://github.com/pypa/get-pip/raw/fa7dc83944936bf09a0e4cb5d5ec852c0d256599/get-pip.py
PATH=/usr/local/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ANSIBLE_VAULT_PASSWORD=SECRET

##### STEPS TO REPRODUCE
```yaml
 - name: Get facts about created virtual machine scale set
      azure_rm_virtualmachinescaleset_info:
        resource_group: aksnodepool
      register: ret

    - name: Debug
      debug:
        msg: "{{ ret }}"
```

##### EXPECTED RESULTS
List of all VMSS in the given resource group

##### ACTUAL RESULTS
TASK [aks : Get facts about created virtual machine scale set] ok: [localhost]

TASK [aks : Debug] 
ok: [localhost] => {
    "msg": {
        "changed": false,
        "failed": false,
        "vmss": []
    }
}

```paste below
ansible-playbook -i inventories/testing/hosts.yml --tags cloud --ask-vault-pass site.yml
```

**Comment by Fred-sun** [comment]
@david-freistrom Thank you for reporting this issue! I repeated the test locally and there is no problem. Can you recreate the resource and try it? In addition, make sure your resource group has vmss, thank you!
```e.g.
TASK [get resource info] ********************************************************************************************************************************************************
ok: [localhost]

TASK [debug] ********************************************************************************************************************************************************************
ok: [localhost] => {
    "output.vmss | length": "2"
}

**Comment by david-freistrom** [comment]
@Fred-sun I deleted all the ressources and recreated it via Ansible. By the way, I use the same Taskbook for creating AKS and print out the created resources at a time.

**Comment by david-freistrom** [comment]
@Fred-sun Thanks for response. I deleted all the ressources and recreated it via Ansible. By the way, I use the same Taskbook to create AKS and print out the created resources via Debug.

**Comment by david-freistrom** [comment]
@Fred-sun Thanks for response. I deleted all the ressources and recreated it via Ansible. By the way, I use the same Taskbook to create AKS as well as print out all the created resources at a time. So it is definitely created and it use the same Target.

Nothing changed here. Do not be confused because of the AKS module output printed here. I cut it out.

```yaml
- name: Create a resource group for AKS
  azure_rm_resourcegroup:
    name: "{{ resource_group }}"
    location: "{{ location }}"
    tags:
      environment: testing

- name: Create a managed Azure Container Services (AKS) instance
  azure.azcollection.azure_rm_aks:
    state: present
    client_id: "{{ lookup('env', 'AZURE_CLIENT_ID') }}"
    secret: "{{ lookup('env', 'AZURE_SECRET') }}"
    tenant: "{{ lookup('env', 'AZURE_TENANT') }}"
    subscription_id: "{{ lookup('env', 'AZURE_SUBSCRIPTION_ID') }}"
    name: "{{ aks_name }}"
    location: "{{ location }}"
    resource_group: "{{ resource_group }}"
    node_resource_group: "{{ node_resource_group }}"
    dns_prefix: "{{ dns_prefix }}"
    kubernetes_version: "{{ aks_version }}"
    # addon:
    #   http_application_routing:
    #     enabled: "{{ addons.http_application_routing.enabled }}"
    network_profile:
      service_cidr: "{{ network.service_cidr }}"
      dns_service_ip: "{{ network.dns_service_ip }}"
      docker_bridge_cidr: "{{ network.docker_bridge_cidr }}"
      pod_cidr: "{{ network.pod_cidr }}"
      network_plugin: "{{ network.network_plugin }}"
      network_policy: "{{ network.network_policy }}"
    linux_profile:
      admin_username: "{{ admin_username }}"
      ssh_key: "{{ ssh_key }}"
    service_principal:
      client_id: "{{ service_principal.client_id }}"
      client_secret: "{{ service_principal.client_secret }}"
    agent_pool_profiles:
      - name: "{{ agent_pool_profiles[0].name }}"
        count: "{{ agent_pool_profiles[0].count }}"
        min_count: "{{ agent_pool_profiles[0].min_count }}"
        max_count: "{{ agent_pool_profiles[0].max_count }}"
        enable_auto_scaling: "{{ agent_pool_profiles[0].enable_auto_scaling }}"
        vm_size: "{{ agent_pool_profiles[0].vm_size }}"
        vnet_subnet_id: "{{ hostvars.localhost['AKSSubnet'] }}"
        type: "{{ agent_pool_profiles[0].type }}"
    enable_rbac: "{{ rbac }}"
    tags:
      environment: testing
  register: ret

- name: Facts about created AKS
  block:
    - name: Set Facts about created AKS itself
      set_fact:
        aks: "{{ ret }}"

    - name: "AKS Cluster: {{ ret.name }}"
      debug:
        msg: "{{ aks }}"

    - name: Get facts about created virtual machine scale set
      azure_rm_virtualmachinescaleset_info:
        resource_group: "{{ node_resource_group }}"
        client_id: "{{ lookup('env', 'AZURE_CLIENT_ID') }}"
        secret: "{{ lookup('env', 'AZURE_SECRET') }}"
        tenant: "{{ lookup('env', 'AZURE_TENANT') }}"
        subscription_id: "{{ lookup('env', 'AZURE_SUBSCRIPTION_ID') }}"
      register: ret

    - name: Debug
      debug:
        msg: "{{ ret }}"

    - name: Set Facts about created virtual machine scale set
      set_fact:
        aks_vmss: "{{ ret.vmss[0] }}"

    - name:
      debug:
        msg: "{{ aks_vmss }}"
```

```
TASK [aks : Create a resource group for AKS] *************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [aks : Create a managed Azure Container Services (AKS) instance] ************************************************************************************************************************************************************************
[WARNING]: Azure API profile latest does not define an entry for ContainerServiceClient
ok: [localhost]

TASK [aks : Set Facts about created AKS itself] **********************************************************************************************************************************************************************************************
ok: [localhost]

TASK [aks : AKS Cluster: testingAKS] *********************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": {
       "failed": false,
        "warnings": [
            "Azure API profile latest does not define an entry for ContainerServiceClient",
            "Azure API profile latest does not define an entry for ContainerServiceClient"
        ]
    }
}

TASK [aks : Get facts about created virtual machine scale set] *******************************************************************************************************************************************************************************
ok: [localhost]

TASK [aks : Debug] ***************************************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": {
        "changed": false,
        "failed": false,
        "vmss": []
    }
}
```

**Comment by david-freistrom** [comment]
I tried also to change the resource group to the one of the AKS itself instead to use the one for the nodes. But without other results.
Is there an issue maybe with the location? I cannot define a location for this module but for the AKS module it is set up? And it is maybe not matching a default location which is used by the info module for vmss. All rsources except the AKS cluster itself are created in the node resource group.

**Comment by Fred-sun** [comment]
@david-freistrom Did I get it wrong? Your title is azure_rm_virtualmachinescaleset_info module cannot find all VMSS resources under the resource group. But your PlayBook looks for azure_rm_routable resources again. Can you describe your purpose in detail? Thank you very much!

**Comment by david-freistrom** [comment]
Just ignore the route table tasks.  They are not processed because of the issue before. I deleted the tasks from my post so you will not longer be confused.

I tried it also with exported default location without result.

export AZURE_DEFAULTS_LOCATION=westeurope

**Comment by Fred-sun** [comment]
@david-freistrom Can you try it like this, after creating it, get the VMSS information one hour later（I couldn’t get it right after I created it, but I got it after a while）, thank you！

**Comment by david-freistrom** [comment]
@Fred-sun I tried it out but without result. Even so, a one hour waiting time is unacceptable for a automation pipeline to continue processing. I never would query for the created resources if 

1) The AKS module would not be a monolithic structured module which creates other resources, which is by the way a bad software design. Better implement atomar and idependent modules and configure mandatory ressources by a reference id of a seperate module create that resource.

OR

2) If the AKS Module return all created resource info and let the engineer configure all the subcomponents for the AKS module.

I also think that only a node pool is required for an AKS in the first moment. There are already single modules for routing tables and security groups as well as vmss. 

I found out, that it's only the vmss info module which has that isue. If I ignore the empty list of vmss and let my taskbook continue process the info modules for route table and security group which is also created by the aks module, they work as expected.

**Comment by Fred-sun** [comment]
@david-freistrom Yes, I am now to prove that the VMSS_info module can obtain VMSS information. Why can't it be obtained immediately after creation? I will continue to track the reason. Thank you!

**Comment by david-freistrom** [comment]
@Fred-sun I found the issue.
Its not in the ansible module itself. It was a missing Permission in the Role I use for deployments. There was no permissions for VirtualMaschieneScaleSets at all. The missing Permission was "Microsoft.Compute/virtualMachineScaleSets/virtualMachines/read". I am confused why no permissions for scale Sets are need to create it. Or it is need but the seperate defined service principle which is used by AKS itself creates it.

By the way. If you want to create a resource with a missing permission, it will run into an error showing you exactly which permission is need. Would be nice to see the same behavior for read permissions.

I will check now again if it can obtain it immediately.

**Comment by david-freistrom** [comment]
@Fred-sun Confirmed. there is a delay. But it's not one hour. It's just 5 second. Workaround is a wait_for task

```yaml
- name: Sleep for 5 seconds and continue with play
  wait_for:
    timeout: 5
```
