### ISSUE TITLE
Wrong return value documentation for azure.azcollection.azure_rm_loadbalancer_info

### ISSUE THREAD

**Issue by david-freistrom** [ansible/ansible_collections_azure#299]
##### SUMMARY
The module azure.azcollection.azure_rm_loadbalancer_info returns the azure_loadbalancer only in a subfield named ansible_info which is not documented in the official documentation. The oficial documentation did not clearify exactly what info are returned.

https://docs.ansible.com/ansible/latest/collections/azure/azcollection/azure_rm_loadbalancer_info_module.html. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure.azcollection.azure_rm_loadbalancer_info
https://docs.ansible.com/ansible/latest/collections/azure/azcollection/azure_rm_loadbalancer_info_module.html.

##### ANSIBLE VERSION
```paste below
ansible 2.10.1
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.6 (default, Sep 24 2020, 21:54:23) [GCC 8.3.0]
```

##### CONFIGURATION
```paste below
```

##### OS / ENVIRONMENT
PYTHON_VERSION=3.8.6
AZURE_TENANT=XXX
ANSIBLE_BECOME_PASS=SECRET
LANG=C.UTF-8
AZURE_SUBSCRIPTION_ID=XXX
AZURE_DEFAULTS_LOCATION=westeurope
AZURE_CLIENT_ID=XXX
PYTHON_PIP_VERSION=20.2.3
PYTHON_GET_PIP_SHA256=6e0bb0a2c2533361d7f297ed547237caf1b7507f197835974c0dd7eba998c53c
AZURE_SECRET=XXX
PYTHON_GET_PIP_URL=https://github.com/pypa/get-pip/raw/fa7dc83944936bf09a0e4cb5d5ec852c0d256599/get-pip.py
PATH=/usr/local/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

Linux b8b1041ff1cf 5.8.13-200.fc32.x86_64 #1 SMP Thu Oct 1 21:49:42 UTC 2020 x86_64 GNU/Linux

##### STEPS TO REPRODUCE

```yaml
- name: Get facts about created loadbalancer
      azure.azcollection.azure_rm_loadbalancer_info:
        resource_group: "{{ node_resource_group }}"
      register: lb

- name: Set Facts about created loadbalancer
  set_fact:
      aks_lb: "{{ lb.ansible_info.azure_loadbalancers[0] }}"
```

##### EXPECTED RESULTS
I expected a complete output documentation and a return value not under a field name "ansible_info".

##### ACTUAL RESULTS
Not documented Output of that module.
LoadBalancer Object is defined under a field "ansible_info"

```paste below
TASK [aks : Debug LB] ************************************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": {
        "ansible_info": {
            "azure_loadbalancers": [...]
        }
    }
}
```
