### ISSUE TITLE
Support for private networks in azure_rm_containerinstance

### ISSUE THREAD

**Issue by Christoph-Majcen** [ansible/ansible_collections_azure#300]
##### SUMMARY

At this time the module azure_rm_containerinstance provides support for public and no ip address. However, for containers connected to a virtual network there seem to be no support.

It should be possible to provide a 'private' network type. In which case it is mandatory to provide the name of a virtual network and the name of a subnet in that particular network.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

azure_rm_containerinstance

##### ADDITIONAL INFORMATION

A possible example would be

```yaml
azure_rm_containerinstance:
  ...
  ip_address: private
  virtual_network: virt_net_0
  subnet: subnet128
  ...
```
Which would be the command line equivalent:
```sh
az container create ... --ip-address "Private" --vnet "virt_net_0" --subnet "subnet128" ...
```

Original issue by JG127 (https://github.com/ansible/ansible/issues/71594)
