### ISSUE TITLE
Support specifying --max-pods for node pools in azure_rm_aks

### ISSUE THREAD

**Issue by pvorb** [ansible/ansible_collections_azure#308]
##### SUMMARY

As far as I can see, there's currently no way to set the maximum number of pods allowed on one node in a node pool if the Azure CNI network provider is used.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

azure_rm_aks

##### ADDITIONAL INFORMATION

This feature would basically just allow to specify how many pods can deployed on a single node in a node pool. This is already possible with other tools like the `az` CLI via the `--max-pods` parameter.

```yaml
- name: Create a managed Azure Container Services (AKS) instance
  azure_rm_aks:
    name: myAKS
    location: eastus
    resource_group: myResourceGroup
    dns_prefix: akstest
    kubernetes_version: 1.14.6
    linux_profile:
      admin_username: azureuser
      ssh_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAA...
    network_profile:
      load_balancer_sku: standard
      network_plugin: azure
      network_policy: azure
    service_principal:
      client_id: "cf72ca99-f6b9-4004-b0e0-bee10c521948"
      client_secret: "Password123!"
    agent_pool_profiles:
      - name: default
        count: 5
        vm_size: Standard_D2_v2
        max_pods: 128 # <-- this is the new configuration feature
    tags:
      Environment: Production
```
