### ISSUE TITLE
New Module for Azure API Management Service

### ISSUE THREAD

**Issue by nikhilpatne** [ansible/ansible_collections_azure#332]
Would be good to have a module for Azure API Management Service.

https://docs.microsoft.com/en-us/azure/templates/microsoft.apimanagement/2020-06-01-preview/service

##### SUMMARY
An Ansible module that allows for create, delete and update azure api management service.

##### ISSUE TYPE
- New Module request

##### COMPONENT NAME
azure_rm_apimanagementservice
azure_rm_apimanagementservice_info

##### ADDITIONAL INFORMATION
Would be able to create, update and delete  Azure API Management service.

```
- name: ApiManagementCreateService
  azure_rm_apimanagementservice:
    resource_group: myResourceGroup
    name: myService
    publisher_email: user@example.com
    publisher_name: Publisher Name
    sku_name: Developer
    sku_capacity: 1

```
