### ISSUE TITLE
Error retrieving available machine sizes - APIVersion 2019-07-01 is not available

### ISSUE THREAD

**Issue by henti** [ansible/ansible_collections_azure#339]
##### SUMMARY
Trying to deploy VM in Azure, fails with erro. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure_rm_networkinterface

##### ANSIBLE VERSION
```paste below
ansible 2.10.3
  config file = /home/henti/src/ansible/ansible.cfg
  configured module search path = ['/home/henti/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/henti/.local/lib/python3.6/site-packages/ansible
  executable location = /home/henti/.local/bin/ansible
  python version = 3.6.9 (default, Oct  8 2020, 12:12:24) [GCC 8.4.0]
```

##### CONFIGURATION
```paste below
ANSIBLE_NOCOWS(env: ANSIBLE_NOCOWS) = True
DEFAULT_FORKS(/home/henti/src/ansible/ansible.cfg) = 10
DEFAULT_HOST_LIST(/home/henti/src/ansible/ansible.cfg) = ['/home/henti/src/ansible/inventory.d']
DEFAULT_JINJA2_EXTENSIONS(/home/henti/src/ansible/ansible.cfg) = jinja2.ext.do
DEFAULT_LOG_PATH(/home/henti/src/ansible/ansible.cfg) = /home/henti/logs/ansible.log
DEFAULT_MANAGED_STR(/home/henti/src/ansible/ansible.cfg) = Ansible managed
DEFAULT_ROLES_PATH(/home/henti/src/ansible/ansible.cfg) = ['/home/henti/src/ansible/roles', '/home/henti/src/ansible']
DEFAULT_STDOUT_CALLBACK(env: ANSIBLE_STDOUT_CALLBACK) = debug
DEFAULT_VAULT_PASSWORD_FILE(/home/henti/src/ansible/ansible.cfg) = /home/henti/src/ansible/scripts/get_vault_password.sh
INTERPRETER_PYTHON(/home/henti/src/ansible/ansible.cfg) = python2
INVENTORY_IGNORE_EXTS(/home/henti/src/ansible/ansible.cfg) = ['.ini']
```

##### OS / ENVIRONMENT
Linux Mint 19.3 Tricia

##### STEPS TO REPRODUCE

```yaml
  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: "{{resourcegroups.name}}"
      subscription_id: "{{resourcegroups.subscription_id}}"
      auth_source: cli
      os_disk_size_gb: 128
      managed_disk_type: Premium_LRS
      name: "{{vm_name}}-{{ ansible_date_time.date }}"
      vm_size: Standard_F8s_v2
      admin_username: admin
      ssh_password_enabled: false
      ssh_public_keys:
        - path: /home/admin/.ssh/authorized_keys
          key_data: "{{ lookup('file', 'ssh_keys/henti-henti-rsa') }}"
      network_interfaces: "{{vm_name}}-nic-{{ ansible_date_time.date }}"
      image:
        offer: debian-10
        publisher: Debian
        sku: '10'
        version: latest
```

##### EXPECTED RESULTS
VM Created

##### ACTUAL RESULTS

```paste below
The full traceback is:
  File "/tmp/ansible_azure_rm_virtualmachine_payload_tw6rl90i/ansible_azure_rm_virtualmachine_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_virtualmachine.py", line 1989, in vm_size_is_valid
  File "/home/henti/.local/lib/python3.6/site-packages/azure/mgmt/compute/compute_management_client.py", line 668, in virtual_machine_sizes
    raise NotImplementedError("APIVersion {} is not available".format(api_version))
```
