### ISSUE TITLE
azure_rm_appgateway multi-site applies same certificate for all sites

### ISSUE THREAD

**Issue by dvntstph** [ansible/ansible_collections_azure#354]
##### SUMMARY

App Gateway configured with 2 or more domains using HTTPS all get the same certificate. The certificate data from the last certificate declared in "ssl_certificates:" is used.

App Gateway is configured to server www.example.com and www.example.org

Each website has a unique certificate encoded as a base64 string.

All Websites listeners end up using the same certificate data despite being named correctly. This results in TLS warnings as only one site is be configured correctly

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

azure_rm_appgateway

##### ANSIBLE VERSION

```paste below

ansible 2.10.2

```

##### CONFIGURATION

```paste below

dvnt@D34dB33F:~$ ansible-config dump --only-changed
dvnt@D34dB33F:~$

```

##### OS / ENVIRONMENT

Azure Cloud Shell
Ubuntu 18.04
Ubuntu 20.04

##### STEPS TO REPRODUCE

Build application gateway using ansible-playbook

```yaml

---
- name: App Gateway
  hosts: localhost
  vars:
   resource_group: my-resource-group
   subscription_id: ef9dxxxx-xxxx-xxxx-xxxx-xxxxxxxxx
   vnet_resource_group: my-resource-group
   vnet: my-virtual-network
   appgateway_vnet_subnet: my-app-gateway-Subnet
   cert_password: !vault |
                  $ANSIBLE_VAULT;1.1;AES256
                  61303965356663306464323834336439363565306664333537336166663965653931306531623734
                  6630663763343235363261383633643664316634306438350a313435613139326332636666353366
                  33643962356639333039623336343934336461343061353335333264643032636434353762643231
                  3966366364306235630a353735346438363065623738373264373130633833646133336431653835
                  3062
  tasks :
  - name: Manage public ip address for App gateway
    azure_rm_publicipaddress:
      location: centralus
      resource_group: "{{ resource_group }}"
      name: my-app-gateway01-IP
      allocation_method: dynamic
      state: present

  - name: Manage Application Gateway 
    azure_rm_appgateway:
      location: centralus
      resource_group: "{{ resource_group }}"
      name: my-app-gateway01
      sku:
        name: standard_small
        tier: standard
        capacity: 1
      gateway_ip_configurations:
        - name: appGatewayFrontendIP
          subnet:
            id: /subscriptions/{{ subscription_id }}/resourceGroups/{{ vnet_resource_group }}/providers/Microsoft.Network/virtualNetworks/{{ vnet }}/subnets/{{ appgateway_vnet_subnet }}
      backend_address_pools:

        - name: www.example.com-WEB-POOL
          backend_addresses:
            - ip_address: xxx.xxx.xxx.131
            - ip_address: xxx.xxx.xxx.18

        - name: www.example.org-WEB-POOL
          backend_addresses:
            - ip_address: xxx.xxx.xxx.133
            - ip_address: xxx.xxx.xxx.135

      backend_http_settings_collection:
        - name: appGatewayBackendHttpSettings
          port: 80
          protocol: http
          cookie_based_affinity: enabled
          
      frontend_ip_configurations:
       - name: appGatewayFrontendIP
         public_ip_address: my-app-gateway01-IP

      frontend_ports:
        - name: port_80
          port: 80
        - name: port_443
          port: 443

      http_listeners:
        - name: www.example.com-HTTP
          hostname: www.example.com
          frontend_ip_configuration: appGatewayFrontendIP
          frontend_port: port_80
          protocol: http

        - name: www.example.com-HTTPS
          hostname: www.example.com
          frontend_ip_configuration: appGatewayFrontendIP
          frontend_port: port_443
          ssl_certificate: www.example.com-cert
          protocol: https

        - name: www.example.org-HTTP
          hostname: www.example.org
          frontend_ip_configuration: appGatewayFrontendIP
          frontend_port: port_80
          protocol: http

        - name: www.example.org-HTTPS
          hostname: www.example.org
          frontend_ip_configuration: appGatewayFrontendIP
          frontend_port: port_443
          ssl_certificate: www.example.org-cert
          protocol: https

      ssl_policy:
        policy_name: ssl_policy20170401_s
        policy_type: predefined

      redirect_configurations:
        - name: www.example.com-ssl-rewrite-rule
          include_path: yes
          include_query_string: yes
          redirect_type: permanent
          target_listener: www.example.com-HTTPS  

        - name: www.example.org-ssl-rewrite-rule
          include_path: yes
          include_query_string: yes
          redirect_type: permanent
          target_listener: www.example.org-HTTPS

      request_routing_rules:
        - name: www.example.com-routing-rule
          rule_type: basic
          backend_address_pool: www.example.com-WEB-POOL
          backend_http_settings: appGatewayBackendHttpSettings
          http_listener: www.example.com-HTTPS

        - name: www.example.com-ssl-rewrite-rule
          rule_type: basic
          redirect_configuration: www.example.com-ssl-rewrite-rule
          http_listener: www.example.com-HTTP

        - name: www.example.org-routing-rule
          rule_type: basic
          backend_address_pool: www.example.org-WEB-POOL
          backend_http_settings: appGatewayBackendHttpSettings
          http_listener: www.example.org-HTTPS

        - name: www.example.org-ssl-rewrite-rule
          rule_type: basic
          redirect_configuration: www.example.org-ssl-rewrite-rule
          http_listener: www.example.org-HTTP

      ssl_certificates:
        - name: www.example.com-cert
          data: "MIILeQIBAzCCCz8GCSqGSIb3DQEHAaCCCzAEggssMIILKDCCBd8GCSqGSIb3DQEHBqCCBdAwggXM
                AgEAMIIFxQYJKoZIhvcNAQcBMBwGCiqGSIb3DQEMAQYwDgQI+NI6aFcboKYCAggAgIIFmBLK14pM
                It4HCD/NnbL7OeBAOU5YSEEqy8SsNHbhE7ApTxeM4nBHp6mlM0c//Xf/9vXQrFZ1D8I9HoBQ5nr6
                jt0pznO81fTzqeKJORbFV8S7Jxd+pX4pgKGYQUKadhmUwGEbf4fi7H/GrRxmhD4qQDG+b/uILBmN
                +pp7PReVRHA+R3T1CvCg3iFo6p0VnUFR9byUIMqqcczZ6nvGYlIIfMvLPyqlf3jO6zYNURvLuvdO
                SeYpBCd3atr2KPTxJ5zz2Vrim461/wKEaLa36km5fYFIcCdb5dL3y7E/q911SkKus3L6oqltx5Ak
                3Iw6UNFwZgc+5sutGqpWVhRuCC/zlB6a+g74pIv/g5RD4CvfjhnnZ8+v0xHgqQ/EaxCBOCryWm56
                pn5bIXksyFciV0CLgbQyZXwF5ftuKaPGNTGZF0TPA+h1eedzIxLGblrwxumv9xbVkcyuPD227OMg
                Rvs666prAdWeu7lGdhuKV+edqHFnuQQX9jI/gFl2LR5EvJYZLeY/jhvqZ5z8zas7G5HUXlc7GACa
                AFCA3lOLDxr+g4/XSAN/tKGTXuwSWbKzpSTlaWPDOZPz4Ra+GMKytrtT3Jbz3ahpi3HC2Vci0ARI
                UGQDgIebDyVgF4E1euYD8x4EIkuB5vCiny/Rm4ZoStbYZPyBKgj5ako4nlEXYmrhsj6Gg5YP3YtZ
                SFSJqUbDhngC3/57NqVhOVxquuvqXzpH5NznpsujVyy4dIgIOFSgxL0B5LYlOn9f/MO/IsaRC/Yi
                sR3V/Hdfv+SKom9o4557xZ6gwk8F2+FeCczQiYNqwUBhfwuBpgic33TpER5nXSKc3ozzn6BlH6fy
                WL1kJXj28Bes+D2NohgAgULreBB6Q1LSkHMeotz3fT0AARUTdb3HKchrmFgsTLLFW8+IIX8uA1Sj
                Pd85rfIPiFPrpSZllZqQXplztvk1+9885Q17n6qWte9CMO18l2Y86bDYVFCovEPz3xGCQVN5gJdF
                eOTFvcrmz2Y9CwtR3F6ncoXQ13d72rzSi2edR1CcBUryVJiFBGhkOxs7eBLjAab8jvKB0oeZodTA
                fjetuTVnK8x3LpUgwAIpI2xoc7yiC0Tc+W403YN5jz/0uMZSkW23K2yALe76BDY8Bxfy9U3o6Mva
                zeIhb1X9aIMnImJvzGx+JSnw9jmsKL3OQA4MoPSsky9r+8/UXsHRPmU5EmdtmFLpVsJF7uODs1kq
                9UlBs+dRZF0+rAzHVOkdYEtJrQkEoLW1MMKrZx4TOtUX/aUFhfOluBJtDwEIBT38qFY/QZt/mdoe
                daXsmxaOe+pkctAtwQC/WBwUdl2MxLKc5VlA+gA6lP28fa6f3w8t7pcCT5pqEvYS656LiY9MP+ld
                B6YLzQpxB9CM4r2irIz2E8Puieje6a5LCLtcIxLG39BSy9o94gEw8pXVR/Fu3/euVr1vMKBMgQi8
                OG0uP6cZrKEYXk9Z3655Hl9w6qUB00EvQczC2b8aMzm5iaeTMq4PgZTOyBpCwE/rGTCahQQB0hJ6
                LY/UWaZQXN8Qw+r/7593ObiF3H73I3xcOfqErGTjvRFqbc9mCAiyGa2B4gjJCOnVoYobzCKZ8FJi
                2n9mbF6GXqEBSPwhQfwvJ7BcIKQIasZzaxmieZN6vm9kEz1+oO+U1WEaDXnkgTaUGBu0WWFmJ8dP
                bpOh6YTJd2VTFgTk+t/QxWXzsYO+7kK1sz8r94T11pU5eycir71M61Z4d3ld7a5WYS/WjmcZ5jYJ
                bmfxA3EKq8O/lV2PmvJJ99JA7GysKBhtpW8HISmeT13MY8fbaxAVcWzueiPnRk42jXOBbRHsHWPx
                8VAzg5wZqO68eZZTLIuPnW9joMaNzpCQKYtTk1XDPrJEkq0L6nkDtvmtvYyZYYj54gqXRuXyyRaF
                iAUwggVBBgkqhkiG9w0BBwGgggUyBIIFLjCCBSowggUmBgsqhkiG9w0BDAoBAqCCBO4wggTqMBwG
                CiqGSIb3DQEMAQMwDgQI1BTanqYQbSkCAggABIIEyBQCPEVWPU5qaI3mKtdYp6K0ee3W+T0hzB7E
                VHHchpCCerS1gPwtjslDD4gF5DdIhTVcHujb/QvSZDurqdr7ZGh72hYO4LztF4cZAP4dLVtZbTf+
                6N/3hvF3I5A1svjJIrTNALvCKq2j7/0nGLw6EJEoU2pZY4cxPxdhDiiXwuPukUvH3eLC3uVVB51P
                Iu9rNOPVp2DYudFf92jJ9roXTulG3el3WSCgS0C61N/xGtF/SoMQPprVD8BGZR+cV3pn7KTHchTa
                YdbYXh6TymYRLYDsvEtuAe2CMgsIC8OjfMCWoXSShNLxZPN/3WU+UnCLdyKe4ry2Htfr/nQG3p8y
                fpyToZVTvDngiBL9Rjqo2pHniUVR62gnSBUjV2/ATYaDzn0nQhMTP4S1BhTuK5ndQIkdlDgJFIPV
                fFEpcZQQNcWtSPK1O7DhBheYvfkwt+Gqb6z4IpBL5YaFzvRm47gGFQYvtG9UCK0+mVrqp11GXd3R
                kDLFThcZIdSKGVDdOgirmeGHNdhr2PseRtaaEK4GjNWQqFQKupSwu50wiNQnUiwZJrX8cXZEJAgQ
                CAMj42LHNl8RrP9ihFzAKDWYBBF0TWnWhz/TH3B+SaZq7eLpR+KWgm0NwO+mm2Zf380qUiYLbpuO
                g4moxepTN8QWPoI2MvMryIoqkhCk7QRTqK7VoixMY3F5+tDxlqgGU+KezLVeh06FqbH1opLzNfqt
                NNkWTzSSCJGJ2AM5xER/9HPOeKboMvxwAatGf08AqRALTT4D/zJB94Iwb1cMGyQOvL3TIlOVe1E/
                1IpMKmXRo1mBoptRHZt4gg6cwxsVRUqth0i9r2g8bFNtaT1kLV6snTqi2sCbQpWiEwYb5KG/HtPX
                zgN8FRcCkjBtf5wdXlXQou7RLDUAb1Y2R0KUtManhlu7wpHkq80QLBHB4cTd2rqXWtDmPF4OH9St
                ZKOK6FwsuAGJstg50sD6PKL2BDMKkMhIIm5fWeNwg3H+145udKFK9AW7YbxYF9n0XWj+EFaYd3r2
                X8mwPLn3dwbTt2Rf4MRKg93xx1wC3C+2AVooSyB/xnzhwiBkpM0Sn0QChp99MrN2ntNcsdULcgRk
                5HPAt0wKOb5mJIBAH58M6s+yWRmgXMroJKSpdQ0yHkA9MZ/2KXDjsdS20qTeDfaL3TU9gzhXYFk8
                BHX2Pz0GN6Rvxlg2/AA8YphWJqgw8WXAtOe0PLaJEc267yNwqRjtvTwKI9vaOcMAPOVXUW/UJvBh
                PJ99jU7r7JoIlxhp2UvReEeNNNjvm5a5ZCdLUifmEKHzfUzNAhNpII6IzQYYo0xHly4MmScRwVgE
                qxDqdLhpZ1siX1KUBgwV0bRujqjYwYkII61prnIvnofAmNNeE7NyrZnHmma0zpMFOJqnWbiqzs1x
                2pdRYvL97mWOypvCCOCkCnGWhHLto/D0b6FrbQRLX+PODyXph8ZaSozbPvuou15KMD9xPlA9Yi/S
                cP47nnCJw7ecCReMDMh8olpBRCynDdoTIy5KmBLLj7VZXNjaniAFxdyXApyljA2u+17JvBEgovYF
                p0MRyboPPWWegDgcoHpZXDerMED8qYaPpA4ndESNikDTAv+AhQEU9ZnFd/XyTdnpXHQBJ1X8CI8/
                1DElMCMGCSqGSIb3DQEJFTEWBBQovxgyCVjZDu6ea1pY/Las2MTuZDAxMCEwCQYFKw4DAhoFAAQU
                xFD7yLi+6e66d1cWToQhfosu7GEECNHxXALCi8f9AgIIAA=="
          password: "{{ cert_password }}"

        - name: www.example.org-cert
          data: "MIILeQIBAzCCCz8GCSqGSIb3DQEHAaCCCzAEggssMIILKDCCBd8GCSqGSIb3DQEHBqCCBdAwggXM
                AgEAMIIFxQYJKoZIhvcNAQcBMBwGCiqGSIb3DQEMAQYwDgQIwgYpL0PoMpQCAggAgIIFmDdpMbNZ
                2XKrZUFemtqQXoqfAqUlo6/b2PNHpGvlU/6qfdrlSCglx5dG5k6TOe1Ed9dsorPIqJ0HnQmiVh8d
                ZXEJwT5sc2ydlTmyeVKqDZ4vEQUfMyak8lMYmKX+5uEBR8HmQ9+70Gx2kpboWz+rTxl+ZG/tnYRC
                /ZYqTP5mOJsqPMp/BayS5an04xkXZdm9vZelxlS1EItMVkhuB2/uy6M1+Az3K9Ls1szdjPzyoNCY
                mUjDPHGc3nSXX9S+XnmwJWcx/oEqZC0TpKFaYB7gnG+p5xVQvNqvOiX97BySgEwAQMKGK3qtUctA
                /nVSiAWGA6CUU2JUKdUrdiivqFgDVVAD3g3RK+2zKCY6K4rgbLGNrSsUVyApg0q3w1DA8VCZgGmm
                +bhvyepI6n8Bga6vFAD3fuGxLjyNHy1+uEXqLs+Ml/FMx50t+ExoXKTawJH6+VXeQq79C+FWZFtd
                EaSWRCKJM5B0B8MxhTpSwldYmMvavl/bvKTVt3D4EU+SG+3HK5C+t2b8ekuuYF95qX64/5+KL8YG
                KRHlbKGl4xUiQLsH0nopxgCCA3txVAzFJHFD7ifejWNyqBLYZLo+PdIUvCdfbJOItKRVs0IYdp3v
                +weIQVEqtnX5s3ah1UU0eErDfiPewSPKw/RQHoEnFsyvA6IeoqiiS1/WodcUXgj0cqGL2Em1IQ2O
                bb00GiUoYFkCEf/HH5GSjFsGmUJF2cyz+pBePe4BcthuU2ugnCWLtIpF5QJl/e4n3HjoCrS/OlVv
                l4wptotsMqttFyzOIkkKreYxSodgj4MaezfVPXIw/G3zxw0gkrAdoWwaqeWB/dlNWvpZ1WoKl+sh
                c0IjCo24tlz++D9XFTgUH7khRTL/59mFuRlfWT6EuZ8aCEHhx3OhqUYWqw1M3dFn0OdbftajiJco
                h/13nseseU2sdUrZ5GgyfcbwhQIYrjlD/6NZz6G9j5nxhK51zUEa5MlXzyt2XDOkYbsoO/G8loHA
                nfsMzZCNVO5OlxxNq27nNca7JpEBbOrJC5rVv67IqXc15HJreNvRWO7AXiIkr8LsExAijVrdgcyK
                bto34us8Uyeru+LSklEx1nLSeExRK18Tdl0Zh7bdoteZQabOFo43MesZFlvz0ti9/DfX7xUNT6ft
                oGo/vbBD6g1o+Wq+vdoG01fLyEVX5qYptjymtVILTnxGWBseysHxMxmvqXePwCJL2wdusVZBhRfz
                oPYlGpDxFZDjGCVp4OY5Bf4Vq3mLoIGk81XLf0TxNLmJ7pGquaYOtfAw0Kn68Xu23BM9AYsmsCVX
                a+6VvgnGuZkMVx1Y2KqFlVfgwiH3PzCBfZyoKtfFL8HloBiIYsG1QpzpqGg2EhyGAzf1m8bC7vz5
                8M1zRWZUfnJV7yVYp5V8b+kSnBwSi+Y0PxIh6212FQlC80DrbQuppdnKKpTRsmgTfxxUVhDTYNk+
                OzLXoHeCbhiXwxNMFZznUJjqxKXjLdCQU0dJHwp6Pk3Pa37qxHt22i8ci/dke5nhpE0XR/rslMUH
                OeFGOnCWIMBWL8t3ReR2nZpxUUzddC8vLqsCIGtrRUuCUPxL6mu1rIQ+eyHfyWQPWHDf5gk/AETv
                NJjUx7sBaeiIg8hiedWTYZ3Gq7/KFJqCzcGpEAK6MaW6DzXWNI0cUdssNunVz7sb8jylAPjb96mn
                S7R+0Fufy7eHw0O9Vl25Bh4tqs0k+VHVmRENKqPstrB6Aj6SRlqynjH1EahBqEKCxCsErRckmher
                A5LyUfYopOY3iADjCHgmtAyC2ilC8znI7F7V+u63s0IzQ5eAUtd1h9o/rAsQIiPOJYEVDCoX3dy1
                +6PbwXuSo/pKM93X7DdZStVRwA3SGVFzKIf5LeOwLvQvyfyRpTZbgN4T4qq4l1I163wHF3nI7AeV
                LYQwggVBBgkqhkiG9w0BBwGgggUyBIIFLjCCBSowggUmBgsqhkiG9w0BDAoBAqCCBO4wggTqMBwG
                CiqGSIb3DQEMAQMwDgQIZCEgQjjd84ECAggABIIEyGobC9w/a8FTeC3LynGW0hMHcNBcwSHz2mD3
                RxFeXYfWxY7aRUptXdwEuVxOct5awY3Sie/ZoAU5F6a2uAcXstTBkMahzVKBo+GCd9VgCOThVYOd
                cywpNJd8E7Z1jYAEzcrobDuXX+RYobf92F8mgvlF5LYlXqAnqSUf4rtV9qruOEWW759XeHVSmdf1
                62R97cpukKehJBNX2D0IVbgxQC2ceZzopBJuJnrZqwOpHwYflCcu0+5iIgecU+YiH4TGsi1lt3KU
                3BVfB7P5cEMGvjTLx0eXUJBNP3K3MgaM06moWzCRf6oz9rdEwVFdfNBia5Da4yBR083p71SEVhTQ
                HHnTNr2f60KpkUm58caowCfGkKUTSH/JhM0/Tch5885ZpWFSYv06odKt2OzmPSNcNVrK7a+2tAyC
                wxpTYHxmi2Tz2D/ZQS/QLEkpE0gL1EjGHEGxsf/Lz5taci/aZwBCd7WD03wEJqzpW4B0C9WTkT/R
                TtoOyulG7KxOvfkgkkUfvBBnNiXawlyrTjmDH67ZQt+hDJqLLZSFormWOtimbjdwwyzCPtovDK8N
                1taS7/1dQMkJ+XGJhsiebo0jhtm8F17217kXr4uxWczZ4K4QoIIR+tmRMK828eqvgFjVcECcWZyg
                CqX2s1G5LTIlfPH4Rw9nEbRksHj8faEx7oBsMM39/e2p07OS/Vsyq+3BKF1Q86rklYeZGhv65hCP
                rQCsKjyyjEU78YOozU/8N3wM9SUgd2+8PVxeRwIh0g4F6eB1c8dYX3YpPfuF2xPBGJD/L4y49Yua
                WuAL+KsUOl8XEWH8DZXCUWr6UPhyeWR1GPLgEronhWlT6WFo1gwRalNNRXyYe4SVl2jFVDFC995S
                FOcoOh7UJOZQwLSp6LIZOxN8I5AM5JYjaiheXHrCe/v5V9BJNfJPjkIqsuTD534sqJi6j3+uwWe4
                howHEU0hOYT3QC5FjjFrHBHBjdmLtwZB0dZzxrJqPRMJVMZyQULnwSDcAQBTvaOjWhc9rvZEo0Uz
                aBFgCAQ4ZUkOOW6L5NuB7WuZygATSCec7oYKPODzwJJ5oYIqNWlzf827N/zCIuYk1oD6WMXCVJn7
                lfD6U7QBE/cxrDC0YQ0aeZrcZu46U5TQRHejyIpkqxDsoJCJJrwybh9F0i7VZvfekkZLDWFn0Lfz
                7U73Yi9nPEsFt4lzduLRG43NA83q9hRuvgskiL0aBqpCgyKaPk6BlDBEUvGAFjjYpbqF+iV0S22V
                3hD5s3NW2S5CNq+BxD7hVSEcC4MAXln5scHPxYXTrV7qaF7Ts2Kob6mXLIDaXZIgdvrXtketB6QQ
                mVk6DugEhBId69x3noygY/ttL1IGF+Lub4gpadBpuxKjEbIfW0Bd2ycFnYFU22KkmdyHGzOzFvIh
                atgnnLuWbUoPa6+MRslnx8q931MKqGHvJ1i+c1yPFUmtCKTLOoY+nGiNzNnieOW1HUi2gd5S7BZ4
                It79L0pPW67e0FuoV5Fi/EL5ZfK37aTHx+v25mO0WHGY3CMZd6SyOk5obEOKHNkqZyZ1JtUuPUK2
                T6NC92DQ85veJlSi0Ms94my1fWaJte9UMcZrbY8VNvBcd2yT7mJiYnb4GuNia/fKu4IwxvAGQGun
                jjElMCMGCSqGSIb3DQEJFTEWBBSaNK+Dc+0TYRQ1U8tdQLn0j+N/szAxMCEwCQYFKw4DAhoFAAQU
                tEx/2cRBqsJeilsruT1d7GEm1X8ECIR87b8c9WLiAgIIAA=="
          password: "{{ cert_password }}"

      tags:
        access: external
        lifecycle : production
        automation: ansible


```

##### EXPECTED RESULTS

Each website should be configured using it's own certificate 

##### ACTUAL RESULTS

As Described

```paste below

```
