### ISSUE TITLE
Is there any Ansible module to create a folder on Azure file share?

### ISSUE THREAD

**Issue by cloudengineers** [ansible/ansible_collections_azure#358]
Hi All, 

Is there any Ansible module to create a folder on Azure file share? including sub directories, Any help much appreciated.  

Thank you

Please Note: 
Currently I am using shell Module to create a folder, but I want to avoid shell module, as it’s require azure cli to execute the commands

Example:   
- name: creating test folder on Azure file Storage
  shell: az storage share create --account-name xxxx --account-key xxxxx --name testing --quota 5 --output none

**Comment by Fred-sun** [comment]
@cloudengineers Thank you for reporting this issue, we will review it as soon as possible, thank you!

**Comment by Fred-sun** [comment]
@cloudengineers Thank you for submitting this issue and we will investigate these new modules as soon as possible!

**Comment by Fred-sun** [comment]
fixes by #603

**Comment by 153957** [comment]
This issues was not fixed by #603 because that module only allows creating the file share, not actual directories in it.

However, I think the original example in this issue does not actually create directories in the file share, just the file share itself, so that part can now indeed be done by this collection.

**Comment by Fred-sun** [comment]
@153957 I will recheck it! Thank you very much!

**Comment by 153957** [comment]
To create the directories we currently use this command:
```
- name: Create required directories in file share
  ansible.builtin.command: "az storage directory create --account-name {{ … }} --account-key {{ … }} --share-name {{ … }} --name {{ item }}"
  loop:
    - …
    - …
```
