### ISSUE TITLE
Build application and deploy to container registry (az acr build)

### ISSUE THREAD

**Issue by l3ender** [ansible/ansible_collections_azure#361]
##### SUMMARY
An Ansible module to handle building an application from source code and deploying to an existing container registry. The module would be provided the path to the application source code, which includes a Docker build file.

This module would be comparable to the following Azure CLI command ([`az acr build`](https://docs.microsoft.com/en-us/cli/azure/acr?view=azure-cli-latest#az_acr_build)):
```bash
az acr build --registry myregistry --image myregistry.azurecr.io/my-app-name:v1 .
```

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
`azure_rm_containerregistry_build`
??

##### ADDITIONAL INFORMATION
We are deploying our applications to Azure as container images, and utilizing Azure build for generating the images. We do not have an environment to perform container image builds (e.g. no Docker). The above example Azure CLI command is the target usage of what we want to do natively in an Ansible playbook without using azure-cli.

Desired usage would be something like following:
```yaml
- name: "Create image in Azure registry."
  azure_rm_containerregistry_build:
    registry: "myregistry"
    repository: "my-app-name"
    tag: "v1"
    directory: "."
```

Assuming this feature doesn't already exist, is there a workaround that can be accomplished in Ansible without dropping to `shell` module and running azure-cli commands?
