### ISSUE TITLE
Get the upgrade versions available for an AKS cluster

### ISSUE THREAD

**Issue by ewsct** [ansible/ansible_collections_azure#377]
##### SUMMARY
To check which Kubernetes releases are available for an AKS cluster we need to use the `az aks get-upgrades` command.

`azure_rm_aks_info` does not provide such information. 
`azure_rm_aksversion_info` returns available kubernetes versions supported by AKS for new clusters, but not for a certain cluster for upgrade. The thing is when you upgrade an AKS cluster, Kubernetes minor versions cannot be skipped. For example, upgrades between 1.12.x -> 1.13.x or 1.13.x -> 1.14.x are allowed, however 1.12.x -> 1.14.x is not. That is why we need that `az aks get-upgrades` command, which gets cluster name and its resource group as parameters.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

- azure_rm_aks_info
- azure_rm_aksupgrades_info

##### ADDITIONAL INFORMATION

There may be two possible ways to solve it.
- add this additional information to output of `azure_rm_aks_info`

```yaml
- name: Cluster all info
  azure_rm_aks_info:
    name: 'aks-test'
    resource_group: 'aks-test-rg'
```

- make another info module (let's say `azure_rm_aksupgrades_info `), like it is done in `az cli` (it has `get-upgrades` and `get-versions` subcommands)

```yaml
- name: Cluster upgrades
  azure_rm_aksupgrades_info:
    name: 'aks-test'
    resource_group: 'aks-test-rg'
```
