### ISSUE TITLE
state absent in azure_rm_deployment simply removes the resource group

### ISSUE THREAD

**Issue by uda** [ansible/ansible_collections_azure#383]
##### SUMMARY
When using the `azure_rm_deployment` module, if running the task with state absent the resource group itself will be deleted.

This can be caused if the previous deployment didn't even succeed, but I don't have now time to test this...

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
module azure_rm_deployment.py

##### ANSIBLE VERSION
```
ansible 2.9.16
  config file = None
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/.pyenv/versions/3.6.11/lib/python3.6/site-packages/ansible
  executable location = /home/user/.pyenv/versions/3.6.11/bin/ansible
  python version = 3.6.11 (default, Aug  1 2020, 19:26:35) [GCC 9.3.0]
```

##### CONFIGURATION
```
# this is changed by local env ANSIBLE_VAULT_PASSWORD_FILE
DEFAULT_VAULT_PASSWORD_FILE
```

##### OS / ENVIRONMENT
Linux mint 20

##### STEPS TO REPRODUCE
I created a resource, successfully, then tried to remove it simply by passing the absent state:

```yaml
    tasks:
      - name: "Setup some resource on Azure"
        azure_rm_deployment:
          state: "{{ desired_state }}"
          resource_group: "{{ resource_group }}"
          location: "{{ location }}"
          name: "my-deployment"
          parameters:
            envName:
              value: "{{ env_name }}"
          template: "{{ arm_template_included_from_vars_file }}"
```

##### EXPECTED RESULTS
Only the deployment should be removed

##### ACTUAL RESULTS
The entire resource group is deleted

**Comment by Fred-sun** [comment]
@uda Now the logic of the module design is such that when State ='absent', the resource group will be deleted. We will discuss this as soon as possible to increase the need to remove deployed resources! Thank you very much!

**Comment by uda** [comment]
Thank you for the response, can the documentation at least be modified to reflect that until there is a decision?
I've just spent some hours restoring a (staging...) resource group.

According to the documentation:
```
# Destroy a template deployment
- name: Destroy Azure Deploy
  azure_rm_deployment:
    resource_group: myResourceGroup
    name: myDeployment
    state: absent
```
