### ISSUE TITLE
No module named 'azure.storage.cloudstorageaccount'

### ISSUE THREAD

**Issue by nicolaibaralmueller** [ansible/ansible_collections_azure#396]
##### SUMMARY

Using collections with azure throws ModuleNotFoundError.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

azure_rm_publicipaddress_info

##### ANSIBLE VERSION

```paste below
ansible 2.10.4
  config file = /home/user/Ansible/ansible-dce/ansible.cfg
  configured module search path = ['/home/nbm/Ansible/repo/Modules']
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]
```

##### STEPS TO REPRODUCE

```
ansible-galaxy collection install azure.azcollection --force
```

```yaml
---

- hosts: localhost
  connection: local
  gather_facts: no
  collections:
    - azure.azcollection
  tasks:
  - name: get facts for public ip
    azure_rm_publicipaddress_info:
      tenant: '{{ tenant }}'
      client_id: '{{ client_id }}'
      secret: '{{ secret }}'
      subscription_id: '{{ subscription_id }}'
      resource_group: '{{ customer_prefix }}-sql'
    register: result

```

##### ACTUAL RESULTS

```paste below
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ModuleNotFoundError: No module named 'azure.storage.cloudstorageaccount'
fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "Failed to import the required Python library (ansible[azure] (azure >= 2.0.0)) on ansible-test's Python /usr/bin/python3. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"}

```
