### ISSUE TITLE
Remove non existing peering using module `azure_rm_virtualnetworkpeering` causes task to fail

### ISSUE THREAD

**Issue by arno-pons** [ansible/ansible_collections_azure#399]
##### SUMMARY
Remove non existing peering using module `azure_rm_virtualnetworkpeering` causes task to fail

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure_rm_virtualnetworkpeering

##### ANSIBLE VERSION
```paste below
ansible 2.9.6
```

##### STEPS TO REPRODUCE
Try to remove a non existing vnet peering using task
```yaml
- name: Remove Vnet Peering from infrastructure side
  azure_rm_virtualnetworkpeering:
    name: "/VNET_PEERING_XXX"
    virtual_network: "YYY"
    resource_group: "ZZZ"
    client_id: "AAA"
    secret: "BBB"
    subscription_id: "CCC"
    tenant: "DDD"
    cloud_environment: "EEE"
    state: absent
```

##### EXPECTED RESULTS
Task should not fail if peering is already absent

##### ACTUAL RESULTS
Task fails with following message:
```
TASK [remove-peering-infra : Remove Vnet Peering from infrastructure side] *****
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Azure Virtual Network Peering /VNET_PEERING_XXX does not exist in resource group ZZZ"}
```

##### IMPLEMENTED WORKAROUND
Add the following error handling to get a temporary workaround:
```yaml
  register: result
  failed_when:
    - result.failed|bool
    - '"does not exist in resource group" not in result.msg'
```
