### ISSUE TITLE
azure_rm_backupazurevm resource in different resourcegroup than the recoveryvault

### ISSUE THREAD

**Issue by ilabrovic** [ansible/ansible_collections_azure#403]
##### SUMMARY

azure_rm_backupazurevm.py handles only 1 resource group for both resource and recoveryvault.
In our environment, we have dedicated resource group for backup vault, all VM's are in other resourcegroups

##### ISSUE TYPE
- Feature Idea
Need support when resource and recoveryvault are in different resource groups.
The Azure API itself can handled this.
Add a new field "backup_resource_group" and use it in line 187 to construct the vault path.
For backward compatibility when it is not given, defaults to the same value as "resource_group"

In portal.azure.com configuring backup is no problem.
Also the API is supporting this. See: https://docs.microsoft.com/en-us/rest/api/backup/protecteditems/createorupdate

##### COMPONENT NAME

file: azure_rm_backupazurevm.py
module: azure.azcollection.azure_rm_backupazurevm

##### ADDITIONAL INFORMATION

Handling resource and recoveryvault are in different resource groups

```yaml
 added paramater in playbook:
      azure.azcollection.azure_rm_backupazurevm:
        backup_resource_group: "{{ azure_backup_resource_group }}"  <<< This line added
        resource_group: "{{ azure_resource_group }}"
        recovery_vault_name: "{{ azure_backup_vault_name }}"
        resource_id: "{{ virtualmachine_info.vms[0].id }}"
        backup_policy_id: "{{ backuppolicy_info.response.id }}"
        state: 'create'
```
