### ISSUE TITLE
azure_rm_loganalyticsworkspace: Retention days does not change after creation

### ISSUE THREAD

**Issue by t-ymwk2** [ansible/ansible_collections_azure#419]
##### SUMMARY
Retention days in log analytics workspace is not changed after creation.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure_rm_loganalyticsworkspace

##### ANSIBLE VERSION
```
ansible 2.10.2
  config file = None
  configured module search path = ['/home/takuya/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/takuya/ansible2.10/lib/python3.8/site-packages/ansible
  executable location = /home/takuya/ansible2.10/bin/ansible
  python version = 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]
```

##### OS / ENVIRONMENT
Ubuntu 20.04.1 LTS

##### STEPS TO REPRODUCE
First, create the resource.
```
- azure_rm_loganalyticsworkspace:
    resource_group: myResourceGroup
    name: myLogAnalyticsWorkspace
    retention_in_days: '90'
```

Then change the value of retention_in_days and re-run.
```
- azure_rm_loganalyticsworkspace:
    resource_group: myResourceGroup
    name: myLogAnalyticsWorkspace
    retention_in_days: '180'
```

The result will be OK and will not be changed.

##### EXPECTED RESULTS
Retention days have been changed.

##### ACTUAL RESULTS
Retention is not changed, return code is OK
