### ISSUE TITLE
azure_rm_loganalyticsworkspace: No tagging

### ISSUE THREAD

**Issue by t-ymwk2** [ansible/ansible_collections_azure#420]
##### SUMMARY
Tags are not attached even if they are specified in the tags option.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure_rm_loganalyticsworkspace

##### ANSIBLE VERSION
```
ansible 2.10.2
  config file = None
  configured module search path = ['/home/takuya/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/takuya/ansible2.10/lib/python3.8/site-packages/ansible
  executable location = /home/takuya/ansible2.10/bin/ansible
  python version = 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]
```

##### OS / ENVIRONMENT
Ubuntu 20.04.1 LTS

##### STEPS TO REPRODUCE

```yaml
- azure_rm_loganalyticsworkspace:
    resource_group: myResourceGroup
    name: myLogAnalyticsWorkspace
    tags:
      env: dev
      sys: example
```

##### EXPECTED RESULTS
A tagged resource will be created.

##### ACTUAL RESULTS
An untagged resource will be created.
