### ISSUE TITLE
azure_rm_image: Required parameter 'hyperVGeneration' is missing

### ISSUE THREAD

**Issue by achevalet** [ansible/ansible_collections_azure#422]
##### SUMMARY
Creating image from blob_uri fails with "Required parameter 'hyperVGeneration' is missing".

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure_rm_image

##### ANSIBLE VERSION

```paste below
ansible 2.10.5
  config file = None
  configured module search path = ['/home/xxx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Nov 16 2020, 16:55:22) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
```

##### OS / ENVIRONMENT

CentOS Linux release 7.9.2009 (Core)

##### STEPS TO REPRODUCE

```yaml
- name: Create an image from blob
  azure_rm_image:
    resource_group: myResourceGroup
    name: myImage
    source: https://my_blob_uri
    os_type: Linux
```

##### EXPECTED RESULTS

Image is created.

##### ACTUAL RESULTS

Image is not created.

```paste below
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error creating image myimage - Azure Error: InvalidParameter\nMessage: Required parameter 'hyperVGeneration' is missing (null).\nTarget: hyperVGeneration"}

```
