### ISSUE TITLE
How to configure azure_rm inventory plugin for multiple subscriptions

### ISSUE THREAD

**Issue by PavelPikat** [ansible/ansible_collections_azure#429]
##### ISSUE TYPE
- Documentation Report

##### ANSIBLE VERSION

```paste below

```
How could I execute Ansible playbook on multiple VMs hosted in different Azure subscriptions within a single tenant?
Let's say I have Subscriptions called Production and Staging and I want to configure VMs in both subscriptions with a single playbook?

I am currently using azure_rm inventory plugin with credentials file, but each profile can only hold a single subscription_id, e.g.:
```
[production]
subscription_id=xxx
client_id=xxx
secret=xxx
tenant=xxx

[staging]
subscription_id=xxx
client_id=xxx
secret=xxx
tenant=xxx

```

My playbook's inventory file looks like this:

```
plugin: azure_rm
auth_source: credential_file
profile: production
plain_host_names: true
```

Can I specify multiple profiles?

**Comment by Fred-sun** [comment]
@PavelPikat You can specify the credentials to use in your PlayBook. Thank you very much!
```e.g.
    - name: Playbook Yaml
      azure_rm_******:
          parameter: value
          client_id: **
          secret: **
          tenant: **
          subscription_id: **

**Comment by victorbrca** [comment]
As per the documentation, `subscription_id` in the dynamic inventory file should take care of that (so you could have multiple inventory files, each configured with a different subscription id). However, when using 'CLI' as the authentication source does not seem to work.

**Comment by tfmark** [comment]
I've just been looking at doing this myself.. If you pass the `profile` argument into the module, you should be good. 

Here's what I'm doing in my playbook:

```yaml
  - name: Add firewall rule
    azure.azcollection.azure_rm_securitygroup:
      profile: staging      # note I actually take this from a group_var, i.e. 'staging' or 'production' or whatever
      resource_group: my_resource_group
      name: my_nsg_group
      rules:
      - name: test123
        protocol: Tcp
        destination_port_range: 12345
        access: Allow
        priority: 101
        direction: Inbound
    delegate_to: 127.0.0.1
 ```

and my `~/.azure/credentials` looks the same as yours.
