### ISSUE TITLE
azure.azcollection.azure_rm_keyvaultsecret_info stalling

### ISSUE THREAD

**Issue by flixman** [ansible/ansible_collections_azure#433]
##### SUMMARY
Running azure.azcollection.azure_rm_keyvaultsecret_info module stalls. **Maybe this is not the place where to ask for help. If so, my apologies.**

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure_rm_keyvaultsecret_info

##### ANSIBLE VERSION

```paste below
2.9.17
```

##### CONFIGURATION

```paste below
DEFAULT_FORKS(/home/test/ansible.cfg) = 5
DEFAULT_MODULE_PATH(/home/test/ansible.cfg) = ['/home/test/library']
DEFAULT_ROLES_PATH(/home/test/ansible.cfg) = ['/home/test/roles']
DEFAULT_TIMEOUT(/home/test/ansible.cfg) = 10
```

##### OS / ENVIRONMENT
CentOS 8

##### STEPS TO REPRODUCE
Run the following task when behind a proxy
```yaml
- name: Get API key from vault
  azure.azcollection.azure_rm_keyvaultsecret_info:
    vault_uri: "https://keyvault.vault.azure.net/"
    name: ELK-ApiKey
  register: secret
  delegate_to: localhost
  run_once: true
```

##### EXPECTED RESULTS
The secret gets retrieved.

##### ACTUAL RESULTS
The module stalls forever.

##### NOTES
Initially I thought this was due to the connection going through a proxy, but I have run the azure_rm_subscription_info and it works as expected. Something else: the service principal I have created is on another subscription, although I have set properly its access policy on the keyvault. If I run 
```powershell
Get-AzKeyVaultSecret -VaultName 'Keyvault' -Name 'ELK-ApiKey' -DefaultProfile $dp
```
After setting $dp to the profile for that service principal, I can retrieve successfully the secret. Might this be an issue for this module?
