### ISSUE TITLE
Auto-Shutdown VM Settings

### ISSUE THREAD

**Issue by tlourey** [ansible/ansible_collections_azure#437]
##### SUMMARY

Provide Auto-Shutdown VM Settings 

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

azure_rm_virtualmachine
azure_rm_devtestlabschedule
##### ADDITIONAL INFORMATION

It seems that the devtestlab auto-shutdown schedule feature is now supported on non-dev-test VM's and the feature doesn't seem to be in preview. Looking at ARM Template after the fact reveals: 

"type": "microsoft.devtestlab/schedules",
"apiVersion": "2018-09-15",

This would be great if it could be supported in azure_rm_virtualmachine, or if azure_rm_devtestlabschedule should no longer have lab_name as a requirement so that it can be used both for devtest labs and for regular virtual machines. 

```yaml
- name: Create (or update) DevTest Lab Schedule (for nonlab)
  azure_rm_devtestlabschedule:
    resource_group: myResourceGroup
    time: "1030"
    time_zone_id: "UTC+12"
    notification_address: "user@domain.com"
```
OR
```yaml
- name: Set VM autoshutdown options
  azure_rm_virtualmachine:
    resource_group: myResourceGroup
    shutdowntime: "1030"
    shutdowntime_zone_id: "UTC+12"
    shutdown_notification_address: "user@domain.com"
```
