### ISSUE TITLE
Add backup settings to azure_rm_postgresqlserver

### ISSUE THREAD

**Issue by dpodder** [ansible/ansible_collections_azure#447]
##### SUMMARY
Please add support for customizing the backup retention period and the backup geo-redundancy flag for deployments created by `azure_rm_postgresqlserver`.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
azure_rm_postgresqlserver

##### ADDITIONAL INFORMATION
Backup geo-redundancy and backup retention period are important settings for a production-grade deployment, but the `azure_rm_postgresqlserver` module does not currently (v1.4.0) support setting either of them. As a result, servers created by the module today default to no geo-redundancy for backups, and a retention period of 7 days; these values are not suitable for our production deployments.

Backup retention can be tweaked after server creation, so we could work around missing that setting. But backup geo-redundancy cannot be changed once a server is created, so this is a hard blocker for us from adopting `azure_rm_postgresqlserver` in our deployment automation.

Note that this appears to have been attempted in ansible/ansible#64894, but those changes don't appear to have been retained in this repo... (Or were they reverted for some reason?)

Example playbook snippet:

```yaml
tasks:
  - name: Deploy PostgreSQL Server
    azure.azcollection.azure_rm_postgresqlserver:
      name: example_server

      # The new settings, as seen in ansible/ansible#64894:
      backup_retention_days: 14
      geo_redundant_backup: yes
```
