### ISSUE TITLE
Unable to create application gateway with path based routing

### ISSUE THREAD

**Issue by l3ender** [ansible/ansible_collections_azure#448]
##### SUMMARY
It is not possible to use `azure_rm_appgateway` with `request_routing_rules -> rule_type = path_based_routing`. When trying to do so, an error is reported that "Request Routing Rule routing must reference a UrlPathMap". However, there is no way to configure a UrlPathMap on `azure_rm_appgateway`.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure_rm_appgateway

##### ANSIBLE VERSION
```paste below
ansible 2.10.3
  config file = None
  configured module search path = ['/Users/ross/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.9.1 (default, Dec 10 2020, 10:36:35) [Clang 12.0.0 (clang-1200.0.32.27)]
```

##### CONFIGURATION
```paste below
(no output from ansible-config dump --only-changed)
```

##### OS / ENVIRONMENT
Mac OS Big Sur 11.2.2.

##### STEPS TO REPRODUCE
```yaml
---
- name: "Playbook to create necessary application gateway."
  hosts: localhost
  connection: local

  tasks:
  - name: "Create application gateway."
    azure.azcollection.azure_rm_appgateway:
      name: "myapp-gw"
      resource_group: "myapp"
      sku:
        capacity: 1
        name: "standard_v2"
        tier: "standard_v2"
      gateway_ip_configurations:
        - name: "appGatewayIpConfig"
          subnet:
            id: /subscriptions/mysubscription/resourceGroups/myapp/providers/Microsoft.Network/virtualNetworks/myapp-vnet/subnets/default
      frontend_ip_configurations:
        - name: "public-inbound-ip"
          public_ip_address: "myapp-ip"
      frontend_ports:
        - name: "public-bound-http"
          port: 80
      backend_address_pools:
        - name: "webapp"
          backend_addresses:
            - fqdn: "myapp-webapp.azurewebsites.net"
      backend_http_settings_collection:
        - name: "webapp-profile"
          port: 443
          protocol: https
          pick_host_name_from_backend_address: true
      http_listeners:
        - name: "inbound-http"
          frontend_ip_configuration: "public-inbound-ip"
          frontend_port: "public-bound-http"
      request_routing_rules:
        - name: "http-routing"
          rule_type: "path_based_routing"
          http_listener: "inbound-http"
          backend_address_pool: "webapp"
      location: "southcentralus"
```

##### EXPECTED RESULTS
It should be possible to use `azure_rm_appgateway` with `rule_type: "path_based_routing"` and provide URL paths for routing.

##### ACTUAL RESULTS
An error is returned that URL path map is not provided.

```paste below
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error creating the Application Gateway instance: Azure Error: ApplicationGatewayRequestRoutingRuleMustReference\nMessage: Request Routing Rule /subscriptions/mysubscription/resourceGroups/myapp/providers/Microsoft.Network/applicationGateways/myapp-gw/requestRoutingRules/http-routing must reference a UrlPathMap."}
```

However, there is no property on the module to be able to configure URL path map.
