### ISSUE TITLE
azure_rm_virtualmachine profile Failed to get credentials.

### ISSUE THREAD

**Issue by dtometzki** [ansible/ansible_collections_azure#455]
##### SUMMARY
hello together,
i define an ansible playbook with the profile for azure_rm_virtualmachine
profile: ~/.azure/credentials
what is the correct structure of this file ?
```
[default]
client_id = 11111111-1f11-1111-1111-af9c41b2c688
secret = 11L1111111111111111111111911111111
tenant = 12111111-1111-1311-1111-111111111111
subscription_id = 11111111-1111-1111-1111-011110101111
```
doesnt work. 

 "msg": "Failed to get credentials. Either pass as parameters, set environment variables, define a profile in ~/.azure/credentials

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
module

##### ANSIBLE VERSION
```
ansible 2.9.18
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/damian/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  executable location = /home/damian/.local/bin/ansible
  python version = 3.9.2 (default, Feb 20 2021, 00:00:00) [GCC 10.2.1 20201125 (Red Hat 10.2.1-9)]

```

##### OS / ENVIRONMENT
Fedora 33

##### STEPS TO REPRODUCE

```
- name: Create azure instances
  hosts: localhost
  gather_facts: true
  vars:
    ami: 'ami-038f1ca1bd58a5790'
    region: 'us-east-1'
    instance:
      - 'i-088c1533c1a2d069f'
  tasks:
    - name: Create a VM with existing storage account and NIC
      azure_rm_virtualmachine:
        **profile: ~/.azure/credentials** --> isnt working
        vm_size: Standard_B1ms
        resource_group: RG_Ansible
        name: testvm002
        admin_username: damian
        admin_password: *********
        # network_interfaces: testvm001
        image:
          offer: "CentOS"
          sku: '8_2'
          publisher: OpenLogic
          version: latest
```
##### ACTUAL RESULTS

```
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "accept_terms": false,
            "ad_user": null,
            "adfs_authority_url": null,
            "admin_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "admin_username": "damian",
            "allocated": true,
            "api_profile": "latest",
            "append_tags": true,
            "auth_source": null,
            "availability_set": null,
            "boot_diagnostics": null,
            "cert_validation_mode": null,
            "client_id": null,
            "cloud_environment": "AzureCloud",
            "custom_data": null,
            "data_disks": null,
            "generalized": false,
            "image": {
                "offer": "CentOS",
                "publisher": "OpenLogic",
                "sku": "8_2",
                "version": "latest"
            },
            "license_type": null,
            "location": null,
            "managed_disk_type": null,
            "name": "testvm002",
            "network_interface_names": null,
            "open_ports": null,
            "os_disk_caching": "ReadOnly",
            "os_disk_name": null,
            "os_disk_size_gb": null,
            "os_type": "Linux",
            "password": null,
            "plan": null,
            "profile": "~/.azure/credentials",
            "public_ip_allocation_method": "Static",
            "remove_on_absent": [
                "all"
            ],
            "resource_group": "RG_Ansible",
            "restarted": false,
            "secret": null,
            "short_hostname": null,
            "ssh_password_enabled": true,
            "ssh_public_keys": null,
            "started": true,
            "state": "present",
            "storage_account_name": null,
            "storage_blob_name": null,
            "storage_container_name": "vhds",
            "subnet_name": null,
            "subscription_id": null,
            "tags": null,
            "tenant": null,
            "virtual_network_name": null,
            "virtual_network_resource_group": null,
            "vm_identity": null,
            "vm_size": "Standard_B1ms",
            "winrm": null,
            "zones": null
        }
    },
    "msg": "Failed to get credentials. Either pass as parameters, set environment variables, define a profile in ~/.azure/credentials, or log in with Azure CLI (`az login`)."


```
