### ISSUE TITLE
No support for DNS alias record sets

### ISSUE THREAD

**Issue by tlourey** [ansible/ansible_collections_azure#467]
##### SUMMARY
No support for DNS alias record sets aka target resource. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure_rm_dnsrecordset
azure_rm_publicipaddress 

##### ANSIBLE VERSION

```paste below
ansible 2.10.2
  config file = None
  configured module search path = ['/home/tim/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/ansible/lib/python3.7/site-packages/ansible
  executable location = /opt/ansible/bin/ansible
  python version = 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]
```

```
ansible 2.10.7
  config file = /home/azureuser/.ansible.cfg
  configured module search path = ['/home/azureuser/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Nov 16 2020, 16:55:22) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Azure Cloud Shell
CentOS Linux release 7.9.2009 (Core)

##### STEPS TO REPRODUCE

None - option not documented on : https://docs.ansible.com/ansible/latest/collections/azure/azcollection/azure_rm_dnsrecordset_module.html#parameters

On https://docs.ansible.com/ansible/latest/collections/azure/azcollection/azure_rm_publicipaddress_module.html#parameters there is an option for domain_name but this only covers 'The customizable portion of the FQDN assigned to public IP address'

```yaml
- name: ensure an "A" record set with multiple records
  azure_rm_dnsrecordset:
    resource_group: myResourceGroup
    relative_name: www
    zone_name: testing.com
    record_type: A
    targetResouce: "/subscriptions/subid/resourceGroups/rg1/providers/Microsoft.Network//providers/Microsoft.Network/dnsZones/zonename/A/recordname"
```
```
- name: Create a public ip address
  azure_rm_publicipaddress:
    resource_group: myResourceGroup
    name: my_public_ip
    allocation_method: static
    targetzone: "subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/dnsZones/{zoneName}"
```

##### EXPECTED RESULTS

DNS Record created and linked to Alias object

##### ACTUAL RESULTS

Doesn't work

```paste below

```

References: 
https://docs.microsoft.com/en-us/rest/api/dns/recordsets/createorupdate#create-a-recordset-with-alias-target-resource
https://docs.microsoft.com/en-us/rest/api/dns/recordsets/createorupdate#subresource
https://docs.microsoft.com/en-us/rest/api/virtualnetwork/publicipaddresses/createorupdate#subresource
