### ISSUE TITLE
azure_rm_dnsrecordset doesn't apply metadata tags for records

### ISSUE THREAD

**Issue by tlourey** [ansible/ansible_collections_azure#470]
##### SUMMARY
azure_rm_dnsrecordset doesn't apply metadata tags for records even with set with append_tags: yes or absent. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure_rm_dnsrecordset

##### ANSIBLE VERSION

```paste below
 [azureuser@quickstartansible-vm ~]$ ansible --version
ansible 2.10.7
  config file = /home/azureuser/.ansible.cfg
  configured module search path = ['/home/azureuser/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Nov 16 2020, 16:55:22) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
[azureuser@quickstartansible-vm ~]$
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

CentOS Linux release 7.9.2009 (Core)

##### STEPS TO REPRODUCE

Run below play

```yaml
  - name: Set "A" record with Public IP address
    azure_rm_dnsrecordset: # used because azure_rm_dnsrecordset doesn't allow setting DNS Alias
      resource_group: "{{ dns_resource_group }}"
      relative_name: "{{ dnshostname }}"
      zone_name: "{{ dnszone }}"
      record_type: A
      records:
        - entry: "{{ output_ip_address.state.ip_address }}"
      append_tags: yes
      tags:
        tagname: value
```

##### EXPECTED RESULTS

Metadata key of tagname and value of value should exist on dns record created

##### ACTUAL RESULTS

Metadata does not exist

```paste below
TASK [Set "A" record with Public IP address] *************************************************************************************************************************************************************************[WARNING]: Azure API profile latest does not define an entry for DnsManagementClient
ok: [localhost]
```
