### ISSUE TITLE
azure_rm_storageaccount FileStorage does not support Premium_ZRS account_type

### ISSUE THREAD

**Issue by francois-travais** [ansible/ansible_collections_azure#481]
##### SUMMARY

The storage account module does not support the `account_type: Premium_ZRS` when `kind: FileStorage`

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

azure_rm_storageaccount

##### ANSIBLE VERSION

```paste below
ansible 2.9.16
  python version = 3.6.9 (default, Oct  8 2020, 12:12:24) [GCC 8.4.0]
```

##### OS / ENVIRONMENT

Windows 10 WSL 1

##### STEPS TO REPRODUCE

```yaml
- name: Setup Premium_ZRS FileStorage
  azure.azcollection.azure_rm_storageaccount:
    name: foo
    kind: FileStorage
    account_type: Premium_ZRS
    resource_group: my_rg
```

##### EXPECTED RESULTS

```
changed: [localhost]
```

##### ACTUAL RESULTS

```paste below
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Parameter error: Storage account with FileStorage kind require account type is Premium_LRS"}
```
