### ISSUE TITLE
Support of Azure SQL Server+Database Auditing and Diagnostics

### ISSUE THREAD

**Issue by juju4** [ansible/ansible_collections_azure#486]
##### SUMMARY
Neither module support to enable auditing or diagnostics and those would be recommended in many cases for any production setup, especially for security reasons.

https://docs.ansible.com/ansible/latest/collections/azure/azcollection/azure_rm_sqlserver_module.html
https://docs.ansible.com/ansible/latest/collections/azure/azcollection/azure_rm_sqldatabase_module.html

Equivalent feature in Terraform
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/mssql_database_extended_auditing_policy
https://github.com/terraform-providers/terraform-provider-azurerm/issues/6849

Microsoft docs
https://docs.microsoft.com/en-us/azure/azure-sql/database/auditing-overview
(REST API pages are currently 404...)
https://docs.microsoft.com/en-us/azure/templates/microsoft.sql/servers?tabs=json

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
azure_rm_sqlserver_module
azure_rm_sqldatabase_module

##### ADDITIONAL INFORMATION

```yaml
    - name: "Create Azure SQL Server Logical host"
      azure_rm_sqlserver: 
        admin_password: "{{password}}"
        admin_username: "{{admin}}"
        name: "{{sqlserver}}"
        resource_group: "{{resourcegroup}}"
        auditing:
          enabled: yes
          options: [STORAGE|LOGANALYTICS|EVENTHUB|MsOperations...]
        diagnostics:
          enabled: yes
          options: [Errors...]
    - name: "Create Azure SQL Database"
      azure_rm_sqldatabase: 
        name: "{{sqldb}}"
        resource_group: "{{resourcegroup}}"
        server_name: "{{sqlserver}}"
        auditing:
          enabled: yes
          options: [STORAGE|LOGANALYTICS|EVENTHUB|MsOperations...]
        diagnostics:
          enabled: yes
          options: [Errors...]
```
