### ISSUE TITLE
Replace azure_rm_keyvaultsecret_info with approved one

### ISSUE THREAD

**Issue by imjoseangel** [ansible/ansible_collections_azure#49]
##### ISSUE TYPE
- Introduce azure_rm_keyvaultsecret_info

##### COMPONENT NAME

azure_rm_keyvaultsecret_info.py

##### ADDITIONAL INFORMATION

```yaml
- name: Get secret current version
  azure_rm_keyvaultsecret_info:
    vault_uri: https://vault{{ rpfx }}.vault.azure.net
    name: testsecret
  register: facts

- name: Assert secret facts
  assert:
    that:
      - facts['secrets'] | length == 1
      - facts['secrets'][0]['sid']
      - facts['secrets'][0]['secret']
      - facts['secrets'][0]['tags']
      - facts['secrets'][0]['version']
```

##### ANSIBLE VERSION
2.10
