### ISSUE TITLE
azure_rm_resource - Documentation on how to fetch subresources information

### ISSUE THREAD

**Issue by bcchagas** [ansible/ansible_collections_azure#498]
##### SUMMARY

There is no example on the documentation for the module [azure_rm_resource](https://docs.ansible.com/ansible/2.8/modules/azure_rm_resource_module.html?highlight=azure_rm_resource) on how to fetch infomation of a subresource, such as a database of a DBforPostgreSQL. I'd like to provide one I'm using.

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME

resource azure_rm_resource

##### ANSIBLE VERSION

```paste below
2.8
```

##### EXAMPLE TO INCLUDE
```
- name: Get DBforPostgreSQL database info
  azure_rm_resource:
    resource_group: myResourceGroup
    provider: DBforPostgreSQL
    resource_type: servers
    resource_name: myDBforPostgreSQL
    subresource:
      - type: databases
        name: myDatabase
    api_version: "2017-12-01"
    method: GET
```
