### ISSUE TITLE
Unable to create service principal in Azure using ansible collection

### ISSUE THREAD

**Issue by anikm1987** [ansible/ansible_collections_azure#500]
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

azure.azcollection.azure_rm_adserviceprincipal

##### ANSIBLE VERSION

```paste below
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/ubuntu/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal

##### STEPS TO REPRODUCE

Configured environment variables -

export AZURE_CLIENT_ID="<client_id>"
export AZURE_SECRET="<secret>"
export AZURE_TENANT="tenant_id"

Then run command - 
ansible-playbook create-azure-rg-vars.yml --extra-vars "subscription_id=<subscription_id>"

```yaml

---
- hosts: localhost
  connection: local
  vars:
    azure_app_id: "e0a62513-1d81-480e-a6dc-5c99cdd58d9a"
  tasks:
    - name: Create resource group
      azure_rm_resourcegroup:
        name: ansible-AppResources-DevTest
        location: eastus2
        tags:
          ApplicationName  : "AnsibleTest"
        state: present
        append_tags: no 
      register: rg
      environment:
        AZURE_SUBSCRIPTION_ID: "{{ subscription_id }}"
    - debug:
        var: rg
    - debug:
        var: rg.state.id
    
    - name: Generate password
      set_fact:
        password: "{{ azure_app_id | password_hash('sha512') }}"
        tenant_id: "{{ lookup('env', 'AZURE_TENANT') }}"
        azure_client_id: "{{ lookup('env', 'AZURE_CLIENT_ID') }}"
 
    - name: Create app Service Principal
      azure.azcollection.azure_rm_adserviceprincipal:
        app_id: "{{ azure_app_id }}"
        state: present
        tenant: "{{ tenant_id }}"
      register: azure_output
      environment:
        AZURE_SUBSCRIPTION_ID: "{{ subscription_id }}"

    - name: Set SPN password
      azure.azcollection.azure_rm_adpassword:
        app_id: "{{ azure_app_id }}"
        service_principal_object_id: "{{ azure_output.object_id }}"
        state: present
        value: "{{ password }}"
        environment:
          AZURE_SUBSCRIPTION_ID: "{{ subscription_id }}"

    - debug:
        var: azure_output

```

##### EXPECTED RESULTS

ansible-playbook create-azure-rg-vars.yml --extra-vars "subscription_id=<subscription_id>" -vvvvv

This should create the resource group and one service principal with password.

##### ACTUAL RESULTS

```paste below

TASK [Create app Service Principal] ************************************************************************************************************************
task path: /mnt/c/pce/2021/github_repos/pce-hosting-portal-awx/samples/create-azure-rg-vars.yml:35
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: ubuntu
<127.0.0.1> EXEC /bin/sh -c 'echo ~ubuntu && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/ubuntu/.ansible/tmp/ansible-tmp-1618853901.74323-121896268505388 `" && echo ansible-tmp-1618853901.74323-121896268505388="` echo /home/ubuntu/.ansible/tmp/ansible-tmp-1618853901.74323-121896268505388 `" ) && sleep 0'
Using module_utils file ansible_collections/azure
Using module_utils file ansible_collections/azure/azcollection
Using module_utils file ansible_collections/azure/azcollection/plugins
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/basic.py
Using module_utils file ansible_collections/azure/azcollection/plugins/module_utils
Using module_utils file ansible_collections
Using module_utils file ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common_ext
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/common/__init__.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/parsing/__init__.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/_text.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/parsing/convert_bool.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/common/text/__init__.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/common/file.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/common/_collections_compat.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/common/sys_info.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/common/_json_compat.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/common/parameters.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/common/text/formatters.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/common/text/converters.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/six/__init__.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/common/_utils.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/pycompat24.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/common/validation.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/common/process.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/distro/__init__.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/distro/_distro.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/common/collections.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/common/dict_transformations.py
Using module_utils file ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/ansible_release.py
Using module file /home/ubuntu/.ansible/collections/ansible_collections/azure/azcollection/plugins/modules/azure_rm_adserviceprincipal.py
<127.0.0.1> PUT /home/ubuntu/.ansible/tmp/ansible-local-9546gm2zzpnz/tmp8ptm8ojq TO /home/ubuntu/.ansible/tmp/ansible-tmp-1618853901.74323-121896268505388/AnsiballZ_azure_rm_adserviceprincipal.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/ubuntu/.ansible/tmp/ansible-tmp-1618853901.74323-121896268505388/ /home/ubuntu/.ansible/tmp/ansible-tmp-1618853901.74323-121896268505388/AnsiballZ_azure_rm_adserviceprincipal.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'AZURE_SUBSCRIPTION_ID=1f913984-b1c8-4187-b297-415b71d6d278 /usr/bin/python3 /home/ubuntu/.ansible/tmp/ansible-tmp-1618853901.74323-121896268505388/AnsiballZ_azure_rm_adserviceprincipal.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/ubuntu/.ansible/tmp/ansible-tmp-1618853901.74323-121896268505388/ > /dev/null 2>&1 && sleep 0'

The full traceback is:
  File "/tmp/ansible_azure.azcollection.azure_rm_adserviceprincipal_payload_a0bjw075/ansible_azure.azcollection.azure_rm_adserviceprincipal_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_adserviceprincipal.py", line 153, in create_resource
  File "/home/ubuntu/.local/lib/python3.8/site-packages/azure/graphrbac/operations/service_principals_operations.py", line 87, in create
    raise models.GraphErrorException(self._deserialize, response)
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "ad_user": null,
            "adfs_authority_url": null,
            "api_profile": "latest",
            "app_id": "e0a62513-1d81-480e-a6dc-5c99cdd58d9a",
            "app_role_assignment_required": null,
            "auth_source": "auto",
            "cert_validation_mode": null,
            "client_id": null,
            "cloud_environment": "AzureCloud",
            "password": null,
            "profile": null,
            "secret": null,
            "state": "present",
            "subscription_id": null,
            "tenant": "<tenant_id>"
        }
    },
    "msg": "Error creating service principle, app id e0a62513-1d81-480e-a6dc-5c99cdd58d9a - Access Token missing or malformed."
}

```
