### ISSUE TITLE
azure_rm_deployment removes existing tags from resource group

### ISSUE THREAD

**Issue by russelljftw** [ansible/ansible_collections_azure#521]
##### SUMMARY
Re-submitting this Issue from the ansible repo
https://github.com/ansible/ansible/issues/32143 

azure_rm_deployment removes existing tags from the Resource group if no tags are provided in the module.  

if no tags are provided, all existing tags should remain in place. 

If the tags parameter is excluded, all tags are removed from the resource group. 
If the tags parameter is included with a new tag, all tags are kept and new tag is added
if the tags parameter is included with 1 existing tag, all tags are kept

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure_rm_deployment

##### ANSIBLE VERSION

```paste below
ansible 2.10.7
  config file = None
  configured module search path = ['/Users/username/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/3.1.0/libexec/lib/python3.9/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.9.2 (default, Mar 26 2021, 23:27:12) [Clang 12.0.0 (clang-1200.0.32.29)]

```

##### CONFIGURATION

```paste below
$ ansible-config dump --only-changed
[no changes]
```

##### OS / ENVIRONMENT

Mac OS 10.15.7
RHEL 7 

##### STEPS TO REPRODUCE

1 - Create a Resource group, and add Tags to resource group. 
2 - run ansible azure_rm_deployment 

```yaml
---

- name: TEST PLAYS
  hosts: localhost
  gather_facts: false

  tasks:

  - name: Run azure_rm_deployment
    azure_rm_deployment:
      resource_group: "TEST-ResourceGroup"
      append_tags: yes
      parameters:
        storageAccounts_name:
          value: storageaccount name
      template_link: "https://storageaaccount/storage_template.json"

```

##### EXPECTED RESULTS
Target Resource group would keep all existing tags: 
```paste below
"tags": {
  "PreExistingTag1": "Value1",
  "PreExistingTag2": "Value2"
}
```

##### ACTUAL RESULTS
All tags are removed from resource group:

```paste below
"tags": null

```
