### ISSUE TITLE
Add `zone` to azure_rm_virtualmachine_info module

### ISSUE THREAD

**Issue by ChandlerSwift** [ansible/ansible_collections_azure#522]
##### SUMMARY
The `azure_rm_virtualmachine_info` module doesn't provide a method for getting the availability zone information.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
azure_rm_virtualmachine_info

##### ADDITIONAL INFORMATION
When adding/updating a tag on a virtual machine in an availability zone, it fails if I don't provide the same zone when updating.
```yml
- name: Set tag
  azure.azcollection.azure_rm_virtualmachine:
    resource_group: "{{ resource_group }}"
    name: "{{ name }}"
    tags:
      new: "data"
  delegate_to: localhost
```
```
    "msg": "You can't change the Availability Zone of a virtual machine (have: [2], want: None)"
```
I'd like to be able to do this:
```yml
- name: Get VM Info for next step
  azure.azcollection.azure_rm_virtualmachine_info:
    resource_group: "{{ resource_group }}"
    name: "{{ name }}"
  delegate_to: localhost
  register: vm_info

- name: Set tag
  azure.azcollection.azure_rm_virtualmachine:
    resource_group: "{{ resource_group }}"
    name: "{{ name }}"
    tags:
      new: "data"
    zones: "{{ availability_zone }}"
  delegate_to: localhost
```
