### ISSUE TITLE
Further CosmosDB support

### ISSUE THREAD

**Issue by ghost** [ansible/ansible_collections_azure#527]
##### SUMMARY
I want to use CosmosDB Containers/Databases with Ansible.
As far as I am aware, currently only cosmosdbaccount and cosmosdbaccount_info exist, which only allow the creation
of a cosmosdb account. Creating Containers and Databases still has to be done using the Web Interface (or another way).
Explicitly I want to be able to configure the maximum RU/s as well as GB of storage for a given database.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
azure_rm_cosmosdatabase
azure_rm_cosmoscontainer

##### ADDITIONAL INFORMATION

This module would allow me to further automate the deployment of cosmosdb services.

```yaml
  - name: Create Cosmos Database
    azure_rm_cosmosdatabase:
      resource_group: test
      name: name
      cosmosdbaccount: testAccount
      maxrus: 10000
      size: 30
```
