### ISSUE TITLE
Add new module for diagnostic settings

### ISSUE THREAD

**Issue by AlvinRamoutar** [ansible/ansible_collections_azure#529]
##### SUMMARY

Add new module for diagnostic settings

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

azure_rm_diagnosticsetting

##### ADDITIONAL INFORMATION

Add a new module to make provisioning diagnostic settings for resources possible.

```yaml
  - name: Create Diagnostic Setting
    azure_rm_diagnosticsetting:
      name: myDiagnosticSetting
      resource_id: /subscriptions/1234abc0-1234-5678-90ab-cdefghijklmn/resourceGroups/myResourceGroup/providers/Microsoft.Network/applicationGateways/myApplicationGateway
      storage_account_id: /subscriptions/1234abc0-1234-5678-90ab-cdefghijklmn/resourceGroups/myResourceGroup/providers/Microsoft.Storage/storageAccounts/myStorageAccount
      logs: 
        - category: ApplicationGatewayFirewallLog
          retention_policy:
            days: 0
```
