### ISSUE TITLE
Allow Java 11 for linux webapp

### ISSUE THREAD

**Issue by x4FF3** [ansible/ansible_collections_azure#546]
##### SUMMARY

It is not possible to set  Java Version 11 for linux_fx_version
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

https://github.com/Azure/azure_preview_modules/blob/master/library/azure_rm_webapp.py

##### ANSIBLE VERSION

```paste below
ansible 2.10.7
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/ansible/library', '/usr/share/ansible/library']
  ansible python module location = /usr/local/lib/python3.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]

```

##### CONFIGURATION

```paste below
DEFAULT_MODULE_PATH(/etc/ansible/ansible.cfg) = ['/home/ansible/library', '/usr/share/ansible/library']
DEFAULT_MODULE_UTILS_PATH(/etc/ansible/ansible.cfg) = ['/home/ansible/library/utils', '/usr/share/ansible/library/utils']
DEFAULT_REMOTE_USER(/etc/ansible/ansible.cfg) = root
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = ['/usr/share/ansible/roles', '/etc/ansible/roles', '/home/ansible/roles']
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
PERSISTENT_CONNECT_TIMEOUT(/etc/ansible/ansible.cfg) = 30

```

##### STEPS TO REPRODUCE

create webapp linux and java version 11

```yaml
- name: create webapp java version 11
  azure.azcollection.azure_rm_webapp:
      auth_source: cli
      resource_group: "{{ resgroup }}"
      name: "{{ app }}"
      location: "{{ location }}"
      plan: "{{ sp }}"
      https_only: "{{ https_only }}"
      frameworks:
        - name: "{{ name }}"
          version: 11-java11
      startup_file: "{{ customer_setting_startup_file }}"
```

##### EXPECTED RESULTS

changed: [localhost]
##### ACTUAL RESULTS

module does not allow to set java version 11, even it is possible to set it manually via the portal.

```paste below
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Linux web app only supports java 8."}

```
