### ISSUE TITLE
Inventory plugin restrict plugin choices

### ISSUE THREAD

**Issue by guillaumewatteeux** [ansible/ansible_collections_azure#551]
##### SUMMARY
With Ansible 4.0.0, inventory plugin with "choices" keyword restrict valid value.
In my case, I used a company inventory plugins to wrap azure_rm. (to set keyed_groups, manage legacy hostname, use include_host_filters..... )

https://github.com/ansible-community/ansible-build-data/blob/main/4/CHANGELOG-v4.rst#included-collections
```
Now 'choices' keyword in config definitions also restricts valid values for the entry.
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure.azcollection.azure_rm inventory plugin
https://github.com/ansible-collections/azure/blob/dev/plugins/doc_fragments/azure_rm.py#L19

##### ANSIBLE VERSION
```
ansible [core 2.11.1] 
  config file = /home/guillaume/Workspaces/ansible/ansible.cfg
  configured module search path = ['/home/guillaume/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/guillaume/.pyenv/versions/3.9.5/envs/ansible4/lib/python3.9/site-packages/ansible
  ansible collection location = /home/guillaume/Workspaces/ansible/collections
  executable location = /home/guillaume/.pyenv/versions/ansible4/bin/ansible
  python version = 3.9.5 (default, May 27 2021, 09:52:00) [GCC 9.3.0]
  jinja version = 3.0.1
  libyaml = True
```

##### CONFIGURATION

```
CALLBACKS_ENABLED(/home/guillaume/Workspaces/ansible/ansible.cfg) = ['timer', 'profile_tasks', 'profile_roles']
COLLECTIONS_PATHS(/home/guillaume/Workspaces/ansible/ansible.cfg) = ['/home/guillaume/Workspaces/ansible/collections']
DEFAULT_ROLES_PATH(/home/guillaume/Workspaces/ansible/ansible.cfg) = ['/home/guillaume/Workspaces/ansible/roles']
DEFAULT_TIMEOUT(/home/guillaume/Workspaces/ansible/ansible.cfg) = 60
HOST_KEY_CHECKING(/home/guillaume/Workspaces/ansible/ansible.cfg) = False
INVENTORY_ANY_UNPARSED_IS_FAILED(/home/guillaume/Workspaces/ansible/ansible.cfg) = True
```

##### OS / ENVIRONMENT
Ubuntu 20.04 in WSL2

##### STEPS TO REPRODUCE

Create a inventory plugins like this:

```python
from ansible.plugins.inventory import BaseInventoryPlugin, Constructable
from ansible_collections.azure.azcollection.plugins.module_utils.azure_rm_common import AzureRMAuth
import ansible_collections.azure.azcollection.plugins.inventory.azure_rm as AzureInventory
from msrest import ServiceClient, Serializer, Deserializer


DOCUMENTATION = r'''
    name: azure_rm
    plugin_type: inventory
    short_description: Azure Resource Manager inventory plugin
    extends_documentation_fragment:
      - azure.azcollection.azure
      - azure.azcollection.azure_rm
'''

class InventoryModule(AzureInventory.InventoryModule):

    NAME = 'mycompany.azcollection.azure_rm'

    def _get_hosts(self):
        # Force legacy name
        self._legacy_hostnames = True

        super()._get_hosts()
```

Inventory:

```yaml
plugin: mycompany.azcollection.azure_rm
auth_source: auto
include_vm_resource_groups:
  - "*"
```

```shell
ansible-inventory -i inventory.azure_rm.yml --list
```

##### EXPECTED RESULTS
Inventory from azure 

##### ACTUAL RESULTS
```
[WARNING]:  * Failed to parse /home/guillaume/Workspaces/ansible/inventory.azure_rm.yml with auto plugin: Invalid value
"mycompany.azcollection.azure_rm" for configuration option "plugin_type: inventory plugin: ansible_collections.mycompany.azcollection.plugins.inventory.azure_rm setting: plugin
", valid values are: ['azure_rm', 'azure.azcollection.azure_rm']
[WARNING]:  * Failed to parse /home/guillaume/Workspaces/ansible/inventory.azure_rm.yml with yaml plugin: Plugin configuration YAML file,
not YAML inventory
[WARNING]:  * Failed to parse /home/guillaume/Workspaces/ansible/inventory.azure_rm.yml with ini plugin: Invalid host pattern '---'
supplied, '---' is normally a sign this is a YAML file.
ERROR! Completely failed to parse inventory source /home/guillaume/Workspaces/ansible/inventory.azure_rm.yml
```

**Comment by guillaumewatteeux** [comment]
.... 😅

Add plugin to DOCUMENTATION BLOCK..


```
DOCUMENTATION = r'''
    name: azure_rm
    plugin_type: inventory
    short_description: Azure Resource Manager inventory plugin
    extends_documentation_fragment:
      - azure.azcollection.azure
      - azure.azcollection.azure_rm
    options:
        plugin:
            description: marks this as an instance of the 'azure_rm' plugin
            required: true
            choices: ['mycompany.azcollection.azure_rm']
```
