### ISSUE TITLE
Retrieve Active Directory user or group

### ISSUE THREAD

**Issue by l3ender** [ansible/ansible_collections_azure#555]
##### SUMMARY
This feature would allow for retrieving user/group detail from Azure Active Directory.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
azure_rm_adprincipal_info

##### ADDITIONAL INFORMATION
This would be a very helpful module to use in combination with `azure_rm_roleassignment`, which requires the ID of the user or group to which the role is being assigned (`assignee_object_id`).

```yaml
- name: Retrieve AD user by name.
  azure_rm_adprincipal_info:
    name: "John Doe"
    type: "user"

- name: Retrieve AD user by principal.
  azure_rm_adprincipal_info:
    principal_name: "john.doe@company.org"
    type: "user"

- name: Retrieve AD group.
  azure_rm_adprincipal_info:
    name: "Network Engineers"
    type: "group"
```

If there is already means to retrieve the above, please provide information. Thank you!
