### ISSUE TITLE
Add ability for webapp vnet integration

### ISSUE THREAD

**Issue by l3ender** [ansible/ansible_collections_azure#556]
##### SUMMARY
This is a request for the ability to add [webapp vnet integration](https://docs.microsoft.com/en-us/cli/azure/webapp/vnet-integration?view=azure-cli-latest), so that networking configuration can be defined for a web app.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

azure_rm_webapp_vnetintegration – Manage Web App Virtual Network Integrations.
azure_rm_webapp_vnetintegration_info – Get Web App Virtual Network Integration facts.

##### ADDITIONAL INFORMATION
This would allow someone to associate a virtual network with a web application.

```yaml
- name: "Configure virtual network for web app."
  azure.azcollection.azure_rm_webapp_vnetintegration:
    resource_group: "MyResourceGroup"
    name: "MyWebapp"
    virtual_network_name: "MyVnetName"
    subnet: "MySubnetName"
```

Please offer thoughts/corrections to above naming. I plan to add a PR to support this feature and would like feedback in advance, if possible!
