### ISSUE TITLE
Idempotency fails for route table and route modules

### ISSUE THREAD

**Issue by l3ender** [ansible/ansible_collections_azure#557]
##### SUMMARY
The `azure_rm_routetable` and `azure_rm_route` modules both fail idempotency tests, and report a status of "changed" when rerunning the module with same inputs.

I believe the issue is related to using the `tags` property.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
* azure_rm_routetable
* azure_rm_route

##### ANSIBLE VERSION

```paste below
-> ansible --version
ansible [core 2.11.0]
  config file = None
  configured module search path = ['/Users/ross/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/ross/repos/myrbfcu-config/venv/lib/python3.9/site-packages/ansible
  ansible collection location = /Users/ross/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/ross/repos/myrbfcu-config/venv/bin/ansible
  python version = 3.9.1 (default, Dec 10 2020, 10:36:35) [Clang 12.0.0 (clang-1200.0.32.27)]
  jinja version = 3.0.1
  libyaml = True
```

##### CONFIGURATION

```paste below
-> ansible-config dump --only-changed

```

##### OS / ENVIRONMENT
Mac OS 11.4, using the latest azcollection version (1.6.0>

##### STEPS TO REPRODUCE
Run the following playbook, and then rerun it.

```yaml
---
- name: "Playbook to test routing idempotency."
  hosts: localhost
  connection: local
  gather_facts: true

  tasks:
  - name: "Create resource group for environment."
    azure.azcollection.azure_rm_resourcegroup:
      name: "idempotency-test-rg"
      location: "southcentralus"

  - name: "Configure app route table."
    azure.azcollection.azure_rm_routetable:
      name: "idempotency-test-routing"
      resource_group: "idempotency-test-rg"
      disable_bgp_route_propagation: true
      append_tags: false
      tags:
        Owner: "test@test.com"

  - name: "Configure app default route."
    azure.azcollection.azure_rm_route:
      name: "idempotency-test-default"
      resource_group: "idempotency-test-rg"
      address_prefix: "0.0.0.0/0"
      next_hop_type: "virtual_appliance"
      next_hop_ip_address: "1.1.1.1"
      route_table_name: "idempotency-test-routing"
      append_tags: false
      tags:
        Owner: "test@test.com"
```

##### EXPECTED RESULTS
The `azure_rm_routetable` and `azure_rm_route` should report status of "ok".

##### ACTUAL RESULTS
The `azure_rm_routetable` and `azure_rm_route` report a status of "changed".

```paste below
-> ansible-playbook sandbox.yml
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

PLAY [Playbook to test routing idempotency.] ********************************************************************************************************************************************

TASK [Gathering Facts] ******************************************************************************************************************************************************************
ok: [localhost]

TASK [Create resource group for environment.] *******************************************************************************************************************************************
ok: [localhost]

TASK [Configure app route table.] *******************************************************************************************************************************************************
changed: [localhost]

TASK [Configure app default route.] *****************************************************************************************************************************************************
changed: [localhost]

PLAY RECAP ******************************************************************************************************************************************************************************
localhost                  : ok=4    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```
