### ISSUE TITLE
Azure colletion is missing _action_groups_ metadata property

### ISSUE THREAD

**Issue by Naadwo** [ansible/ansible_collections_azure#569]
##### SUMMARY
Azure colletion is missing _action_groups_ metadata property which is causing some ansible functionalities to not work properly (for example module_defaults). I compared it with AWS collection (for which it is defined and it works properly): [runtime.yml](https://github.com/ansible-collections/community.aws/blob/main/meta/runtime.yml )

When I created a simple runtime file _ansible_collections/azure/azcollection/meta/runtime.yml_ 
```yaml
---
action_groups:
  azure:
  - azure_rm_resourcegroup_info
```
module_defaults worked for azure_rm_resourcegroup_info (but still didn't for other modules). 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Missing information in module metadata

##### ANSIBLE VERSION
Not relevant.

##### COLLECTION VERSION
Not relevant - checked in repo on latest version.

##### CONFIGURATION
Not relevant.

##### OS / ENVIRONMENT
Not relevant.

##### STEPS TO REPRODUCE
Run any module from connection and provide required parameters using _module_defaults_
```yaml
- block:
  - name: Check Azure Resource Group
    azure_rm_resourcegroup_info:
      name: "{{ _az_rg }}"
      list_resources: no
    register: _rg_result
  module_defaults:
    group\azure:
      client_id: "{{ _az_client_id }}"
      secret: "{{ _az_secret }}"
      subscription_id: "{{ _az_subscription_id }}"
      tenant: "{{ _az_tenant }}"
```

##### EXPECTED RESULTS
Module azure_rm_resourcegroup_info should work with parameters provided in module_defaults

##### ACTUAL RESULTS
Module fails because of missing parameters.

**Comment by Fred-sun** [comment]
@Naadwo Thanks for  your contribute, we are working in it!

**Comment by Fred-sun** [comment]
@Naadwo All modules are supported. Please try again as follows. Thank you very much!

```e.g.
---
- name: Using Azure collection
  hosts: localhost
  connection: local
  collections:
    - azure.azcollection
  module_defaults:
    azure_rm_****:
      client_id: "{{ client_id }}"
      secret: "{{ secret_id }}"
      subscription_id: "{{ subscription_id }}"
      tenant: "{{ tenant_id }}"
  tasks:
    - block:
      - name: Check Azure Resource Group
        azure_rm_***: #---- same with module_defaults set.
          parameter1: value1
         ***: ***
        register: _rg_result
    - debug:
        var: _rg_result

**Comment by Naadwo** [comment]
The example you pasted is only to define defaults for a single module - which doesn't make much sense, because the whole point of module_defaults is to apply it all modules from a collection at once (to avoid defining it per module). Defining it per module works, because it is using different mechanism. 
When `group\azure` is used, ansible is looking up for `action_groups` module metadata, which is missing here (see linked file for AWS).

**Comment by Fred-sun** [comment]
@Naadwo Yes, there is no way to specify multiple modules via group/azure, but you can set multiple modules as follows. To solve this problem, Please send questions migrated to https://github.com/ansible/ansible.git, this is ansible core without analytic module_defaults right assignment. Thank you very much!
```e.g.
---
- name: Using Azure collection
  hosts: localhost
  connection: local
  collections:
    - azure.azcollection
  module_defaults:
    azure_rm_****1:
      client_id: "{{ client_id }}"
      secret: "{{ secret_id }}"
      subscription_id: "{{ subscription_id }}"
      tenant: "{{ tenant_id }}"
    azure_rm_****2:
      client_id: "{{ client_id }}"
      secret: "{{ secret_id }}"
      subscription_id: "{{ subscription_id }}"
      tenant: "{{ tenant_id }}"
  tasks:
    - block:
      - name: Check Azure Resource Group
        azure_rm_***1: #---- same with module_defaults set.
          parameter1: value1
         ***: ***
      - name: Check Azure Resource Group
        azure_rm_***2: #---- same with module_defaults set.
          parameter1: value1
         ***: ***

**Comment by Fred-sun** [comment]
@Naadwo Please reference this link ---https://docs.ansible.com/ansible/latest/user_guide/playbooks_module_defaults.html ! Thank you very much!
```e.g.
Module defaults
If you frequently call the same module with the same arguments, it can be useful to define default arguments for that particular module using the module_defaults keyword.

**Comment by Geogboe** [comment]
@Fred-sun any chance this can be opened back up? The issue still persists. 

Per ansible docs: https://docs.ansible.com/ansible/latest/user_guide/playbooks_module_defaults.html#module-defaults-groups since v2.7 there should be an action group called 'azure' which allows you to specify parameters for all the azure modules. I guess when the azure collection was moved out of ansible core this configuration got removed.

It looks like the only change that needs to be made is to add an 'action_groups' block to https://github.com/ansible-collections/azure/blob/dev/meta/runtime.yml and add a list all the azure modules. 

for example
```yaml
action_groups:
  azure:
  - azure.azcollection.azure_rm_adapplication
  - azure.azcollection.azure_rm_adapplication_info
  - azure.azcollection.azure_rm_adgroup
....
```

This would be a really helpful feature for me if implemented. Thanks!
