### ISSUE TITLE
ansible awx azure.azcollection usage fails

### ISSUE THREAD

**Issue by nicolaibaralmueller** [ansible/ansible_collections_azure#572]
##### SUMMARY

It is required to upgrade python azure sdk in order use azure.azcollection modules. When upgrading my local python azure sdk modules (azure.azcollection.azure_rm_sqldatabase) work as expected. However old modules (azure_rm_sqldatabase) does not work anymore. 

This means every azure module usage must be migrated to use azure.azcollection. How is azure sdk updated on ansible awx 15.0.1? 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

azure.azcollection.azure_rm_sqldatabase

##### ANSIBLE VERSION

```paste below
2.9.14
```

##### COLLECTION VERSION

```paste below
1.7.0
```

##### STEPS TO REPRODUCE

```yaml
- name: Downsize SQL Database
    azure.azcollection.azure_rm_sqldatabase:
      tenant: '{{ tenant }}'
      client_id: '{{ client_id }}'
      secret: '{{ secret }}'
      subscription_id: '{{ subscription_id }}'
      resource_group: '{{ resource_group }}'
      server_name: MySQLServer
      name: MyDatabase
      sku:
        capacity: 10
        name: Standard
        tier: Standard
```

##### ACTUAL RESULTS

```paste below
{
    "msg": "Failed to import the required Python library (ansible[azure] (azure >= 2.0.0)) on awx's Python /usr/libexec/platform-python. Please read module documentation and install in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter",
    "exception": "Traceback (most recent call last):\n  File \"/tmp/ansible_azure.azcollection.azure_rm_sqldatabase_payload_kttj0a93/ansible_azure.azcollection.azure_rm_sqldatabase_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py\", line 243, in <module>\n    from azure.mgmt.managementgroups import ManagementGroupsAPI as ManagementGroupsClient\nModuleNotFoundError: No module named 'azure.mgmt.managementgroups'\n",
    "invocation": {
        "module_args": {
            "tenant": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "client_id": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "secret": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "subscription_id": "MySubscription",
            "resource_group": "MyResourceGroup",
            "server_name": "MySQLServer",
            "name": "MyDatabase",
            "sku": {
                "capacity": 10,
                "name": "Standard",
                "tier": "Standard",
                "size": null,
                "family": null
            },
            "auth_source": "auto",
            "cloud_environment": "AzureCloud",
            "api_profile": "latest",
            "append_tags": true,
            "read_scale": false,
            "zone_redundant": false,
            "state": "present",
            "profile": null,
            "ad_user": null,
            "password": null,
            "cert_validation_mode": null,
            "adfs_authority_url": null,
            "log_mode": null,
            "log_path": null,
            "tags": null,
            "location": null,
            "collation": null,
            "create_mode": null,
            "source_database_id": null,
            "source_database_deletion_date": null,
            "restore_point_in_time": null,
            "recovery_services_recovery_point_resource_id": null,
            "edition": null,
            "max_size_bytes": null,
            "elastic_pool_name": null,
            "sample_name": null,
            "force_update": null
        }
    },
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/libexec/platform-python"
    },
    "_ansible_no_log": false,
    "changed": false
}
```
