### ISSUE TITLE
Correct use of security_group with azure_rm_networkinterface unclear from documentation

### ISSUE THREAD

**Issue by LHurst-JM** [ansible/ansible_collections_azure#583]
##### SUMMARY

I think there are a couple of issues with the documentation for using security_group with a NIC.

1. The first is that if `create_with_security_group` is set to `False`, the security group is cleared - that is existing security groups are removed from the interface.  This is not clear from the documentation, which says "Whether a security group should be be created with the NIC.  If this flag set to True and no security_group set, a default security group will be created.".  I think a sentence should be added that reads "If this flag is set to `False` any existing security group will be removed from the NIC."

2. If `create_with_security_group` is set to `False`, any existing security group set using `security_group` will not be set (the NIC's existing `security_group` will in fact be cleared).  Again, this is unclear from the documentation which just describes `create_with_security_group` as controlling the creation of a new security group ("Whether a **security group should be be created** with the NIC." (amphasis mine)).  The above wording change (1.) would also clarify this behaviour (i.e. `security_group` only does anything with `create_with_security_group`).

3. If `create_with_security_group` is True and an existing security group is specifed for `security_group` (as documented - "An existing security group with which to associate the network interface.") the module fails for me with `Error creating or updating network interface nicName - Parameter 'FlowLog.target_resource_id' can not be None.`.  This exception is thrown in ` create_or_update_nic(self, nic)` and, with _debug set to `True`, I can see in syslog it does find the existing NSG so I am little lost as to the cause of this fault.

##### ISSUE TYPE

- Bug Report

##### COMPONENT NAME

azure_rm_networkinterface

##### ANSIBLE VERSION

```paste below
ansible [core 2.11.1] 
  config file = <redacted>/ansible.cfg
  configured module search path = ['<redacted>/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = <redacted>/ansible-venv/lib/python3.8/site-packages/ansible
  ansible collection location = <redacted>/.ansible/collections:/usr/share/ansible/collections
  executable location = <redacted>/ansible-venv/bin/ansible
  python version = 3.8.3 (default, Jul  2 2020, 16:21:59) [GCC 7.3.0]
  jinja version = 3.0.1
  libyaml = True
```

##### COLLECTION VERSION

```paste below
Collection         Version
------------------ -------
azure.azcollection 1.7.0  
```

##### CONFIGURATION

```paste below
DISPLAY_SKIPPED_HOSTS(<redacted>/ansible.cfg) = False
```

##### OS / ENVIRONMENT

CentOS 7.8.2003

##### STEPS TO REPRODUCE

`test_playbook.yml`:

```yaml
- name: Provision Resources
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Network interface
      azure.azcollection.azure_rm_networkinterface:
        name: existingNIC
        ip_configurations:
          - name: ipconfig1
            primary: True
            private_ip_address: 10.0.0.1
            private_ip_allocation_method: Static
        location: westeurope
        resource_group: myRG
        create_with_security_group: True
        subnet_name: mySN
        security_group:
           name: myNSG
           resource_group: myNetRg
        virtual_network:
            name: myVNET
            resource_group: myNetRg
```

inventory (as `inventory.azure_rm.yml`):

```yaml
plugin: azure_rm

auth_source: cli

keyed_groups:
  - key: resource_group
    prefix: rg
```

```
ansible-playbook -i inventory.azure_rm.yml test_playbook.yml
```

##### EXPECTED RESULTS

Play succeeds.

##### ACTUAL RESULTS

```paste below
The full traceback is:
  File "/tmp/ansible_azure.azcollection.azure_rm_networkinterface_payload_mlljrgib/ansible_azure.azcollection.azure_rm_networkinterface_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_netwo
rkinterface.py", line 807, in create_or_update_nic
  File "<redacted>/ansible-venv/lib/python3.8/site-packages/azure/mgmt/network/v2020_06_01/operations/_network_interfaces_operations.py", line 269, in create_or_update
    raw_result = self._create_or_update_initial(
  File "<redacted>/ansible-venv/lib/python3.8/site-packages/azure/mgmt/network/v2020_06_01/operations/_network_interfaces_operations.py", line 220, in _create_or_update_initial
    body_content = self._serialize.body(parameters, 'NetworkInterface')
  File "<redacted>/ansible-venv/lib/python3.8/site-packages/msrest/serialization.py", line 578, in body
    raise errors[0]
  File "<redacted>/ansible-venv/lib/python3.8/site-packages/msrest/serialization.py", line 220, in validate
    Serializer.validate(value, debug_name, **self._validation.get(attr_name, {}))
  File "<redacted>/ansible-venv/lib/python3.8/site-packages/msrest/serialization.py", line 661, in validate
    raise ValidationError("required", name, True)
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "ad_user": null,
            "adfs_authority_url": null,
            "api_profile": "latest",
            "append_tags": true,
            "auth_source": "auto",
            "cert_validation_mode": null,
            "client_id": null,
            "cloud_environment": "AzureCloud",
            "create_with_security_group": true,
            "dns_servers": null,
            "enable_accelerated_networking": false,
            "enable_ip_forwarding": false,
            "ip_configurations": [
                {
                    "application_security_groups": null,
                    "load_balancer_backend_address_pools": null,
                    "name": "ipconfig1",
                    "primary": true,
                    "private_ip_address": "10.0.0.1",
                    "private_ip_allocation_method": "Static",
                    "public_ip_address_name": null,
                    "public_ip_allocation_method": "Dynamic"
                }
            ],
            "location": "westeurope",
            "log_mode": null,
            "log_path": null,
            "name": "existingNIC",
            "open_ports": null,
            "os_type": "Linux",
            "password": null,
            "private_ip_address": null,
            "private_ip_allocation_method": "Dynamic",
            "profile": null,
            "public_ip": true,
            "public_ip_address_name": null,
            "public_ip_allocation_method": "Dynamic",
            "resource_group": "myRG",
            "secret": null,
            "security_group": {
                "name": "myNSG",
                "resource_group": "myNetRg",
                "subscription_id": "<redacted>"
            },
            "state": "present",
            "subnet_name": "mySN",
            "subscription_id": null,
            "tags": null,
            "tenant": null,
            "virtual_network": {
                "name": "myVNET",
                "resource_group": "myNetRg",
                "subscription_id": "<redacted>"
            }
        }
    },
    "msg": "Error creating or updating network interface existingNIC - Parameter 'FlowLog.target_resource_id' can not be None."
}

```
