### ISSUE TITLE
azure_rm_virtualmachine latest image selection incorrect

### ISSUE THREAD

**Issue by megrehncitrix** [ansible/ansible_collections_azure#601]
##### SUMMARY
In latest azcollection module azure_rm_virtualmachine selects an incorrect latest marketplace image.
The the selection logic assumes that the image list is returned in correct order with latest image as last of the list, this is not the case for some skus and the logic should be updated to retrieve the image flagged as latest, and not rely on an ordered list: https://github.com/ansible-collections/azure/blob/dev/plugins/modules/azure_rm_virtualmachine.py#L1973

Affects sku for generation 1 vm Server 2016:
`"publisher": "MicrosoftWindowsServer", "offer": "WindowsServer", "sku": "2016-Datacenter"`

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure_rm_virtualmachine

##### ANSIBLE VERSION

```
ansible 2.10.8
  python version = 3.6.8 (default, Nov 16 2020, 16:55:22) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
```

##### COLLECTION VERSION

```
Collection         Version
------------------ -------
azure.azcollection 1.5.0
```

##### STEPS TO REPRODUCE

Call the module for affected marketplace image: "publisher": "MicrosoftWindowsServer", "offer": "WindowsServer", "sku": "2016-Datacenter"
pass values for below:
```
- name: Create a Windows Virtual Machine
  azure_rm_virtualmachine:
    resource_group: "{{ resource_group }}"
    name: "{{ name }}"
    admin_username: "{{ admin_username }}"
    admin_password: "{{ admin_password }}"
    image:
      offer: WindowsServer
      publisher: MicrosoftWindowsServer
      sku: "2016-Datacenter"
      version: latest

```

##### EXPECTED RESULTS

This should create a vm with the latest image for the sku , which is `14393.4583.2108010852` today.

##### ACTUAL RESULTS
VM is created with the image version of `2016.127.20190416` an old version for sku "2016-Datacenter"

As a temporary workaround, we are pulling the latest marketplace image version from the Azure API before calling the module. Example: `az vm image show --location eastus --urn MicrosoftWindowsServer:WindowsServer:2016-Datacenter:latest`
