### ISSUE TITLE
azure_rm_keyvault_info not show storage field for access policies

### ISSUE THREAD

**Issue by Eugen1987** [ansible/ansible_collections_azure#61]
##### SUMMARY
The module azure_rm_keyvault_info not show storage field for access policies

From ansible/ansible #68167
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure_rm_keyvault_info

##### ANSIBLE VERSION

```
ansible 2.9.6

```

##### CONFIGURATION

```
None
```

##### OS / ENVIRONMENT

ansible 2.9.6
python version = 3.7.6 (v3.7.6:43364a7ae0, Dec 18 2019, 14:18:50) [Clang 6.0 (clang-600.0.57)]
macOs Catalina 10.15.1 (19B88)

##### STEPS TO REPRODUCE

1.  Get info with the azure_rm_keyvault_info module of  a keyvault  which has a storage access policy.

```yaml
    - name: Get Key Vault by name
      azure_rm_keyvault_info:
        resource_group: "{{ rg }}"
        name: "{{ kv_name }}"
      register: _kv_info

    - name:  Show keyvault info
      debug:
        msg: "{{ _kv_info }}"
```
##### EXPECTED RESULTS
```yaml
    - access_policies:
      - object_id: xxxx
        permissions:
          certificates:
          - get
          - list
          keys:
          - encrypt
          secrets:
          - get
          storage:
          - get
          - list
```

##### ACTUAL RESULTS

```yaml
    - access_policies:
      - object_id: xxxx
        permissions:
          certificates:
          - get
          - list
          keys:
          - encrypt
          secrets:
          - get
```
