### ISSUE TITLE
azure_rm_virtualmachine: data_disks -> lun required but not enforced

### ISSUE THREAD

**Issue by nbr23** [ansible/ansible_collections_azure#614]
##### SUMMARY
In azure_rm_virtualmachine, the suboption `lun` in `data_disks` is marked as required but not enforced.
Omitting this option crashes the module with a KeyError when the module attemps a `disk['lun']` access.

https://github.com/ansible-collections/azure/blob/0132b3009d5f9daa14e82db02cab0b91a830205b/plugins/modules/azure_rm_virtualmachine.py#L1475

https://github.com/ansible-collections/azure/blob/0132b3009d5f9daa14e82db02cab0b91a830205b/plugins/modules/azure_rm_virtualmachine.py#L1635

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure_rm_virtualmachine

##### ANSIBLE VERSION

```
ansible [core 2.11.0] 

```

##### COLLECTION VERSION

```
azure.azcollection 1.9.0  

```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE
Building a VM while attaching existing managed disks and omitting the `lun` option

```yaml
  - name: Create VM
    azure.azcollection.azure_rm_virtualmachine:
      resource_group: "{{ resource_group }}"
      name: myVM
      admin_username: nbr23
      image: 
          publisher: "debian"
          offer: "debian-10"
          sku: "10-gen2"
          version: "latest"
      location: eastus
      data_disks:
        - managed_disk_id: "{{ disk_id }}"

```

##### EXPECTED RESULTS

An explicit error being raised by `self.fail()`

##### ACTUAL RESULTS

The module crashes with KeyError

https://github.com/ansible-collections/azure/blob/0132b3009d5f9daa14e82db02cab0b91a830205b/plugins/modules/azure_rm_virtualmachine.py#L1475

https://github.com/ansible-collections/azure/blob/0132b3009d5f9daa14e82db02cab0b91a830205b/plugins/modules/azure_rm_virtualmachine.py#L1635

Thanks!

**Comment by Fred-sun** [comment]
@nbr23 Thank you for contributing this question, can you share your full Yaml? Easy to copy and repair locally. Thank you very much!

**Comment by Fred-sun** [comment]
@nbr23 In addition, the suboptions of data_disks are not defined in the module ARG, so the documentation is not completely correct. Thank you very much!

**Comment by nbr23** [comment]
Yes, the documentation is not fully accurate. And once we specify the `lun` in my specific case, then we get hit by https://github.com/ansible-collections/azure/issues/146 unfortunately.

Working on getting you a shareable full yaml.
Thanks!

**Comment by Fred-sun** [comment]
> Yes, the documentation is not fully accurate. And once we specify the `lun` in my specific case, then we get hit by #146 unfortunately.
> 
> Working on getting you a shareable full yaml.
> Thanks!

Ok， I will try it! Thank you very much!

**Comment by nbr23** [comment]
```yaml
    - name: Create data disk
      azure.azcollection.azure_rm_manageddisk:
        resource_group: "{{ resource_group }}"
        name: 'testvm-data'
        location: eastus
        disk_size_gb: 64
        storage_account_type: Standard_LRS
      register: datadisk

    - name: Create VM
      azure.azcollection.azure_rm_virtualmachine:
        resource_group: "{{ resource_group }}"
        name: testvm
        admin_username: testuser
        admin_password: '{{ vm_password }}'
        vm_size: Standard_D2s_v3
        managed_disk_type: Standard_LRS
        os_disk_name: testvm-os
        os_disk_size_gb: 120
        image: 
            publisher: "debian"
            offer: "debian-10"
            sku: "10-gen2"
            version: "latest"
        location: eastus
        public_ip_allocation_method: Disabled
        data_disks:
          - managed_disk_id: '{{ datadisk.state.id }}'

```
