### ISSUE TITLE
azure_rm_securitygroup.py

### ISSUE THREAD

**Issue by rohmattriindra** [ansible/ansible_collections_azure#615]
##### SUMMARY
The **existing rule** will be replaced with a **new rule** with the **same rule name** on a different priority

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
ansible 2.10.4
```

##### COLLECTION VERSION

```paste below
 1.4.0
```

##### CONFIGURATION

```
```

##### OS / ENVIRONMENT

Ubuntu 18.04 with Python 3 virtual environment.

##### STEPS TO REPRODUCE

```yaml
  - name: Create rules 1
      azure_rm_securitygroup:
        resource_group: "{{ resource_group }}"
        name: "{{ network_security_group }}"
        rules:
            - name: allow-icmp-1
              protocol: Icmp
              source_address_prefix: "*"
              destination_address_prefix:
              - "172.24.0.0/16"
              destination_port_range: "*"
              access: Allow
              priority: 201
              direction: Inbound
        state: present

    - name: Create rules 2
      azure_rm_securitygroup:
        resource_group: "{{ resource_group }}"
        name: "{{ network_security_group }}"
        rules:
            - name: allow-icmp-1
              protocol: Icmp
              source_address_prefix: "*"
              destination_address_prefix:
              - "172.24.0.0/16"
              destination_port_range: "*"
              access: Allow
              priority: 202
              direction: Inbound
        state: present
```

##### EXPECTED RESULTS

Based on the step reproduce above, the rule name with priority 201 will be replaced with priority 202 ( rule with priority 201 is gone ). Since to avoid the multiple rules in 1 task, I try to split 1 rule that represents 1 task. I'm afraid when I put multiple rules in 1 task, and accidentally change state to absent, all rules will be gone. I think the "error message" should appear and not replace the existing rule

##### ACTUAL RESULTS

The existing rule
```bash
Name          ResourceGroup    Priority    SourcePortRanges    SourceAddressPrefixes    SourceASG    Access    Protocol    Direction    DestinationPortRanges    DestinationAddressPrefixes    DestinationASG
------------  ---------------  ----------  ------------------  -----------------------  -----------  --------  ----------  -----------  -----------------------  ----------------------------  ----------------
allow-icmp-1  network          201         *                   *                        None         Allow     ICMP        Inbound      *                        172.24.0.0/16                 None
```
Execute ansible playbook
```bash
TASK [Create rules 1] ********************************************************************************************
ok: [localhost]

TASK [Create rules 2] *********************************************************************************************
changed: [localhost]

PLAY RECAP ********************************************************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```

the new rule replaced the existing ( previously with priority 201 )
```bash
Name          ResourceGroup    Priority    SourcePortRanges    SourceAddressPrefixes    SourceASG    Access    Protocol    Direction    DestinationPortRanges    DestinationAddressPrefixes    DestinationASG
------------  ---------------  ----------  ------------------  -----------------------  -----------  --------  ----------  -----------  -----------------------  ----------------------------  ----------------
allow-icmp-1  network          202         *                   *                        None         Allow     Icmp        Inbound      *                        172.24.0.0/16                 None
```
