### ISSUE TITLE
azure_rm_deployment removes tags on Resource Group

### ISSUE THREAD

**Issue by nmajin** [ansible/ansible_collections_azure#628]
##### SUMMARY
This module remove existing tags from a Resource Group, which was tested with an AKS install.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure_rm_deployment

##### ANSIBLE VERSION

```
ansible 2.9.21
```

##### COLLECTION VERSION

```
1.9.0
```

##### CONFIGURATION

```
DEFAULT_REMOTE_USER(/Users/<user REDACTED>/.ansible.cfg) = admin
GALAXY_SERVER_LIST(/Users/<user REDACTED>/.ansible.cfg) = ['automation_hub']
HOST_KEY_CHECKING(/Users/<user REDACTED>/.ansible.cfg) = False
RETRY_FILES_ENABLED(/Users/<user REDACTED>/.ansible.cfg) = False
```

##### OS / ENVIRONMENT
macOS Big Sur

##### STEPS TO REPRODUCE
Run playbook to run task to create resource group with tags and task to deploy AKS cluster. Apparently this was an issue with the modules packaged with ansible: https://github.com/ansible/ansible/issues/32143, but even the built-in modules have the same issue with this version of ansible.

```
- name: Create resource group
  azure.azcollection.azure_rm_resourcegroup:
    name: "{{ resource_group_name }}"
    location: "{{ location }}"
    tags:
      tag1: "abc"
      tag2: "123"

- name: Create cluster
  azure.azcollection.azure_rm_deployment:
    location: "{{ location }}"
    resource_group_name: "{{ resource_group_name }}"
    state: present
    template: "{{ templatePath }}"
    parameters: "{{ paramsPath }}"
    append_tags: no
```

##### EXPECTED RESULTS
Expect the tags to NOT get wiped out on the Resource Group

##### ACTUAL RESULTS
Tags are removed from the Resource Group

```
PLAY [AKS Provisioning] *******************************************************************************************************************************************************************************************

TASK [Create resource group] **************************************************************************************************************************************************************************************
changed: [localhost]

TASK [Provision cluster] ******************************************************************************************************************************************************************************************
changed: [localhost]

PLAY RECAP ********************************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0  

```
