### ISSUE TITLE
NSG rule with source_address_prefix "Internet" not supported

### ISSUE THREAD

**Issue by tepene** [ansible/ansible_collections_azure#639]
##### SUMMARY

According to the documentation it should be possible to use default tags in the parameter "rules.source_address_prefix"
`Default tags such as VirtualNetwork, AzureLoadBalancer and Internet can also be used.`

When I use the default tag `Internet` in a rule, i get an error **Unsupported value used: Internet**. When I specify a prefix such as **172.23.0.0/16** the rule is accepted without errors

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

azure.azcollection.azure_rm_securitygroup

##### ANSIBLE VERSION

```paste below
ansible 2.9.26
  config file = /workspaces/azure-setup/ansible.cfg
  configured module search path = ['/home/vscode/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/vscode/.local/lib/python3.6/site-packages/ansible
  executable location = /home/vscode/.local/bin/ansible
  python version = 3.6.14 (default, Aug 17 2021, 16:32:35) [GCC 10.2.1 20210110]
```

##### COLLECTION VERSION

```paste below
1.9.0
```

##### CONFIGURATION

```paste below
COLLECTIONS_PATHS(/workspaces/azure-setup/ansible.cfg) = ['/workspaces/azure-setup/collections']
DEFAULT_CALLBACK_WHITELIST(/workspaces/azure-setup/ansible.cfg) = ['ansible.posix.profile_tasks']
DEFAULT_HOST_LIST(/workspaces/azure-setup/ansible.cfg) = ['/workspaces/azure-setup/inventory']
DEFAULT_LOAD_CALLBACK_PLUGINS(/workspaces/azure-setup/ansible.cfg) = True
DEFAULT_ROLES_PATH(/workspaces/azure-setup/ansible.cfg) = ['/workspaces/azure-setup/roles']
DEFAULT_STDOUT_CALLBACK(/workspaces/azure-setup/ansible.cfg) = yaml
DEFAULT_VAULT_PASSWORD_FILE(env: ANSIBLE_VAULT_PASSWORD_FILE) = /workspaces/shared/azure/.vault_pass.txt
DISPLAY_SKIPPED_HOSTS(/workspaces/azure-setup/ansible.cfg) = False
GALAXY_SERVER_LIST(/workspaces/azure-setup/ansible.cfg) = ['automation_hub', 'release_galaxy']
```

##### OS / ENVIRONMENT

Azure NSG

##### STEPS TO REPRODUCE

```yaml
- name: Create network security groups
  azure.azcollection.azure_rm_securitygroup:
    subscription_id: "{{ azure_module_defaults.subscription_id }}"
    client_id: "{{ azure_module_defaults.client_id }}"
    secret: "{{ azure_module_defaults.secret }}"
    tenant: "{{ azure_module_defaults.tenant }}"
    resource_group: "{{ item.0.resource_group }}"
    name: "{{ item.1.nsg_name }}"
    purge_rules: true
    rules: "{{ item.1.nsg_rules }}"
  loop: "{{ tmp_subnet|subelements('subnet', skip_missing=True) }}"
  loop_control:
    label: "{{ item.1.nsg_name|default(omit) }}"
  when: item.1.gateway_subnet|bool is false
```

Example Input for `rules:` 
```yaml
          - name: HTTP
            priority: "111"
            access: Allow
            direction: Inbound
            protocol: Tcp
            source_address_prefix:
              - "Internet"
            source_port_range: "*"
            destination_address_prefix: "VirtualNetwork"
            destination_port_range:
              - "443"
```

##### EXPECTED RESULTS

NSG Rule with source "Internet" and destination "VirtualNetwork"

##### ACTUAL RESULTS

Unsupported value used: Internet

```paste below
    Error creating/updating security group nsg-bondix-01 - Azure Error: SecurityRuleParameterContainsUnsupportedValue
    Message: Security rule parameter SourceAddressPrefix for rule with Id /subscriptions/c6da2853-bd3e-4600-9637-a4a28e2eab67/resourceGroups/rg-bondix-test/providers/Microsoft.Network/networkSecurityGroups/nsg-bondix-01/securityRules/Bondix-01 cannot specify existing VIRTUALNETWORK, INTERNET, AZURELOADBALANCER, '*' or system tags. Unsupported value used: Internet.
```

**Comment by nbr23** [comment]
Hi @tepene 

Try not using a list for `source_address_prefix`. I think lists only work if you're using IPs/CIDR ranges.
This makes sense if you compare to the web UI, you if you use Service Tag as the source, you must pick one, you cannot specify several.

The following works for me:
```
          - name: HTTP
            priority: "111"
            access: Allow
            direction: Inbound
            protocol: Tcp
            source_address_prefix: "Internet"
            source_port_range: "*"
            destination_address_prefix: "VirtualNetwork"
            destination_port_range:
              - "443"
```
