### ISSUE TITLE
VM generation not supported in azure.azcollection.azure_rm_galleryimage

### ISSUE THREAD

**Issue by ghost** [ansible/ansible_collections_azure#646]
##### SUMMARY
Will allow for v2 generation of VM's in image gallery 

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
azure.azcollection.azure_rm_galleryimage

##### ADDITIONAL INFORMATION
Used to create an image gallery that supports v2 images
```
-   name: Create or update gallery image
    azure_rm_galleryimage:
        hyperVGeneration: V2  <- this is what id like to add
        resource_group: '{{ clientname }}-rg'
        gallery_name: '{{ clientname }}avdimages'
        name: Windows10MSPrimary-Gold
        location: '{{ location }}'
        os_type: windows
        os_state: generalized
        identifier:
            publisher: '{{ clientname }}Publisher'
            offer: '{{ clientname }}Offer'
            sku: '{{ clientname }}SKU'
        disallowed:
            disk_types: Standard_LRS
        recommended:
            memory:
                max: 64
                min: 8
            v_cpus:
                max: 24
                min: 4
```
