### ISSUE TITLE
vm from existing managed disk

### ISSUE THREAD

**Issue by DII-dsward** [ansible/ansible_collections_azure#655]
How to create a VM from an existing managed disk? We have a VHD that we'd like to convert to a managed disk and deploy the VM. Not seeing any documentation on that.

```yaml
- name: Create managed disk from vhd
  azure_rm_manageddisk:
    name: "{{ vm_name }}-OS"
    location: "{{ Region }}"
    resource_group: "{{ ResourceGroup }}"
    create_option: import
    source_uri: "{{ vhd_uri }}"
    os_type: linux
    storage_account_type: Premium_LRS
    state: present

- name: Create Virtual Appliance
  azure_rm_virtualmachine:
    state: present
    resource_group: "{{ ResourceGroup }}"
    name: "{{ vm_name }}"
    vm_size: "{{ vm_size }}"
    network_interfaces: "{{ vm_nic_1 }}"
    os_disk_name: "{{vm_name}}-OS"
    managed_disk_type: "Premium_LRS"
    boot_diagnostics:
      enabled: "yes"
      storage_account: "{{ diag_name }}"
    availability_set: "{{ avs_name }}"
```
