### ISSUE TITLE
Feature Proposal: eventgridsubscriptions

### ISSUE THREAD

**Issue by howardjones** [ansible/ansible_collections_azure#664]
##### SUMMARY

(I'm actually proposing that I will write this feature, at least for the part that I have a use-case for)

Add `azure.azcollection.azure_rm_eventgridsubscription` to allow creation of webhook event listeners on Azure objects that support them (my use-case is KeyVaults). 

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
azure.azcollection.azure_rm_eventgridsubscription

##### ADDITIONAL INFORMATION

Ansible does not currently allow you to add event listeners to objects. This is useful for additional automation while 
creating a deployment. 

There is a larger scope for the full eventgrid product with eventgrid domains etc. My personal use-case doesn't need that, but that's why I'm proposing eventgridsubscription as a seperate module from (e.g.) azure_rm_eventgriddomain or the other routing objects.

```yaml

azure.azcollection.azure_rm_eventgridsubscription:
    name: my-event-hook
    destination_type: webhook
    webhook_url: https://someplace.com/
    event_types:
    - Microsoft.KeyVault.SecretNearExpiry
    - Microsoft.KeyVault.SecretExpired
    scope: /subscriptions/12345678-1234-1234-1234-1234567890/resourceGroups/vault-test/providers/Microsoft.KeyVault/vaults/testvault42
    state: present
    subscription_id: 12345678-1234-1234-1234-1234567890

```
