### ISSUE TITLE
module 'azure.mgmt.storage._storage_management_client' has no attribute 'VERSION'

### ISSUE THREAD

**Issue by fiftin** [ansible/ansible_collections_azure#669]
##### SUMMARY

https://github.com/ansible/ansible/issues/76169

**Comment by Fred-sun** [comment]
@fiftin Thank you for submitting this problem, could you please help confirm the installation (Azure - MgmT-storage ==11.1.0), if not, please help reinstall and try again. Thank you very much!

**Comment by fiftin** [comment]
yes, I use this version.

**Comment by Fred-sun** [comment]
@fiftin According to the error log, because the track2 package you are using caused the error, can you uninstall and install the specified version again? Thank you very much!

**Comment by Fred-sun** [comment]
Any update?

**Comment by fiftin** [comment]
I reinstalled it several times.

**Comment by Fred-sun** [comment]
@fiftin Could you please provide information about your test environment and Playbook? Thank you very much!

**Comment by fiftin** [comment]
Ubuntu 20.04

```console
$ ansible --version
ansible [core 2.11.5]
  config file = None
  configured module search path = ['/home/ec2-user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ec2-user/.local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/ec2-user/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/ec2-user/.local/bin/ansible
  python version = 3.8.10 (default, Sep 28 2021, 16:10:42) [GCC 9.3.0]
  jinja version = 2.10.1
  libyaml = True
```


```yaml (paste below)
- name: copy build to Azure
  azure_rm_storageblob:
    resource_group: ***
    storage_account_name: ***
    container: "{{ build_container_name }}"
    blob: "{{ item }}"
    src: "{{ build_root_dir }}/distrib/directory/{{ item }}"
    client_id: "{{ manager_access_key }}"
    secret: "{{ manager_secret_key }}"
    subscription_id: "{{ manager_subscription }}"
    tenant: "{{ manager_domain }}"
```
