### ISSUE TITLE
azure_rm_manageddisk_info managed_by not working

### ISSUE THREAD

**Issue by DII-dsward** [ansible/ansible_collections_azure#679]
Due to the dynamic inventory script not populating the names of the managed disks attached to a VM, I am trying to pull the names of the managed disks attached to a 'vm fqid'. 

```yaml
    - name: Get Disks managed by VM
      azure_rm_manageddisk_info:
        managed_by: "{{ id }}"
      register: vmdisks
    - debug:
        var: vmdisks
```

The error returned it...
fatal: [DVMANFSTEST01.dii.local]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (azure_rm_manageddisk_info) module: managed_by Supported parameters include: ad_user, adfs_authority_url, api_profile, append_tags, auth_source, cert_validation_mode, client_id, cloud_environment, name, password, profile, resource_group, secret, subscription_id, tags, tenant"}

Following this documentation
https://github.com/ansible-collections/azure/blob/dev/plugins/modules/azure_rm_manageddisk_info.py

##### SUMMARY
This playbook is returning an error saying managed_by is not a valid parameter
```yaml
      azure_rm_manageddisk_info:
        managed_by: "{{ id }}"
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure.azcollection.azure_rm_manageddisk_info

##### ANSIBLE VERSION
ansible 2.9

##### OS / ENVIRONMENT
Ansible Tower 3.8.4

**Comment by nbr23** [comment]
Hi @DII-dsward,
~~As far as I know, the best way to get this info today is to use `azure_rm_virtualmachine_info` and look at the returned [data_disks](https://docs.ansible.com/ansible/latest/collections/azure/azcollection/azure_rm_virtualmachine_info_module.html#return-vms/data_disks) list.~~

Edit: Disregard, this doesn't give as much info as I thought.

Cheers!

**Comment by kinect1things** [comment]
I have checked azure_rm_virtualmachine_info, but it does not show the name of the disk. I'm not seeing how to use azure_rm_manageddisk to tag it if i cannot get the name of these disks.
```yaml
---
- name: Get managed disks
  azure_rm_virtualmachine_info:
    resource_group: "{{ resource_group }}"
    name: "{{ inventory_hostname_short }}"
  register: vminfo
- debug:
    var: vminfo
```
```yaml
"data_disks": [
                    {
                        "lun": 0,
                        "disk_size_gb": 10,
                        "managed_disk_type": "Standard_LRS",
                        "caching": "None"
                    }
```

**Comment by nbr23** [comment]
@kinect1things you're absolutely right, my bad!

However, jumping back to the original post, filtering `azure_rm_manageddisk_info` with `managed_by` does work if you give the full VM path (eg `/subscriptions/XXXXXX-XXX-XXXX-XXX-XXXXXXXXXX/resourceGroups/RGNAME-eastus2/providers/Microsoft.Compute/virtualMachines/myVM`).

This successfully lists the attached disks in my test cases:
```yaml
    - name: Get Disks associated with my VM
      azure.azcollection.azure_rm_manageddisk_info:
        managed_by: /subscriptions/XXXXXX-XXX-XXXX-XXX-XXXXXXXXXX/resourceGroups/RGNAME-eastus2/providers/Microsoft.Compute/virtualMachines/myVM
```

@DII-dsward  can you confirm which version of the azure collection you are using? I suspect you are using an older version. Support for this was merged in [October 2020](https://github.com/ansible-collections/azure/commit/b697acc08b692c641f0450e582a9b7607e5f501f#diff-8b5a8a2ae2de0b64e02d36f1032de4c580324ec1bddf6b68aefdb3ec9f94f22e)

**Comment by DII-dsward** [comment]
This is the playbook i'm using
```yaml
---
- hosts: vms
  connection: local
  collections:
    - azure.azcollection
  tasks:
     - debug:
        var: id
    - name: Get Disks managed by VM
      azure_rm_manageddisk_info:
        managed_by: "{{ id }}"
      register: vmdisks
    - debug:
        var: vmdisks
```

The Output looks like this
```
PLAY [vms] ***********************************************************
TASK [debug] *******************************************************************
ok: [SERVERNAME.domain.com] => {
    "id": "/subscriptions/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXXX/resourceGroups/resourcegroup1/providers/Microsoft.Compute/virtualMachines/SERVERNAME"
}
TASK [Get Disks managed by VM] *************************************************
fatal: [SERVERNAME.domain.com]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/libexec/platform-python"}, "changed": false, "msg": "Unsupported parameters for (azure_rm_manageddisk_info) module: managed_by Supported parameters include: ad_user, adfs_authority_url, api_profile, append_tags, auth_source, cert_validation_mode, client_id, cloud_environment, name, password, profile, resource_group, secret, subscription_id, tags, tenant"}
PLAY RECAP *********************************************************************
SERVERNAME.domain.com    : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
```
