### ISSUE TITLE
Could not retrieve credential from local cache for service principal ***. Please run 'az login' for this service principal."

### ISSUE THREAD

**Issue by dkirrane** [ansible/ansible_collections_azure#688]
##### SUMMARY

 `azure_rm_postgresqlfirewallrule` `auth_source` `cli` no longer working 

##### ISSUE TYPE
```
fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "Error retrieving resource group my-rg - Could not retrieve credential from local cache for service principal ***. Please run 'az login' for this service principal."}
```

##### COMPONENT NAME

`azure_rm_postgresqlfirewallrule`

##### ANSIBLE VERSION

```paste below
ansible-4.8.0
```

##### COLLECTION VERSION

```paste below
azure.azcollection:1.10.0
```

##### CONFIGURATION

```paste below
- name: Configure PostgreSQL firewall rule
  azure_rm_postgresqlfirewallrule:
    auth_source: cli
    resource_group: "{{ resource_group }}"
    server_name: "{{ server_name }}"
    name: github-action
    start_ip_address: "{{ gh_runner_ip }}"
    end_ip_address: "{{ gh_runner_ip }}"
    state: "present"
```

##### OS / ENVIRONMENT

I suspect this maybe related to GitHub Actions Azure CLI login change: https://stackoverflow.com/questions/69895247/could-not-retrieve-credential-from-local-cache-for-service-principal-when-usin

But workaround posted here doesn't apply to Ansible.

```
      - uses: actions/checkout@v2

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # ... Install Ansible etc..

      - name: Ansible Run
        run: ansible-playbook -i hosts.ini playbook.yml
```
