### ISSUE TITLE
`azure_rm_appserviceplan` not idempotent for premium app service plans

### ISSUE THREAD

**Issue by l3ender** [ansible/ansible_collections_azure#692]
##### SUMMARY
When using `azure_rm_appserviceplan`, idempotency fails for premium app service plans.

The SKU returned from an existing premium plan includes lower case (`P1v2`), but the module comparison converts input parameters to upper case (`P1V2`) and so the idempotency check fails.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure_rm_appserviceplan

##### ANSIBLE VERSION

```bash
-> ansible --version
ansible [core 2.11.6]
  config file = None
  configured module search path = ['/Users/ross/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/ross/repos/azure/venv/lib/python3.9/site-packages/ansible
  ansible collection location = /Users/ross/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/ross/repos/azure/venv/bin/ansible
  python version = 3.9.6 (default, Jun 29 2021, 05:25:02) [Clang 12.0.5 (clang-1205.0.22.9)]
  jinja version = 3.0.2
  libyaml = True
```

##### COLLECTION VERSION

```yaml
-> ansible-galaxy collection list azure.azcollection

# /Users/ross/repos/azure/venv/lib/python3.9/site-packages/ansible_collections
Collection         Version
------------------ -------
azure.azcollection 1.10.0
```

##### CONFIGURATION

```yaml
-> ansible-config dump --only-changed
```

##### STEPS TO REPRODUCE

Sample playbook demonstrating the issue:
```yaml
---
- name: "Playbook for testing."
  hosts: "localhost"
  connection: "local"
  gather_facts: false
  vars:
    resource_group: "automated-testing"
  collections:
    - azure.azcollection

  tasks:
    - name: create premium linux plan
      azure_rm_appserviceplan:
        resource_group: "{{ resource_group }}"
        name: "test-premium-plan"
        sku: P1v2
        is_linux: true
      register: output

    - name: assert app service was created
      assert:
        that:
          - output.changed
          - output.id

    - name: create premium linux plan idempotent
      azure_rm_appserviceplan:
        resource_group: "{{ resource_group }}"
        name: "test-premium-plan"
        sku: P1v2
        is_linux: true
      register: output

    - name: assert app service is not updated
      assert:
        that: not output.changed
```

##### EXPECTED RESULTS

The idempotency check should succeed and the plan should not be updated.

##### ACTUAL RESULTS

The idempotency check fails.

```bash
-> ansible-playbook sandbox.yml
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

PLAY [Playbook for testing.] ************************************************************************************************************************************************************

TASK [create premium linux plan] ********************************************************************************************************************************************************
changed: [localhost]

TASK [assert app service was created] ***************************************************************************************************************************************************
ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [create premium linux plan idempotent] *********************************************************************************************************************************************
changed: [localhost]

TASK [assert app service is not updated] ************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {
    "assertion": "not output.changed",
    "changed": false,
    "evaluated_to": false,
    "msg": "Assertion failed"
}

PLAY RECAP ******************************************************************************************************************************************************************************
localhost                  : ok=3    changed=2    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```
