### ISSUE TITLE
Keyvault Secret Token Url HardCoded

### ISSUE THREAD

**Issue by JSlater743** [ansible/ansible_collections_azure#702]
##### SUMMARY
https://github.com/ansible-collections/azure/blob/dev/plugins/modules/azure_rm_keyvaultsecret.py
Line 202, is hardcoded to https://vault.azure.net, and as such does not support other cloud environments, such as AzureUSGovernment where this URL should be: https://vault.usgovcloudapi.net

![image](https://user-images.githubusercontent.com/72266415/143572872-67d77067-5e11-4267-bc08-beb5046b3284.png)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure_rm_keyvaultsecret

##### ANSIBLE VERSION
4.8

##### COLLECTION VERSION
azure-keyvault-secrets         4.3.0

##### OS / ENVIRONMENT
Ubuntu 20

##### STEPS TO REPRODUCE
Using Azure cloud environment other an commercial. eg Government 
Create a keyvault, add a secret using service principal authentication

```yaml

`- name: Create instance of Key Vault
  azure_rm_keyvault:
    resource_group: "{{resource_group}}"
    vault_name: "{{key_vault_name}}"
    enabled_for_deployment: yes
    vault_tenant: "{{tenant_id}}"
    cloud_environment: "AzureUSGovernment"
    sku:
      name: standard
    access_policies:
      - tenant_id: "{{tenant_id}}"
        object_id: "{{object_id}}"
        secrets:
          - get
          - set
 
- name: Create secret
  azure_rm_keyvaultsecret:
    secret_name: "name"
    secret_value: "1234"
    keyvault_uri: "{{key_vault_uri}}"
    cloud_environment: "AzureUSGovernment"    

`
```

##### EXPECTED RESULTS
Secret is created 

##### ACTUAL RESULTS
`fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Your credentials class does not support session injection. Performance will not be at the maximum.\nYour credentials class does not support session injection. Performance will not be at the maximum.\nTraceback (most recent call last):\n  File \"/home/james/.ansible/tmp/ansible-tmp-1637924584.0018017-10811-77988896586815/AnsiballZ_azure_rm_keyvaultsecret.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/james/.ansible/tmp/ansible-tmp-1637924584.0018017-10811-77988896586815/AnsiballZ_azure_rm_keyvaultsecret.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/james/.ansible/tmp/ansible-tmp-1637924584.0018017-10811-77988896586815/AnsiballZ_azure_rm_keyvaultsecret.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.azure.azcollection.plugins.modules.azure_rm_keyvaultsecret', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib/python3.8/runpy.py\", line 207, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.8/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_azure_rm_keyvaultsecret_payload_w9hxt6fy/ansible_azure_rm_keyvaultsecret_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_keyvaultsecret.py\", line 239, in <module>\n  File \"/tmp/ansible_azure_rm_keyvaultsecret_payload_w9hxt6fy/ansible_azure_rm_keyvaultsecret_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_keyvaultsecret.py\", line 235, in main\n  File \"/tmp/ansible_azure_rm_keyvaultsecret_payload_w9hxt6fy/ansible_azure_rm_keyvaultsecret_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_keyvaultsecret.py\", line 130, in __init__\n  File \"/tmp/ansible_azure_rm_keyvaultsecret_payload_w9hxt6fy/ansible_azure_rm_keyvaultsecret_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py\", line 441, in __init__\n  File \"/tmp/ansible_azure_rm_keyvaultsecret_payload_w9hxt6fy/ansible_azure_rm_keyvaultsecret_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_keyvaultsecret.py\", line 166, in exec_module\n  File \"/tmp/ansible_azure_rm_keyvaultsecret_payload_w9hxt6fy/ansible_azure_rm_keyvaultsecret_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_keyvaultsecret.py\", line 223, in create_update_secret\n  File \"/usr/local/lib/python3.8/dist-packages/azure/keyvault/key_vault_client.py\", line 1586, in set_secret\n    raise models.KeyVaultErrorException(self._deserialize, response)\nazure.keyvault.models.key_vault_error.KeyVaultErrorException: (Unauthorized) AKV10022: Invalid audience. Expected https://vault.usgovcloudapi.net, found: https://vault.azure.net.\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}`

Important line here is:
**(Unauthorized) AKV10022: Invalid audience. Expected https://vault.usgovcloudapi.net, found: https://vault.azure.net.**
