### ISSUE TITLE
Feature Proposal: Local Direct Upload of Azure Managed Disks

### ISSUE THREAD

**Issue by maksymiliev** [ansible/ansible_collections_azure#707]
##### SUMMARY

Azure has introduced an ability to upload VHD from host's local storage to a managed disk instead of pulling VHD from Azure Storage Blob URI. It would be great to introduce this ability to the module.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

azure.azcollection.azure_rm_manageddisk
##### ADDITIONAL INFORMATION

Currently, Direct Upload of VHD is only available using AzCopy utility by generating a writable SAS of the managed disk and uploading the local file. It would be great to have this option in this module.

```yaml
- name: Create managed operating system disk from local page blob
  azure_rm_manageddisk:
    name: mymanageddisk
    location: eastus2
    resource_group: myResourceGroup
    create_option: import
    source: "./somewhere/mydisk.vhd"
    os_type: windows
    storage_account_type: Premium_LRS
```
