### ISSUE TITLE
`azure_rm_cosmosdbaccount_info` does not filter by `resource_group`

### ISSUE THREAD

**Issue by l3ender** [ansible/ansible_collections_azure#708]
##### SUMMARY

The `azure_rm_cosmosdbaccount_info` module does not filter by `resource_group`. Instead, all db accounts for the subscription are returned.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure_rm_cosmosdbaccount_info

##### STEPS TO REPRODUCE
These tasks will return the same result (all of the db accounts in the subscription):
```yaml
- name: "Load MongoDB (CosmosDB) for rg1"
  azure.azcollection.azure_rm_cosmosdbaccount_info:
    resource_group: rg1

- name: "Load MongoDB (CosmosDB) for rg2"
  azure.azcollection.azure_rm_cosmosdbaccount_info:
    resource_group: rg2
```

##### EXPECTED RESULTS
If a `resource_group` is provided without `name`, the module should return only db accounts for that resource group.

##### ACTUAL RESULTS
When using `resource_group` without `name`, the module returns all db accounts for the subscription.
