### ISSUE TITLE
Add the ability to use `private_dns_hostnames` in plugin `azure_rm`

### ISSUE THREAD

**Issue by nightguide** [ansible/ansible_collections_azure#710]
##### SUMMARY
Add the ability to use `private_dns_hostnames` in plugin `azure_rm`

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
`azure_rm`

##### ADDITIONAL INFORMATION

I have hostnames on VM in my AKS cluster:

```
aks-ingress-10946177-vmss000000   
aks-ingress-10946177-vmss000001   
aks-main-10946177-vmss000000      
aks-main-10946177-vmss000001 
aks-main-10946177-vmss00001j
``` 

but in ansible inventory (using `azure_rm` plugin) i getting list hosts with inventory_hostname:

```
aks-ingress-10946177-vmss_0_7dcf 
aks-ingress-10946177-vmss_1_544f 
aks-main-10946177-vmss_0_487d 
aks-main-10946177-vmss_1_7537 
aks-main-10946177-vmss_55_0a4d 
```

I tried use parameter `plain_host_names: yes` in myazure_rm.yml, but did not get the expected result.

```
ok: [aks-ingress-10946177-vmss_1]
ok: [aks-main-10946177-vmss_1]
ok: [aks-main-10946177-vmss_55]
ok: [aks-main-10946177-vmss_0]
ok: [aks-ingress-10946177-vmss_0]
```

I defined var inventory_hosname with expression  in `hostvar_expressions section` but is not working ((
```
hostvar_expressions section:
  inventory_hostname: private_dns_hostnames | first
```
I getting empty list hosts:

```
skipping: no hosts matched
```

I don't understanding how I can get real hostname in ansible inventory as on VM's in my AKS cluster....

**Comment by nightguide** [comment]
i found solution

Upgrading azure_rm plugin to version 1.4.0

and using section hostnames with computer_name

```
---
plugin: azure.azcollection.azure_rm
auth_source: env
include_vm_resource_groups:
  - MC_EU-AKS-RG_aks-prd-pl1_germanywestcentral
include_vmss_resource_groups:
  - '*'
hostnames:
  - computer_name
conditional_groups:
  kube_ingress: "tags['nodePool'] == 'ingress'"
  kube_workers: "tags['nodePool'] == 'workers'"
  kubernetes: "tags['nodePool'] in ['ingress', 'workers']"
...
```

result: 
ok: [aks-ingress-10946177-vmss000000]
ok: [aks-ingress-10946177-vmss000001]
ok: [aks-main-10946177-vmss000001]
ok: [aks-main-10946177-vmss00001J]
ok: [aks-main-10946177-vmss000000]
ok: [aks-main-10946177-vmss00001W]
