### ISSUE TITLE
Feature Proposal: Add support for PostgreSQL flexible servers

### ISSUE THREAD

**Issue by arahja** [ansible/ansible_collections_azure#714]
##### SUMMARY
Add Azure Database for PostgreSQL flexible servers support

##### ISSUE TYPE
- Currently azure.azcollection.azure_rm_postgresqlserver_info and the other "azure_rm_postgresql" prefixed modules do not list or see the postgresql flexible servers.
- Can support be added to the existing modules for postgresql flexible servers or add new modules to support these servers?
- [Azure Database for PostgreSQL flexible servers have recently been made generally available.](https://techcommunity.microsoft.com/t5/azure-database-for-postgresql/azure-database-for-postgresql-flexible-server-is-now-ga/ba-p/2987030)

##### COMPONENT NAME
- azure_rm_postgresqlconfiguration
- azure_rm_postgresqlconfiguration_info
- azure_rm_postgresqldatabase
- azure_rm_postgresqldatabase_info
- azure_rm_postgresqlfirewallrule
- azure_rm_postgresqlfirewallrule_info
- azure_rm_postgresqlserver
- azure_rm_postgresqlserver_info

**Comment by tschechniker** [comment]
+1

**Comment by NemoDang** [comment]
+1

**Comment by sharvarikhedkar** [comment]
+1

**Comment by MrChips821** [comment]
+1

**Comment by AlbertoGonzalezMayorga** [comment]
+1

**Comment by pwakano** [comment]
+1
Specially given the single server won't be available for creation from Nov 2023 and is going to be retired in 2025. https://learn.microsoft.com/en-us/azure/postgresql/single-server/whats-happening-to-postgresql-single-server

**Comment by anitoshsaha** [comment]
+

**Comment by pwakano** [comment]
For those interested, a workaround to create the flexible server using the generic azure_rm_resource:
```
- azure_rm_resource:
    subscription_id: "{{ subscription_id }}"
    resource_group: "{{ resource_group }}"
    provider: DBforPostgreSQL
    resource_type: flexibleServers
    resource_name: "{{ name }}"
    idempotency: true
    api_version: '2021-06-01'
    body: # Ref: https://learn.microsoft.com/en-us/rest/api/postgresql/flexibleserver/servers/create?tabs=HTTP
       location: "{{ location }}"
       sku: "{{ sku }}"
       properties:
          administratorLogin: "{{ admin_username }}"
          administratorLoginPassword: "{{ admin_password }}"
          createMode: Create
          backup:
             geoRedundantBackup: "{{ geo_redundant_backup }}"
          highAvailability:
             mode: "{{ high_availability }}"
          network:
             delegatedSubnetResourceId: "{{ pg_subnet_id }}"
             privateDnsZoneArmResourceId: "{{ pg_dns_zone_id }}"
             publicNetworkAccess: Disabled
          storage:
             storageSizeGB: "{{ storage_size_gb }}"
          version: "{{ version }}"
       tags: "{{ tags }}"
```
