### ISSUE TITLE
ModuleNotFoundError: No module named 'azure.mgmt.monitor.version'

### ISSUE THREAD

**Issue by dj-wasabi** [ansible/ansible_collections_azure#715]
##### SUMMARY

Get an error when I do something with any of the Ansible modules, this is since a few days.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

azure_rm_resourcegroup
##### ANSIBLE VERSION

```paste below
ansible [core 2.11.5]
  config file = None
  configured module search path = ['/Users/wdijkerman/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/wdijkerman/.venv3101/lib/python3.10/site-packages/ansible
  ansible collection location = /Users/wdijkerman/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/wdijkerman/.venv3101/bin/ansible
  python version = 3.10.1 (v3.10.1:2cd268a3a9, Dec  6 2021, 14:28:59) [Clang 13.0.0 (clang-1300.0.29.3)]
  jinja version = 3.0.3
  libyaml = True
```

##### COLLECTION VERSION

```paste below
[DEPRECATION WARNING]: Ansible will require Python 3.8 or newer on the controller starting with Ansible 2.12. Current version: 3.6.8 (default, Nov 16 2020, 16:55:22) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]. This feature will be removed
from ansible-core in version 2.12. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.

# /usr/local/lib/python3.6/site-packages/ansible_collections
Collection      Version
--------------- -------
community.azure 1.1.0
```

##### CONFIGURATION

```paste below
n.a.
```

##### OS / ENVIRONMENT

RedHat/Ubuntu

##### STEPS TO REPRODUCE

Followed: https://docs.microsoft.com/en-us/azure/developer/ansible/configure-in-docker-container?tabs=azure-cli

```yaml
pip install -r requirements-azure.txt
ansible-galaxy collection install azure.azcollection --force

# create a playbook.yml

---
- hosts: localhost
  connection: local

  vars:
    resource_group_name: somename
    azure_location: germanywestcentral

  tasks:
  - name: Create resource group
    azure_rm_resourcegroup:
      name: "{{ resource_group_name }}"
      location: "{{ azure_location }}"
```

##### EXPECTED RESULTS

Creation of an resource group.

##### ACTUAL RESULTS

```paste below
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ModuleNotFoundError: No module named 'azure.mgmt.monitor.version'

```
