### ISSUE TITLE
Feature Request: Allow tagging of virtual machines without power operations being required

### ISSUE THREAD

**Issue by DII-dsward** [ansible/ansible_collections_azure#721]
##### SUMMARY
azure_rm_virtualmachine has a default parameter started: true. We have many dozens of machines we need to tag whether the VM is powered on or not. As of not, if we attempt to tag a powered off VM with azure_rm_virtualmachine, ansible will power the VM on which is causing us headaches. I'm attempting to work around the issue by switching to powershell or azure cli.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
```yaml
- azure_rm_virtualmachine:
    started: true #please remove this default parameter
```

##### ADDITIONAL INFORMATION
```yaml
- name: Update VM Tags
   vars:
      typetag: 'Virtual Machine'
   azure_rm_virtualmachine:
      resource_group: "{{ resource_group }}"
      name: "{{ inventory_hostname_short }}"
      append_tags: true
      tags: "{{ tictags }}"
      #started: true/false
```
