### ISSUE TITLE
Azure RM Private Endpoint

### ISSUE THREAD

**Issue by adthorn** [ansible/ansible_collections_azure#725]
##### SUMMARY
Private Endpoints fail to provision

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure.azcollection.azure_rm_privateendpoint

##### ANSIBLE VERSION
Ansible 2.9.27

##### COLLECTION VERSION
1.10.0

##### OS / ENVIRONMENT
RHEL 7.6 / Azure Cloudshell

##### STEPS TO REPRODUCE
    - name: Create private endpoint
      azure_rm_privateendpoint:
        name: "pve-vault-{{kv_instance}}"
        subscription_id: "{{azr_subid}}"
        resource_group: "{{azr_rg_name}}"
        state: present
        auth_source: auto
        location: "{{location}}us"
        private_link_service_connections:
          - name: "pve-{{azr_kv_name}}-vault-{{pve_kv_instance}}"
            private_link_service_id: /subscriptions/{{azr_subid}}/resourceGroups/{{azr_rg_name}}/providers/Microsoft.KeyVault/vaults/{{azr_kv_name}}
            group_ids: "{{azr_sub_resource}}"
        subnet:
          id: /subscriptions/{{azr_subid}}/resourceGroups/{{azr_rg_name}}/providers/Microsoft.Network/virtualNetworks/{{azr_vnet_name}}/subnets/{{azr_snet_sec}}
        private_dns_zone_configs:
         - name: "privatelink-vaultcore-azure-net"
           private_dns_zone_group: "/subscriptions/xxx/resourceGroups/rg-net-hub-prd-east-001/providers/Microsoft.Network/privateDnsZones/privatelink.vaultcore.azure.net"
        tags:
            Description: "Private Endpoint: For Resource {{azr_kv_name}}"
            Subscription: "{{subscode}}"
            AppCode: "{{appcode}}"
            AppOwner: "{{appowner}}"
            Environment: "{{envcode}}"
            Location: "{{location}}us"
            Instance: "{{pve_kv_instance}}"
            ResourceType: pve

##### EXPECTED RESULTS
Creates Private Endpoint for my Keyvault

##### ACTUAL RESULTS
The full traceback is:
  File "/tmp/ansible_azure_rm_privateendpoint_payload_s8prtrc5/ansible_azure_rm_privateendpoint_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_privateendpoint.py", line 312, in create_update_resource_private_endpoint
  File "/home/adam/.local/lib/python3.7/site-packages/azure/mgmt/network/v2020_06_01/operations/_private_endpoints_operations.py", line 267, in create_or_update
    **operation_config
  File "/home/adam/.local/lib/python3.7/site-packages/azure/mgmt/network/v2020_06_01/operations/_private_endpoints_operations.py", line 220, in _create_or_update_initial
    raise models.ErrorException(self._deserialize, response)
fatal: [localhost]: FAILED! => {

"msg": "Error creating or updating private endpoint pve-test - Operation returned an invalid status code 'Bad Request'"

**Comment by Fred-sun** [comment]
@adthorn This module does not support the "private_dns_zone_configs" parameter. Can you use the following test case to try again? Thank you very much!
```e.g.
- name: Create private endpoint
  azure_rm_privateendpoint:
    name: privateendpoint{{ rpfx }}
    resource_group: "{{ resource_group }}"
    private_link_service_connections:
      - name: privateEndpoints_test_name02
        private_link_service_id: "{{ keyvault_output.state.id }}"
        group_ids:
          - vault
    subnet:
      id: "{{ subnet_output.state.id }}"
    tags:
      Description: "Private Endpoint: For Resource {{azr_kv_name}}"
      Subscription: "{{subscode}}"
      AppCode: "{{appcode}}"
      AppOwner: "{{appowner}}"
      Environment: "{{envcode}}"
      Location: "{{location}}us"
      Instance: "{{pve_kv_instance}}"
      ResourceType: pve

**Comment by adthorn** [comment]
vars:
    azr_subid: "xxxxxx-xxxx-xxxx-xxxx-xxx"
    azr_subid_net: "xxxxxx-xxxx-xxxx-xxxx-xxx"
    azr_aad_tenant_id: "xxxxxx-xxxx-xxxx-xxxx-xxx"
    azr_kv_sku: "standard"
    kv_instance: "004"
    pve_kv_instance: "001"
    rg_instance: "001"
    vnet_instance: "001"
    snet_sec_instance: "001"
    azr_vnet_hub_name: "vnet-net-hub-prd-east-001"
    Description: ""
    subscode: exe
    appcode: rxc
    envcode: tst
    location: "east"
    azr_pve_sub_resource: vault
    azr_pve_dns_zone: privatelink-vaultcore-azure-net
  
  - name: Create private endpoint
      azure_rm_privateendpoint:
        name: "{{azr_pve_name}}"
        subscription_id: "{{azr_subid}}"
        resource_group: "{{azr_rg_name}}"
        state: present
        private_link_service_connections:
          - name: "{{azr_pve_name}}"
            private_link_service_id: /subscriptions/{{azr_subid}}/resourceGroups/{{azr_rg_name}}/providers/Microsoft.KeyVault/vaults/{{azr_kv_name}}
            group_ids: 
              - "{{azr_pve_sub_resource}}"
        subnet:
          id: /subscriptions/{{azr_subid}}/resourceGroups/{{azr_rg_name}}/providers/Microsoft.Network/virtualNetworks/{{azr_vnet_name}}/subnets/{{azr_snet_sec}}
        tags:
            Description: "Private Endpoint: For Resource {{azr_kv_name}}"
            Subscription: "{{subscode}}"
            AppCode: "{{appcode}}"
            AppOwner: "{{appowner}}"
            Environment: "{{envcode}}"
            Location: "{{location}}us"
            Instance: "{{pve_kv_instance}}"
            ResourceType: pve

As follows, I still receive the same error. Operation received bad input. You may want to remove that function from the documentation too. I also tried to added the private endpoint DNS module but it seems as thought it's not part of the major release of ansible 1.10.0.

    - name: Create zone group for private endpoint
      azure_rm_privateendpointdnszonegroup:
        name: "{{azr_pve_name}}/default"
        private_endpoint: "{{azr_pve_name}}"
        resource_group: "rg-net-hub-prd-east-001"
        subscription_id: "{{azr_subid_net}}"
        private_dns_zone_configs:
          - name: default
            private_dns_zone: "{{azr_pve_dns_zone}}"

**Comment by adthorn** [comment]
`fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "ad_user": null,
            "adfs_authority_url": null,
            "api_profile": "latest",
            "append_tags": true,
            "auth_source": "auto",
            "cert_validation_mode": null,
            "client_id": null,
            "cloud_environment": "AzureCloud",
            "location": null,
            "log_mode": null,
            "log_path": null,
            "name": "pve-kv-exe-rxc-tst-east-004-vault-004",
            "password": null,
            "private_link_service_connections": [
                {
                    "group_ids": [
                        "vault"
                    ],
                    "name": "pve-kv-exe-rxc-tst-east-004-vault-004",
                    "private_link_service_id": "/subscriptions/19ca04cb-7fab-4475-bdb4-56b323efff4a/resourceGroups/rg-exe-rxc-tst-east-001/providers/Microsoft.KeyVault/vaults/kv-exe-rxc-tst-east-004"
                }
            ],
            "profile": null,
            "resource_group": "rg-exe-rxc-tst-east-001",
            "secret": null,
            "state": "present",
            "subnet": {
                "id": "/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Network/virtualNetworks/xx-xx-xx-xx-xx-xxx/subnets/xx"
            },
            "subscription_id": "xxx",
            "tags": {
                "AppCode": "xxx",
                "AppOwner": "xxx",
                "Description": "Private Endpoint: For Resource xxx",
                "Environment": "tst",
                "Instance": "001",
                "Location": "eastus",
                "ResourceType": "pve",
                "Subscription": "xxx"
            },
            "tenant": null
        }
    },`

**Comment by adthorn** [comment]
fatal: [localhost]: FAILED! => { "changed": false, "invocation": { "module_args": { "ad_user": null, "adfs_authority_url": null, "api_profile": "latest", "append_tags": true, "auth_source": "auto", "cert_validation_mode": null, "client_id": null, "cloud_environment": "AzureCloud", "location": null, "log_mode": null, "log_path": null, "name": "pve-kv-exe-rxc-tst-east-004-vault-004", "password": null, "private_link_service_connections": [ { "group_ids": [ "vault" ], "name": "pve-kv-exe-rxc-tst-east-004-vault-004", "private_link_service_id": "/subscriptions/xxx/resourceGroups/rg-exe-rxc-tst-east-001/providers/Microsoft.KeyVault/vaults/kv-exe-rxc-tst-east-004" } ], "profile": null, "resource_group": "rg-exe-rxc-tst-east-001", "secret": null, "state": "present", "subnet": { "id": "/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Network/virtualNetworks/xx-xx-xx-xx-xx-xxx/subnets/xx" }, "subscription_id": "xxx", "tags": { "AppCode": "xxx", "AppOwner": "xxx", "Description": "Private Endpoint: For Resource xxx", "Environment": "tst", "Instance": "001", "Location": "eastus", "ResourceType": "pve", "Subscription": "xxx" }, "tenant": null } },

**Comment by adthorn** [comment]
```
  vars:
    azr_subid: "xxxxxx-xxxx-xxxx-xxxx-xxx"
    azr_subid_net: "xxxxxx-xxxx-xxxx-xxxx-xxx"
    azr_aad_tenant_id: "xxxxxx-xxxx-xxxx-xxxx-xxx"
    azr_kv_sku: "standard"
    kv_instance: "004"
    pve_kv_instance: "001"
    rg_instance: "001"
    vnet_instance: "001"
    snet_sec_instance: "001"
    azr_vnet_hub_name: "xxx-xxx-xxx-xx-xxx-001"
    Description: ""
    subscode: exe
    appcode: rxc
    envcode: tst
    location: "east"
    azr_pve_sub_resource: vault
    azr_pve_dns_zone: privatelink-vaultcore-azure-net
  
  - name: Create private endpoint
      azure_rm_privateendpoint:
        name: "{{azr_pve_name}}"
        subscription_id: "{{azr_subid}}"
        resource_group: "{{azr_rg_name}}"
        state: present
        private_link_service_connections:
          - name: "{{azr_pve_name}}"
            private_link_service_id: /subscriptions/{{azr_subid}}/resourceGroups/{{azr_rg_name}}/providers/Microsoft.KeyVault/vaults/{{azr_kv_name}}
            group_ids: 
              - "{{azr_pve_sub_resource}}"
        subnet:
          id: /subscriptions/{{azr_subid}}/resourceGroups/{{azr_rg_name}}/providers/Microsoft.Network/virtualNetworks/{{azr_vnet_name}}/subnets/{{azr_snet_sec}}
        tags:
            Description: "Private Endpoint: For Resource {{azr_kv_name}}"
            Subscription: "{{subscode}}"
            AppCode: "{{appcode}}"
            AppOwner: "{{appowner}}"
            Environment: "{{envcode}}"
            Location: "{{location}}us"
            Instance: "{{pve_kv_instance}}"
            ResourceType: pve
```

As follows, I still receive the same error. Operation received bad input. You may want to remove that dns function from the private endpoint documentation too. I also tried to added the private endpoint DNS module but it seems as thought it's not part of the major release of ansible azcollection 1.10.0.

    - name: Create zone group for private endpoint
      azure_rm_privateendpointdnszonegroup:
        name: "{{azr_pve_name}}/default"
        private_endpoint: "{{azr_pve_name}}"
        resource_group: "rg-xxx-xxx-xxx-xxxx-001"
        subscription_id: "{{azr_subid_net}}"
        private_dns_zone_configs:
          - name: default
            private_dns_zone: "{{azr_pve_dns_zone}}"
