### ISSUE TITLE
[azure_rm_aks]: Error creating the AKS instance, must define at least one system pool.

### ISSUE THREAD

**Issue by khusseini** [ansible/ansible_collections_azure#731]
##### SUMMARY
Error encountered when trying to create a cluster using `azure_rm_aks`

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure_rm_aks

##### ANSIBLE VERSION

```
ansible [core 2.11.6] 
  config file = /opt/provision/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.9.7 (default, Nov 24 2021, 21:15:59) [GCC 10.3.1 20211027]
  jinja version = 3.0.1
  libyaml = True
```

##### COLLECTION VERSION

```paste below
# /root/.ansible/collections/ansible_collections
Collection         Version
------------------ -------
azure.azcollection 1.10.0 

# /usr/lib/python3.9/site-packages/ansible_collections
Collection         Version
------------------ -------
azure.azcollection 1.10.0 

```

##### CONFIGURATION

```
DEFAULT_ROLES_PATH(/opt/provision/ansible.cfg) = ['/opt/provision/roles', '/opt/provision/vendors/roles']
DEFAULT_STDOUT_CALLBACK(/opt/provision/ansible.cfg) = debug
```

##### OS / ENVIRONMENT

Alpine Container with following `Dockerfile`:
```Dockerfile
# syntax=docker/dockerfile:1

####
FROM docker:dind AS base

RUN apk add --update --no-cache bash curl make ansible git py3-pip
RUN pip install kubernetes

RUN curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
RUN /bin/bash ./get_helm.sh 

RUN curl -sSL https://cli.openfaas.com | sh
RUN curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
RUN curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl \
        && chmod +x ./kubectl \
        && mv ./kubectl /usr/local/bin/kubectl

RUN curl -sLo /usr/local/bin/mkcert https://github.com/FiloSottile/mkcert/releases/download/v1.4.3/mkcert-v1.4.3-linux-amd64
RUN chmod +x /usr/local/bin/mkcert

RUN ansible-galaxy collection install community.kubernetes


####
FROM base AS azure
RUN apk add \
        --update \
        --no-cache \
        build-base \
        gcc \
        libc-dev \
        linux-headers  \
        python3-dev \
        libffi-dev

RUN ansible-galaxy collection install azure.azcollection \ 
        && pip install -r /root/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt

####
FROM azure AS final
ADD . /opt/provision
WORKDIR /opt/provision
CMD ["/bin/bash", "-c", "make help"]
```
hosted on

```
uname --all
Linux pop-os 5.13.0-25-lowlatency #26-Ubuntu SMP PREEMPT Fri Jan 7 16:59:39 UTC 2022 x86_64 Linux
```


##### STEPS TO REPRODUCE

Reproduction using docker image:
```
set -o allexport; source .env; set +o allexport; ANSIBLE_CONFIG="/opt/provision/ansible.cfg" ansible-playbook --tags "all" -i hosts --extra-vars "state=present"  ./cloud/index.yml
```

Ansible Config:
`ansible.cfg`:
```
[defaults]
stdout_callback=debug
stderr_callback=debug
roles_path=./roles:./vendors/roles
```

Ansible Playbook:

`cloud/index.yml`:
```
---
- name: Ensure cloud components are {{ state }}.
  hosts: cloud-operator:&azure
  collections:
   - azure.azcollection
  tasks:
  - name: Ensure resource group is {{ state }}
    azure_rm_resourcegroup:
      name: "{{ cluster_name }}-{{ item }}"
      location: "{{ item }}"
      state: "{{ state }}"
    loop: "{{ locations }}"

  - name: Deploy cluster for {{ location }}
    include_tasks: ./aks.yml
    loop: "{{ locations }}"
    loop_control:
      loop_var: location
```


Ansible tasks:
`aks.yml`:

```
---
- name: Get available versions for AKS in location {{ location }}
  azure_rm_aksversion_info:
    location: "{{ location }}"
  register: aks_version_info

- set_fact:
    aks_version: "{{ aks_version_info.azure_aks_versions[(aks_version_info.azure_aks_versions | length) - 1] }}"

- name: Ensure managed Azure Container Services (AKS) cluster is {{ state }}.
  azure_rm_aks:
    agent_pool_profiles:
      - name: default
        count: 1
        vm_size: Standard_B2s
        enable_auto_scaling: True
        type: VirtualMachineScaleSets
        mode: System
        max_count: 3
        min_count: 1
        enable_rbac: yes
      - name: nodes
        count: 1
        mode: User
        vm_size: Standard_D2_v2
        enable_auto_scaling: yes
        enable_rbac: yes
    dns_prefix: cluster
    enable_rbac: yes
    kubernetes_version: "{{ aks_version }}"
    location: "{{ location }}"
    name: "{{ cluster_name }}"
    resource_group: "{{ cluster_name }}-{{ location }}"
    state: "{{ state }}"
    tags:
      environment: development

```
Files are also available here: https://gitlab.com/faasaf/faasaf/-/tree/azure/cloud

##### EXPECTED RESULTS
I expected a k8s cluster with a node pool to be created.


##### ACTUAL RESULTS
Unfortunately I am getting the following error:
```
Error creating the AKS instance: Operation failed with status: 'Bad Request'. Details: Must define at least one system pool.
```

<!--- Paste verbatim command output between quotes -->
```
Error creating the AKS instance: Operation failed with status: 'Bad Request'. Details: Must define at least one system pool.

TASK [Ensure managed Azure Container Services (AKS) cluster is present.] ***********************************************************************************************************[407/8376]task path: /opt/provision/cloud/aks.yml:11                                                                                                                                                    
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root                                                                                                                                         
<localhost> EXEC /bin/sh -c 'echo ~root && sleep 0'                                                                                                                                           
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir "` echo /root/.ansible/tmp/ansible-tmp-1642508408.2568195-260-186696789280408 `" && echo ansible-tmp
-1642508408.2568195-260-186696789280408="` echo /root/.ansible/tmp/ansible-tmp-1642508408.2568195-260-186696789280408 `" ) && sleep 0'                                                        
Using module file /root/.ansible/collections/ansible_collections/azure/azcollection/plugins/modules/azure_rm_aks.py                                                                           
<localhost> PUT /root/.ansible/tmp/ansible-local-149oqy4je6d/tmpvu8k9y4_ TO /root/.ansible/tmp/ansible-tmp-1642508408.2568195-260-186696789280408/AnsiballZ_azure_rm_aks.py                   
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1642508408.2568195-260-186696789280408/ /root/.ansible/tmp/ansible-tmp-1642508408.2568195-260-186696789280408/AnsiballZ_
azure_rm_aks.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python3.9 /root/.ansible/tmp/ansible-tmp-1642508408.2568195-260-186696789280408/AnsiballZ_azure_rm_aks.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1642508408.2568195-260-186696789280408/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
  File "/tmp/ansible_azure_rm_aks_payload_x4hf92na/ansible_azure_rm_aks_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_aks.py", line 902, in create_update_aks
  File "/usr/lib/python3.9/site-packages/azure/mgmt/containerservice/v2020_04_01/operations/_managed_clusters_operations.py", line 664, in create_or_update
    raw_result = self._create_or_update_initial(
  File "/usr/lib/python3.9/site-packages/azure/mgmt/containerservice/v2020_04_01/operations/_managed_clusters_operations.py", line 621, in _create_or_update_initial
    raise exp
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "aad_profile": null,
            "ad_user": null,
            "addon": null,
            "adfs_authority_url": null,
            "agent_pool_profiles": [
                {
                    "availability_zones": null, 
                    "count": 3,
                    "dns_prefix": null,
                    "enable_auto_scaling": null,
                    "max_count": null,
                    "max_pods": null,
                    "min_count": null,
                    "mode": null,
                    "name": "default",
                    "node_labels": null,
                    "os_disk_size_gb": null,
                    "os_type": null,
                    "ports": null,
                    "storage_profiles": null,
                    "type": null,
                    "vm_size": "Standard_D2_v2",
                    "vnet_subnet_id": null
                }
            ],
            "api_profile": "latest",
            "append_tags": true,
            "auth_source": "auto",
            "cert_validation_mode": null,
            "client_id": null,
            "cloud_environment": "AzureCloud",                                                                                                                                      [355/8376]
            "dns_prefix": "cluster",          
            "enable_rbac": true,    
            "kubernetes_version": "1.22.4",
            "linux_profile": null,         
            "location": null,     
            "log_mode": null,       
            "log_path": null,           
            "name": "faasaf",
            "network_profile": null,
            "node_resource_group": null,                                                       
            "password": null,           
            "profile": null,          
            "resource_group": "faasaf-germanywestcentral",
            "secret": null,                                                                      
            "service_principal": null,
            "state": "present",             
            "subscription_id": null,                         
            "tags": {                                        
                "environment": "development"                 
            },                                               
            "tenant": null                                   
        }                                                    
    }                                                        
}                                                            
                                                                                                                                                                                              MSG: 
                                                           
Error creating the AKS instance: Operation failed with status: 'Bad Request'. Details: Must define at least one system pool.                                                                                                                                                                 

```
