### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by desand01** [ansible/ansible_collections_azure#739]
##### SUMMARY
Hi, for my work, I had to create and modify some modules.  It may be useful for some one else.
If so, I like to know what should I do next?

Thanks

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
azure_rm_appgateway_host
azure_rm_appgateway_info
azure_rm_storagefile
azure_rm_storagefile_info
azure_rm_sqlmanaged
azure_rm_sqlmanaged_info
azure_rm_containerinstance

##### ADDITIONAL INFORMATION
azure_rm_appgateway_info: Add private/public IP, useful for Network Security Group config
azure_rm_appgateway_host: Add/Remove "host" to a shared Gateway, no need to know all hosts already created
```yaml
- name: Create new host bar
  azure_rm_appgateway_host:
    resource_group: "myResourceGroup"
    name: "appgateway{{ rpfx }}"
    backend_address_pools:
    - backend_addresses:
      - ip_address: "10.1.0.20"
      - ip_address: "10.1.0.21"
      name: "{{ name }}-backend-pool"
    backend_http_settings_collection:
    - port: 8080
      protocol: http
      cookie_based_affinity: disabled
      name: "{{ name }}-http-settings"
    http_listeners:
    - frontend_port: 443
      ssl_certificate: "cert2"
      name: "{{ name }}-http-listener"
      protocol: "Https"
      host_name: "{{ name }}.mydomain.org"
    request_routing_rules:
    - rule_type: Basic
      backend_address_pool: "{{ name }}-backend-pool"
      backend_http_settings: "{{ name }}-http-settings"
      http_listener: "{{ name }}-http-listener"
      name: "{{ name }}-rule-public"
  vars:
    name: "bar-test"

- name: Delete host foo
  azure_rm_appgateway_host:
    resource_group: "myResourceGroup"
    name: "appgateway{{ rpfx }}"
    backend_address_pools:
    - name: "{{ name }}-backend-pool"
    backend_http_settings_collection:
    - name: "{{ name }}-http-settings"
    http_listeners:
    - name: "{{ name }}-http-listener"
    request_routing_rules:
    - name: "{{ name }}-rule-public"
    state: absent
  vars:
    name: "foo-test"
```
azure_rm_storagefile
azure_rm_storagefile_info
Behave like azure_rm_storageblob, with added supoort for Directory
```yaml
- name: Upload file and create sub directory if missing
  azure_rm_storagefile:
    resource_group: "myResourceGroup"
    account_name: "{{ storage_account }}"
    share_name: my-files
    file: 'folder1/sub1/newsub/Ratings.png'
    src: './targets/azure_rm_storagefile/files/Ratings.png'
    content_type: image/png

- name: Create sub folders tree
  azure_rm_storagefile:
    resource_group: "myResourceGroup"
    account_name: "{{ storage_account }}"
    share_name: my-files
    file: 'folder1/sub1/sub2/sub3'

- name: Get fact
  azure_rm_storagefile_info:
    resource_group: "myResourceGroup"
    account_name: "{{ storage_account }}"
    share_name: my-files
    file: 'folder1/sub1/newsub/Ratings.png'
  register: file_info_results
```
azure_rm_sqlmanaged
azure_rm_sqlmanaged_info
Behave like azure_rm_sqldatabase
```yaml
- name: Create managed SQL Database
  azure_rm_sqlmanaged:
    resource_group: "myResourceGroup"
    instance_name: "mySqlInstanceName"
    name: "newDataBase"
  register: database_info
```
azure_rm_containerinstance
azure-mgmt-containerinstance ==9.1.0
Support for private IP, protocol UDP
Add state: restart, stop
Execute command inside container
```yaml
- name: Disable master realm required SSL for keycloak container
  azure_rm_containerinstance:
    resource_group: "myResourceGroup"
    name: "myContainerInstanceGroup"
    state: "execute"
    terminal:
      container: "myContainerInstance"
      lines:
        - 'cd $JBOSS_HOME/bin'
        - './kcadm.sh config credentials --server http://localhost:8080/auth --realm master --user admin'
        - 'mysecretpassword'
        - './kcadm.sh update realms/master -s sslRequired=NONE'

- name: Restart containers group and wait 300 secondes
  azure_rm_containerinstance:
    resource_group: "myResourceGroup"
    name: "myContainerInstanceGroup"
    state: "restart"
    restart_wait: 300
```
