### ISSUE TITLE
Allow to associate Load Balancer NAT rules to NIC

### ISSUE THREAD

**Issue by piotr-gbyliczek** [ansible/ansible_collections_azure#758]
##### SUMMARY

Support for associating Load Balancer NAT inbound rules to the network interface

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

azure_rm_networkinterface

##### ADDITIONAL INFORMATION

When creating virtual machines behind load balancer, it is possible to create NAT rules that forward ports to individual VMs (for example port 22201 to port 22 of vm1, port 22202 to port 22 of vm2, and so on). It is done by associating Inbound NAT rule to an IP configuration on the network interface.
This functionality is missing from azure_rm_networkinterface module, while possible when using azire_rm_resource module.

You can create load balancer with inbound NAT rules using azure_rm_loadbalancer module:

```yaml
- name: create a load balancer
  azure_rm_loadbalancer:
    resource_group: "{{ resource_group }}"
    name: "{{ vm.name }}-lb"
    sku: "Standard"
    frontend_ip_configurations:
      - name: "{{ vm.name }}-lb-frontend-ip-config"
        public_ip_address: "{{ vm.name }}-lb-pip"
    backend_address_pools:
      - name: "{{ vm.name }}-lb-backend-address-pool"
    probes:
      - name: "{{ vm.name }}-lb-probe"
        port: "22"
        fail_count: "3"
        protocol: "Tcp"
    inbound_nat_rules:
      - name: "{{ vm.name }}-nat-ssh-22201"
        backend_port: "22"
        protocol: "Tcp"
        frontend_port: "22201"
        frontend_ip_configuration: "{{ vm.name }}-lb-frontend-ip-config"      
      - name: "{{ vm.name }}-nat-admin-12345"
        backend_port: "12345"
        protocol: "Tcp"
        frontend_port: "12345"
        frontend_ip_configuration: "{{ vm.name }}-lb-frontend-ip-config"
```
You can then create a network interface using azure_rm_resource module so the NAT rules are associated to the network interface: 
```yaml
- name: create the network interface 
  azure_rm_resource:
    api_version: '2019-09-01'
    resource_group: "{{ resource_group }}"
    idempotency: "yes"
    provider: "network"
    resource_type: "networkinterfaces"
    resource_name: "{{ vm.name }}_{{ item }}"
    body:
      location: {{ location }}
      properties: 
        enableAcceleratedNetworking: false
        primary: true
        networksecuritygroup:
          id: /subscriptions/{{ sub_id }}/resourceGroups/{{ resource_group }}/providers/Microsoft.Network/networkSecurityGroups/{{ vm.name }}-nsg
        ipConfigurations: 
          - name: {{ vm.name }}_{{ item }}_ipconfig1
            properties: 
              subnet: 
                id: /subscriptions/{{ sub_id }}/resourceGroups/{{ resource_group }}/providers/Microsoft.Network/virtualNetworks/{{ network.name }}/subnets/{{ vm.subnet_name }}
              loadBalancerBackendAddressPools:
                - id: /subscriptions/{{ sub_id }}/resourceGroups/{{ resource_group }}/providers/Microsoft.Network/loadBalancers/{{ vm.name }}-lb/backendAddressPools/{{ vm.name }}-lb-backend-address-pool
              loadBalancerInboundNatRules:
                - id: /subscriptions/{{ sub_id }}/resourceGroups/{{ resource_group }}/providers/Microsoft.Network/loadBalancers/{{ vm.name }}-lb/inboundNatRules/{{ vm.name }}-nat-ssh-22201                
                - id: /subscriptions/{{ sub_id }}/resourceGroups/{{ resource_group }}/providers/Microsoft.Network/loadBalancers/{{ vm.name }}-lb/inboundNatRules/{{ vm.name }}-nat-admin-12345
```
Later that interface is used by azure_rm_virtualmachine module to create VM with it.

The same is not possible while using azure_rm_networkinterface. The best conversion from azure_rm_resource to the dedicated module is this: 
```yaml
- name: create the network interface for VM
  azure_rm_networkinterface:
    name: "{{ vm.name }}_{{ item }}"
    resource_group: "{{ resource_group }}"
    enable_accelerated_networking: no
    location: "{{ location }}"
    security_group: "{{ vm.name }}-nsg"
    virtual_network: "{{ network.name }}"
    subnet_name: "{{ vm.subnet_name }}"
    ip_configurations:
      - name: "{{ vm.name }}_{{ item }}_ipconfig1"
        primary: yes
        load_balancer_backend_address_pools:
          - name: "{{ vm.name }}-lb-backend-address-pool"
            load_balancer: "{{ vm.name }}-lb"
```
It looks much cleaner and is more clear to understand that way, so adding the NAT rules association element would be helpful.
