### ISSUE TITLE
azure.azcollection.azure_rm_privatednsrecordset_info doesn't return  dnsrecordsets  list / elements=dictionary

### ISSUE THREAD

**Issue by sdminonne** [ansible/ansible_collections_azure#785]
##### SUMMARY

`azure.azcollection.azure_rm_privatednsrecordset_info` does not return azure_rm_privatednsrecordset_info does not return any recorded set

##### ISSUE TYPE
- Bug Report

Trying to use the `azcollection.azure_rm_privatednszone_info` module to list the recoredset in the private DNS zone does not return any value.
Please advise if for whatever reason I'm missing something
Thanks

##### COMPONENT NAME

azure.azcollection.azure_rm_privatednsrecordset_info

##### ANSIBLE VERSION

```paste below
$ ansible --version
ansible 2.10.17
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/sdminonne/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/sdminonne/dev/ansible/az-private-endpoint-investigation/ansible/python-env/lib64/python3.10/site-packages/ansible
  executable location = /home/sdminonne/dev/ansible/az-private-endpoint-investigation/ansible/python-env/bin/ansible
  python version = 3.10.2 (main, Jan 17 2022, 00:00:00) [GCC 11.2.1 20211203 (Red Hat 11.2.1-7)]
```

##### COLLECTION VERSION

```paste below
$ ansible-galaxy collection list azure.azcollection

# /home/sdminonne/dev/ansible/az-private-endpoint-investigation/ansible/python-env/lib/python3.10/site-packages/ansible_collections
Collection         Version
------------------ -------
azure.azcollection 1.0.0  

# /home/sdminonne/.ansible/collections/ansible_collections
Collection         Version
------------------ -------
azure.azcollection 1.11.0 

# /home/sdminonne/dev/ansible/az-private-endpoint-investigation/ansible/python-env/lib64/python3.10/site-packages/ansible_collections
Collection         Version
------------------ -------
azure.azcollection 1.0.0  

```

##### CONFIGURATION

```paste below
$ ansible-config dump --only-changed
$
```

##### OS / ENVIRONMENT

````
$ uname -a
Linux lenovo-dock.home 5.16.13-200.fc35.x86_64 #1 SMP PREEMPT Tue Mar 8 22:50:58 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

##### STEPS TO REPRODUCE
<!--- Describe exactly how to reproduce the problem, using a minimal test-case -->

<!--- Paste example playbooks or commands between quotes below -->


```yaml
---

- name: "Ansible AZ issue"
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - name: Show me all private-dns-zone
      azure.azcollection.azure_rm_privatednszone_info:
        resource_group: myResourceGroup
      register: all_private_dns_zones

    - name: Exit if number of privateDNSZone is not 1
      fail: msg="Expected one private DNS zone. Cannot continue"
      when: all_private_dns_zones.ansible_info.azure_privatednszones|length!=1

    - name: Get private DNS zone
      set_fact: privateDNSZoneName={{ all_private_dns_zones.ansible_info.azure_privatednszones[0].name }}

    - name: show me the DNS zone
      ansible.builtin.debug:
        msg: "Private DNS zone: {{ privateDNSZoneName }}"

    - name: Retrieve DNS Record Set
      azure.azcollection.azure_rm_privatednsrecordset_info:
        resource_group: myResourceGroup
        zone_name: "{{ privateDNSZoneName }}"
        record_type: A
      register: dnsrecordsets

    - name: Show me recordset
      debug:
        msg: Record Set {{ item }}
      with_items: "{{ dnsrecordsets }}"

```

<!--- HINT: You can paste gist.github.com links for larger files -->

##### EXPECTED RESULTS
<!--- Describe what you expected to happen when running the steps above -->
The output similar to what is shown in the doc  https://docs.ansible.com/ansible/latest/collections/azure/azcollection/azure_rm_privatednsrecordset_info_module.html#return-dnsrecordsets

##### ACTUAL RESULTS
<!--- Describe what actually happened. If possible run with extra verbosity (-vvvv) -->

<!--- Paste verbatim command output between quotes -->
```paste below
$ ansible-playbook to-open-issue.yml
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

PLAY [Ansible AZ issue] ****************************************************************************************************************************************

TASK [Show me all private-dns-zone] ****************************************************************************************************************************
[WARNING]: Azure API profile latest does not define an entry for PrivateDnsManagementClient
ok: [localhost]

TASK [Exit if number of privateDNSZone is not 1] ***************************************************************************************************************
skipping: [localhost]

TASK [Get private DNS zone] ************************************************************************************************************************************
ok: [localhost]

TASK [show me the DNS zone] ************************************************************************************************************************************
ok: [localhost] => {
    "msg": "Private DNS zone: ocp4.az.asimov.lab"
}

TASK [Retrieve DNS Record Set] *********************************************************************************************************************************
ok: [localhost]

TASK [Show me recordset] ***************************************************************************************************************************************
ok: [localhost] => (item=changed) => {
    "msg": "Record Set changed"
}
ok: [localhost] => (item=dnsrecordsets) => {
    "msg": "Record Set dnsrecordsets"
}
ok: [localhost] => (item=warnings) => {
    "msg": "Record Set warnings"
}
ok: [localhost] => (item=failed) => {
    "msg": "Record Set failed"
}

PLAY RECAP *****************************************************************************************************************************************************
localhost                  : ok=5    changed=0    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0   


```
