### ISSUE TITLE
azure_rm_image doesn't support choosing HyperV generation version

### ISSUE THREAD

**Issue by spongebob331** [ansible/ansible_collections_azure#793]
##### SUMMARY

Add HyperVGeneration parameter to the module so the hyperv generation version is passed when the image is created. The terraform provider already allows this, but I see no way to specify the version using the ansible module.
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

azure_rm_image
##### ADDITIONAL INFORMATION

Add parameter HyperVGeneration to the parameters with acceptable values of V1 or V2 to match what is available in Azure. The default can be V1 if no option is specified.

```
- name: Create image from disk
    azure_rm_image:
      subscription_id: '{{ az_subscription_id }}'
      client_id: '{{ az_client_id }}'
      secret: '{{ az_secret }}'
      tenant: '{{ az_tenant }}'
      resource_group: '{{ az_resource_group }}'
      name: '{{ release }}-{{ image_version }}'
      source:
        type: disks
        resource_group: '{{ az_resource_group }}'
        name: '{{ release }}-{{ image_version }}'
      os_type: 'Linux'
      hyperVGeneration: 'V2'
```
