### ISSUE TITLE
Add Support for NAT Gateways

### ISSUE THREAD

**Issue by jberkers42** [ansible/ansible_collections_azure#794]
##### SUMMARY
Addition of support to create/maintain/delete NAT Gateways, including ability to associate a subnet to a NAT Gateway.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
azure_rm_natgateway

##### ADDITIONAL INFORMATION
In order to have control over the egress IP from Subnets within Azure it is helpful to use NAT Gateways and associate them to one or more subnets.  This would require a new module to support the creation/maintenance of NAT Gateways as well as extension of the Subnet module to support associations to NAT Gateways.

In regions where Availability zones are supported, support for these would be ideal.

Example: Create a Public IP, NAT Gateway using the public IP as the outbound IP, and associate it to a subnet.

```yaml
- name: Create a public ip address
  azure_rm_publicipaddress:
    resource_group: myResourceGroup
    name: myPublicNatIP
    allocation_method: static
    domain_name: foobar
- name: Create a NAT Gateway
  azure_rm_natgateway:
    resource_group: myResourceGroup
    name: myNatGateway
    outbound_public_ip: myPublicNatIP
    location: eastus
    availability_zone: zone1
    idle_timeout_minutes: 10
- name: Create a subnet
  azure_rm_subnet:
    resource_group: myResourceGroup
    virtual_network_name: myVirtualNetwork
    name: mySubnet
    address_prefix_cidr: "10.1.0.0/24"
```
