### ISSUE TITLE
Getting couldn't resolve module/action 'azure_rm_recoveryservicesvault' even with the Azure collection installed

### ISSUE THREAD

**Issue by tannerjonj** [ansible/ansible_collections_azure#796]
##### SUMMARY
Getting the following message:
         couldn't resolve module/action 'azure_rm_recoveryservicesvault' 
even with the Azure collection installed.  When the module azure_rm_recoveryservicesvault is run in a role, I get the error listed above.  When this same command is a task in a playbook, it works correctly.  When I run other modules from the azure collection within a role, they also work correctly.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure_rm_recoveryservicesvault

##### ANSIBLE VERSION

```paste below
ansible [core 2.11.9]
  config file = /home/azroot/.ansible.cfg
  configured module search path = ['/tmp/ansible_code/library']
  ansible python module location = /home/azroot/.local/lib/python3.6/site-packages/ansible
  ansible collection location = /home/azroot/.ansible/collections:/home/azroot/.local/lib/python3.6/site-packages
  executable location = /home/azroot/.local/bin/ansible
  python version = 3.6.8 (default, Aug  3 2021, 06:54:29) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
  jinja version = 2.10.1
  libyaml = True

```

##### COLLECTION VERSION

```paste below
ansible-galaxy collection list azure.azcollection

# /home/azroot/.local/lib/python3.6/site-packages/ansible_collections
Collection         Version
------------------ -------
azure.azcollection 1.10.0

# /home/azroot/.ansible/collections/ansible_collections
Collection         Version
------------------ -------
azure.azcollection 1.12.0

```

##### CONFIGURATION

```paste below
COLLECTIONS_PATHS(/home/azroot/.ansible.cfg) = ['/home/azroot/.ansible/collections', '/home/azroot/.local/lib/python3.6/site-packages']
COMMAND_WARNINGS(/home/azroot/.ansible.cfg) = False
DEFAULT_HOST_LIST(/home/azroot/.ansible.cfg) = ['/tmp/ansible_code/inventories/hosts']
DEFAULT_MODULE_PATH(/home/azroot/.ansible.cfg) = ['/tmp/ansible_code/library']
DEPRECATION_WARNINGS(/home/azroot/.ansible.cfg) = False
HOST_KEY_CHECKING(/home/azroot/.ansible.cfg) = False

```

##### OS / ENVIRONMENT

Red Hat Enterprise Linux release 8.2 (Ootpa)

##### STEPS TO REPRODUCE

```yaml
playbooks
    ├── play.yaml
    └── roles
        ├── RSG
        │   └── tasks
        │       └── main.yaml
        └── RSV
            ├── defaults
            │   └── main.yaml
            └── tasks
                └── main.yaml
cat playbooks/play.yaml
---
- hosts: localhost
  collections:
    - azure.azcollection
  gather_facts: no
  vars:
    RSVRSG:                "backup-{{ env_code }}-{{ geo_code }}-rsg"
    RSVName:               "{{ ApplicationTag }}-{{ env_code }}-{{ geo_code }}-rsv"
    RSVBackup_Policy_Name: "IaaSVMDefaultBackupPolicyAnsible"
  tasks:
    - name: Create Recovery Services Vault from playbook
      azure_rm_recoveryservicesvault:
        resource_group: "{{ RSVRSG }}"
        name:           "{{ RSVName }}"
        location:       "{{ geo_loc }}"
  roles:
    - role: RSG
    - role: RSV
   
cat playbooks/roles/RSV/tasks/main.yaml
---
- name: Create Recovery Services Vault from role
  azure_rm_recoveryservicesvault:
    resource_group: "{{ RSVRSG }}"
    name:           "{{ RSVName }}"
    location:       "{{ geo_loc }}"

cat playbooks/roles/RSG/tasks/main.yaml
---
- name: Create a resource group "{{ RSVName }}" in "{{ geo_loc }}" from role
  azure_rm_resourcegroup:
    name:     "{{ RSVName }}"
    location: "{{ geo_loc }}"
    state:    present

ansible-playbook playbooks/play.yaml --extra-vars "ApplicationTag=backup loc_code=az-eus geo_loc=eastus env_code=dev geo_code=eus"


```

##### EXPECTED RESULTS

 When I run the playbook, with the create recovery services vault command in a role, I get the resulting error listed in the ACTUAL RESULTS below.  BUT, if I comment out the RSV role, the play runs successfully.  The create recovery services vault command as a task in the playbook works.  The create resource group command in the 2nd role executes just fine.  The create resourse group command is a module that is also from the Azure collection.

##### ACTUAL RESULTS

```paste below
ansible-playbook playbooks/play.yaml -vvvv --extra-vars "ApplicationTag=backup loc_code=az-eus geo_loc=eastus env_code=dev geo_code=eus"
ansible-playbook [core 2.11.9]
  config file = /home/azroot/.ansible.cfg
  configured module search path = ['/tmp/ansible_code/library']
  ansible python module location = /home/azroot/.local/lib/python3.6/site-packages/ansible
  ansible collection location = /home/azroot/.ansible/collections:/home/azroot/.local/lib/python3.6/site-packages
  executable location = /home/azroot/.local/bin/ansible-playbook
  python version = 3.6.8 (default, Aug  3 2021, 06:54:29) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
  jinja version = 2.10.1
  libyaml = True
Using /home/azroot/.ansible.cfg as config file
setting up inventory plugins
host_list declined parsing /tmp/ansible_code/inventories/hosts as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
script declined parsing /tmp/ansible_code/inventories/hosts as it did not pass its verify_file() method
auto declined parsing /tmp/ansible_code/inventories/hosts as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
yaml declined parsing /tmp/ansible_code/inventories/hosts as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
ini declined parsing /tmp/ansible_code/inventories/hosts as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
toml declined parsing /tmp/ansible_code/inventories/hosts as it did not pass its verify_file() method
[WARNING]: Unable to parse /tmp/ansible_code/inventories/hosts as an inventory source
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'
Loading collection azure.azcollection from /home/azroot/.ansible/collections/ansible_collections/azure/azcollection
redirecting (type: modules) ansible.builtin.azure_rm_resourcegroup to azure.azcollection.azure_rm_resourcegroup
ERROR! couldn't resolve module/action 'azure_rm_recoveryservicesvault'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/home/azroot/playbooks/roles/RSV/tasks/main.yaml': line 2, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

---
- name: Create Recovery Services Vault from role
  ^ here


```
