### ISSUE TITLE
azure_rm_privatednszonelink returns False Fail when already existing link

### ISSUE THREAD

**Issue by pauronda-visma** [ansible/ansible_collections_azure#813]
##### SUMMARY
Task is marked as failed when there is an already  existing Virtual network link with an Azure Private DNS Zone

`  msg: |-
    Error creating or updating virtual network link ***nameofthelink*** - Azure Error: Conflict
    Message: Private zone '***nameoftheprivatezone***' is already linked to the virtual network '/subscriptions/********-****-****-****-************/resourceGroups/***rsggroupname***/providers/Microsoft.Network/virtualNetworks/***nameoftheprivatezone***'.`

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Module: azure.azcollection.azure_rm_privatednszonelink
[modules/azure_rm_privatednszonelink.py](https://github.com/ansible-collections/azure/blob/f47822c74f9eef0691f61563eda5dd44d3f65c27/plugins/modules/azure_rm_privatednszonelink.py)

##### ANSIBLE VERSION

```
ansible 2.9.16
  python version = 3.7.9 (default, Apr  5 2022, 14:20:14) [GCC 9.4.0]
```

##### COLLECTION VERSION

```
azure.azcollection
```

##### OS / ENVIRONMENT
WSL 2 Ubuntu 20.04.4 LTS

##### STEPS TO REPRODUCE
Just launch the module when there is already a link created between the Private Zone DNS and the Vnet

```yaml
- name: "Creating Virtual network links on {{ privatednszone_name }}"
  azure.azcollection.azure_rm_privatednszonelink:
    name: "vnetlinkname"
    resource_group: "name-rsg"
    subscription_id: "subs-id"
    zone_name: "privatezonednsname"
    virtual_network: "/subscriptions//resourceGroups//providers/Microsoft.Network/virtualNetworks/"
    client_id: "client_id"
    secret: "secret "
    tenant: "tenant"
```

##### EXPECTED RESULTS
Module returns a not changed

##### ACTUAL RESULTS

```
  msg: |-
    Error creating or updating virtual network link ***nameofthelink*** - Azure Error: Conflict
    Message: Private zone '***nameoftheprivatezone***' is already linked to the virtual network '/subscriptions/********-****-****-****-************/resourceGroups/***rsggroupname***/providers/Microsoft.Network/virtualNetworks/***nameoftheprivatezone***'.
```
