### ISSUE TITLE
Ansible tasks are getting timed out need timeout option for resource creation on playbook or increase the poller time for get_poller_result(self, poller, wait=5) 

### ISSUE THREAD

**Issue by Srinirap** [ansible/ansible_collections_azure#828]
##### SUMMARY

Each and every task on Azure resource creation is getting failed from my local due to unable to get the results on time but the resources are actually created on the cloud but when I have tried from Azure VMs it's a success.
Could you please either increase get_poller_result(self, poller, wait=5) wait time or timeout option on the playbook

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
srinivasan@srinivasan-VirtualBox:~$ ansible --version
ansible [core 2.12.3]
  config file = None
  configured module search path = ['/home/srinivasan/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  ansible collection location = /home/srinivasan/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.8.10 (default, Mar 15 2022, 12:22:08) [GCC 9.4.0]
  jinja version = 3.1.0
  libyaml = True
srinivasan@srinivasan-VirtualBox:~$
```

##### COLLECTION VERSION

```paste below
srinivasan@srinivasan-VirtualBox:~$ ansible-galaxy collection list azure.azcollection

# /usr/local/lib/python3.8/dist-packages/ansible_collections
Collection         Version
------------------ -------
azure.azcollection 1.11.0

# /home/srinivasan/.ansible/collections/ansible_collections
Collection         Version
------------------ -------
azure.azcollection 1.12.0
srinivasan@srinivasan-VirtualBox:~$
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Ubuntu 20.04.3 LTS \n \l

##### STEPS TO REPRODUCE

```yaml
- name: Create a resource group
  azure_rm_resourcegroup:
    name: '{{ rg_name }}'
    location: '{{ location }}'

- name: Create virtual network
  azure_rm_virtualnetwork:
    resource_group: '{{ rg_name }}'
    name: '{{ vnet_name }}'
    address_prefixes: "{{ vnet_prefix | default('10.0.0.0/16') }}"

- name: Add subnet
  azure_rm_subnet:
    resource_group: '{{ rg_name }}'
    virtual_network: '{{ vnet_name }}'
    address_prefix_cidr: '10.0.{{ item }}.0/24'
    name: 'subnet_{{item}}'
  with_sequence: start=1 end="{{ vm_count }}"

- name: Create public IP address
  azure_rm_publicipaddress:
    resource_group: '{{ rg_name }}'
    allocation_method: static
    name: '{{ vm_name }}_pubip_{{ item }}'
  register: 'pubipout'
  with_sequence: start=1 end="{{ vm_count }}"


```

##### ACTUAL RESULTS

```paste below

```
