### ISSUE TITLE
Backup SQL Server in Azure VM

### ISSUE THREAD

**Issue by kiweezi** [ansible/ansible_collections_azure#835]
##### SUMMARY

A way to backup just the SQL DB on an Azure VM.
This could be added as a param to the azure_rm_backupazurevm module or made separately.
It would also need to be available to use with the azure_rm_backuppolicy module.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

- Azure.AzCollection

##### ADDITIONAL INFORMATION

This is a commonly used recovery method in Azure in prod environments that is not available in Ansible.

```yaml
---
- name: Creating a backup for Azure VM SQL Server
  azure_rm_backupazurevm:
    resource_group: 'myResourceGroup'
    recovery_vault_name: 'testVault'
    resource_id: '/subscriptions/00000000-0000-0000-0000-000000000000/         resourceGroups/myResourceGroup/providers/Microsoft.Compute/virtualMachines/testVM'
    backup_policy_id: '/subscriptions/00000000-0000-0000-0000-000000000000/         resourceGroups/myResourceGroup/providers/microsoft.recoveryservices/vaults/testVault/backupPolicies/ProdPolicy'
    backup_type: 'AzureVMSQLServer'
    state: 'create'
```
