### ISSUE TITLE
Azure_rm_iotdevice is unable to create iotdevice and states that variable is undefined even when given a string directly

### ISSUE THREAD

**Issue by JorisRijs** [ansible/ansible_collections_azure#837]
##### SUMMARY
When trying to create an iot device in a specified iothub, using the azure_rm_iotdevice module, ansible returns that the task includes an option which is undefined. It states that the hub variable is undefined whilst the variable is definately defined and accessible (when printing the variable using debug)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Azure_rm_iotdevice

##### ANSIBLE VERSION
```
ansible [core 2.12.5]
  config file = /Users/jorisrijs/Documents/School/Graduation-Thales/Code/Automations/ansible.cfg
  configured module search path = ['/Users/jorisrijs/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/homebrew/lib/python3.9/site-packages/ansible
  ansible collection location = /Users/jorisrijs/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/homebrew/bin/ansible
  python version = 3.9.12 (main, Mar 26 2022, 15:44:31) [Clang 13.1.6 (clang-1316.0.21.2)]
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION
-->
```
# /Users/jorisrijs/.ansible/collections/ansible_collections
Collection         Version
------------------ -------
azure.azcollection 1.12.0

# /opt/homebrew/lib/python3.9/site-packages/ansible_collections
Collection         Version
------------------ -------
azure.azcollection 1.12.0
```

##### CONFIGURATION
```
DEFAULT_HOST_LIST(/Users/jorisrijs/Documents/School/Graduation-Thales/Code/Automations/ansible.cfg) = ['/Users/jorisrijs/Documents/School/Graduation-Thales/Code/Automations/hosts']
(END)
```

##### OS / ENVIRONMENT
- Target OS: Azure (main machine: macOS 12)

##### STEPS TO REPRODUCE
run the task outline below, the variables for the name are defined in ./group_vars/all and an ansible vault in the same location

```yaml
- name: "Create Iotdevice"
  azure.azcollection.azure_rm_iotdevice:
    hub: "{{ IoTHubName }}"
    name: test01
    auth_source: cli
    hub_policy_name: "{{ hub-policy-name }}"
    hub_policy_key: "{{ hub-policy-name }}"
    twin_tags:
      location:
          country: NL
      sensor: humidity
    desired: 
      period: 100
```

##### EXPECTED RESULTS
Expected behavior is that an IoT device is created in the specified iot hub with the give parameters.

##### ACTUAL RESULTS
Ansible returns the message below indicating that the hub variable is not defined, this message is also given if the hub option removed completely or the variable calling is replaced with the actual string.
```
fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'hub' is undefined\n\nThe error appears to be in './Code/Automations/tasks/Azure.yml': line 42, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Create Iotdevice\n  ^ here\n"}
```
