### ISSUE TITLE
Azure Arc Module

### ISSUE THREAD

**Issue by scottharwell** [ansible/ansible_collections_azure#843]
##### SUMMARY
Add support for Azure Arc services configuration, and, when the capability becomes available, support for automating against Arc connected VMs and devices as Ansible hosts

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
azure_rm_arc

##### ADDITIONAL INFORMATION
Azure Arc is becoming a pillar of Azure's hybrid cloud strategy, and Azure customers that automate with Ansible plan to configure both the Arc service and Arc connected machines.  As capabilities like server connectivity over Arc come online, Ansible Automation Platform on Microsoft Azure can use Arc to help Azure customers configure and automate against those connected devices.

- Dynamic inventory for Arc managed hosts
- Arc service configuration and management
- VM connectivity over Arc for SSH when feature is released

```yaml
---
- name: Get Arc Attachment Scripts
  hosts: azure
  azure.azcollection.azure_rm_arcservers:
    resource_group: "{{ resource_group_name }}"
    location: "{{ region }}"
    operating_system: linux
    register: arc_attachment_scripts
    tags:
      deployment: ansible
# This is not literal and would likely need to be tweaked to accurately run the Arc setup script retrieved in the previous step.
- name: Attach VMs to Arc
  hosts: azure
  become: true
  ansible.builtin.shell:
    cmd: "{{ item }}"
    loop: "{{ arc_attachment_scripts }}"
```
