### ISSUE TITLE
The error was: ModuleNotFoundError: No module named 'msrest' fatal

### ISSUE THREAD

**Issue by beerygaz** [ansible/ansible_collections_azure#852]
##### SUMMARY
Trying to execute a playbook on MacOS produces the above error.  I have installed the dependencies from https://raw.githubusercontent.com/ansible-collections/azure/dev/requirements-azure.txt 

ansible [core 2.12.5]
  python version = 3.10.4 (main, Apr 26 2022, 19:36:29) [Clang 13.1.6 (clang-1316.0.21.2)]
  jinja version = 3.1.2
  libyaml = True

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
- name: Using Azure collection
  azure.azcollection.azure_rm_storageaccount:
    resource_group: myResourceGroup
    name: myStorageAccount
    account_type: Standard_LRS
  delegate_to: localhost

##### ANSIBLE VERSION

```paste below
ansible [core 2.12.5]
  python version = 3.10.4 (main, Apr 26 2022, 19:36:29) [Clang 13.1.6 (clang-1316.0.21.2)]
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
Collection         Version
------------------ -------
azure.azcollection 1.12.0 
```

**Comment by Fred-sun** [comment]
@beerygaz Could you please provide your installation steps and commands? This will help solve the problem. Because I have not been able to copy the problem you encountered locally. Thank you very much!

**Comment by beerygaz** [comment]
brew install ansible
ansible-galaxy collection install azure.azcollection
pip install -r ~/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt
```

---
- name: Using Azure collection
  hosts: test-host
  tasks:
    - azure.azcollection.azure_rm_storageaccount:
        resource_group: myResourceGroup
        name: myStorageAccount
        account_type: Standard_LRS
       delegate_to: localhost
```
