### ISSUE TITLE
Expose softDeleteRetentionInDays property in azure_rm_keyvault

### ISSUE THREAD

**Issue by andreadecorte** [ansible/ansible_collections_azure#905]
##### SUMMARY
azure_rm_keyvault is currently not exposing this property, so you get the default value 90

##### ISSUE TYPE
- add this property, allowed values 7 <= x <= 90

##### COMPONENT NAME
azure_rm_keyvault

##### ADDITIONAL INFORMATION

```yaml
- name: Create instance of Key Vault
  azure_rm_keyvault:
    resource_group: myResourceGroup
    vault_name: samplekeyvault
    enabled_for_deployment: yes
    soft_delete_retention_in_days: 7
    sku:
      name: standard
```
