### ISSUE TITLE
Credentials Via Ansible Variables

### ISSUE THREAD

**Issue by beerygaz** [ansible/ansible_collections_azure#920]
Should it be possible to define credentials once for all Azure roles?  If I set SP detail (client_id, secret, tenant, subscription_id) as vars in all.yaml the Azure roles fail to authenticate, but if I pass them in every task, then authentication work.  Is this expected behaviour?  Should these global vars not be in scope?

Example:
This works:

``` yaml
vars: 
  client_id: xxxx
  secret: xxxxx
  tenant: xxxxx
  subscription_id: xxxx

 name: Create A record
  azure.azcollection.azure_rm_dnsrecordset:
    auth_source: auto
    client_id: "{{ client_id }}"
    subscription_id: "{{ subscription_id }}"
    secret: "{{ secret }}"
    tenant: "{{ tenant }}"

```

This does not:
``` yaml

vars: 
  client_id: xxxx
  secret: xxxxx
  tenant: xxxxx
  subscription_id: xxxx

 name: Create A record
  azure.azcollection.azure_rm_dnsrecordset:
    auth_source: auto

```
