### ISSUE TITLE
add  setting enableAutomaticUpdates for azure_rm_virtualmachine module option

### ISSUE THREAD

**Issue by tasoint** [ansible/ansible_collections_azure#924]
##### SUMMARY
please add new option of azure_rm_virtualmachine module.
this option is setting config enableAutomaticUpdates.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
EnableAutomaticUpdates is true by default when the current module is executed.
enableAutomaticUpdates can only be set when a VM is created, so please add it as an option in the module.

##### ADDITIONAL INFORMATION
EnableAutomaticUpdates is Automatic VM guest patching for Azure VMs
(https://docs.microsoft.com/en-us/azure/virtual-machines/automatic-vm-guest-patching)

Executed Playbook
```yaml
- name: Create virtual machine
  azure_rm_virtualmachine:
    resource_group: "{{ item.resource_group }}"
    name: "{{ item.vm_name }}"
    vm_size: Standard_DS1_v2
    managed_disk_type: Premium_LRS
    os_disk_caching: ReadWrite
    admin_username: ansible
    admin_password: xxxxxxx
    network_interfaces: "{{ item.vm_name }}"
    os_type: Windows
    image:
      offer: WindowsServer
      publisher: MicrosoftWindowsServer
      sku: 2019-Datacenter
      version: latest
  register: res_vm
```
Excerpt of results
```
"osProfile": {
                        "adminUsername": "ansible",
                        "allowExtensionOperations": true,
                        "computerName": "test",
                        "requireGuestProvisionSignal": true,
                        "secrets": [],
                        "windowsConfiguration": {
                            "enableAutomaticUpdates": true,
                            "provisionVMAgent": true
                        }
                    }
```
