### ISSUE TITLE
Azure - Unable to change Existing NIC Security Group

### ISSUE THREAD

**Issue by kTipSSIoYv** [ansible/ansible_collections_azure#928]
##### SUMMARY
  Azure doesn't let me update Network security group of existing NIC using Ansible.

I get the error The resource name already exists.

[azure_rm_networkinterface](https://docs.ansible.com/ansible/latest/collections/azure/azcollection/azure_rm_networkinterface_module.html) module documentation says it can be used to update NIC configurations.

I've used Ruby SDK for updating Azure NIC with a new Security group and it works (we have to provide the existing IP configuration and then it will allow us to update NIC) but it doesn't work using Ansible.

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```
ansible [core 2.13.2]
  config file = /root/azure_ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.8.12 (default, Sep 16 2021, 10:46:05) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
  jinja version = 3.1.2
  libyaml = True

```

##### COLLECTION VERSION

```
# /root/.ansible/collections/ansible_collections
Collection         Version
------------------ -------
azure.azcollection 1.13.0

# /usr/local/lib/python3.8/site-packages/ansible_collections
Collection         Version
------------------ -------
azure.azcollection 1.13.0

```

##### CONFIGURATION

```
sh-4.4# ansible-config dump --only-changed
DEFAULT_HOST_LIST(/root/azure_ansible/ansible.cfg) = ['/root/azure_ansible/inventory/test.azure_rm.yml']
DEFAULT_LOAD_CALLBACK_PLUGINS(/root/azure_ansible/ansible.cfg) = True
DEFAULT_STDOUT_CALLBACK(/root/azure_ansible/ansible.cfg) = json

```

##### OS / ENVIRONMENT

Centos 7 Docker container

##### STEPS TO REPRODUCE

```
  - name: Get facts for one network interface
    azure_rm_networkinterface_info:
      resource_group: "{{ resource_group }}"
      name: "{{ azure_vm_network_interface }}"
    register: azure_network_interface_info


  - name: Applying NSG to target NIC
    azure_rm_networkinterface:
      name: "Ubuntu915"
      resource_group: "{{ resource_group }}"
      subnet_name: "{{ azure_network_interface_info.networkinterfaces[0].subnet }}"
      virtual_network: "{{ azure_network_interface_info.networkinterfaces[0].virtual_network.name }}"
      ip_configurations:
        - name: "{{ azure_network_interface_info.name }}"      
          primary: "{{ azure_network_interface_info.primary }}"
          private_ip_address: "{{ azure_network_interface_info.private_ip_address }}"
          private_ip_allocation_method: "{{ azure_network_interface_info.private_ip_allocation_method }}"
          public_ip_address_name: "{{ azure_network_interface_info.name }}"
          public_ip_allocation_method: "Dynamic"     
      security_group: "testing_temp_8"

```

##### EXPECTED RESULTS
Update Security Group for existing NIC

##### ACTUAL RESULTS
 "msg": "Error creating or updating network interface Ubuntu915 - 
(InvalidResourceLocation) The resource 'Ubuntu915' already exists in location 'eastus' in resource
 group 'cloud-shell-storage-centralindia'. A resource with the same name cannot be created in 
location 'centralindia'. Please select a new resource name.\nCode: 
InvalidResourceLocation\nMessage: The resource 'Ubuntu915' already exists in location 'eastus' in 
resource group 'cloud-shell-storage-centralindia'. A resource with the same name cannot be created 
in location 'centralindia'. Please select a new resource name."
     }
