### ISSUE TITLE
Python Error Configuring Azure Firewall

### ISSUE THREAD

**Issue by scottharwell** [ansible/ansible_collections_azure#947]
##### SUMMARY
The `azure.azcollection.azure_rm_azurefirewall` module throws an error when any of the firewall attribute parameters are provided as part of the playbook.  A simple test is to take the playbook example from the product docs and run the playbook.  Any time a firewall attribute parameter exists in a playbook, then `AttributeError: 'dict' object has no attribute 'split'` is thrown as an error.  Removing the parameters circumvents the error, but does not allow for any firewall configuration.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure.azcollection.azure_rm_azurefirewall

##### ANSIBLE VERSION
```paste below
2.12.5
```

##### COLLECTION VERSION
```paste below
Collection                        Version
--------------------------------- -------
awx.awx                           21.2.0
azure.azcollection                1.13.0
community.aws                     4.0.0
community.general                 5.4.0
```

##### CONFIGURATION
```paste below
No Output
```

##### OS / ENVIRONMENT
Container deployment / Execution Environment running from the latest ansible runner image at quay.io/ansible/ansible-runner:latest

##### STEPS TO REPRODUCE

An example of a task that will run:

```yaml
- name: Create Azure Firewall
  azure.azcollection.azure_rm_azurefirewall:
    resource_group: sh-rg-peering-demo
    location: eastus
    name: test-firewall
    state: present
    tags:
      tag1: test
      tag2: test
```

An example of a task that will fail, which is a derivative of examples in the Azure Collection Ansible documentation:

```yaml
- name: Create Azure Firewall
  azure.azcollection.azure_rm_azurefirewall:
    resource_group: rg-peering-demo
    location: eastus
    name: test-firewall
    state: present
    tags:
      tag1: test
      tag2: test
    application_rule_collections:
      - priority: 110
        action:
          type: deny
        rules:
          - name: rule1
            description: Deny inbound rule
            source_addresses:
              - 216.58.216.164
              - 10.0.0.0/24
            protocols:
              - type: https
                port: '443'
            target_fqdns:
              - www.test.com
        name: apprulecoll
```

The following parameters all lead to the same failure type:

- application_rule_collections
- ip_configurations
- nat_rule_collections
- network_rule_collections

##### EXPECTED RESULTS

The expectation would be that the resources are created properly based on what is configured in the playbook.  Given that the error appears to be at the Python level, as opposed to a playbook syntax error, the error is not user-serviceable.

##### ACTUAL RESULTS
Traceback attached.
[traceback.txt](https://github.com/ansible-collections/azure/files/9339644/traceback.txt)
