### ISSUE TITLE
Allow os disk size specification for azure_rm_virtualmachinescaleset

### ISSUE THREAD

**Issue by deubert-it** [ansible/ansible_collections_azure#957]
##### SUMMARY

- We create an image from a VM with a 50 GB OS disk.
- We create a VM scalingset from this image, it fails:

```
Error creating or updating virtual machine foo-prod-scaleset - Azure Error: OperationNotAllowed
Message: The specified disk size 30 GB is smaller than the size of the corresponding disk in the VM image: 50 GB. This is not allowed. Please choose equal or greater size or do not specify an explicit size.
Target: osDisk.diskSizeGB
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure collection, azure_rm_virtualmachinescaleset resource

##### ANSIBLE VERSION
ansible 2.9.16

##### STEPS TO REPRODUCE

```yaml
- name: Create VM
  azure_rm_virtualmachine:
    [..]
    os_disk_size_gb: "50"

- name: Deallocate the VM before it can be generalized
  azure_rm_virtualmachine:
    [..]
    allocated: "yes"
    state: present

- name: Generalize the VM
  azure_rm_virtualmachine:
    [..]
    generalized: "yes"
    state: present

- name: Create VM Image
  azure_rm_image:
    [..]
    state: present

- name: Manage VM Scale set
  azure_rm_virtualmachinescaleset:
    [..]
```

##### EXPECTED RESULTS
Expected:
- provide a way to add os disk size configuration for scaleset vms. The documentation hints to its availability:

see: https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/tutorial-use-disks-powershell#create-and-attach-disks

> As of API version 2019-07-01, you can set the size of the OS disk in a virtual machine scale set with the storageProfile.osDisk.diskSizeGb property. After provisioning, you may have to expand or repartition the disk to make use of the whole space.

so I would expect to be able to configure it like this:

```yaml
- name: Create VM
  azure_rm_virtualmachine:
    [..]
    os_disk_size_gb: "50"

- name: Deallocate the VM before it can be generalized
  azure_rm_virtualmachine:
    [..]
    allocated: "yes"
    state: present

- name: Generalize the VM
  azure_rm_virtualmachine:
    [..]
    generalized: "yes"
    state: present

- name: Create VM Image
  azure_rm_image:
    [..]
    state: present

- name: Manage VM Scale set
  azure_rm_virtualmachinescaleset:
    [..]
    **os_disk_size_gb**: "50"
```

And then the vm scale set should work successfully without showing the error that the disk size is too small.
