### ISSUE TITLE
azure_rm_virtualmachine PowerOn Multiple machines

### ISSUE THREAD

**Issue by bendaniels052** [ansible/ansible_collections_azure#963]
- [ x] Verify first that your issue is not already reported on GitHub

- [ x] Also test if the latest release and devel branch are affected too 

- [x ] Complete *all* sections as described, this form is processed automatically 

##### SUMMARY
I'm trying to powerOn multiple Azure VMs via the `azure_rm_virtualmachine` module, To do this I'm getting the VM info based of resource group tags. With the VM data, I'm obtaining all the VM names and their associated resource group assigned to them. With this data collected, im then trying to loop through the data to turn the VMs on. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`azure_rm_virtualmachine`

##### ANSIBLE VERSION

```
ansible-playbook [core 2.12.5.post0]
  config file = None
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /runner/requirements_collections:/home/runner/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.8.13 (default, Jun 24 2022, 15:27:57) [GCC 8.5.0 20210514 (Red Hat 8.5.0-13)]
  jinja version = 2.11.3
  libyaml = True

```

##### COLLECTION VERSION

```
azure.azcollection.1.13.0

```

##### OS / ENVIRONMENT
Localhost - AWX 21.1.0  running on Kubernetes 

##### STEPS TO REPRODUCE

```yaml

- name: Get resource groups facts - limit by tags
  azure.azcollection.azure_rm_resourcegroup_info:
    client_id: "{{ az_client_id }}"
    secret: "{{ az_spn_secret }}"
    subscription_id: "{{ az_subscription }}"
    tenant: "{{ az_tenant_id }}"
    tags:
      - patchGroup:R2D2
  register: az_rsg_info

- name: Azure VM Info
  azure_rm_virtualmachine_info:
    client_id: "{{ az_client_id }}"
    secret: "{{ az_spn_secret }}"
    subscription_id: "{{ az_subscription }}"
    tenant: "{{ az_tenant_id }}"
    resource_group: "{{ item }}"
  with_items: '{{ az_rsg_info.resourcegroups | map(attribute="name") }}'
  register: az_rsg_vm_info

- name: debug - az_vm_info - with_items
  ansible.builtin.debug:
    msg: '{{ az_rsg_vm_info.results  }}'

- name: debug - az_vm_info - with_items
  ansible.builtin.debug:
    msg: '{{ item | json_query("vms[].resource_group ") | list }}'
  with_items: "{{ az_rsg_vm_info.results }}"
  
- name: Power On machines
  azure_rm_virtualmachine:
    client_id: "{{ az_client_id }}"
    secret: "{{ az_spn_secret }}"
    subscription_id: "{{ az_subscription }}"
    tenant: "{{ az_tenant_id }}"
    resource_group: '{{ item | json_query("vms[].resource_group ") }}'
    name: '{{ item | json_query("vms[].name ") }}'
  with_items: "{{ az_rsg_vm_info.results }}"

```

##### EXPECTED RESULTS
All Azure VMs looped through and powered on.

##### ACTUAL RESULTS

The module doesnt loop through each VM name or resource group. Instead it tries to add the full list of VM/RSG's to the one field.

```paste below
{
  "msg": "Error retrieving resource group ['ZNE-ANES-N-05-MGM-RSG', 'ZNE-ANES-N-05-MGM-RSG', 'ZNE-ANES-N-05-MGM-RSG'] - Parameter 'resource_group_name' must conform to the following pattern: '^[-\\\\w\\\\._\\\\(\\\\)]+$'.",
  "invocation": {
    "module_args": {
      "client_id": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
      "secret": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
      "subscription_id": "573e0e43-432c-4d4a-a31e-11a2f55c1b22",
      "tenant": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
      "resource_group": "['ZNE-ANES-N-05-MGM-RSG', 'ZNE-ANES-N-05-MGM-RSG', 'ZNE-ANES-N-05-MGM-RSG']",
      "name": "['zneanesn05mg71', 'zneanesn05mguy', 'zneanesn05mgxk']",
      "auth_source": "auto",
      "cloud_environment": "AzureCloud",
      "api_profile": "latest",
      "append_tags": true,
      "state": "present",
      "max_price": -1,
      "ssh_password_enabled": true,
      "storage_container_name": "vhds",
      "os_type": "Linux",
      "public_ip_allocation_method": "Static",
      "remove_on_absent": [
        "all"
      ],
      "allocated": true,
      "restarted": false,
      "started": true,
      "generalized": false,
      "accept_terms": false,
      "profile": null,
      "ad_user": null,
      "password": null,
      "cert_validation_mode": null,
      "adfs_authority_url": null,
      "log_mode": null,
      "log_path": null,
      "tags": null,
      "custom_data": null,
      "location": null,
      "short_hostname": null,
      "vm_size": null,
      "priority": null,
      "eviction_policy": null,
      "admin_username": null,
      "admin_password": null,
      "ssh_public_keys": null,
      "image": null,
      "availability_set": null,
      "storage_account_name": null,
      "storage_blob_name": null,
      "os_disk_caching": null,
      "os_disk_size_gb": null,
      "managed_disk_type": null,
      "os_disk_name": null,
      "proximity_placement_group": null,
      "open_ports": null,
      "network_interface_names": null,
      "virtual_network_resource_group": null,
      "virtual_network_name": null,
      "subnet_name": null,
      "data_disks": null,
      "plan": null,
      "zones": null,
      "license_type": null,
      "vm_identity": null,
      "winrm": null,
      "boot_diagnostics": null,
      "ephemeral_os_disk": null
    }
  },
```

**Comment by Fred-sun** [comment]
@bendaniels052 You get a list of resource groups and VM names from '{{ item | json_query("vms[].resource_group ") }}' and '{{ item | json_query("vms[].name ") }}' . If you want to power on the VM, you need to pass the resource group and VM names in the playbook. Thank you very much!

**Comment by bendaniels052** [comment]
@Fred-sun I've tried creating a list, but still getting the same response, unless im doing something wrong? 

```yaml 
- name: Set_fact - az_vm_info - loop
  ansible.builtin.set_fact:
    az_vm_name_l: '{{ item | json_query("vms[].name ") }}'
    az_vm_rsg_l: '{{ item | json_query("vms[].resource_group ") }}'
  loop: "{{ az_rsg_vm_info.results | list }}"

- name: debug - az_vm_name_l
  ansible.builtin.debug:
    msg: '{{ item }}'
  loop: "{{ az_vm_name_l }}"

- name: Power On machines
  azure_rm_virtualmachine:
    client_id: "{{ az_client_id }}"
    secret: "{{ az_spn_secret }}"
    subscription_id: "{{ az_subscription }}"
    tenant: "{{ az_tenant_id }}"
    resource_group: '{{ item.vm_rsg | list }}'
    name: '{{ item.vm_name | list }}'
  loop:
    - { vm_name: '{{ az_vm_name_l }}', vm_rsg: '{{ az_vm_rsg_l }}' }
```

Results 
```yaml

TASK [az_vm : debug - az_vm_name_l] ********************************************
ok: [localhost] => (item=zneanesn20dobn) => {
    "msg": "zneanesn20dobn"
}
ok: [localhost] => (item=zneanesn20dof8) => {
    "msg": "zneanesn20dof8"
}
ok: [localhost] => (item=zneanesn20dopb) => {
    "msg": "zneanesn20dopb"
}


TASK [az_vm : Power On machines] ***********************************************
failed: [localhost] (item={'vm_name': ['zneanesn20dobn', 'zneanesn20dof8', 'zneanesn20dopb'], 'vm_rsg': ['ZNE-ANES-N-20-DOM-RSG', 'ZNE-ANES-N-20-DOM-RSG', 'ZNE-ANES-N-20-DOM-RSG']}) => {"ansible_loop_var": "item", "changed": false, "item": {"vm_name": ["zneanesn20dobn", "zneanesn20dof8", "zneanesn20dopb"], "vm_rsg": ["ZNE-ANES-N-20-DOM-RSG", "ZNE-ANES-N-20-DOM-RSG", "ZNE-ANES-N-20-DOM-RSG"]}, "msg": "Error retrieving resource group ['ZNE-ANES-N-20-DOM-RSG', 'ZNE-ANES-N-20-DOM-RSG', 'ZNE-ANES-N-20-DOM-RSG'] - Parameter 'resource_group_name' must conform to the following pattern: '^[-\\\\w\\\\._\\\\(\\\\)]+$'."}

```

**Comment by bendaniels052** [comment]
** Resolved **  - Thanks for the assistance! 

Here's the final playbook encase anyone else is interested. 

```yaml 
---
---

- name: Get resource groups facts - limit by tags
  azure.azcollection.azure_rm_resourcegroup_info:
    client_id: "{{ az_client_id }}"
    secret: "{{ az_spn_secret }}"
    subscription_id: "{{ az_subscription }}"
    tenant: "{{ az_tenant_id }}"
    tags:
      - patchGroup:R2D2
  register: az_rsg_info

- name: Azure VM Info
  azure_rm_virtualmachine_info:
    client_id: "{{ az_client_id }}"
    secret: "{{ az_spn_secret }}"
    subscription_id: "{{ az_subscription }}"
    tenant: "{{ az_tenant_id }}"
    resource_group: "{{ item }}"
  with_items: '{{ az_rsg_info.resourcegroups | map(attribute="name" ) }}'
  register: az_rsg_vm_info

- name: set_fact - az_vm_name/az_vm_rsg
  ansible.builtin.set_fact:
    az_vm_name: '{{ az_rsg_vm_info.results | json_query("[*].vms[].name | [] ")  }}'
    az_vm_rsg: '{{ az_rsg_vm_info.results | json_query("[*].vms[].resource_group | [] ")  }}'

- name: Power On machines
  azure_rm_virtualmachine:
    client_id: "{{ az_client_id }}"
    secret: "{{ az_spn_secret }}"
    subscription_id: "{{ az_subscription }}"
    tenant: "{{ az_tenant_id }}"
    resource_group: '{{ item.1 }}'
    name: '{{ item.0 }}'
  with_together:
    - '{{ az_vm_name }}'
    - '{{ az_vm_rsg }}'

```
