### ISSUE TITLE
The error was: ModuleNotFoundError: No module named 'msrest'

### ISSUE THREAD

**Issue by dkirrane** [ansible/ansible_collections_azure#970]
##### SUMMARY
GitHub action failing with
```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ModuleNotFoundError: No module named 'msrest'
fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "Failed to import the required Python library (msrestazure) on fv-az39-51's Python /usr/bin/python3. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"}
```

Here is my GitHub Action workflow
```
name: Ansible Test

on:
  workflow_dispatch:

jobs:

  Playbook:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Ansible Install
        run: |
          pip3 install --user ansible
          ansible --version

      - name: Ansible Galaxy Install
        run: |
          ansible-galaxy collection install -r requirements.yml
          pip3 install -r ~/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt
          pip3 install msrest -I
          pip3 install msrestazure -I
          pip3 install psycopg2 -I

      - name: Ansible Run
        run: ansible-playbook -i hosts.ini playbook.yml
```

`requirements.yml`
````
collections:

  - name: azure.azcollection
    version: 1.13.0
    type: galaxy

  - name: community.postgresql
    version: 2.2.0
    type: galaxy
```

##### ANSIBLE VERSION
```
ansible [core 2.13.3]
  config file = None
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/runner/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /home/runner/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/runner/.local/bin/ansible
  python version = 3.10.6 (main, Aug  3 2022, 07:09:11) [GCC 9.4.0]
  jinja version = 3.1.2
  libyaml = True
```
