### ISSUE TITLE
The module_defaults group name is inconsistent

### ISSUE THREAD

**Issue by akira6592** [ansible/ansible_collections_azure#977]
##### SUMMARY

The module_defaults group name is inconsistent between ansible-core and this collection.

ansibe-core side points [`azure.azcollection.azure`](https://github.com/ansible/ansible/blob/v2.12.0/lib/ansible/config/ansible_builtin_runtime.yml#L9705-L9708) and this collection side defines `all` (`azure.azcollection.all`).

I think it shuld be `azure` for the following reasons. 

- It's been `azure` since asnible-core 2.12. On the other hands collection that define goup name is not still release. If it should be fix it, now is the time.
- Many other collections don't use `all` group name although including all modules. Such as [`awx.awx.controller`](https://github.com/ansible/awx/blob/21.6.0/awx_collection/meta/runtime.yml#L4).

related to: https://github.com/ansible-collections/azure/issues/569#issuecomment-1219010931

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

- module_defaults 
- `meta/runtime.yml` 

##### ANSIBLE VERSION

```paste below
% ansible --version
ansible [core 2.13.1]
```

##### COLLECTION VERSION

devel at https://github.com/ansible-collections/azure/tree/83f1895f4f3b72d4dc59751a2faa974fbdaf03ee

installed by `ansible-galaxy collection install git+https://github.com/ansible-collections/azure,dev`

##### CONFIGURATION

```paste below
% ansible-config dump --only-changed        
HOST_KEY_CHECKING(/Users/sakana/Documents/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

macOS 12.5.1

##### STEPS TO REPRODUCE

```yaml
---
- hosts: localhost
  connection: local
  gather_facts: false

  module_defaults:
    group/azure:
      resource_group: rg01

  tasks:
    - name: vnet
      azure.azcollection.azure_rm_virtualnetwork:
        name: rg01_nw
        address_prefixes_cidr:
          - 172.16.0.0/16
```

##### EXPECTED RESULTS

```
TASK [vnet] ****************************************************************************************************
changed: [localhost]
```

##### ACTUAL RESULTS

```paste below
TASK [vnet] ******************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "missing required arguments: resource_group"}
```
The above output indicates module_defaults group name is not valid.

Of course if I use `group/azure.azcollection.all` it will work fine.
