### ISSUE TITLE
InvalidAuthenticationTokenAudience with AzureUSGovernment

### ISSUE THREAD

**Issue by dc-chris-smith** [ansible/ansible_collections_azure#985]
##### SUMMARY

I am working on a role to allow department users to start and stop VMs in Azure when they are needed.  I have worked through a number of issues that were not documented only to be presented with "the access token has been obtained for the wrong audience."

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

azure.azcollection.azure_rm_virtualmachine

##### ANSIBLE VERSION

```paste below
ansible [core 2.12.3]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.8.12 (default, Sep 16 2021, 10:46:05) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
  jinja version = 3.0.3
  libyaml = True
```

##### COLLECTION VERSION

```paste below
execution environment rebuilt weekly with all latest versions
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

AzureUSGovernment

##### STEPS TO REPRODUCE

I have a powered off VM in Azure and the configured playbook below.  When I execute the playbook, it errors out with the error code pasted at the bottom.

A custom credential is used that provides the AZURE_CLIENT_ID and AZURE_SECRET values.

Extra vars yaml
```yaml
role_name: power
vm_operation: start
vm_name: REDACTED
resource_group_name: REDACTED
subscription_id: REDACTED
tenant: REDACTED
cloud_environment: AzureUSGovernment
```

Playbook yaml to start the VM
```yaml
- name: Start Azure VM
  azure.azcollection.azure_rm_virtualmachine:
    tenant: '{{ tenant }}'
    subscription_id: '{{ subscription_id }}'
    client_id: '{{ AZURE_CLIENT_ID }}'
    secret: '{{ AZURE_SECRET }}'
    cloud_environment: '{{ cloud_environment }}'
    resource_group: '{{ resource_group_name }}'
    name: '{{ vm_name }}'
    started: yes
  when: "vm_operation == 'start'"
```

##### EXPECTED RESULTS

The target VM would be started

##### ACTUAL RESULTS

```paste below
The access token has been obtained for wrong audience or resource 'https://management.azure.com'. It should exactly match with one of the allowed audiences 'https://management.core.usgovcloudapi.net/','https://management.core.usgovcloudapi.net','https://management.usgovcloudapi.net/','https://management.usgovcloudapi.net'.
```
