### ISSUE TITLE
Ansible azure_rm_keyvaultsecret_info module has dependency to deprecated azure.storage 0.37.0

### ISSUE THREAD

**Issue by julianbergner** [ansible/ansible_collections_azure#987]
##### SUMMARY
Ansible azure_rm_keyvaultsecret_info module has module dependency to azure.storage which is deprecated since 0.37.0 and not part of the requirements-azure.txt.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure_rm_keyvaultsecret_info

##### ANSIBLE VERSION
```
ansible [core 2.13.4]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.7 (default, Sep 13 2021, 08:22:52) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION
```
Collection                    Version
----------------------------- -------
ansible.netcommon             3.1.1
ansible.posix                 1.4.0
ansible.utils                 2.6.1
ansible.windows               1.11.1
azure.azcollection            1.13.0

```

##### CONFIGURATION
```
sh-4.4# ansible-config dump --only-changed

sh-4.4#

```

##### OS / ENVIRONMENT
Docker image: redhat/ubi8-init:8.6

```
  Operating System: Red Hat Enterprise Linux 8.6 (Ootpa)
       CPE OS Name: cpe:/o:redhat:enterprise_linux:8::baseos
            Kernel: Linux 5.10.104-linuxkit
      Architecture: arm64
```

##### STEPS TO REPRODUCE
```
- name: Test
  hosts: localhost

  tasks:
    - name: Get secret value for keystore
      azure.azcollection.azure_rm_keyvaultsecret_info:
        vault_uri: "{{ azure_keyvault_uri }}"
        name: "{{ azure_keystore_secret_name }}"
        subscription_id: "{{ azure_subscription_id }}"
        client_id: "{{ azure_client_id }}"
        secret: "{{ azure_secret }}"
        tenant: "{{ azure_tenant }}"
      register: kvsecret_keystore
```

##### EXPECTED RESULTS
I only get it working when adding `azure-storage==0.36.0` and removing `azure-storage-blob==12.11.0` to/from requirements.

##### ACTUAL RESULTS
```
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_azure.azcollection.azure_rm_keyvaultsecret_info_payload_sfa9kt8g/ansible_azure.azcollection.azure_rm_keyvaultsecret_info_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py", line 250, in <module>
    from azure.storage.cloudstorageaccount import CloudStorageAccount
ModuleNotFoundError: No module named 'azure.storage.cloudstorageaccount'
fatal: [os.example.com]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "ad_user": null,
            "adfs_authority_url": null,
            "api_profile": "latest",
            "auth_source": "auto",
            "cert_validation_mode": null,
            "client_id": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "cloud_environment": "AzureCloud",
            "log_mode": null,
            "log_path": null,
            "name": "keystore-secret",
            "password": null,
            "profile": null,
            "secret": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "show_deleted_secret": false,
            "subscription_id": "9bxxxxx",
            "tags": null,
            "tenant": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "vault_uri": "https://vault-name.vault.azure.net/",
            "version": "current"
        }
    },
    "msg": "Failed to import the required Python library (ansible[azure] (azure >= 2.0.0)) on os.example.com's Python /usr/bin/python3. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"
}

PLAY RECAP *********************************************************************
os.example.com             : ok=16   changed=13   unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```
