### ISSUE TITLE
Does azcollection/azure_rm_keyvaultkey support the ability to upload externally generated SSH keys to Keyvault?

### ISSUE THREAD

**Issue by alexw-z** [ansible/ansible_collections_azure#995]
Hi

I'm not quite sure if this is a documentation query, a feature request or a general question to be honest, but I'm writing an Ansible script to perform key rotation across my company's Linux estate and having some difficulty with trying to add some SSH Keys to Azure Keyvault using the azcollection modules.

We use Azure as a cloud platform and I'm looking to store a backup copy of the public and private keys in Azure Keyvault. The Linux estate itself is hosted on VMWare and isn't part of the Azure cloud.

Using the ```azure_rm_keyvaultkey``` module I have been able to successfully generate a new key via the Keyvault itself using the code below, but I need the functionality to upload the key I've generated on our local AWX instance instead, and I'm not certain if the module provides this functionality:

```
- name: Create a key
  azure_rm_keyvaultkey:
    key_name: "TestKey2"
    keyvault_uri: "https://<redacted>.vault.azure.net/"
    state: present
    #pem_file: "{{ lookup('file', '/tmp/{{ ssh_key_filename }}') }}"
  delegate_to: localhost
  become: false
```

There is a pem_file parameter which can be set to a string (the documentation for this module is pretty sparse and information for this parameter consists just of a copy of its name), I've tried using this to reference the keyfile I've created as in the commented line above, but this doesn't seem to result in my key being added to the vault.

Can I please query if I'm understanding this parameter correctly and/or if the azcollection supports the functionality to upload externally generated keys? If not, could I propose it as a feature request?

Many thanks.

Alex Walker.
